export const linuxAppCategories = [
  "system",
  "development",
  "network",
  "data",
  "office",
  "media",
  "security",
  "learning",
] as const

export type LinuxAppCategory = (typeof linuxAppCategories)[number]
export type LinuxAppCategoryFilter = LinuxAppCategory | "all"

export type LinuxApp = {
  readonly id: string
  readonly name: string
  readonly category: LinuxAppCategory
  readonly principle: string
  readonly concept: string
  readonly process: string
  readonly command: string
  readonly output: string
  readonly exercise: string
}

export const linuxAppCategoryLabels: Readonly<Record<LinuxAppCategoryFilter, string>> = {
  all: "All apps",
  system: "System",
  development: "Development",
  network: "Network",
  data: "Data",
  office: "Office",
  media: "Media",
  security: "Security",
  learning: "Learning",
}

export const linuxApps = [
  {
    id: "terminal",
    name: "Terminal",
    category: "system",
    principle: "Command line interface",
    concept: "Parsing, streams, process exit codes",
    process: "Read text, split arguments, run a program, then return stdout, stderr, and status.",
    command: "printf 'hello linux'",
    output: "hello linux",
    exercise: "Run one command, then explain which part is input, output, and control flow.",
  },
  {
    id: "files",
    name: "Files",
    category: "system",
    principle: "Filesystem navigation",
    concept: "Trees, paths, inodes, permissions",
    process: "Resolve a path from root or the current directory, then list directory entries.",
    command: "ls /home/learner/projects",
    output: "rate-limiter  key-value-store  url-shortener",
    exercise: "Predict whether an absolute or relative path is being resolved.",
  },
  {
    id: "processes",
    name: "Processes",
    category: "system",
    principle: "Process lifecycle",
    concept: "Creation, scheduling, signals, termination",
    process: "The kernel tracks process ids, state, parent links, and resource usage.",
    command: "ps -o pid,stat,comm",
    output: "101 S vite\n142 R learner-lab\n188 S shell",
    exercise: "Identify which process is running and which ones are sleeping.",
  },
  {
    id: "system-monitor",
    name: "System Monitor",
    category: "system",
    principle: "Resource observation",
    concept: "Sampling, aggregation, CPU and memory counters",
    process: "Collect samples over time and summarize them without blocking the workload.",
    command: "top -b -n 1",
    output: "cpu 18%  mem 42%  load 0.72",
    exercise: "Explain why a single sample can mislead performance debugging.",
  },
  {
    id: "disk-utility",
    name: "Disk Utility",
    category: "system",
    principle: "Storage layout",
    concept: "Blocks, filesystems, mount points",
    process: "Map bytes on devices into named files through filesystem metadata.",
    command: "df -h /",
    output: "/dev/vda1  64G  21G  43G  33% /",
    exercise: "Find the difference between disk capacity and used filesystem space.",
  },
  {
    id: "settings",
    name: "Settings",
    category: "system",
    principle: "Configuration management",
    concept: "State, defaults, overrides",
    process: "Load default values, apply user overrides, and persist only intentional changes.",
    command: "gsettings list-recursively lab.theme",
    output: "theme.mode dark\ntheme.accent brass",
    exercise: "Name one value that belongs in config and one that belongs in code.",
  },
  {
    id: "users",
    name: "Users",
    category: "system",
    principle: "Identity and groups",
    concept: "Users, groups, privilege boundaries",
    process:
      "Authorize operations by matching a user id and group membership to a permission rule.",
    command: "id learner",
    output: "uid=1000(learner) gid=1000(learner) groups=dev,lab",
    exercise: "Explain why groups are easier than per-user permission lists.",
  },
  {
    id: "logs",
    name: "Logs",
    category: "system",
    principle: "Event records",
    concept: "Append-only data, timestamps, severity",
    process: "Write immutable facts so later debugging can reconstruct what happened.",
    command: "journalctl -p warning -n 2",
    output: "warn auth retry-limit\nwarn disk cache-near-limit",
    exercise: "Separate an event fact from a debugging hypothesis.",
  },
  {
    id: "services",
    name: "Services",
    category: "system",
    principle: "Long-running daemons",
    concept: "Supervision, restart policy, health checks",
    process: "A supervisor starts a service, watches it, and applies a restart rule on failure.",
    command: "systemctl status lesson-api",
    output: "lesson-api.service active running",
    exercise: "Explain how supervision differs from manually running a command.",
  },
  {
    id: "code-editor",
    name: "Code Editor",
    category: "development",
    principle: "Text editing model",
    concept: "Buffers, cursors, syntax tokens",
    process: "Keep an editable buffer in memory and render tokens without changing source text.",
    command: "codex-edit main.ts",
    output: "buffer opened: main.ts  132 tokens highlighted",
    exercise: "Explain the difference between text storage and syntax highlighting.",
  },
  {
    id: "git-client",
    name: "Git Client",
    category: "development",
    principle: "Version control",
    concept: "Content-addressed snapshots and diffs",
    process: "Hash file content into objects, connect commits, and compare trees.",
    command: "git status --short",
    output: "M src/app.ts\nA src/data/linuxApps.ts",
    exercise: "Explain why Git stores snapshots but shows diffs.",
  },
  {
    id: "compiler",
    name: "Compiler",
    category: "development",
    principle: "Translation pipeline",
    concept: "Lexing, parsing, type checking, code generation",
    process: "Transform source into an executable form through staged representations.",
    command: "tsc --noEmit",
    output: "type check complete: 0 errors",
    exercise: "Name the compiler stage that catches a missing property.",
  },
  {
    id: "debugger",
    name: "Debugger",
    category: "development",
    principle: "Program inspection",
    concept: "Breakpoints, stack frames, variable scope",
    process: "Pause execution at a known point and inspect the current call frame.",
    command: "debug run --break reduceState",
    output: "paused at reduceState(action.kind)",
    exercise: "Explain why a breakpoint is more precise than adding prints everywhere.",
  },
  {
    id: "repl",
    name: "REPL",
    category: "development",
    principle: "Interactive evaluation",
    concept: "Read, evaluate, print, loop",
    process:
      "Accept a small expression, evaluate it immediately, and keep context for the next one.",
    command: 'node -e "console.log(2 ** 8)"',
    output: "256",
    exercise: "Describe the loop in REPL using input, transform, output.",
  },
  {
    id: "package-manager",
    name: "Package Manager",
    category: "development",
    principle: "Dependency resolution",
    concept: "Graphs, versions, constraints, lockfiles",
    process:
      "Solve compatible package versions and record the exact result for repeatable installs.",
    command: "pnpm list --depth 0",
    output: "typescript 5.9.3\nvite 7.2.7\nvitest 4.0.15",
    exercise: "Explain why a lockfile is evidence, not clutter.",
  },
  {
    id: "containers",
    name: "Container Lab",
    category: "development",
    principle: "Isolation",
    concept: "Namespaces, images, layers",
    process:
      "Run a process with isolated filesystem and network views while sharing the host kernel.",
    command: "podman ps --format names",
    output: "lesson-db\nsandbox-api",
    exercise: "Explain why a container is not a full virtual machine.",
  },
  {
    id: "build-pipeline",
    name: "Build Pipeline",
    category: "development",
    principle: "Automation",
    concept: "Directed acyclic graphs, caching, artifacts",
    process: "Run steps in dependency order and reuse outputs when inputs have not changed.",
    command: "make build",
    output: "lint ok\ntest ok\nbundle ok",
    exercise: "Find the step that should run first when source code changes.",
  },
  {
    id: "api-tester",
    name: "API Tester",
    category: "development",
    principle: "Protocol contracts",
    concept: "HTTP methods, status codes, JSON boundaries",
    process: "Send a request, parse the response, and validate the contract at the boundary.",
    command: "curl -i /api/lessons/terminal",
    output: "HTTP/1.1 200 OK\ncontent-type: application/json",
    exercise: "Explain why a status code is part of the API contract.",
  },
  {
    id: "browser",
    name: "Browser",
    category: "network",
    principle: "Client-server model",
    concept: "URLs, DNS, HTTP, rendering",
    process: "Resolve a host, request resources, parse responses, then render a document tree.",
    command: "curl -I https://example.test",
    output: "HTTP/2 200\ncache-control: max-age=3600",
    exercise: "Trace what happens between typing a URL and seeing a page.",
  },
  {
    id: "dns-lookup",
    name: "DNS Lookup",
    category: "network",
    principle: "Name resolution",
    concept: "Distributed lookup, caching, TTL",
    process:
      "Resolve human names into network addresses using recursive and authoritative servers.",
    command: "dig lab.local A +short",
    output: "127.0.0.1",
    exercise: "Explain why DNS answers expire.",
  },
  {
    id: "packet-trace",
    name: "Packet Trace",
    category: "network",
    principle: "Packet switching",
    concept: "Frames, packets, ports, latency",
    process: "Capture packets at an interface and decode headers into readable protocol fields.",
    command: "tcpdump -c 2 port 443",
    output:
      "IP learner.51110 > api.443: TLS ClientHello\nIP api.443 > learner.51110: TLS ServerHello",
    exercise: "Identify source, destination, and protocol in one captured line.",
  },
  {
    id: "firewall",
    name: "Firewall",
    category: "network",
    principle: "Policy enforcement",
    concept: "Rules, matching, allow and deny lists",
    process: "Check packet fields against ordered rules and stop at the first matching decision.",
    command: "nft list ruleset",
    output: "allow tcp dport 443\ndrop tcp dport 23",
    exercise: "Explain why rule order matters.",
  },
  {
    id: "ssh-client",
    name: "SSH Client",
    category: "network",
    principle: "Secure remote shell",
    concept: "Public keys, encrypted channels, trust on first use",
    process: "Authenticate a server key, negotiate encryption, then run a remote command stream.",
    command: "ssh learner@lab whoami",
    output: "learner",
    exercise: "Explain what the client must verify before sending credentials.",
  },
  {
    id: "sftp",
    name: "SFTP",
    category: "network",
    principle: "Remote file transfer",
    concept: "Streams, paths, checksums",
    process: "Move file bytes over an encrypted session while preserving names and metadata.",
    command: "sftp lab:/tmp/report.txt ./report.txt",
    output: "downloaded 4.2 KB",
    exercise: "Explain why file transfer needs both path metadata and byte content.",
  },
  {
    id: "port-scanner",
    name: "Port Scanner",
    category: "network",
    principle: "Service discovery",
    concept: "Sockets, ports, timeouts",
    process: "Attempt connections and classify ports by response, refusal, or timeout.",
    command: "scan 127.0.0.1 22 80 5173",
    output: "22 closed\n80 closed\n5173 open",
    exercise: "Explain the difference between closed and filtered.",
  },
  {
    id: "http-server",
    name: "HTTP Server",
    category: "network",
    principle: "Request handling",
    concept: "Routing, handlers, headers",
    process: "Accept a socket, parse an HTTP request, route it, and write a response.",
    command: "serve ./dist --port 5173",
    output: "serving ./dist at http://127.0.0.1:5173",
    exercise: "Name the boundary where raw bytes become a request object.",
  },
  {
    id: "database",
    name: "Database",
    category: "data",
    principle: "Persistent query engine",
    concept: "Tables, indexes, transactions",
    process: "Parse a query, choose an access path, lock data, and commit changes atomically.",
    command: "select title from lessons where id='terminal';",
    output: "Terminal",
    exercise: "Explain why indexes speed lookup but cost writes.",
  },
  {
    id: "spreadsheet",
    name: "Spreadsheet",
    category: "data",
    principle: "Reactive cells",
    concept: "Dependency graphs and formulas",
    process: "Track which cells depend on others and recalculate them in order after edits.",
    command: "A3 = SUM(A1:A2)",
    output: "A3 recalculated: 42",
    exercise: "Draw the dependency graph for three formula cells.",
  },
  {
    id: "json-viewer",
    name: "JSON Viewer",
    category: "data",
    principle: "Structured data",
    concept: "Parsing, trees, schema shape",
    process: "Parse text into values, then render nested objects and arrays safely.",
    command: "jq '.activeUnit.title' learner.json",
    output: '"Terminal foundations"',
    exercise: "Explain why parsed JSON is safer than searching raw text.",
  },
  {
    id: "csv-lab",
    name: "CSV Lab",
    category: "data",
    principle: "Tabular parsing",
    concept: "Rows, delimiters, quoting",
    process: "Read records while respecting quoted commas and newline rules.",
    command: "csvcut -c app,principle linux.csv",
    output: "Terminal,Command line interface\nFiles,Filesystem navigation",
    exercise: "Explain why splitting every comma is not a CSV parser.",
  },
  {
    id: "chart-studio",
    name: "Chart Studio",
    category: "data",
    principle: "Data visualization",
    concept: "Encoding, scale, domain, range",
    process: "Map data values into visual marks so patterns become easier to compare.",
    command: "plot cpu --window 60s",
    output: "line chart: 60 samples, max 71%",
    exercise: "Choose whether a bar, line, or scatter plot fits a time series.",
  },
  {
    id: "queue-monitor",
    name: "Queue Monitor",
    category: "data",
    principle: "Asynchronous work",
    concept: "Queues, consumers, backpressure",
    process: "Store jobs until workers can process them without overwhelming downstream systems.",
    command: "queue depth lesson-jobs",
    output: "depth 12\noldest 3s",
    exercise: "Explain why queues smooth spikes but can hide overload.",
  },
  {
    id: "cache-lab",
    name: "Cache Lab",
    category: "data",
    principle: "Caching",
    concept: "Key-value lookup, TTL, invalidation",
    process: "Serve repeated reads from fast storage while expiring or invalidating stale values.",
    command: "cache get lesson:terminal",
    output: "hit ttl=42s",
    exercise: "Explain why invalidation is harder than storing a value.",
  },
  {
    id: "notes",
    name: "Notes",
    category: "office",
    principle: "Information capture",
    concept: "Plain text, tags, retrieval",
    process: "Store small durable records and index tags for later lookup.",
    command: "note add linux 'signals stop processes'",
    output: "saved note #18 with tag linux",
    exercise: "Turn one observation into a searchable note.",
  },
  {
    id: "writer",
    name: "Writer",
    category: "office",
    principle: "Document model",
    concept: "Blocks, inline styles, serialization",
    process: "Represent a document as structured blocks rather than only screen pixels.",
    command: "writer export lesson.md",
    output: "exported 21 paragraphs to Markdown",
    exercise: "Explain why document structure matters for export.",
  },
  {
    id: "presentation",
    name: "Presentation",
    category: "office",
    principle: "Narrative sequencing",
    concept: "Slides, state, transitions",
    process: "Show one frame at a time and preserve order so a concept builds step by step.",
    command: "slides play linux-basics",
    output: "slide 1/12: Processes are running programs",
    exercise: "Write one slide title that teaches a single idea.",
  },
  {
    id: "calendar",
    name: "Calendar",
    category: "office",
    principle: "Time modeling",
    concept: "Intervals, recurrence, time zones",
    process: "Store events as intervals and expand recurrence rules into concrete occurrences.",
    command: "cal next review",
    output: "review: tomorrow 09:00 America/Sao_Paulo",
    exercise: "Explain why recurring meetings should not be stored as copied events.",
  },
  {
    id: "mail",
    name: "Mail",
    category: "office",
    principle: "Message passing",
    concept: "Queues, addresses, delivery states",
    process: "Send a message through relays, then track accepted, delivered, or bounced states.",
    command: "mailq",
    output: "0 queued\nlast delivery ok",
    exercise: "Explain why accepted does not always mean read.",
  },
  {
    id: "task-board",
    name: "Task Board",
    category: "office",
    principle: "Workflow state",
    concept: "Finite states, queues, WIP limits",
    process: "Move tasks across explicit states and constrain work in progress.",
    command: "task move linux-lab doing",
    output: "linux-lab -> doing",
    exercise: "Explain how a WIP limit exposes bottlenecks.",
  },
  {
    id: "pdf-viewer",
    name: "PDF Viewer",
    category: "office",
    principle: "Page description",
    concept: "Vector drawing, fonts, layout boxes",
    process: "Interpret page instructions and render them at the current zoom level.",
    command: "pdfinfo systems.pdf",
    output: "42 pages\npage size A4",
    exercise: "Explain why PDFs preserve layout better than plain text.",
  },
  {
    id: "image-viewer",
    name: "Image Viewer",
    category: "media",
    principle: "Raster display",
    concept: "Pixels, color channels, metadata",
    process: "Decode bytes into pixels and map those pixels onto the screen.",
    command: "identify screenshot.png",
    output: "PNG 1440x900 RGBA",
    exercise: "Explain why alpha is a channel, not a color.",
  },
  {
    id: "vector-draw",
    name: "Vector Draw",
    category: "media",
    principle: "Vector graphics",
    concept: "Paths, strokes, fills, transforms",
    process: "Store shapes as math instructions so they scale without pixelation.",
    command: "svg path inspect icon.svg",
    output: "3 paths, 2 strokes, 1 fill",
    exercise: "Explain why SVG icons stay sharp at different sizes.",
  },
  {
    id: "color-picker",
    name: "Color Picker",
    category: "media",
    principle: "Color encoding",
    concept: "RGB, HSL, contrast",
    process: "Sample a pixel, convert color spaces, and check readable contrast.",
    command: "pick --contrast #d8aa35 #11110f",
    output: "contrast 8.7:1 pass",
    exercise: "Explain why contrast is a usability requirement.",
  },
  {
    id: "screenshot",
    name: "Screenshot",
    category: "media",
    principle: "Visual evidence",
    concept: "Frame buffers, capture, regression checks",
    process: "Capture current pixels so future runs can compare the rendered surface.",
    command: "screenshot linux-lab.png",
    output: "saved linux-lab.png 1440x900",
    exercise: "Explain what a screenshot proves and what it does not.",
  },
  {
    id: "audio-mixer",
    name: "Audio Mixer",
    category: "media",
    principle: "Signal mixing",
    concept: "Streams, gain, clipping",
    process: "Combine audio streams by scaling samples and preventing overflow.",
    command: "amixer set Master 70%",
    output: "Master volume 70%",
    exercise: "Explain why two loud streams can clip when mixed.",
  },
  {
    id: "video-player",
    name: "Video Player",
    category: "media",
    principle: "Streaming playback",
    concept: "Codecs, buffers, frames",
    process: "Decode compressed frames ahead of time and present them on a clock.",
    command: "ffprobe lesson.mp4",
    output: "h264 1920x1080 30fps",
    exercise: "Explain why buffering prevents playback stalls.",
  },
  {
    id: "password-vault",
    name: "Password Vault",
    category: "security",
    principle: "Secret storage",
    concept: "Encryption, key derivation, locked state",
    process: "Derive a key from a passphrase and decrypt secrets only while unlocked.",
    command: "vault status",
    output: "locked: false\nentries: 24",
    exercise: "Explain why hashing a master password is not the same as encrypting a vault.",
  },
  {
    id: "hash-tool",
    name: "Hash Tool",
    category: "security",
    principle: "One-way fingerprints",
    concept: "Hash functions, integrity, collisions",
    process: "Map bytes to a fixed-size digest that changes when input changes.",
    command: "sha256sum lesson.txt",
    output: "8f14e45fceea167a5a36dedd4bea2543  lesson.txt",
    exercise: "Explain why a hash checks integrity but does not hide content.",
  },
  {
    id: "key-manager",
    name: "Key Manager",
    category: "security",
    principle: "Public key cryptography",
    concept: "Key pairs, signing, verification",
    process: "Use a private key to sign and a public key to verify without sharing the secret.",
    command: "ssh-keygen -lf ~/.ssh/id_ed25519.pub",
    output: "256 SHA256:lab learner@linux-lab",
    exercise: "Explain which key is safe to copy to a server.",
  },
  {
    id: "permissions",
    name: "Permissions",
    category: "security",
    principle: "Access control",
    concept: "Read, write, execute bits",
    process: "Check owner, group, and other mode bits before permitting file operations.",
    command: "stat -c %A script.sh",
    output: "-rwxr-x---",
    exercise: "Explain who can execute this file.",
  },
  {
    id: "sandbox",
    name: "Sandbox",
    category: "security",
    principle: "Least privilege",
    concept: "Capabilities, isolation, allowed effects",
    process: "Run code with only the permissions it needs and deny everything else.",
    command: "sandbox run --net=off demo",
    output: "demo finished\nnetwork denied by policy",
    exercise: "Explain why denying by default is safer than allowing by default.",
  },
  {
    id: "audit-trail",
    name: "Audit Trail",
    category: "security",
    principle: "Accountability",
    concept: "Immutable records, actors, actions",
    process: "Record who did what and when so sensitive actions can be reviewed later.",
    command: "auditctl recent --user learner",
    output: "learner changed permissions on script.sh",
    exercise: "Explain why audit logs must be append-only.",
  },
  {
    id: "algorithm-visualizer",
    name: "Algorithm Visualizer",
    category: "learning",
    principle: "Algorithm tracing",
    concept: "State transitions and complexity",
    process: "Step through each operation and show how input state changes over time.",
    command: "trace binary-search 1 3 5 8 13 --find 8",
    output: "mid=5 low moves right\nmid=8 found",
    exercise: "Explain why binary search needs sorted input.",
  },
  {
    id: "memory-lab",
    name: "Memory Lab",
    category: "learning",
    principle: "Memory model",
    concept: "Stack, heap, references, ownership",
    process: "Allocate values, pass references, and release memory when ownership ends.",
    command: "mem trace allocate buffer",
    output: "stack frame main\nheap block buffer[1024]",
    exercise: "Explain which data outlives the function call.",
  },
  {
    id: "binary-studio",
    name: "Binary Studio",
    category: "learning",
    principle: "Binary representation",
    concept: "Bits, bytes, base conversion",
    process: "Convert values between human notation and machine-friendly bit patterns.",
    command: "bin 42",
    output: "00101010",
    exercise: "Explain why 8 bits can store 256 different values.",
  },
  {
    id: "regex-lab",
    name: "Regex Lab",
    category: "learning",
    principle: "Pattern matching",
    concept: "Automata, tokens, greedy matching",
    process: "Compile a pattern into a matcher and scan input left to right.",
    command: "regex '^lab-[0-9]+$' lab-42",
    output: "match true",
    exercise: "Explain what the anchors change in the pattern.",
  },
  {
    id: "scheduler",
    name: "Scheduler",
    category: "learning",
    principle: "CPU scheduling",
    concept: "Queues, fairness, latency, throughput",
    process: "Choose which runnable process gets CPU time next according to a policy.",
    command: "schedule round-robin P1 P2 P3",
    output: "P1 -> P2 -> P3 -> P1",
    exercise: "Explain what round-robin optimizes and what it sacrifices.",
  },
  {
    id: "architecture",
    name: "Computer Architecture",
    category: "learning",
    principle: "Fetch-decode-execute",
    concept: "Registers, instructions, memory bus",
    process: "Fetch an instruction, decode operands, execute it, then update registers.",
    command: "cpu step ADD R1,R2",
    output: "R1 = R1 + R2\npc += 1",
    exercise: "Explain why a program counter is state.",
  },
  {
    id: "manual",
    name: "Linux Manual",
    category: "learning",
    principle: "Self-directed lookup",
    concept: "Documentation, examples, flags",
    process: "Find the contract for a command before guessing its behavior.",
    command: "man chmod | head",
    output: "CHMOD(1) user commands\nchange file mode bits",
    exercise: "Look up one flag and restate it in your own words.",
  },
] as const satisfies readonly LinuxApp[]

// ⚡ Bolt: Pre-compute indexes to convert O(n) lookups and filters to O(1) cache lookups,
// preventing new array allocations and O(n) scans during every render loop.
const appsById = new Map<string, LinuxApp>()
const appsByCategory = new Map<LinuxAppCategory, LinuxApp[]>()

for (const app of linuxApps) {
  appsById.set(app.id, app)

  const categoryApps = appsByCategory.get(app.category)
  if (categoryApps === undefined) {
    appsByCategory.set(app.category, [app])
  } else {
    categoryApps.push(app)
  }
}

export function getLinuxApp(id: string): LinuxApp {
  const app = appsById.get(id)
  if (app !== undefined) {
    return app
  }

  // ponytail: catalog is a static const; empty only if someone deletes the array
  if (linuxApps[0] === undefined) {
    throw new Error("Linux Lab needs at least one app.")
  }
  return linuxApps[0]
}

export function getLinuxAppsForCategory(category: LinuxAppCategoryFilter): readonly LinuxApp[] {
  if (category === "all") {
    return linuxApps
  }

  return appsByCategory.get(category) ?? []
}
