#!/usr/bin/env bash
# AI-native SDLC hook (PreToolUse: Edit|Write|MultiEdit)
# Blocks edits to generated/derived paths. These are regenerated by tooling
# (see AGENTS.md NOTES) and must never be hand-edited.
# Override: set SDLC_ALLOW_DERIVED_EDIT=1 (owner-approved regeneration only).
set -euo pipefail

INPUT="$(cat)"
FILE="$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // .tool_input.notebook_path // ""')"

[ -z "$FILE" ] && exit 0

BLOCK_PATTERNS=(
  'node_modules/'
  '/dist/'
  '/build/'
  '/target/'
  '/coverage/'
  '/.codegraph/'
  '/graphify-out/'
  '/.mavis/'
  '/.opencode/node_modules/'
  '/.loops/'
  '/test-results/'
  '/playwright-report/'
  'aidevschool.egg-info/'
  '.min.'          # bundled/minified assets
  '.pyc'
)

for PAT in "${BLOCK_PATTERNS[@]}"; do
  if [[ "$FILE" == *"$PAT"* ]]; then
    if [ "${SDLC_ALLOW_DERIVED_EDIT:-0}" = "1" ]; then
      exit 0
    fi
    >&2 echo "BLOCKED: '$FILE' is a generated/derived path ($PAT)."
    >&2 echo "It is regenerated by tooling (e.g. python3 -m learner.substrate) — edit the canonical source instead."
    >&2 echo "If the owner explicitly approved regeneration, rerun with SDLC_ALLOW_DERIVED_EDIT=1."
    exit 2
  fi
done

exit 0
