// AUTO-GENERATED by learner/substrate/dashboard_snapshot.py.
// DO NOT EDIT BY HAND — run `python3 -m learner.substrate` to regenerate.
// Read-only review slice for pixelDojo: the game reads scheduling truth here,
// emits evidence only, and never marks mastery (GameNeverMarksMastery).
// Generated: 2026-07-05T21:27:04.479403Z

import type { ReviewSlice } from "../game/review/types"

export const reviewSlice: ReviewSlice = {
  nextReviews: [
    {
      unitId: "P-001",
      title: "Reivindicar domínio a partir de trabalho de documentação/dashboard",
      dueIn: "today",
      reason: "recurring-trap",
    },
  ],
  streak: {
    current: 1,
    longest: 1,
    lastGateDate: "2026-07-05",
    freezesEquipped: 2,
    freezesMax: 2,
  },
}
