// AUTO-GENERATED by learner/substrate/dashboard_snapshot.py.
// DO NOT EDIT BY HAND — run `python3 -m learner.substrate` to regenerate.
// Read-only review slice for pixelDojo: the game reads scheduling truth here,
// emits evidence only, and never marks mastery (GameNeverMarksMastery).

import type { ReviewSlice } from "../game/review/types"

export const reviewSlice: ReviewSlice = {
  nextReviews: [
    {
      unitId: "U0-sonda-rate-limiter-robustness",
      title: "GATEKEEPER: token-bucket rate limiter robustness",
      dueIn: "overdue 42d",
      reason: "overdue",
    },
    {
      unitId: "U2-key-value-store",
      title: "KV WAREHOUSE: hash-map-backed CRUD with TTL expiration",
      dueIn: "overdue 3d",
      reason: "overdue",
    },
    {
      unitId: "P-001",
      title: "Reivindicar domínio a partir de trabalho de documentação/dashboard",
      dueIn: "today",
      reason: "recurring-trap",
    },
  ],
  streak: {
    current: 0,
    longest: 2,
    lastGateDate: "2026-08-13",
    freezesEquipped: 0,
    freezesMax: 2,
  },
}
