'use strict';
const test=require('node:test'),a=require('node:assert/strict');
const C=require('../src/tlc-core'),D=require('../src/tlc-data'),Q=require('../src/core'),QD=require('../src/data');
const oracle=require('./fixtures/tlc-decisions.json'),oldOracle=require('./fixtures/accepted-decisions.json');
const tasks=D.modules.flatMap(m=>m.tasks);
for(const t of tasks){
 test('TLC fixed acceptance: '+t.id,()=>a.equal(C.validate(t,oracle[t.id]).ok,true));
 test('TLC empty is not an attempt: '+t.id,()=>{const s=C.empty();for(const m of D.modules)for(const prev of m.tasks){if(prev.id===t.id)break;C.submit(s,prev.id,oracle[prev.id]);}const r=C.submit(s,t.id,C.cleanAnswer(t,null));a.equal(r.ok,false);a.equal(r.empty,true);a.equal(s.attempts[t.id]||0,0);});
 test('TLC has free teaching and source: '+t.id,()=>{a.ok(t.concept.length>=100);a.ok(t.example.length>60);a.ok(D.modules.find(m=>m.tasks.includes(t)).source.startsWith('https://agent-skills.techleads.club/skills/'));});
 if(t.type==='choice')for(const o of t.options.filter(o=>o.id!==t.answer))test('TLC rejects distractor '+t.id+':'+o.id,()=>a.equal(C.validate(t,o.id).ok,false));
}
test('TLC exactly 16 tasks in 4 modules, fixed oracle covers all',()=>{a.equal(D.modules.length,4);a.equal(tasks.length,16);a.deepEqual(Object.keys(oracle),tasks.map(t=>t.id));a.equal(new Set(tasks.map(t=>t.id)).size,16);});
test('TLC complete without unlocking base campaign',()=>{const s=C.empty();for(const t of tasks)a.equal(C.submit(s,t.id,oracle[t.id]).ok,true);a.deepEqual(C.stats(s),{done:16,total:16,xp:1600,modules:4});});
test('TLC modules independent; later task within module is not',()=>{const s=C.empty();a.equal(C.canOpen(s,'tlc-review'),true);a.equal(C.submit(s,'tlc-severity',oracle['tlc-severity']).locked,true);a.equal(C.canOpen(s,'tlc-verdict'),false);});
test('TLC replay cannot farm XP, mistakes on replay cannot lower it',()=>{const s=C.empty();const t=tasks[0];C.submit(s,t.id,'stack');a.equal(s.attempts[t.id],1);C.submit(s,t.id,oracle[t.id]);a.equal(C.stats(s).xp,85);C.submit(s,t.id,oracle[t.id]);C.submit(s,t.id,'stack');a.equal(C.stats(s).xp,85);a.equal(s.attempts[t.id],1);});
for(const suite of ['happy','placebo','contract'])for(const patch of ['original','scoped','denyAll'])test(`TLC lab matrix ${suite}/${patch}`,()=>a.equal(C.runLab(suite,patch).ok,suite==='contract'&&patch==='scoped'));
test('TLC strong lab executes fifteen assertions: red green red',()=>{const r=C.runLab('contract','scoped');a.deepEqual(r.versions.map(v=>v.exitCode),[1,0,1]);a.equal(r.versions.flatMap(v=>v.checks).length,15);a.deepEqual(r.versions[0].checks.filter(c=>!c.pass).map(c=>c.id),['cross-a','cross-b']);a.deepEqual(r.versions[2].checks.filter(c=>!c.pass).map(c=>c.id),['own-a','own-b']);});
test('TLC happy path suite cannot see the old defect',()=>a.equal(C.runLab('happy','scoped').versions[0].exitCode,0));
test('TLC placebo passes the mutant and is rejected',()=>{const r=C.runLab('placebo','scoped');a.deepEqual(r.versions.map(v=>v.exitCode),[0,0,0]);a.equal(r.ok,false);});
for(const pair of [['evil','scoped'],['contract','constructor'],['contract','__proto__'],[null,null]])test('TLC lab invalid input '+JSON.stringify(pair),()=>{const r=C.runLab(...pair);a.equal(r.ok,false);a.deepEqual(r.versions,[]);});
test('TLC review rejects unsupported finding and wrong verdict',()=>{const t=tasks.find(t=>t.type==='reviewlab');for(const v of [{findings:['F1','F4'],verdict:'REQUEST_CHANGES'},{findings:['F1'],verdict:'APPROVE'},{findings:['F1','F1'],verdict:'REQUEST_CHANGES'}])a.equal(C.validate(t,v).ok,false);});
test('TLC verdict reflects prior blockers even without new findings',()=>{a.equal(C.verdict({blocker:1}), 'REQUEST_CHANGES');a.equal(C.verdict({shouldFix:1}), 'COMMENT');a.equal(C.verdict(), 'APPROVE');});
test('TLC normalized local progress is contiguous per module',()=>{const s=C.empty();s.done['tlc-verdict']={score:500};s.done['tlc-review']={score:500};s.done['evil']={score:500};const n=C.normalize(s);a.equal(n.done['tlc-verdict'],undefined);a.equal(n.done.evil,undefined);a.equal(n.done['tlc-review'].score,100);});
test('TLC sanitized drafts ignore unknown/prototype fields and duplicates',()=>{const s=C.empty();s.drafts['tlc-design']=['decision','decision','<img>'];s.drafts['tlc-proof-lab']={suite:'contract',patch:'__proto__',proof:'fake'};const n=C.normalize(s);a.deepEqual(n.drafts['tlc-design'],['decision']);a.deepEqual(n.drafts['tlc-proof-lab'],{suite:'contract',patch:''});});
test('TLC unknown version becomes blank, input not mutated',()=>{const x={version:99,done:{x:{score:100}}};a.deepEqual(C.normalize(x),C.empty());a.equal(x.version,99);});
test('TLC backup roundtrip preserves old 1800XP and new 1600XP',()=>{const s=Q.empty();for(const t of QD.missions.flatMap(m=>m.tasks))Q.complete(s,QD,t,oldOracle[t.id]);for(const t of tasks)C.submit(s.tlc,t.id,oracle[t.id]);s.transfer.intent='Meu contexto';const n=Q.importBackup(JSON.stringify(Q.makeBackup(s,QD)),QD);a.equal(Q.stats(n,QD).xp,1800);a.equal(C.stats(n.tlc).xp,1600);a.equal(n.transfer.intent,'Meu contexto');});
test('TLC old v1.1 backup migrates without taking away achievements',()=>{const s=Q.empty();Q.complete(s,QD,QD.missions[0].tasks[0],oldOracle.intent);delete s.tlc;const n=Q.importBackup(JSON.stringify({format:'sdlc-quest-backup',backupVersion:1,appVersion:'1.1.0',state:s}),QD);a.equal(Q.stats(n,QD).done,1);a.equal(C.stats(n.tlc).done,0);a.equal(n.done.intent.score,100);});
test('TLC persisted proof results cannot be forged',()=>{const s=C.empty();s.drafts['tlc-proof-lab']={suite:'happy',patch:'scoped',ok:true,exitCode:0};const n=C.normalize(s);a.equal(n.drafts['tlc-proof-lab'].ok,undefined);a.equal(C.validate(tasks.find(t=>t.id==='tlc-proof-lab'),n.drafts['tlc-proof-lab']).ok,false);});
test('TLC attribution and no pretending installation or official gate output',()=>{a.match(D.notice,/Adaptação didática/);a.match(D.notice,/CC BY 4.0/);a.equal(C.reviewArtifact().simulation,true);a.match(C.reviewArtifact().publication,/Nenhuma review/);a.equal(D.install,'npx @tech-leads-club/agent-skills install --skill tlc-discover tlc-plan tlc-implement the-judge');});
