/* UI controller. Persistent progression, transient workbench state and renderer stay separate. */
(function(){
'use strict';
const D=QuestData,C=QuestCore,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bossNames={monster:'MONSTRO DO DIFF',weakener:'ENFRAQUECEDOR DE TESTES',secret:'VAZADOR DE SEGREDOS',outage:'INCIDENTE DAS 3H',editor:'EDITOR DE GUARDRAILS'};
let storageOK=true,saveNotice='',state=C.empty(),active=null,world=null,toastTimer=null,audio=null,infoTab='glossary',pendingImport=null,importToken=0;
try { const raw=localStorage.getItem(C.key);if(raw){try{state=C.normalize(JSON.parse(raw),D);}catch{saveNotice='Save inválido: uma nova campanha foi iniciada.';}} }catch{storageOK=false;}
if(matchMedia('(prefers-reduced-motion: reduce)').matches)state.motion=false;
const play=$('#play-dialog'),info=$('#info-dialog');
function save(){try{localStorage.setItem(C.key,JSON.stringify(state));storageOK=true;}catch{storageOK=false;}updateSave();document.dispatchEvent(new Event('quest-state-changed'));}
function updateSave(){$('#save-status').textContent=storageOK?'✓ Progresso salvo neste navegador':'Modo temporário · armazenamento indisponível';}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4200);}
function sound(kind='tap'){
 if(!state.sound)return;
 try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const notes=kind==='win'?[523.25,659.25,783.99]:kind==='wrong'?[196,164.81]:[440];notes.forEach((freq,i)=>{const o=audio.createOscillator(),g=audio.createGain(),at=audio.currentTime+i*.085;o.type='sine';o.frequency.setValueAtTime(freq,at);g.gain.setValueAtTime(0,at);g.gain.linearRampToValueAtTime(.04,at+.012);g.gain.exponentialRampToValueAtTime(.001,at+.15);o.connect(g);g.connect(audio.destination);o.start(at);o.stop(at+.16);});}catch{state.sound=false;save();}
}
function syncModal(){const opened=!!document.querySelector('dialog[open]');document.body.classList.toggle('modal-open',opened);world?.setPaused(opened);}
document.addEventListener('quest-modal',syncModal);
function openDialog(dialog){if(!dialog.open)dialog.showModal();syncModal();dialog.scrollTop=0;}
play.addEventListener('close',()=>{syncModal();renderHome();if(!document.querySelector('dialog[open]'))$('#start-mission')?.focus({preventScroll:true});});info.addEventListener('close',syncModal);
for(const dialog of [play,info])dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();});
function currentAvailable(){return Math.min(C.stats(state,D).completed,5);}
function chooseMission(i){if(i<0||i>=D.missions.length)return;const fromNav=document.activeElement?.hasAttribute('data-stage');clearTimeout(toastTimer);$('#toast').classList.remove('visible');state.selected=i;save();renderHome();if(fromNav)$(`[data-stage="${i}"]`)?.focus({preventScroll:true});sound();if(!C.canOpen(state,D,i))toast(`Estação ${i+1}: conclua ${D.missions[i-1]?.name.toLowerCase()} para desbloquear.`);}
function renderHome(){
 const st=C.stats(state,D),m=D.missions[state.selected],open=C.canOpen(state,D,state.selected),finished=m.tasks.every(t=>state.done[t.id]);
 $('#xp').textContent=st.xp.toLocaleString('pt-BR');$('#progress-fraction').textContent=`${st.done}/18`;$('#bag-count').textContent=st.completed;
 $('#rank').textContent=st.completed===6?'GUARDIÃO DO RELEASE':st.completed>=4?'ENGENHEIRO DE EVIDÊNCIAS':st.completed>=2?'ARQUITETO EM FORMAÇÃO':'APRENDIZ DE ENGENHARIA';
 $('#stage-nav').innerHTML=D.missions.map((mission,i)=>{const allowed=C.canOpen(state,D,i),complete=mission.tasks.every(t=>state.done[t.id]);return `<button class="stage-node" data-stage="${i}" aria-current="${i===state.selected}" data-locked="${!allowed}" aria-label="${i+1}. ${esc(mission.name)}: ${complete?'concluída; revisar':allowed?'disponível':'bloqueada; visualizar resumo'}"><span class="node-icon" aria-hidden="true">${complete?'✓':mission.glyph}</span><span class="node-label"><small>${String(i+1).padStart(2,'0')} ${mission.en}</small><strong>${mission.name}</strong></span>${complete?'<span class="status-tick">✓</span>':''}</button>`;}).join('');
 $('#mission-panel').innerHTML=`<div class="mission-kicker"><span>${finished?'MISSÃO CONCLUÍDA':open?'MISSÃO DISPONÍVEL':'ESTAÇÃO BLOQUEADA'}</span><span class="mission-number">${String(state.selected+1).padStart(2,'0')} / 06</span></div><div class="mission-icon" aria-hidden="true">${m.glyph}</div><h2>${esc(m.title)}</h2><p>${esc(m.brief)}</p><div class="mission-meta"><span class="tag">3 desafios</span><span class="tag">${m.boss?'1 chefe':'Até 300 XP'}</span><span class="tag">${esc(m.artifact)}</span></div><ol class="task-preview">${m.tasks.map((t,i)=>`<li class="${state.done[t.id]?'finished':''}"><span>${state.done[t.id]?'✓':i+1}</span>${esc(t.title.replace('Equipe-se contra o ','').replace('Enfrente o ','').replace('Derrote o ',''))}</li>`).join('')}</ol><button class="primary" id="start-mission" ${!open?'disabled':''}>${finished?'Revisitar missão':m.tasks.some(t=>state.done[t.id])?'Continuar missão':'Iniciar missão'} <span aria-hidden="true">→</span></button><p class="mission-note">${open?'Sem cronômetro. Aprenda no seu ritmo.':`Conclua a estação ${state.selected} para entrar.`}</p>${QuestTLCData.stageMap[state.selected].length?`<div class="tlc-station-links"><span>PRATIQUE COM AS SKILLS</span>${QuestTLCData.stageMap[state.selected].map(id=>`<button class="tlc-station-link" data-open-tlc="${id}">${QuestTLCData.modules.find(m=>m.id===id).skill} ↗</button>`).join('')}</div>`:''}${st.completed===6?'<button class="text-button" id="journey-btn">Ver resumo da jornada ↗</button>':''}`;
 $('#start-mission').addEventListener('click',()=>openMission(state.selected));$('#journey-btn')?.addEventListener('click',showFinal);
 document.body.classList.toggle('reduce-motion',!state.motion);$('#motion-btn').textContent=state.motion?'Ⅱ Pausar cenário':'▷ Animar cenário';$('#motion-btn').setAttribute('aria-pressed',String(!state.motion));updateSave();world?.refresh();
}
$('#stage-nav').addEventListener('click',e=>{const b=e.target.closest('[data-stage]');if(b)chooseMission(Number(b.dataset.stage));});
function initialAnswer(task){if(task.type==='incident')return C.freshIncident();if(['select','diff','order'].includes(task.type))return [];if(['classify','gate'].includes(task.type))return {};return '';}
function openMission(mi){
 if(!C.canOpen(state,D,mi)){toast('Conclua a estação anterior.');return;}
 const pending=D.missions[mi].tasks.findIndex(t=>!state.done[t.id]);state.selected=mi;save();renderHome();openTask(mi,pending<0?0:pending);openDialog(play);
}
function openTask(mi,ti){
 const task=D.missions[mi].tasks[ti];active={mi,ti,answer:structuredClone(state.drafts[task.id]??initialAnswer(task)),success:false,feedback:null,hintOpen:false,results:null,award:0};
 if(task.type==='incident')active.answer=state.done[task.id]?C.freshIncident():C.restoreIncident(state.drafts[task.id]);renderTask();play.scrollTop=0;requestAnimationFrame(()=>$('#dialog-title')?.focus({preventScroll:true}));
}
function getTask(){return D.missions[active.mi].tasks[active.ti];}
function draft(){if(!active)return;const t=getTask();state.drafts[t.id]=t.type==='incident'?C.restoreIncident(active.answer):structuredClone(active.answer);save();}
function renderTask(){
 const t=getTask(),m=D.missions[active.mi];
 $('#dialog-content').innerHTML=`<div class="dialog-top"><span class="eyebrow">${String(active.mi+1).padStart(2,'0')} / ${m.en} <span class="sep">/</span> ${esc(m.place)}</span><button class="close-btn" data-action="close" aria-label="Salvar e voltar ao mapa">×</button></div><div class="dialog-main"><div class="lesson-top"><div class="lesson-head"><div class="step-dots" aria-label="Desafio ${active.ti+1} de 3">${m.tasks.map((_,i)=>`<span class="${i<=active.ti?'active':''}"></span>`).join('')}</div>${t.boss?`<span class="boss-kicker">BATALHA DE CHEFE · ${bossNames[t.boss]}</span>`:'<span class="eyebrow">MISSÃO WEBHOOK-042</span>'}<h2 id="dialog-title" tabindex="-1">${esc(t.title)}</h2><p>${esc(t.lead)}</p></div>${t.boss?'<canvas class="boss-portrait" id="boss-portrait" aria-hidden="true"></canvas>':''}</div><details class="lesson-primer"><summary>Estudar o conceito · grátis</summary><p>${esc(D.primers[t.id].concept)}</p><p><strong>Exemplo:</strong> ${esc(D.primers[t.id].example)}</p></details><div class="instruction">${esc(t.instruction||'Escolha a decisão e observe suas consequências.')}</div><div id="exercise">${exerciseHTML(t)}</div><div id="test-results"></div><div id="hint-slot"></div><div id="feedback-slot" aria-live="polite"></div><div class="dialog-actions"><button class="hint-button" data-action="hint">? Dica da solução <span>(−20 XP)</span></button><div class="action-main"><span class="xp-note">${state.done[t.id]?'Revisão · sem XP adicional':'Até '+C.score(state.attempts[t.id],state.hints[t.id])+' XP'}</span><button class="primary" id="verify-btn" data-action="verify">${verifyLabel(t)}</button></div></div></div>`;
 if(t.boss)QuestBoss($('#boss-portrait'),t.boss,active.success);renderFeedback();renderHint();renderTestResults();if(active.success)freezeExercise();
}
function verifyLabel(t){if(active.success)return active.ti===2?'Concluir missão →':'Próximo desafio →';return t.type==='patch'?'Executar microtestes ▶':t.type==='gate'?'Solicitar release →':t.type==='incident'?'Concluir resposta →':'Verificar decisão →';}
function optionHTML(o,index,{multi=false,patch=false}={}){const selected=Array.isArray(active.answer)?active.answer.includes(o.id):active.answer===o.id;return `<button class="option" data-option="${o.id}" aria-pressed="${selected}">${multi?'<span class="check" aria-hidden="true">✓</span>':`<span class="option-index" aria-hidden="true">${String(index+1).padStart(2,'0')}</span>`}<div><strong>${esc(o.label)}</strong>${o.code?`<pre>${esc(o.code)}</pre>`:''}${o.text?`<p>${esc(o.text)}</p>`:''}</div>${o.lines?`<span class="line-count">+${o.lines}</span>`:''}</button>`;}
function exerciseHTML(t){
 const options=t.options?C.shuffled(t.options,t.id):null;
 if(t.type==='select')return `<div class="cards">${options.map((o,i)=>optionHTML(o,i,{multi:true})).join('')}</div>`;
 if(t.type==='diff')return `<div id="diff-budget">${budgetHTML(t)}</div><div class="cards">${options.map((o,i)=>optionHTML(o,i,{multi:true})).join('')}</div>`;
 if(t.type==='choice')return `${t.chart?chartHTML(8):''}<div class="options-list">${options.map((o,i)=>optionHTML(o,i)).join('')}</div>`;
 if(t.type==='patch')return `<div class="cards">${options.map((o,i)=>optionHTML(o,i,{patch:true})).join('')}</div>`;
 if(t.type==='classify')return `<div class="classify-list">${t.items.map((item,i)=>`<div class="classify-row" data-item="${item.id}"><label for="classify-${item.id}">${esc(item.text)}</label><select id="classify-${item.id}" data-field="${item.id}"><option value="">Escolha a categoria…</option>${C.shuffled(t.groups,t.id+item.id).map(([id,label])=>`<option value="${id}" ${active.answer[item.id]===id?'selected':''}>${esc(label)}</option>`).join('')}</select></div>`).join('')}</div>`;
 if(t.type==='order')return `<div class="order-workbench"><div class="order-zone"><div class="zone-title"><span>SUA SEQUÊNCIA · ${active.answer.length}/${t.steps.length}</span><button class="small-btn" data-action="undo" ${active.answer.length?'':'disabled'}>Desfazer ↶</button></div>${active.answer.length?active.answer.map((id,i)=>`<div class="order-item"><b>${i+1}</b><span>${esc(t.steps.find(s=>s.id===id)?.text)}</span></div>`).join(''):'<div class="empty-order">O primeiro passo começa aqui.<br>Escolha uma peça ao lado ou abaixo.</div>'}</div><div class="order-options">${C.shuffled(t.steps,t.id).map(s=>`<button class="option" data-step="${s.id}" ${active.answer.includes(s.id)?'disabled':''}><span class="option-index">＋</span>${esc(s.text)}</button>`).join('')}</div></div>`;
 if(t.type==='gate')return `<div class="gate-revision"><span>CANDIDATA:</span><del>7c9e2a1</del><span>→</span><code>8d0fa42</code><span>POLÍTICA: p4</span></div><div class="gate-grid">${t.fields.map((f,i)=>`<div class="gate-field" data-item="${f.id}"><label for="gate-${f.id}"><b>${String(i+1).padStart(2,'0')}</b>${esc(f.label)}</label><select id="gate-${f.id}" data-field="${f.id}"><option value="">Selecione uma entrada…</option>${f.options.map(([id,text])=>`<option value="${id}" ${active.answer[f.id]===id?'selected':''}>${esc(text)}</option>`).join('')}</select></div>`).join('')}</div>`;
 if(t.type==='incident')return incidentHTML();return '';
}
function budgetHTML(t){const n=t.options.filter(o=>active.answer.includes(o.id)).reduce((s,o)=>s+o.lines,0);return `<div class="diff-budget ${n>t.budget?'over':''}"><div class="budget-number">${n} <small>/ ${t.budget}</small></div><div class="budget-info"><span>LINHAS NA SUA PR · ORÇAMENTO DIDÁTICO</span><div class="meter"><span style="width:${Math.min(100,n/t.budget*100)}%"></span></div></div></div>`;}
function chartHTML(burn){const points=burn===8?'18,81 72,76 125,79 178,73 231,75 284,56 337,42 390,37 443,24 496,21 549,17 600,14':'18,23 72,28 125,35 178,31 231,39 284,45 337,42 390,53 443,50 496,52 549,49 600,48';return `<svg class="metric-plot" viewBox="0 0 620 108" role="img" aria-label="Gráfico fictício: consumo do orçamento de erro segue acima do objetivo. Burn rate atual ${burn} vezes."><path d="M18 25H600 M18 52H600 M18 81H600" stroke="#2c4547" stroke-width="1"/><path d="M18 87H600" stroke="#96c9a0" stroke-dasharray="4 6"/><polyline points="${points}" fill="none" stroke="#f0ba8e" stroke-width="2.5"/><text x="22" y="17" fill="#b1c9bb" font-size="8" font-family="monospace">DADOS FICTÍCIOS / BURN RATE</text><text x="595" y="100" fill="#84b59b" text-anchor="end" font-size="8" font-family="monospace">OBJETIVO: ≤ 1×</text></svg><div class="plot-caption">Sinal ilustrativo, sem escala temporal operacional. Não é um detector configurável nem uma regra de rollback.</div>`;}
function incidentHTML(){const s=active.answer,labels={alert:'ALERTA',diagnosed:'DIAGNÓSTICO VALIDADO',mitigated:'MITIGAÇÃO APLICADA',verified:'DEGRADAÇÃO PERSISTE',escalated:'ESCALADO · AINDA ABERTO',complete:'ESCALADO E REGISTRADO'};return `${chartHTML(s.burn)}<div class="incident-console"><div class="incident-status"><span>● ${labels[s.phase]}</span><span>AÇÕES AUTOMÁTICAS: ${s.actions}/1</span></div><div class="incident-log" aria-live="polite">${s.log.map(line=>`<p>${esc(line)}</p>`).join('')}</div></div><div class="incident-actions">${[['diagnose','⌕ Diagnosticar'],['pause','Ⅱ Pausar novos retries'],['verify','✓ Verificar resultado'],['rollback','↶ Fazer rollback'],['escalate','↑ Acionar plantonista'],['record','▤ Registrar nova intenção']].map(([id,label])=>`<button data-incident="${id}" class="${id==='rollback'?'danger-btn':''}">${label}</button>`).join('')}</div>`;}
function freezeExercise(){$$('#exercise button, #exercise select').forEach(b=>b.disabled=true);$('#verify-btn').textContent=verifyLabel(getTask());$('#verify-btn').disabled=false;}
function renderHint(){const t=getTask();$('#hint-slot').innerHTML=active.hintOpen?`<div class="hint"><strong>Mentor · </strong>${esc(t.hint)}<br><span>${esc(D.missions[active.mi].lesson)}</span></div>`:'';const b=$('[data-action="hint"]');if(b){b.innerHTML=active.hintOpen?'Ocultar dica':`? Dica da solução <span>(${state.done[t.id]||state.hints[t.id]?'sem custo adicional':'−20 XP'})</span>`;}}
function renderFeedback(){
 const f=active.feedback,t=getTask(),el=$('#feedback-slot');if(!el)return;
 el.innerHTML=f?`<div class="feedback ${f.ok?'good':''}" tabindex="-1"><strong>${active.success?(t.boss?'Chefe superado. Defesa demonstrada.':'Decisão validada.'):(f.ok?'Console atualizado.':f.empty?'Antes de verificar:':'O gate segurou a mudança.')} ${active.success&&active.award?`+${active.award} XP`:''}</strong>${esc(f.message)}${active.success?`<div class="takeaway"><b>NA SUA PRÓXIMA PR</b>${esc(t.takeaway)}</div>`:''}</div>`:'';
 if(f&&!f.ok&&!f.empty&&['classify','gate'].includes(t.type)){$$('[data-item]').forEach(row=>{const id=row.dataset.item,expected=t.type==='classify'?t.items.find(i=>i.id===id).answer:t.answer[id];row.classList.toggle('invalid',active.answer[id]!==expected);row.querySelector('select')?.setAttribute('aria-invalid',String(active.answer[id]!==expected));});}
}
function renderTestResults(){const el=$('#test-results');if(!active.results){el.innerHTML='';return;}el.innerHTML=`<div class="test-console"><strong>VERIFICADOR LOCAL · ${active.results.filter(r=>r.pass).length}/4 checks aprovados</strong><div>Fixtures fictícias. Expectativas independentes da alteração escolhida.</div>${active.results.map(r=>`<div class="test-result"><span class="${r.pass?'yes':'no'}">${r.pass?'PASS':'FAIL'}</span><span>${esc(r.label)}${!r.pass?` <span class="result-actual">(esperado ${esc(r.expected??'null')}; recebido ${esc(r.actual??'null')})</span>`:''}</span></div>`).join('')}</div>`;}
function clearFeedback(){active.feedback=null;$('#feedback-slot').innerHTML='';$$('.invalid').forEach(el=>el.classList.remove('invalid'));$$('[aria-invalid]').forEach(el=>el.removeAttribute('aria-invalid'));}
function verify(){
 if(active.success){nextTask();return;}
 const t=getTask();if(t.type==='incident'&&active.answer.phase!=='complete'){active.feedback={ok:false,message:'O incidente ainda exige ações. Use o console; validar exige diagnóstico, mitigação limitada, verificação, escalonamento e registro.'};renderFeedback();return;}
 if(!C.hasAnswer(t,active.answer)){active.feedback={ok:false,empty:true,message:'Escolha uma resposta antes de verificar. Nenhuma tentativa ou XP foi descontado.'};renderFeedback();return;}
 const existing=!!state.done[t.id];if(t.type==='patch'){active.results=C.runPatch(active.answer);renderTestResults();}
 const r=C.complete(state,D,t,active.answer);active.feedback=r;
 if(r.ok){active.success=true;active.award=existing?0:state.done[t.id].score;sound('win');freezeExercise();if(t.boss)QuestBoss($('#boss-portrait'),t.boss,true);}
 else{if(!existing)state.attempts[t.id]=(state.attempts[t.id]||0)+1;sound('wrong');}
 draft();renderHint();renderFeedback();const xpNote=$('.xp-note');if(xpNote)xpNote.textContent=existing?'Revisão · sem XP adicional':active.success?`${active.award} XP conquistados`:`Até ${C.score(state.attempts[t.id],state.hints[t.id])} XP`;renderHome();
 requestAnimationFrame(()=>{const f=$('#feedback-slot');f.scrollIntoView({behavior:'instant',block:'nearest'});if(document.activeElement===document.body||document.activeElement?.disabled)$('#verify-btn')?.focus({preventScroll:true});});
}
function nextTask(){if(active.ti<2)openTask(active.mi,active.ti+1);else showReward(active.mi);}
function showReward(mi){
 const m=D.missions[mi],xp=m.tasks.reduce((n,t)=>n+(state.done[t.id]?.score||0),0),stars=xp>=270?3:xp>=210?2:1;
 $('#dialog-content').innerHTML=`<div class="dialog-top"><span class="eyebrow">ESTAÇÃO ${String(mi+1).padStart(2,'0')} · ${m.en}</span><button class="close-btn" data-action="close" aria-label="Voltar ao mapa">×</button></div><div class="dialog-main"><div class="reward"><div class="reward-badge" aria-hidden="true">${m.glyph}</div><div class="eyebrow">UM ARTEFATO. UMA DECISÃO MELHOR.</div><h2 id="dialog-title" tabindex="-1">${m.name}: missão cumprida.</h2><div class="stars" aria-label="${stars} de 3 estrelas">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div><p>${esc(m.lesson)}</p><div class="artifact-display"><span class="artifact-icon">▤</span><div><strong>${esc(m.artifact)}</strong><small>Modelo didático desbloqueado · ${xp} / 300 XP</small></div></div><p>Este artefato é um exemplo para aprender e adaptar. Não representa uma implementação, aprovação ou execução de CI real.</p><div class="reward-buttons"><button class="secondary" data-action="download-artifact" data-mi="${mi}">Salvar artefato ↓</button><button class="primary" data-action="advance" data-mi="${mi}">${mi===5?'Ver minha jornada →':'Próxima estação →'}</button></div></div></div>`;
 play.scrollTop=0;$('#dialog-title').focus({preventScroll:true});renderHome();
}
function showFinal(){
 const st=C.stats(state,D);if(st.completed!==6)return;const needs=D.missions.flatMap(m=>m.tasks).filter(t=>(state.attempts[t.id]||0)>0||state.hints[t.id]);const first=D.missions.flatMap(m=>m.tasks).filter(t=>!state.attempts[t.id]&&!state.hints[t.id]).length;
 $('#dialog-content').innerHTML=`<div class="dialog-top"><span class="eyebrow">JORNADA CONCLUÍDA · RESUMO DE APRENDIZAGEM</span><button class="close-btn" data-action="close" aria-label="Voltar ao mapa">×</button></div><div class="dialog-main"><div class="reward"><div class="reward-badge" aria-hidden="true">✦</div><div class="eyebrow">CONQUISTA DIDÁTICA DESBLOQUEADA</div><h2 id="dialog-title" tabindex="-1">Guardião do Release</h2><p>Você conduziu uma feature pelas seis etapas, enfrentou cinco chefes e separou intenção, evidência e autoridade.</p><div class="summary-grid"><div><strong>${st.xp}</strong><small>XP / 1800</small></div><div><strong>${first}/18</strong><small>SEM AJUDA OU ERRO</small></div><div><strong>5/5</strong><small>CHEFES SUPERADOS</small></div></div><div class="medals">${st.bosses.map(id=>`<canvas data-medal="${id}" aria-label="${bossNames[id]} superado"></canvas>`).join('')}</div><div class="final-status"><strong>O incidente foi escalado, não declarado resolvido.</strong><br>Seu resultado demonstra decisões corretas nesta simulação. Não certifica competência profissional nem prontidão de um sistema real.</div>${needs.length?`<div class="review-list"><div class="eyebrow">REVISITE PARA FIXAR · ${needs.length} CONCEITOS</div>${needs.map(t=>`<div class="glossary-item"><h3>${esc(t.title)}</h3><p>${esc(t.takeaway)}</p></div>`).join('')}</div>`:'<p>Todos os desafios foram resolvidos sem ajuda ou erro. O próximo teste é aplicar o processo a uma mudança real, com evidências do seu ambiente.</p>'}<div class="reward-buttons"><button class="primary" data-action="transfer">Aplicar a uma feature minha →</button><button class="secondary" data-action="report">Exportar meu playbook ↓</button><button class="secondary" data-action="close">Voltar ao mapa</button></div></div></div>`;
 openDialog(play);$$('[data-medal]').forEach(el=>QuestBoss(el,el.dataset.medal,true));$('#dialog-title').focus({preventScroll:true});
}
$('#dialog-content').addEventListener('click',e=>{
 const button=e.target.closest('button');if(!button||button.disabled)return;
 const action=button.dataset.action;
 if(action==='close'){play.close();return;}
 if(action==='advance'){const i=Number(button.dataset.mi);if(i===5)showFinal();else openMission(i+1);return;}
 if(action==='download-artifact'){downloadArtifact(Number(button.dataset.mi));return;}
 if(action==='report'){exportReport();return;}
 if(action==='transfer'){openTransfer();return;}
 if(!active)return;const t=getTask();
 if(action==='verify'){verify();return;}
 if(action==='hint'){active.hintOpen=!active.hintOpen;if(active.hintOpen&&!state.done[t.id]){state.hints[t.id]=1;save();}renderHint();const xp=$('.xp-note');if(xp&&!state.done[t.id])xp.textContent=`Até ${C.score(state.attempts[t.id],state.hints[t.id])} XP`;return;}
 if(active.success)return;
 if(button.dataset.option){const id=button.dataset.option;if(['select','diff'].includes(t.type)){active.answer=active.answer.includes(id)?active.answer.filter(x=>x!==id):[...active.answer,id];}else active.answer=id;
  $$('[data-option]').forEach(b=>b.setAttribute('aria-pressed',String(Array.isArray(active.answer)?active.answer.includes(b.dataset.option):active.answer===b.dataset.option)));clearFeedback();if(t.type==='diff')$('#diff-budget').innerHTML=budgetHTML(t);active.results=null;renderTestResults();draft();sound();return;}
 if(button.dataset.step){active.answer.push(button.dataset.step);clearFeedback();$('#exercise').innerHTML=exerciseHTML(t);draft();sound();const next=$('[data-step]:not(:disabled)');(next||$('#verify-btn')).focus({preventScroll:true});return;}
 if(action==='undo'){active.answer.pop();clearFeedback();$('#exercise').innerHTML=exerciseHTML(t);draft();($('[data-action="undo"]:not(:disabled)')||$('[data-step]:not(:disabled)'))?.focus({preventScroll:true});return;}
 if(button.dataset.incident){
  const r=C.stepIncident(active.answer,button.dataset.incident);active.answer=r.state;active.feedback={ok:r.ok,message:r.message};if(!r.ok&&!state.done[t.id])state.attempts[t.id]=(state.attempts[t.id]||0)+1;
  $('#exercise').innerHTML=incidentHTML();renderFeedback();draft();sound(r.ok?'tap':'wrong');
  if(r.done){verify();}else requestAnimationFrame(()=>{const btn=$(`[data-incident="${button.dataset.incident}"]`);btn?.focus({preventScroll:true});});
 }
});
$('#dialog-content').addEventListener('change',e=>{if(!active||active.success)return;const field=e.target.dataset.field;if(!field)return;active.answer[field]=e.target.value;clearFeedback();draft();});
function download(name,content,type='text/markdown;charset=utf-8'){
 const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);toast(`${name} preparado.`);
}
function downloadArtifact(mi){const m=D.missions[mi];if(!m.tasks.every(t=>state.done[t.id])){toast('Conclua a missão para desbloquear o artefato.');return;}download(m.artifact,D.artifacts[m.artifact],m.artifact.endsWith('.json')?'application/json':'text/markdown;charset=utf-8');}
function exportReport(){
 const st=C.stats(state,D),time=new Date().toISOString();let out=`# SDLC Quest — Meu playbook de aprendizagem\n\nGerado em: ${time}\n\n## Limite desta evidência\nEste é um registro local de uma simulação didática. Não comprova a execução de uma API, pipeline ou infraestrutura real. Não é certificado profissional nem autorização de release. O save é local e editável.\n\n## Progresso\n${st.completed}/6 missões, ${st.done}/18 desafios, ${st.bosses.length}/5 chefes. Pontuação: ${st.xp}/1800 XP.\n\n## Decisões e aprendizado\n`;
 for(const m of D.missions){out+=`\n### ${m.en} — ${m.name}\n${m.lesson}\n\n`;for(const t of m.tasks){out+=`- ${state.done[t.id]?'CONCLUÍDO':'PENDENTE'}: ${t.title}. Erros: ${state.attempts[t.id]||0}. Ajuda: ${state.hints[t.id]?'sim':'não'}. XP: ${state.done[t.id]?.score||0}.\n  ${t.takeaway}\n`;}}
 out+='\n## Minha aplicação a uma feature real\nEste rascunho é do jogador e não foi validado por IA, teste ou revisor. Não concede aprovação.\n';for(const [k,title] of transferFields)out+=`\n### ${title}\n${state.transfer?.[k]||'[Não preenchido]'}\n`;
 out+='\n## Modelos desbloqueados (não são evidência operacional)\n';for(const m of D.missions)if(m.tasks.every(t=>state.done[t.id]))out+=`\n### ${m.artifact}\n\n\`\`\`${m.artifact.endsWith('.json')?'json':'markdown'}\n${D.artifacts[m.artifact]}\n\`\`\`\n`;
 out+='\n## Referências primárias\nMaterial consultado em 8 de setembro de 2026. As políticas e cenários do jogo são propostas didáticas, não padrões universais.\n';for(const s of D.sources)out+=`\n- ${s.name}: ${s.url}\n`;if(window.SDLCQuestTLC)out+='\n\n'+SDLCQuestTLC.guide();download('meu-playbook-sdlc-quest.md',out);
}
function infoShell(title,body,focusSelector=null){$('#info-content').innerHTML=`<div class="dialog-top"><span class="eyebrow">SDLC QUEST / CADERNO DE CAMPO</span><button class="close-btn" data-info="close" aria-label="Fechar caderno">×</button></div><div class="info-main"><h2 id="info-title" tabindex="-1">${title}</h2>${body}</div>`;openDialog(info);requestAnimationFrame(()=>{const target=focusSelector?info.querySelector(focusSelector):$('#info-title');target?.focus({preventScroll:true});});}
function openManual(tab='glossary'){
 infoTab=tab;const tabs=`<div class="info-tabs"><button data-info="glossary" aria-pressed="${tab==='glossary'}" class="${tab==='glossary'?'active':''}">Conceitos</button><button data-info="method" aria-pressed="${tab==='method'}" class="${tab==='method'?'active':''}">O método</button><button data-info="sources" aria-pressed="${tab==='sources'}" class="${tab==='sources'?'active':''}">Fontes e limites</button></div>`;
 let body='';if(tab==='glossary')body='<label class="hidden" for="glossary-search">Buscar conceito</label><input type="search" class="search" id="glossary-search" aria-label="Buscar conceito" placeholder="Busque por gate, worktree, evidência…"><div id="glossary-results"></div>';
 else if(tab==='method')body=`<p>Não basta pedir código. O jogador escolhe a intenção, constrói a prova e limita a autoridade do executor.</p>${D.missions.map((m,i)=>`<div class="glossary-item"><h3>${i+1}. ${m.name} · ${m.en}</h3><p>${esc(m.lesson)}</p><p><strong>Artefato:</strong> ${m.artifact}</p></div>`).join('')}<p class="info-note">O limite de 180 linhas, as trilhas de risco e a única mitigação automática são políticas da campanha. Adapte limites à realidade do projeto, não copie números como regra universal.</p>`;
 else body=`<p>Referências primárias consultadas em <strong>8 de setembro de 2026</strong>. O jogo adapta os conceitos a cenários originais e simplificados.</p>${D.sources.map(s=>`<a class="source-item" href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.name)} ↗<small>${esc(s.topic)}</small></a>`).join('')}<p class="info-note">O jogo não usa LLM, não configura hooks, não acessa APIs ou produção e não executa comandos de sistema. A rede só é usada se você abrir uma fonte. Os testes de tenant são microtestes locais, não uma suite completa de aplicação. Acertos não demonstram eficácia de controles no seu ambiente. Verifique documentação e versões antes de implementar.</p>`;
 infoShell('Seu manual de engenharia.',tabs+body+'<div class="transfer-link"><button class="secondary" data-open-tlc="kit">Skills TLC: instalação, prompts e fontes ↗</button></div><div class="transfer-link"><button class="secondary" data-info="transfer">Aplicar a uma feature minha →</button></div>');if(tab==='glossary'){renderGlossary('');$('#glossary-search').addEventListener('input',e=>renderGlossary(e.target.value));}
}
function renderGlossary(query){const q=query.toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');const items=D.glossary.filter(g=>g.join(' ').toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').includes(q));$('#glossary-results').innerHTML=items.length?items.map(([name,text])=>`<article class="glossary-item"><h3>${esc(name)}</h3><p>${esc(text)}</p></article>`).join(''):'<p>Nenhum conceito encontrado. Tente outro termo.</p>';}
function openBag(){
 const st=C.stats(state,D);infoShell('Artefatos da sua jornada.',`<p>${st.completed} de 6 modelos desbloqueados. Cada artefato tem uma função: dar contexto, estabelecer um contrato ou registrar uma decisão.</p>${D.missions.map((m,i)=>{const unlocked=m.tasks.every(t=>state.done[t.id]);return `<div class="artifact-row"><div><code>${esc(m.artifact)}</code><small>${unlocked?'✓ Desbloqueado':'○ Complete a missão '+(i+1)} · ${m.en}</small></div><button class="small-btn" data-info="artifact" data-mi="${i}" ${unlocked?'':'disabled'}>Abrir ↗</button></div>`;}).join('')}<p class="info-note">Estes são modelos didáticos. Um arquivo que diz “aprovado” não autentica uma aprovação e não verifica um software real.</p><button class="primary" data-info="report">Exportar playbook e progresso ↓</button>`);
}
function showArtifact(mi){const m=D.missions[mi];if(!m.tasks.every(t=>state.done[t.id]))return;infoShell(esc(m.artifact),`<p>Exemplo desbloqueado na estação ${m.name}. Adapte e valide no seu projeto.</p><pre class="artifact-preview">${esc(D.artifacts[m.artifact])}</pre><div class="reward-buttons"><button class="secondary" data-info="bag">← Artefatos</button><button class="primary" data-info="download" data-mi="${mi}">Salvar arquivo ↓</button></div>`);}
function openSettings(){const previous=document.activeElement?.dataset.info;infoShell('Ajuste sua experiência.',`<div class="settings-row"><div>Sons de interação<span>Tons suaves. Desligados por padrão.</span></div><button class="secondary" data-info="sound" aria-pressed="${state.sound}">${state.sound?'Ligados':'Desligados'}</button></div><div class="settings-row"><div>Animação do cenário<span>Também respeita a preferência de movimento reduzido do sistema.</span></div><button class="secondary" data-info="motion" aria-pressed="${state.motion}">${state.motion?'Ligada':'Pausada'}</button></div><div class="settings-row"><div>Progresso local<span>${storageOK?'Salvo neste navegador. Mover o arquivo ou limpar dados pode mudar ou apagar o save.':'Armazenamento indisponível. O jogo funciona nesta sessão; exporte seu relatório.'}</span></div><button class="secondary" data-info="report">Exportar</button></div><div class="settings-row"><div>Uma nova jornada<span>Apaga somente o progresso deste jogo neste navegador.</span></div><button class="danger-outline" data-info="reset-confirm">Reiniciar</button></div><div class="backup-controls"><button class="secondary" data-info="backup">Baixar backup JSON ↓</button><button class="secondary" data-info="import">Restaurar backup ↑</button><input class="hidden" type="file" id="import-file" accept=".json,application/json" aria-label="Arquivo de backup do SDLC Quest"></div><p class="info-note">O Markdown registra seu aprendizado. O backup JSON permite retomar em outro navegador. Importe somente arquivos locais de até 256 KiB; a substituição pede confirmação. O progresso é editável e não é certificado.</p><button class="text-button" data-info="help">Como jogar e atalhos ↗</button>`,['sound','motion'].includes(previous)?`[data-info="${previous}"]`:null);}
function openHelp(){infoShell('Sua missão começa aqui.',`<p>Você é responsável por entregar um retry seguro de webhooks. Seu copiloto de IA pode ajudar, mas cada decisão precisa de intenção, evidência e limites.</p><div class="help-step"><b>1</b><p><strong>Entre na estação disponível.</strong> Use o mapa ou os seis botões. As próximas etapas são liberadas quando os três desafios da atual terminam.</p></div><div class="help-step"><b>2</b><p><strong>Construa a solução.</strong> Selecione cartões, classifique riscos, ordene passos, recorte o diff e experimente os microtestes. No incidente, leia o console antes de agir.</p></div><div class="help-step"><b>3</b><p><strong>Aprenda com a resposta.</strong> Estudar o conceito é gratuito. Uma decisão errada custa 15 XP; pedir uma dica da solução custa 20 XP uma única vez. Confirmar sem escolher nada não custa XP. Cada desafio vale de 40 a 100 XP. Não há vidas, cronômetro ou bloqueio por errar.</p></div><div class="help-step"><b>4</b><p><strong>Leve o aprendizado.</strong> Desbloqueie seis artefatos e exporte seu playbook. Revisitar missões não gera XP extra nem altera a nota original.</p></div><p class="info-note"><strong>Teclado:</strong> Tab e Shift+Tab navegam; Enter ou Espaço acionam botões; setas operam os seletores nativos; Esc fecha a janela. Não é necessário arrastar peças. O cenário pausa durante os desafios. O incidente é retomado do último estado salvo, inclusive seu orçamento de ação. Revisitar um incidente já concluído inicia apenas uma simulação de revisão.</p><button class="primary" data-info="start">Ir para a missão disponível →</button>`);}
$('#info-content').addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const action=b.dataset.info;
 if(action==='close')info.close();
 if(['glossary','method','sources'].includes(action))openManual(action);
 if(action==='bag')openBag();if(action==='artifact')showArtifact(Number(b.dataset.mi));if(action==='download')downloadArtifact(Number(b.dataset.mi));if(action==='report')exportReport();
 if(action==='sound'){state.sound=!state.sound;save();sound('win');openSettings();}
 if(action==='motion'){state.motion=!state.motion;save();renderHome();openSettings();}
 if(action==='help')openHelp();
 if(action==='transfer')openTransfer();
 if(action==='backup')download('sdlc-quest-backup.json',JSON.stringify(C.makeBackup(state,D),null,2),'application/json');
 if(action==='import')$('#import-file')?.click();
 if(action==='cancel-import'){pendingImport=null;openSettings();}
 if(action==='confirm-import'&&pendingImport){state=C.normalize(pendingImport,D);pendingImport=null;if(matchMedia('(prefers-reduced-motion: reduce)').matches)state.motion=false;save();active=null;if(play.open)play.close();info.close();renderHome();toast('Backup restaurado. Continue a missão do último estado salvo.');document.dispatchEvent(new Event('quest-state-replaced'));}

 if(action==='start'){info.close();openMission(currentAvailable());}
 if(action==='reset-confirm'){infoShell('Recomeçar esta campanha?',`<p>Esta ação apaga o progresso da campanha, da oficina TLC, as entradas do laboratório de execução e as notas locais do SDLC Quest. Seus arquivos exportados não serão alterados.</p><div class="reward-buttons"><button class="secondary" data-info="settings">Cancelar</button><button class="danger-outline" data-info="reset">Apagar progresso e recomeçar</button></div>`);}
 if(action==='settings')openSettings();
 if(action==='reset'){state=C.empty();if(matchMedia('(prefers-reduced-motion: reduce)').matches)state.motion=false;save();active=null;if(play.open)play.close();info.close();renderHome();toast('Nova campanha iniciada.');document.dispatchEvent(new Event('quest-state-replaced'));}
});
const transferFields=[['intent','1. Intenção e resultado observável'],['evidence','2. Prova de aceitação e revisão verificada'],['authority','3. Limite de autoridade e responsável'],['stop','4. Sinal para abortar, mitigar ou escalar']];
const transferPrompts={intent:'Qual problema sua feature resolve? Para quem? O que ficará fora do escopo?',evidence:'Que teste negativo demonstra a falha? Como ligar o resultado ao commit e ao artefato?',authority:'Que ação o agente não pode autorizar? Quem aprova e onde a restrição é imposta?',stop:'Qual condição impede o release? Qual é o limite da mitigação e quem assume o incidente?'};
function openTransfer(){
 infoShell('Leve o método para sua próxima PR.',`<p>Escolha uma feature sua e transforme o aprendizado em quatro decisões. Este rascunho é opcional, não altera XP e não recebe uma nota automática.</p><p class="info-note">Não inclua senhas, tokens, dados de clientes ou outros segredos. Os campos ficam neste navegador e nos arquivos que você exportar.</p><div class="worksheet">${transferFields.map(([k,label])=>`<label class="worksheet-field" for="transfer-${k}"><strong>${label}</strong><span>${transferPrompts[k]}</span><textarea id="transfer-${k}" data-transfer="${k}" maxlength="1600" rows="4">${esc(state.transfer?.[k]||'')}</textarea></label>`).join('')}</div><p class="worksheet-status" id="worksheet-status"></p><div class="reward-buttons"><button class="primary" data-info="report">Exportar playbook com meu rascunho ↓</button><button class="secondary" data-info="backup">Baixar backup JSON ↓</button></div><p class="info-note">Preencher os campos não prova que a feature é segura ou correta. Leve-os à revisão do time, execute as verificações e registre o que não foi validado.</p>`);
 updateWorksheetStatus();
}
function updateWorksheetStatus(){const el=$('#worksheet-status');if(el)el.textContent=`${transferFields.filter(([k])=>state.transfer?.[k]?.trim()).length}/4 campos preenchidos · ${storageOK?'rascunho salvo localmente':'modo temporário; exporte para preservar'}.`;}
$('#info-content').addEventListener('input',e=>{const k=e.target.dataset.transfer;if(!C.transferKeys.includes(k))return;state.transfer[k]=e.target.value.slice(0,1600);save();updateWorksheetStatus();});
$('#info-content').addEventListener('change',async e=>{
 if(e.target.id!=='import-file')return;const file=e.target.files?.[0];if(!file)return;
 const token=++importToken;pendingImport=null;
 try{
  if(file.size>262144)throw new Error('Backup muito grande. O limite é 256 KiB.');
  const text=await file.text();if(token!==importToken||!info.open)return;
  const candidate=C.importBackup(text,D);pendingImport=candidate;const st=C.stats(candidate,D);
  infoShell('Conferir antes de restaurar.',`<p>Arquivo: <strong>${esc(file.name)}</strong></p><p>${st.done}/18 desafios, ${st.completed}/6 estações e ${st.xp} XP. ${QuestTLC.stats(candidate.tlc).done}/16 desafios TLC. Seus rascunhos também serão restaurados. No laboratório de execução, o backup restaura entradas, nunca validações: reexecute os gates.</p><p class="info-note">Confirmar substitui o progresso deste jogo neste navegador. Baixe um backup do progresso atual antes se precisar preservá-lo. Arquivos já exportados não serão alterados.</p><div class="reward-buttons"><button class="secondary" data-info="backup">Salvar backup atual ↓</button><button class="secondary" data-info="cancel-import">Cancelar</button><button class="primary" data-info="confirm-import">Substituir pelo backup</button></div>`);
 }catch(error){pendingImport=null;infoShell('Não foi possível restaurar.',`<p class="info-note" role="alert">${esc(error.message)}</p><p>Seu progresso atual não foi alterado.</p><button class="secondary" data-info="settings">Voltar às configurações</button>`);}
});
$('#quick-start')?.addEventListener('click',()=>C.stats(state,D).completed===6?showFinal():openMission(currentAvailable()));
$('#book-btn').addEventListener('click',()=>openManual());$('#bag-btn').addEventListener('click',openBag);$('#settings-btn').addEventListener('click',openSettings);$('#how-btn').addEventListener('click',openHelp);
$('.brand').addEventListener('click',e=>{e.preventDefault();chooseMission(currentAvailable());window.scrollTo({top:0,behavior:'instant'});});
$('#motion-btn').addEventListener('click',()=>{state.motion=!state.motion;save();renderHome();});
renderHome();
try{world=new QuestWorld($('#world'),D,()=>state,chooseMission);}catch(error){$('#world-tip').textContent='Use os botões de estação abaixo para jogar.';console.warn('O mapa não está disponível, mas os desafios continuam acessíveis.',error);}
// Read-only inspection aids: no debug bypass, network, prompt execution, or production actions.
Object.defineProperty(window,'SDLCQuest',{value:Object.freeze({version:'1.3.0',getState:()=>structuredClone(state),getStats:()=>C.stats(state,D),currentTask:()=>active?getTask().id:null}),writable:false});
Object.defineProperty(window,'QuestBridge',{value:Object.freeze({readHarness:()=>structuredClone(state.harness),writeHarness:value=>{state.harness=QuestHarness.normalizeDraft(value);save();},read:()=>structuredClone(state.tlc),write:value=>{state.tlc=QuestTLC.normalize(value);save();},toast,download,backup:()=>download('sdlc-quest-backup.json',JSON.stringify(C.makeBackup(state,D),null,2),'application/json')}),writable:false});
if(saveNotice)toast(saveNotice);save();
})();
