/* UI controller. Persistent progression, transient workbench state and renderer stay separate.
 * Chrome is bilingual via QuestLang; data fields resolve *_en with pt-BR fallback. */
(function(){
'use strict';
const D=QuestData,C=QuestCore,QL=QuestLang,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const STRINGS={
pt:{
 saveOk:'✓ Progresso salvo neste navegador',saveTemp:'Modo temporário · armazenamento indisponível',saveInvalid:'Save inválido: uma nova campanha foi iniciada.',
 ranks:{guardian:'GUARDIÃO DO RELEASE',evidence:'ENGENHEIRO DE EVIDÊNCIAS',architect:'ARQUITETO EM FORMAÇÃO',apprentice:'APRENDIZ DE ENGENHARIA'},
 bossNames:{monster:'MONSTRO DO DIFF',weakener:'ENFRAQUECEDOR DE TESTES',secret:'VAZADOR DE SEGREDOS',outage:'INCIDENTE DAS 3H',editor:'EDITOR DE GUARDRAILS'},
 lockedStation:(i,name)=>`Estação ${i}: conclua ${name} para desbloquear.`,prevStation:'Conclua a estação anterior.',filePrepared:name=>`${name} preparado.`,artifactLocked:'Conclua a missão para desbloquear o artefato.',backupRestored:'Backup restaurado. Continue a missão do último estado salvo.',newCampaign:'Nova campanha iniciada.',
 mDone:'MISSÃO CONCLUÍDA',mAvailable:'MISSÃO DISPONÍVEL',mLocked:'ESTAÇÃO BLOQUEADA',tagChallenges:'3 desafios',tagBoss:'1 chefe',tagXp:'Até 300 XP',btnRevisit:'Revisitar missão',btnContinue:'Continuar missão',btnStart:'Iniciar missão',noteOpen:'Sem cronômetro. Aprenda no seu ritmo.',noteLocked:n=>`Conclua a estação ${n} para entrar.`,practiceSkills:'PRATIQUE COM AS SKILLS',journeySummary:'Ver resumo da jornada ↗',motionPause:'Ⅱ Pausar cenário',motionPlay:'▷ Animar cenário',
 stageAriaDone:'concluída; revisar',stageAriaOpen:'disponível',stageAriaLocked:'bloqueada; visualizar resumo',
 closeSave:'Salvar e voltar ao mapa',closeMap:'Voltar ao mapa',dotsAria:(i)=>`Desafio ${i} de 3`,bossKicker:'BATALHA DE CHEFE · ',missionCode:'MISSÃO WEBHOOK-042',primerSummary:'Estudar o conceito · grátis',exampleLabel:'Exemplo:',instructionDefault:'Escolha a decisão e observe suas consequências.',
 hintLabel:'? Dica da solução ',hintCost:'(−20 XP)',hintFree:'(sem custo adicional)',hideHint:'Ocultar dica',mentor:'Mentor · ',xpReview:'Revisão · sem XP adicional',xpUpTo:n=>`Até ${n} XP`,xpWon:n=>`${n} XP conquistados`,
 verifyNext:'Próximo desafio →',verifyFinish:'Concluir missão →',verifyPatch:'Executar microtestes ▶',verifyGate:'Solicitar release →',verifyIncident:'Concluir resposta →',verifyChoice:'Verificar decisão →',
 chooseCategory:'Escolha a categoria…',selectEntry:'Selecione uma entrada…',seqTitle:(n,m)=>`SUA SEQUÊNCIA · ${n}/${m}`,undo:'Desfazer ↶',emptyOrder:'O primeiro passo começa aqui.<br>Escolha uma peça ao lado ou abaixo.',budgetLabel:'LINHAS NA SUA PR · ORÇAMENTO DIDÁTICO',
 chartAria:burn=>`Gráfico fictício: consumo do orçamento de erro segue acima do objetivo. Burn rate atual ${burn} vezes.`,chartData:'DADOS FICTÍCIOS / BURN RATE',chartGoal:'OBJETIVO: ≤ 1×',chartCaption:'Sinal ilustrativo, sem escala temporal operacional. Não é um detector configurável nem uma regra de rollback.',
 incidentPhases:{alert:'ALERTA',diagnosed:'DIAGNÓSTICO VALIDADO',mitigated:'MITIGAÇÃO APLICADA',verified:'DEGRADAÇÃO PERSISTE',escalated:'ESCALADO · AINDA ABERTO',complete:'ESCALADO E REGISTRADO'},incidentActions:'AÇÕES AUTOMÁTICAS: ',incidentBtns:{diagnose:'⌕ Diagnosticar',pause:'Ⅱ Pausar novos retries',verify:'✓ Verificar resultado',rollback:'↶ Fazer rollback',escalate:'↑ Acionar plantonista',record:'▤ Registrar nova intenção'},
 fbBoss:'Chefe superado. Defesa demonstrada.',fbValidated:'Decisão validada.',fbConsole:'Console atualizado.',fbEmpty:'Antes de verificar:',fbGate:'O gate segurou a mudança.',nextPr:'NA SUA PRÓXIMA PR',
 consoleTitle:n=>`VERIFICADOR LOCAL · ${n}/4 checks aprovados`,consoleNote:'Fixtures fictícias. Expectativas independentes da alteração escolhida.',pass:'PASS',fail:'FAIL',expectedActual:(e,a)=>`(esperado ${e}; recebido ${a})`,
 incidentIncomplete:'O incidente ainda exige ações. Use o console; validar exige diagnóstico, mitigação limitada, verificação, escalonamento e registro.',chooseFirst:'Escolha uma resposta antes de verificar. Nenhuma tentativa ou XP foi descontado.',
 rewardEyebrow:'UM ARTEFATO. UMA DECISÃO MELHOR.',rewardTitle:name=>`${name}: missão cumprida.`,starsAria:n=>`${n} de 3 estrelas`,artifactUnlocked:xp=>`Modelo didático desbloqueado · ${xp} / 300 XP`,artifactNote:'Este artefato é um exemplo para aprender e adaptar. Não representa uma implementação, aprovação ou execução de CI real.',saveArtifact:'Salvar artefato ↓',nextStation:'Próxima estação →',myJourney:'Ver minha jornada →',
 finalEyebrow:'JORNADA CONCLUÍDA · RESUMO DE APRENDIZAGEM',finalAchievement:'CONQUISTA DIDÁTICA DESBLOQUEADA',finalTitle:'Guardião do Release',finalLead:'Você conduziu uma feature pelas seis etapas, enfrentou cinco chefes e separou intenção, evidência e autoridade.',finalXp:'XP / 1800',finalNoHelpCount:n=>`${n}/18`,finalNoHelp:'SEM AJUDA OU ERRO',finalBosses:'CHEFES SUPERADOS',medalAria:name=>`${name} superado`,finalStatusStrong:'O incidente foi escalado, não declarado resolvido.',finalStatusText:'Seu resultado demonstra decisões corretas nesta simulação. Não certifica competência profissional nem prontidão de um sistema real.',revisit:n=>`REVISITE PARA FIXAR · ${n} CONCEITOS`,allClean:'Todos os desafios foram resolvidos sem ajuda ou erro. O próximo teste é aplicar o processo a uma mudança real, com evidências do seu ambiente.',transferBtn:'Aplicar a uma feature minha →',exportPlaybook:'Exportar meu playbook ↓',
 fieldNotebook:'SDLC QUEST / CADERNO DE CAMPO',closeNotebook:'Fechar caderno',tabConcepts:'Conceitos',tabMethod:'O método',tabSources:'Fontes e limites',searchAria:'Buscar conceito',searchPlaceholder:'Busque por gate, worktree, evidência…',manualTitle:'Seu manual de engenharia.',methodIntro:'Não basta pedir código. O jogador escolhe a intenção, constrói a prova e limita a autoridade do executor.',artifactLabel:'Artefato:',methodNote:'O limite de 180 linhas, as trilhas de risco e a única mitigação automática são políticas da campanha. Adapte limites à realidade do projeto, não copie números como regra universal.',sourcesIntro:'Referências primárias consultadas em <strong>8 de setembro de 2026</strong>. O jogo adapta os conceitos a cenários originais e simplificados.',sourcesNote:'O jogo não usa LLM, não configura hooks, não acessa APIs ou produção e não executa comandos de sistema. A rede só é usada se você abrir uma fonte. Os testes de tenant são microtestes locais, não uma suite completa de aplicação. Acertos não demonstram eficácia de controles no seu ambiente. Verifique documentação e versões antes de implementar.',tlcLink:'Skills TLC: instalação, prompts e fontes ↗',transferLink:'Aplicar a uma feature minha →',glossaryEmpty:'Nenhum conceito encontrado. Tente outro termo.',
 bagTitle:'Artefatos da sua jornada.',bagIntro:n=>`${n} de 6 modelos desbloqueados. Cada artefato tem uma função: dar contexto, estabelecer um contrato ou registrar uma decisão.`,unlocked:'✓ Desbloqueado',lockedMission:i=>`○ Complete a missão ${i}`,open:'Abrir ↗',bagNote:'Estes são modelos didáticos. Um arquivo que diz “aprovado” não autentica uma aprovação e não verifica um software real.',exportProgress:'Exportar playbook e progresso ↓',artifactIntro:name=>`Exemplo desbloqueado na estação ${name}. Adapte e valide no seu projeto.`,backArtifacts:'← Artefatos',saveFile:'Salvar arquivo ↓',
 settingsTitle:'Ajuste sua experiência.',soundLabel:'Sons de interação',soundNote:'Tons suaves. Desligados por padrão.',on:'Ligados',off:'Desligados',motionLabel:'Animação do cenário',motionNote:'Também respeita a preferência de movimento reduzido do sistema.',motionOn:'Ligada',motionPaused:'Pausada',progressLabel:'Progresso local',progressSaved:'Salvo neste navegador. Mover o arquivo ou limpar dados pode mudar ou apagar o save.',progressTemp:'Armazenamento indisponível. O jogo funciona nesta sessão; exporte seu relatório.',exportBtn:'Exportar',resetLabel:'Uma nova jornada',resetNote:'Apaga somente o progresso deste jogo neste navegador.',restart:'Reiniciar',backupDown:'Baixar backup JSON ↓',backupUp:'Restaurar backup ↑',backupFileAria:'Arquivo de backup do SDLC Quest',settingsNote:'O Markdown registra seu aprendizado. O backup JSON permite retomar em outro navegador. Importe somente arquivos locais de até 256 KiB; a substituição pede confirmação. O progresso é editável e não é certificado.',helpLink:'Como jogar e atalhos ↗',
 helpTitle:'Sua missão começa aqui.',helpIntro:'Você é responsável por entregar um retry seguro de webhooks. Seu copiloto de IA pode ajudar, mas cada decisão precisa de intenção, evidência e limites.',help1Title:'Entre na estação disponível.',help1Body:'Use o mapa ou os seis botões. As próximas etapas são liberadas quando os três desafios da atual terminam.',help2Title:'Construa a solução.',help2Body:'Selecione cartões, classifique riscos, ordene passos, recorte o diff e experimente os microtestes. No incidente, leia o console antes de agir.',help3Title:'Aprenda com a resposta.',help3Body:'Estudar o conceito é gratuito. Uma decisão errada custa 15 XP; pedir uma dica da solução custa 20 XP uma única vez. Confirmar sem escolher nada não custa XP. Cada desafio vale de 40 a 100 XP. Não há vidas, cronômetro ou bloqueio por errar.',help4Title:'Leve o aprendizado.',help4Body:'Desbloqueie seis artefatos e exporte seu playbook. Revisitar missões não gera XP extra nem altera a nota original.',keyboardNote:'<strong>Teclado:</strong> Tab e Shift+Tab navegam; Enter ou Espaço acionam botões; setas operam os seletores nativos; Esc fecha a janela. Não é necessário arrastar peças. O cenário pausa durante os desafios. O incidente é retomado do último estado salvo, inclusive seu orçamento de ação. Revisitar um incidente já concluído inicia apenas uma simulação de revisão.',goToAvailable:'Ir para a missão disponível →',
 resetConfirmTitle:'Recomeçar esta campanha?',resetConfirmBody:'Esta ação apaga o progresso da campanha, da oficina TLC, as entradas do laboratório de execução e as notas locais do SDLC Quest. Seus arquivos exportados não serão alterados.',cancel:'Cancelar',resetConfirmBtn:'Apagar progresso e recomeçar',
 transferTitle:'Leve o método para sua próxima PR.',transferIntro:'Escolha uma feature sua e transforme o aprendizado em quatro decisões. Este rascunho é opcional, não altera XP e não recebe uma nota automática.',transferSecrets:'Não inclua senhas, tokens, dados de clientes ou outros segredos. Os campos ficam neste navegador e nos arquivos que você exportar.',transferFields:{intent:'1. Intenção e resultado observável',evidence:'2. Prova de aceitação e revisão verificada',authority:'3. Limite de autoridade e responsável',stop:'4. Sinal para abortar, mitigar ou escalar'},transferPrompts:{intent:'Qual problema sua feature resolve? Para quem? O que ficará fora do escopo?',evidence:'Que teste negativo demonstra a falha? Como ligar o resultado ao commit e ao artefato?',authority:'Que ação o agente não pode autorizar? Quem aprova e onde a restrição é imposta?',stop:'Qual condição impede o release? Qual é o limite da mitigação e quem assume o incidente?'},transferFilled:n=>`${n}/4 campos preenchidos · `,transferSaved:'rascunho salvo localmente',transferTemp:'modo temporário; exporte para preservar',transferExport:'Exportar playbook com meu rascunho ↓',transferNote:'Preencher os campos não prova que a feature é segura ou correta. Leve-os à revisão do time, execute as verificações e registre o que não foi validado.',
 importTitle:'Conferir antes de restaurar.',importSummary:(done,completed,xp,tlc)=>`${done}/18 desafios, ${completed}/6 estações e ${xp} XP. ${tlc}/16 desafios TLC. Seus rascunhos também serão restaurados. No laboratório de execução, o backup restaura entradas, nunca validações: reexecute os gates.`,importFile:'Arquivo:',importNote:'Confirmar substitui o progresso deste jogo neste navegador. Baixe um backup do progresso atual antes se precisar preservá-lo. Arquivos já exportados não serão alterados.',importCurrentBackup:'Salvar backup atual ↓',replaceBtn:'Substituir pelo backup',importFailTitle:'Não foi possível restaurar.',importUnchanged:'Seu progresso atual não foi alterado.',backSettings:'Voltar às configurações',worldFallback:'Use os botões de estação abaixo para jogar.'
},
en:{
 saveOk:'✓ Progress saved in this browser',saveTemp:'Temporary mode · storage unavailable',saveInvalid:'Invalid save: a new campaign has started.',
 ranks:{guardian:'RELEASE GUARDIAN',evidence:'EVIDENCE ENGINEER',architect:'ARCHITECT IN TRAINING',apprentice:'ENGINEERING APPRENTICE'},
 bossNames:{monster:'DIFF MONSTER',weakener:'TEST WEAKENER',secret:'SECRET LEAKER',outage:'3 A.M. INCIDENT',editor:'GUARDRAIL EDITOR'},
 lockedStation:(i,name)=>`Station ${i}: complete ${name} to unlock.`,prevStation:'Complete the previous station.',filePrepared:name=>`${name} prepared.`,artifactLocked:'Complete the mission to unlock the artifact.',backupRestored:'Backup restored. Continue the mission from the last saved state.',newCampaign:'New campaign started.',
 mDone:'MISSION COMPLETE',mAvailable:'MISSION AVAILABLE',mLocked:'STATION LOCKED',tagChallenges:'3 challenges',tagBoss:'1 boss',tagXp:'Up to 300 XP',btnRevisit:'Revisit mission',btnContinue:'Continue mission',btnStart:'Start mission',noteOpen:'No timer. Learn at your own pace.',noteLocked:n=>`Complete station ${n} to enter.`,practiceSkills:'PRACTICE WITH THE SKILLS',journeySummary:'See journey summary ↗',motionPause:'Ⅱ Pause scenery',motionPlay:'▷ Animate scenery',
 stageAriaDone:'complete; review',stageAriaOpen:'available',stageAriaLocked:'locked; view summary',
 closeSave:'Save and go back to the map',closeMap:'Back to the map',dotsAria:(i)=>`Challenge ${i} of 3`,bossKicker:'BOSS BATTLE · ',missionCode:'MISSION WEBHOOK-042',primerSummary:'Study the concept · free',exampleLabel:'Example:',instructionDefault:'Choose the decision and observe its consequences.',
 hintLabel:'? Solution hint ',hintCost:'(−20 XP)',hintFree:'(no extra cost)',hideHint:'Hide hint',mentor:'Mentor · ',xpReview:'Review · no extra XP',xpUpTo:n=>`Up to ${n} XP`,xpWon:n=>`${n} XP earned`,
 verifyNext:'Next challenge →',verifyFinish:'Complete mission →',verifyPatch:'Run microtests ▶',verifyGate:'Request release →',verifyIncident:'Complete answer →',verifyChoice:'Verify decision →',
 chooseCategory:'Choose a category…',selectEntry:'Select an entry…',seqTitle:(n,m)=>`YOUR SEQUENCE · ${n}/${m}`,undo:'Undo ↶',emptyOrder:'The first step starts here.<br>Pick a piece beside or below.',budgetLabel:'LINES IN YOUR PR · TEACHING BUDGET',
 chartAria:burn=>`Fictional chart: error budget consumption stays above target. Current burn rate ${burn}x.`,chartData:'FICTIONAL DATA / BURN RATE',chartGoal:'TARGET: ≤ 1×',chartCaption:'Illustrative signal, no operational time scale. Not a configurable detector or a rollback rule.',
 incidentPhases:{alert:'ALERT',diagnosed:'VALIDATED DIAGNOSIS',mitigated:'MITIGATION APPLIED',verified:'DEGRADATION PERSISTS',escalated:'ESCALATED · STILL OPEN',complete:'ESCALATED AND RECORDED'},incidentActions:'AUTOMATIC ACTIONS: ',incidentBtns:{diagnose:'⌕ Diagnose',pause:'Ⅱ Pause new retries',verify:'✓ Verify result',rollback:'↶ Roll back',escalate:'↑ Page on-call',record:'▤ Record new intent'},
 fbBoss:'Boss overcome. Defense demonstrated.',fbValidated:'Decision validated.',fbConsole:'Console updated.',fbEmpty:'Before verifying:',fbGate:'The gate held the change.',nextPr:'IN YOUR NEXT PR',
 consoleTitle:n=>`LOCAL VERIFIER · ${n}/4 checks passed`,consoleNote:'Fictional fixtures. Expectations independent of the chosen change.',pass:'PASS',fail:'FAIL',expectedActual:(e,a)=>`(expected ${e}; received ${a})`,
 incidentIncomplete:'The incident still requires actions. Use the console; validating requires diagnosis, limited mitigation, verification, escalation and recording.',chooseFirst:'Choose an answer before verifying. No attempt or XP was charged.',
 rewardEyebrow:'ONE ARTIFACT. ONE BETTER DECISION.',rewardTitle:name=>`${name}: mission accomplished.`,starsAria:n=>`${n} of 3 stars`,artifactUnlocked:xp=>`Teaching template unlocked · ${xp} / 300 XP`,artifactNote:'This artifact is an example to learn from and adapt. It does not represent a real implementation, approval or CI execution.',saveArtifact:'Save artifact ↓',nextStation:'Next station →',myJourney:'See my journey →',
 finalEyebrow:'JOURNEY COMPLETE · LEARNING SUMMARY',finalAchievement:'TEACHING ACHIEVEMENT UNLOCKED',finalTitle:'Release Guardian',finalLead:'You guided a feature through the six stages, faced five bosses and kept intent, evidence and authority separate.',finalXp:'XP / 1800',finalNoHelpCount:n=>`${n}/18`,finalNoHelp:'WITHOUT HELP OR ERRORS',finalBosses:'BOSSES OVERCOME',medalAria:name=>`${name} overcome`,finalStatusStrong:'The incident was escalated, not declared resolved.',finalStatusText:'Your result demonstrates correct decisions in this simulation. It does not certify professional competence or the readiness of a real system.',revisit:n=>`REVISIT TO CONSOLIDATE · ${n} CONCEPTS`,allClean:'Every challenge was solved without help or errors. The next test is applying the process to a real change, with evidence from your environment.',transferBtn:'Apply to my own feature →',exportPlaybook:'Export my playbook ↓',
 fieldNotebook:'SDLC QUEST / FIELD NOTEBOOK',closeNotebook:'Close notebook',tabConcepts:'Concepts',tabMethod:'The method',tabSources:'Sources and limits',searchAria:'Search concept',searchPlaceholder:'Search by gate, worktree, evidence…',manualTitle:'Your engineering manual.',methodIntro:'Just asking for code is not enough. The player chooses the intent, builds the proof and limits the executor’s authority.',artifactLabel:'Artifact:',methodNote:'The 180-line limit, the risk tracks and the single automatic mitigation are campaign policies. Adapt limits to your project’s reality; do not copy numbers as a universal rule.',sourcesIntro:'Primary references consulted on <strong>September 8, 2026</strong>. The game adapts the concepts to original, simplified scenarios.',sourcesNote:'The game uses no LLM, configures no hooks, accesses no APIs or production and runs no system commands. The network is only used if you open a source. The tenant tests are local microtests, not a full application suite. Correct answers do not demonstrate control effectiveness in your environment. Check documentation and versions before implementing.',tlcLink:'TLC skills: installation, prompts and sources ↗',transferLink:'Apply to my own feature →',glossaryEmpty:'No concept found. Try another term.',
 bagTitle:'Your journey artifacts.',bagIntro:n=>`${n} of 6 templates unlocked. Each artifact has a role: providing context, establishing a contract or recording a decision.`,unlocked:'✓ Unlocked',lockedMission:i=>`○ Complete mission ${i}`,open:'Open ↗',bagNote:'These are teaching templates. A file that says “approved” does not authenticate an approval and does not verify real software.',exportProgress:'Export playbook and progress ↓',artifactIntro:name=>`Example unlocked in station ${name}. Adapt and validate in your project.`,backArtifacts:'← Artifacts',saveFile:'Save file ↓',
 settingsTitle:'Adjust your experience.',soundLabel:'Interaction sounds',soundNote:'Soft tones. Off by default.',on:'On',off:'Off',motionLabel:'Scenery animation',motionNote:'Also respects the system reduced-motion preference.',motionOn:'On',motionPaused:'Paused',progressLabel:'Local progress',progressSaved:'Saved in this browser. Moving the file or clearing data can change or erase the save.',progressTemp:'Storage unavailable. The game works in this session; export your report.',exportBtn:'Export',resetLabel:'A new journey',resetNote:'Erases only this game’s progress in this browser.',restart:'Restart',backupDown:'Download JSON backup ↓',backupUp:'Restore backup ↑',backupFileAria:'SDLC Quest backup file',settingsNote:'The Markdown records your learning. The JSON backup lets you resume in another browser. Import only local files up to 256 KiB; replacing asks for confirmation. Progress is editable and is not a certificate.',helpLink:'How to play and shortcuts ↗',
 helpTitle:'Your mission starts here.',helpIntro:'You are responsible for delivering a safe webhook retry. Your AI copilot can help, but every decision needs intent, evidence and limits.',help1Title:'Enter the available station.',help1Body:'Use the map or the six buttons. The next stages unlock when the three challenges of the current one are finished.',help2Title:'Build the solution.',help2Body:'Select cards, classify risks, order steps, trim the diff and try the microtests. In the incident, read the console before acting.',help3Title:'Learn from the response.',help3Body:'Studying the concept is free. A wrong decision costs 15 XP; asking for a solution hint costs 20 XP once. Confirming with nothing chosen costs no XP. Each challenge is worth 40 to 100 XP. There are no lives, timers or blocking on errors.',help4Title:'Take the learning with you.',help4Body:'Unlock six artifacts and export your playbook. Revisiting missions gives no extra XP and does not change the original score.',keyboardNote:'<strong>Keyboard:</strong> Tab and Shift+Tab navigate; Enter or Space activate buttons; arrow keys operate the native selects; Esc closes the window. Dragging pieces is not required. The scenery pauses during challenges. The incident resumes from the last saved state, including its action budget. Revisiting a completed incident starts a review simulation only.',goToAvailable:'Go to the available mission →',
 resetConfirmTitle:'Restart this campaign?',resetConfirmBody:'This action erases the campaign progress, the TLC workshop, the execution lab entries and the SDLC Quest local notes. Your exported files will not be changed.',cancel:'Cancel',resetConfirmBtn:'Erase progress and restart',
 transferTitle:'Take the method to your next PR.',transferIntro:'Choose one of your features and turn the learning into four decisions. This draft is optional, does not change XP and receives no automatic grade.',transferSecrets:'Do not include passwords, tokens, customer data or other secrets. The fields stay in this browser and in the files you export.',transferFields:{intent:'1. Intent and observable outcome',evidence:'2. Acceptance proof and verified review',authority:'3. Authority limit and responsible person',stop:'4. Signal to abort, mitigate or escalate'},transferPrompts:{intent:'What problem does your feature solve? For whom? What stays out of scope?',evidence:'Which negative test demonstrates the failure? How do you tie the result to the commit and the artifact?',authority:'Which action can the agent not authorize? Who approves and where is the restriction enforced?',stop:'Which condition blocks the release? What is the mitigation limit and who owns the incident?'},transferFilled:n=>`${n}/4 fields filled · `,transferSaved:'draft saved locally',transferTemp:'temporary mode; export to preserve',transferExport:'Export playbook with my draft ↓',transferNote:'Filling in the fields does not prove the feature is safe or correct. Take them to your team’s review, run the verifications and record what was not validated.',
 importTitle:'Review before restoring.',importSummary:(done,completed,xp,tlc)=>`${done}/18 challenges, ${completed}/6 stations and ${xp} XP. ${tlc}/16 TLC challenges. Your drafts are also restored. In the execution lab, the backup restores inputs, never validations: rerun the gates.`,importFile:'File:',importNote:'Confirming replaces this game’s progress in this browser. Download a backup of the current progress first if you need to keep it. Already exported files will not be changed.',importCurrentBackup:'Save current backup ↓',replaceBtn:'Replace with the backup',importFailTitle:'Could not restore.',importUnchanged:'Your current progress was not changed.',backSettings:'Back to settings',worldFallback:'Use the station buttons below to play.'
}};
const T=(k,...args)=>{const v=(QL.get()==='en'?STRINGS.en[k]:undefined)??STRINGS.pt[k];return typeof v==='function'?v(...args):v;};
const SN=k=>(QL.get()==='en'?STRINGS.en[k]:undefined)??STRINGS.pt[k];
const F=(record,name)=>QL.field(record,name,QL.get());
const locale=()=>QL.get()==='en'?'en-US':'pt-BR';
/* Tuples like [id,label] may grow a third label_en slot; pt stays index 1. */
const tupleLabel=t=>QL.get()==='en'&&t.length>2?t[2]:t[1];
const CHROME={
pt:{skip:'Ir para as missões',brandAria:'SDLC Quest, voltar ao mapa',brandTag:'GUARDIÕES DO RELEASE',campaign:'CAMPANHA 01',campaignName:'A FEATURE PERDIDA',toolsAria:'Ferramentas do jogo',bookAria:'Manual de engenharia',book:'Manual',langAria:'Trocar idioma para inglês',langCode:'EN',bagAria:'Artefatos da jornada',bag:'Artefatos',settingsAria:'Configurações e ajuda',eyebrow:'APRENDA CONSTRUINDO. VENÇA VERIFICANDO.',h1a:'Da intenção ao',headingLead:'Uma aventura de engenharia com IA. O código é só parte da missão.',quickStart:'Jogar missão disponível →',challenges:'DESAFIOS',tlcBannerAria:'Expansão TLC AI Dev Flow',harnessBannerAria:'Laboratório de execução com gates',worldAria:'Mapa da campanha',mapCaption:'6 estações · 1 ciclo',worldCanvasAria:'Ilhas isométricas das seis etapas. Use os botões de missão abaixo para navegar.',worldTip:'Toque em uma estação para explorar',mapAvailable:'Disponível',mapLocked:'Ainda bloqueada',missionPanelAria:'Missão selecionada',stageNavAria:'Etapas do SDLC',bottomEyebrow:'O QUE REALMENTE PROTEGE UMA ENTREGA',pillar1:'Intenção clara',pillar2:'Evidência real',pillar3:'Autoridade limitada',howToPlay:'Como jogar',footerNote:'Um laboratório para aprender, não um acesso à produção.',noscript:'<p class="noscript">Este jogo precisa de JavaScript ativado no navegador. Não requer internet.</p>',docTitle:'SDLC Quest v1.3 — Laboratório de execução'},
en:{skip:'Go to the missions',brandAria:'SDLC Quest, back to the map',brandTag:'GUARDIANS OF THE RELEASE',campaign:'CAMPAIGN 01',campaignName:'THE LOST FEATURE',toolsAria:'Game tools',bookAria:'Engineering manual',book:'Manual',langAria:'Switch language to Portuguese',langCode:'PT',bagAria:'Journey artifacts',bag:'Artifacts',settingsAria:'Settings and help',eyebrow:'LEARN BY BUILDING. WIN BY VERIFYING.',h1a:'From intent to',headingLead:'An engineering adventure with AI. Code is only part of the mission.',quickStart:'Play the available mission →',challenges:'CHALLENGES',tlcBannerAria:'TLC AI Dev Flow expansion',harnessBannerAria:'Execution lab with gates',worldAria:'Campaign map',mapCaption:'6 stations · 1 cycle',worldCanvasAria:'Isometric islands of the six stages. Use the mission buttons below to navigate.',worldTip:'Tap a station to explore',mapAvailable:'Available',mapLocked:'Still locked',missionPanelAria:'Selected mission',stageNavAria:'SDLC stages',bottomEyebrow:'WHAT REALLY PROTECTS A DELIVERY',pillar1:'Clear intent',pillar2:'Real evidence',pillar3:'Limited authority',howToPlay:'How to play',footerNote:'A lab for learning, not production access.',noscript:'<p class="noscript">This game needs JavaScript enabled in the browser. It does not require internet.</p>',docTitle:'SDLC Quest v1.3 — Execution lab'}
};
function renderChrome(){
 const c=(QL.get()==='en'?CHROME.en:undefined)??CHROME.pt;
 for(const el of $$('[data-i18n]')){const k=el.dataset.i18n;if(typeof c[k]==='string')el.textContent=c[k];}
 for(const el of $$('[data-i18n-aria]')){const k=el.dataset.i18nAria;if(typeof c[k]==='string'){el.setAttribute('aria-label',c[k]);if(el.hasAttribute('title'))el.setAttribute('title',c[k]);}}
 const ns=document.querySelector('noscript');if(ns)ns.innerHTML=c.noscript;
 document.title=c.docTitle;
}
let storageOK=true,saveNotice='',state=C.empty(),active=null,world=null,toastTimer=null,audio=null,infoTab='glossary',pendingImport=null,importToken=0;
try { const raw=localStorage.getItem(C.key);if(raw){try{state=C.normalize(JSON.parse(raw),D);}catch{saveNotice=T('saveInvalid');}} }catch{storageOK=false;}
if(matchMedia('(prefers-reduced-motion: reduce)').matches)state.motion=false;
const play=$('#play-dialog'),info=$('#info-dialog');
function save(){try{localStorage.setItem(C.key,JSON.stringify(state));storageOK=true;}catch{storageOK=false;}updateSave();document.dispatchEvent(new Event('quest-state-changed'));}
function updateSave(){$('#save-status').textContent=storageOK?T('saveOk'):T('saveTemp');}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4200);}
function sound(kind='tap'){
 if(!state.sound)return;
 try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const notes=kind==='win'?[523.25,659.25,783.99]:kind==='wrong'?[196,164.81]:[440];notes.forEach((freq,i)=>{const o=audio.createOscillator(),g=audio.createGain(),at=audio.currentTime+i*.085;o.type='sine';o.frequency.setValueAtTime(freq,at);g.gain.setValueAtTime(0,at);g.gain.linearRampToValueAtTime(.04,at+.012);g.gain.exponentialRampToValueAtTime(.001,at+.15);o.connect(g);g.connect(audio.destination);o.start(at);o.stop(at+.16);});}catch{state.sound=false;save();}
}
function syncModal(){const opened=!!document.querySelector('dialog[open]');document.body.classList.toggle('modal-open',opened);world?.setPaused(opened);}
document.addEventListener('quest-modal',syncModal);
function openDialog(dialog){if(!dialog.open)dialog.showModal();syncModal();dialog.scrollTop=0;}
play.addEventListener('close',()=>{syncModal();renderHome();if(!document.querySelector('dialog[open]'))$('#start-mission')?.focus({preventScroll:true});});info.addEventListener('close',syncModal);
for(const dialog of [play,info])dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();});
function currentAvailable(){return Math.min(C.stats(state,D).completed,5);}
function chooseMission(i){if(i<0||i>=D.missions.length)return;const fromNav=document.activeElement?.hasAttribute('data-stage');clearTimeout(toastTimer);$('#toast').classList.remove('visible');state.selected=i;save();renderHome();if(fromNav)$(`[data-stage="${i}"]`)?.focus({preventScroll:true});sound();if(!C.canOpen(state,D,i))toast(T('lockedStation',i+1,F(D.missions[i-1],'name').toLowerCase()));}
function renderHome(){
 const st=C.stats(state,D),m=D.missions[state.selected],open=C.canOpen(state,D,state.selected),finished=m.tasks.every(t=>state.done[t.id]);
 $('#xp').textContent=st.xp.toLocaleString(locale());$('#progress-fraction').textContent=`${st.done}/18`;$('#bag-count').textContent=st.completed;
 $('#rank').textContent=st.completed===6?SN('ranks').guardian:st.completed>=4?SN('ranks').evidence:st.completed>=2?SN('ranks').architect:SN('ranks').apprentice;
 $('#stage-nav').innerHTML=D.missions.map((mission,i)=>{const allowed=C.canOpen(state,D,i),complete=mission.tasks.every(t=>state.done[t.id]);return `<button class="stage-node" data-stage="${i}" aria-current="${i===state.selected}" data-locked="${!allowed}" aria-label="${i+1}. ${esc(mission.name)}: ${complete?T('stageAriaDone'):allowed?T('stageAriaOpen'):T('stageAriaLocked')}"><span class="node-icon" aria-hidden="true">${complete?'✓':mission.glyph}</span><span class="node-label"><small>${String(i+1).padStart(2,'0')} ${mission.tag}</small><strong>${esc(mission.name)}</strong></span>${complete?'<span class="status-tick">✓</span>':''}</button>`;}).join('');
 $('#mission-panel').innerHTML=`<div class="mission-kicker"><span>${finished?T('mDone'):open?T('mAvailable'):T('mLocked')}</span><span class="mission-number">${String(state.selected+1).padStart(2,'0')} / 06</span></div><div class="mission-icon" aria-hidden="true">${m.glyph}</div><h2>${esc(m.title)}</h2><p>${esc(m.brief)}</p><div class="mission-meta"><span class="tag">${T('tagChallenges')}</span><span class="tag">${m.boss?T('tagBoss'):T('tagXp')}</span><span class="tag">${esc(m.artifact)}</span></div><ol class="task-preview">${m.tasks.map((t,i)=>`<li class="${state.done[t.id]?'finished':''}"><span>${state.done[t.id]?'✓':i+1}</span>${esc(F(t,'title').replace('Equipe-se contra o ','').replace('Enfrente o ','').replace('Derrote o ',''))}</li>`).join('')}</ol><button class="primary" id="start-mission" ${!open?'disabled':''}>${finished?T('btnRevisit'):m.tasks.some(t=>state.done[t.id])?T('btnContinue'):T('btnStart')} <span aria-hidden="true">→</span></button><p class="mission-note">${open?T('noteOpen'):T('noteLocked',state.selected)}</p>${QuestTLCData.stageMap[state.selected].length?`<div class="tlc-station-links"><span>${T('practiceSkills')}</span>${QuestTLCData.stageMap[state.selected].map(id=>`<button class="tlc-station-link" data-open-tlc="${id}">${QuestTLCData.modules.find(m=>m.id===id).skill} ↗</button>`).join('')}</div>`:''}${st.completed===6?`<button class="text-button" id="journey-btn">${T('journeySummary')}</button>`:''}`;
 $('#start-mission').addEventListener('click',()=>openMission(state.selected));$('#journey-btn')?.addEventListener('click',showFinal);
 document.body.classList.toggle('reduce-motion',!state.motion);$('#motion-btn').textContent=state.motion?T('motionPause'):T('motionPlay');$('#motion-btn').setAttribute('aria-pressed',String(!state.motion));updateSave();world?.refresh();
}
$('#stage-nav').addEventListener('click',e=>{const b=e.target.closest('[data-stage]');if(b)chooseMission(Number(b.dataset.stage));});
function initialAnswer(task){if(task.type==='incident')return C.freshIncident(QL.get());if(['select','diff','order'].includes(task.type))return [];if(['classify','gate'].includes(task.type))return {};return '';}
function openMission(mi){
 if(!C.canOpen(state,D,mi)){toast(T('prevStation'));return;}
 const pending=D.missions[mi].tasks.findIndex(t=>!state.done[t.id]);state.selected=mi;save();renderHome();openTask(mi,pending<0?0:pending);openDialog(play);
}
function openTask(mi,ti){
 const task=D.missions[mi].tasks[ti];active={mi,ti,answer:structuredClone(state.drafts[task.id]??initialAnswer(task)),success:false,feedback:null,hintOpen:false,results:null,award:0};
 if(task.type==='incident')active.answer=state.done[task.id]?C.freshIncident(QL.get()):C.restoreIncident(state.drafts[task.id],QL.get());renderTask();play.scrollTop=0;requestAnimationFrame(()=>$('#dialog-title')?.focus({preventScroll:true}));
}
function getTask(){return D.missions[active.mi].tasks[active.ti];}
function draft(){if(!active)return;const t=getTask();state.drafts[t.id]=t.type==='incident'?C.restoreIncident(active.answer,QL.get()):structuredClone(active.answer);save();}
function renderTask(){
 const t=getTask(),m=D.missions[active.mi];
 $('#dialog-content').innerHTML=`<div class="dialog-top"><span class="eyebrow">${String(active.mi+1).padStart(2,'0')} / ${m.tag} <span class="sep">/</span> ${esc(m.place)}</span><button class="close-btn" data-action="close" aria-label="${T('closeSave')}">×</button></div><div class="dialog-main"><div class="lesson-top"><div class="lesson-head"><div class="step-dots" aria-label="${T('dotsAria',active.ti+1)}">${m.tasks.map((_,i)=>`<span class="${i<=active.ti?'active':''}"></span>`).join('')}</div>${t.boss?`<span class="boss-kicker">${T('bossKicker')}${SN('bossNames')[t.boss]}</span>`:`<span class="eyebrow">${T('missionCode')}</span>`}<h2 id="dialog-title" tabindex="-1">${esc(F(t,'title'))}</h2><p>${esc(F(t,'lead'))}</p></div>${t.boss?'<canvas class="boss-portrait" id="boss-portrait" aria-hidden="true"></canvas>':''}</div><details class="lesson-primer"><summary>${T('primerSummary')}</summary><p>${esc(F(D.primers[t.id],'concept'))}</p><p><strong>${T('exampleLabel')}</strong> ${esc(F(D.primers[t.id],'example'))}</p></details><div class="instruction">${esc(F(t,'instruction')||T('instructionDefault'))}</div><div id="exercise">${exerciseHTML(t)}</div><div id="test-results"></div><div id="hint-slot"></div><div id="feedback-slot" aria-live="polite"></div><div class="dialog-actions"><button class="hint-button" data-action="hint">${T('hintLabel')}<span>${T('hintCost')}</span></button><div class="action-main"><span class="xp-note">${state.done[t.id]?T('xpReview'):T('xpUpTo',C.score(state.attempts[t.id],state.hints[t.id]))}</span><button class="primary" id="verify-btn" data-action="verify">${verifyLabel(t)}</button></div></div></div>`;
 if(t.boss)QuestBoss($('#boss-portrait'),t.boss,active.success);renderFeedback();renderHint();renderTestResults();if(active.success)freezeExercise();
}
function verifyLabel(t){if(active.success)return active.ti===2?T('verifyFinish'):T('verifyNext');return t.type==='patch'?T('verifyPatch'):t.type==='gate'?T('verifyGate'):t.type==='incident'?T('verifyIncident'):T('verifyChoice');}
function optionHTML(o,index,{multi=false,patch=false}={}){const selected=Array.isArray(active.answer)?active.answer.includes(o.id):active.answer===o.id;return `<button class="option" data-option="${o.id}" aria-pressed="${selected}">${multi?'<span class="check" aria-hidden="true">✓</span>':`<span class="option-index" aria-hidden="true">${String(index+1).padStart(2,'0')}</span>`}<div><strong>${esc(F(o,'label'))}</strong>${o.code?`<pre>${esc(o.code)}</pre>`:''}${o.text?`<p>${esc(F(o,'text'))}</p>`:''}</div>${o.lines?`<span class="line-count">+${o.lines}</span>`:''}</button>`;}
function exerciseHTML(t){
 const options=t.options?C.shuffled(t.options,t.id):null;
 if(t.type==='select')return `<div class="cards">${options.map((o,i)=>optionHTML(o,i,{multi:true})).join('')}</div>`;
 if(t.type==='diff')return `<div id="diff-budget">${budgetHTML(t)}</div><div class="cards">${options.map((o,i)=>optionHTML(o,i,{multi:true})).join('')}</div>`;
 if(t.type==='choice')return `${t.chart?chartHTML(8):''}<div class="options-list">${options.map((o,i)=>optionHTML(o,i)).join('')}</div>`;
 if(t.type==='patch')return `<div class="cards">${options.map((o,i)=>optionHTML(o,i,{patch:true})).join('')}</div>`;
 if(t.type==='classify')return `<div class="classify-list">${t.items.map((item,i)=>`<div class="classify-row" data-item="${item.id}"><label for="classify-${item.id}">${esc(F(item,'text'))}</label><select id="classify-${item.id}" data-field="${item.id}"><option value="">${T('chooseCategory')}</option>${C.shuffled(t.groups,t.id+item.id).map(g=>`<option value="${g[0]}" ${active.answer[item.id]===g[0]?'selected':''}>${esc(tupleLabel(g))}</option>`).join('')}</select></div>`).join('')}</div>`;
 if(t.type==='order')return `<div class="order-workbench"><div class="order-zone"><div class="zone-title"><span>${T('seqTitle',active.answer.length,t.steps.length)}</span><button class="small-btn" data-action="undo" ${active.answer.length?'':'disabled'}>${T('undo')}</button></div>${active.answer.length?active.answer.map((id,i)=>`<div class="order-item"><b>${i+1}</b><span>${esc(F(t.steps.find(s=>s.id===id)||{},'text'))}</span></div>`).join(''):`<div class="empty-order">${T('emptyOrder')}</div>`}</div><div class="order-options">${C.shuffled(t.steps,t.id).map(s=>`<button class="option" data-step="${s.id}" ${active.answer.includes(s.id)?'disabled':''}><span class="option-index">＋</span>${esc(F(s,'text'))}</button>`).join('')}</div></div>`;
 if(t.type==='gate')return `<div class="gate-revision"><span>CANDIDATA:</span><del>7c9e2a1</del><span>→</span><code>8d0fa42</code><span>POLÍTICA: p4</span></div><div class="gate-grid">${t.fields.map((f,i)=>`<div class="gate-field" data-item="${f.id}"><label for="gate-${f.id}"><b>${String(i+1).padStart(2,'0')}</b>${esc(F(f,'label'))}</label><select id="gate-${f.id}" data-field="${f.id}"><option value="">${T('selectEntry')}</option>${f.options.map(o=>`<option value="${o[0]}" ${active.answer[f.id]===o[0]?'selected':''}>${esc(tupleLabel(o))}</option>`).join('')}</select></div>`).join('')}</div>`;
 if(t.type==='incident')return incidentHTML();return '';
}
function budgetHTML(t){const n=t.options.filter(o=>active.answer.includes(o.id)).reduce((s,o)=>s+o.lines,0);return `<div class="diff-budget ${n>t.budget?'over':''}"><div class="budget-number">${n} <small>/ ${t.budget}</small></div><div class="budget-info"><span>${T('budgetLabel')}</span><div class="meter"><span style="width:${Math.min(100,n/t.budget*100)}%"></span></div></div></div>`;}
function chartHTML(burn){const points=burn===8?'18,81 72,76 125,79 178,73 231,75 284,56 337,42 390,37 443,24 496,21 549,17 600,14':'18,23 72,28 125,35 178,31 231,39 284,45 337,42 390,53 443,50 496,52 549,49 600,48';return `<svg class="metric-plot" viewBox="0 0 620 108" role="img" aria-label="${T('chartAria',burn)}"><path d="M18 25H600 M18 52H600 M18 81H600" stroke="#2c4547" stroke-width="1"/><path d="M18 87H600" stroke="#96c9a0" stroke-dasharray="4 6"/><polyline points="${points}" fill="none" stroke="#f0ba8e" stroke-width="2.5"/><text x="22" y="17" fill="#b1c9bb" font-size="8" font-family="monospace">${T('chartData')}</text><text x="595" y="100" fill="#84b59b" text-anchor="end" font-size="8" font-family="monospace">${T('chartGoal')}</text></svg><div class="plot-caption">${T('chartCaption')}</div>`;}
function incidentHTML(){const s=active.answer,labels=SN('incidentPhases');return `${chartHTML(s.burn)}<div class="incident-console"><div class="incident-status"><span>● ${labels[s.phase]}</span><span>${T('incidentActions')}${s.actions}/1</span></div><div class="incident-log" aria-live="polite">${s.log.map(line=>`<p>${esc(line)}</p>`).join('')}</div></div><div class="incident-actions">${Object.entries(SN('incidentBtns')).map(([id,label])=>`<button data-incident="${id}" class="${id==='rollback'?'danger-btn':''}">${label}</button>`).join('')}</div>`;}
function freezeExercise(){$$('#exercise button, #exercise select').forEach(b=>b.disabled=true);$('#verify-btn').textContent=verifyLabel(getTask());$('#verify-btn').disabled=false;}
function renderHint(){const t=getTask();$('#hint-slot').innerHTML=active.hintOpen?`<div class="hint"><strong>${T('mentor')}</strong>${esc(F(t,'hint'))}<br><span>${esc(F(D.missions[active.mi],'lesson'))}</span></div>`:'';const b=$('[data-action="hint"]');if(b){b.innerHTML=active.hintOpen?T('hideHint'):`${T('hintLabel')}<span>(${state.done[t.id]||state.hints[t.id]?T('hintFree'):T('hintCost')})</span>`;}}
function renderFeedback(){
 const f=active.feedback,t=getTask(),el=$('#feedback-slot');if(!el)return;
 el.innerHTML=f?`<div class="feedback ${f.ok?'good':''}" tabindex="-1"><strong>${active.success?(t.boss?T('fbBoss'):T('fbValidated')):(f.ok?T('fbConsole'):f.empty?T('fbEmpty'):T('fbGate'))} ${active.success&&active.award?`+${active.award} XP`:''}</strong>${esc(f.message)}${active.success?`<div class="takeaway"><b>${T('nextPr')}</b>${esc(F(t,'takeaway'))}</div>`:''}</div>`:'';
 if(f&&!f.ok&&!f.empty&&['classify','gate'].includes(t.type)){$$('[data-item]').forEach(row=>{const id=row.dataset.item,expected=t.type==='classify'?t.items.find(i=>i.id===id).answer:t.answer[id];row.classList.toggle('invalid',active.answer[id]!==expected);row.querySelector('select')?.setAttribute('aria-invalid',String(active.answer[id]!==expected));});}
}
function renderTestResults(){const el=$('#test-results');if(!active.results){el.innerHTML='';return;}el.innerHTML=`<div class="test-console"><strong>${T('consoleTitle',active.results.filter(r=>r.pass).length)}</strong><div>${T('consoleNote')}</div>${active.results.map(r=>`<div class="test-result"><span class="${r.pass?'yes':'no'}">${r.pass?T('pass'):T('fail')}</span><span>${esc(r.label)}${!r.pass?` <span class="result-actual">${T('expectedActual',r.expected??'null',r.actual??'null')}</span>`:''}</span></div>`).join('')}</div>`;}
function clearFeedback(){active.feedback=null;$('#feedback-slot').innerHTML='';$$('.invalid').forEach(el=>el.classList.remove('invalid'));$$('[aria-invalid]').forEach(el=>el.removeAttribute('aria-invalid'));}
function verify(){
 if(active.success){nextTask();return;}
 const t=getTask();if(t.type==='incident'&&active.answer.phase!=='complete'){active.feedback={ok:false,message:T('incidentIncomplete')};renderFeedback();return;}
 if(!C.hasAnswer(t,active.answer)){active.feedback={ok:false,empty:true,message:T('chooseFirst')};renderFeedback();return;}
 const existing=!!state.done[t.id];if(t.type==='patch'){active.results=C.runPatch(active.answer,QL.get());renderTestResults();}
 const r=C.complete(state,D,t,active.answer,QL.get());active.feedback=r;
 if(r.ok){active.success=true;active.award=existing?0:state.done[t.id].score;sound('win');freezeExercise();if(t.boss)QuestBoss($('#boss-portrait'),t.boss,true);}
 else{if(!existing)state.attempts[t.id]=(state.attempts[t.id]||0)+1;sound('wrong');}
 draft();renderHint();renderFeedback();const xpNote=$('.xp-note');if(xpNote)xpNote.textContent=existing?T('xpReview'):active.success?T('xpWon',active.award):T('xpUpTo',C.score(state.attempts[t.id],state.hints[t.id]));renderHome();
 requestAnimationFrame(()=>{const f=$('#feedback-slot');f.scrollIntoView({behavior:'instant',block:'nearest'});if(document.activeElement===document.body||document.activeElement?.disabled)$('#verify-btn')?.focus({preventScroll:true});});
}
function nextTask(){if(active.ti<2)openTask(active.mi,active.ti+1);else showReward(active.mi);}
function showReward(mi){
 const m=D.missions[mi],xp=m.tasks.reduce((n,t)=>n+(state.done[t.id]?.score||0),0),stars=xp>=270?3:xp>=210?2:1;
 $('#dialog-content').innerHTML=`<div class="dialog-top"><span class="eyebrow">ESTAÇÃO ${String(mi+1).padStart(2,'0')} · ${m.tag}</span><button class="close-btn" data-action="close" aria-label="${T('closeMap')}">×</button></div><div class="dialog-main"><div class="reward"><div class="reward-badge" aria-hidden="true">${m.glyph}</div><div class="eyebrow">${T('rewardEyebrow')}</div><h2 id="dialog-title" tabindex="-1">${esc(T('rewardTitle',m.name))}</h2><div class="stars" aria-label="${T('starsAria',stars)}">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div><p>${esc(m.lesson)}</p><div class="artifact-display"><span class="artifact-icon">▤</span><div><strong>${esc(m.artifact)}</strong><small>${T('artifactUnlocked',xp)}</small></div></div><p>${T('artifactNote')}</p><div class="reward-buttons"><button class="secondary" data-action="download-artifact" data-mi="${mi}">${T('saveArtifact')}</button><button class="primary" data-action="advance" data-mi="${mi}">${mi===5?T('myJourney'):T('nextStation')}</button></div></div></div>`;
 play.scrollTop=0;$('#dialog-title').focus({preventScroll:true});renderHome();
}
function showFinal(){
 const st=C.stats(state,D);if(st.completed!==6)return;const needs=D.missions.flatMap(m=>m.tasks).filter(t=>(state.attempts[t.id]||0)>0||state.hints[t.id]);const first=D.missions.flatMap(m=>m.tasks).filter(t=>!state.attempts[t.id]&&!state.hints[t.id]).length;
 $('#dialog-content').innerHTML=`<div class="dialog-top"><span class="eyebrow">${T('finalEyebrow')}</span><button class="close-btn" data-action="close" aria-label="${T('closeMap')}">×</button></div><div class="dialog-main"><div class="reward"><div class="reward-badge" aria-hidden="true">✦</div><div class="eyebrow">${T('finalAchievement')}</div><h2 id="dialog-title" tabindex="-1">${T('finalTitle')}</h2><p>${T('finalLead')}</p><div class="summary-grid"><div><strong>${st.xp}</strong><small>${T('finalXp')}</small></div><div><strong>${T('finalNoHelpCount',first)}</strong><small>${T('finalNoHelp')}</small></div><div><strong>5/5</strong><small>${T('finalBosses')}</small></div></div><div class="medals">${st.bosses.map(id=>`<canvas data-medal="${id}" aria-label="${T('medalAria',SN('bossNames')[id])}"></canvas>`).join('')}</div><div class="final-status"><strong>${T('finalStatusStrong')}</strong><br>${T('finalStatusText')}</div>${needs.length?`<div class="review-list"><div class="eyebrow">${T('revisit',needs.length)}</div>${needs.map(t=>`<div class="glossary-item"><h3>${esc(F(t,'title'))}</h3><p>${esc(F(t,'takeaway'))}</p></div>`).join('')}</div>`:`<p>${T('allClean')}</p>`}<div class="reward-buttons"><button class="primary" data-action="transfer">${T('transferBtn')}</button><button class="secondary" data-action="report">${T('exportPlaybook')}</button><button class="secondary" data-action="close">${T('closeMap')}</button></div></div></div>`;
 openDialog(play);$$('[data-medal]').forEach(el=>QuestBoss(el,el.dataset.medal,true));$('#dialog-title').focus({preventScroll:true});
}
$('#dialog-content').addEventListener('click',e=>{
 const button=e.target.closest('button');if(!button||button.disabled)return;
 const action=button.dataset.action;
 if(action==='close'){play.close();return;}
 if(action==='advance'){const i=Number(button.dataset.mi);if(i===5)showFinal();else openMission(i+1);return;}
 if(action==='download-artifact'){downloadArtifact(Number(button.dataset.mi));return;}
 if(action==='report'){exportReport();return;}
 if(action==='transfer'){openTransfer();return;}
 if(!active)return;const t=getTask();
 if(action==='verify'){verify();return;}
 if(action==='hint'){active.hintOpen=!active.hintOpen;if(active.hintOpen&&!state.done[t.id]){state.hints[t.id]=1;save();}renderHint();const xp=$('.xp-note');if(xp&&!state.done[t.id])xp.textContent=T('xpUpTo',C.score(state.attempts[t.id],state.hints[t.id]));return;}
 if(active.success)return;
 if(button.dataset.option){const id=button.dataset.option;if(['select','diff'].includes(t.type)){active.answer=active.answer.includes(id)?active.answer.filter(x=>x!==id):[...active.answer,id];}else active.answer=id;
  $$('[data-option]').forEach(b=>b.setAttribute('aria-pressed',String(Array.isArray(active.answer)?active.answer.includes(b.dataset.option):active.answer===b.dataset.option)));clearFeedback();if(t.type==='diff')$('#diff-budget').innerHTML=budgetHTML(t);active.results=null;renderTestResults();draft();sound();return;}
 if(button.dataset.step){active.answer.push(button.dataset.step);clearFeedback();$('#exercise').innerHTML=exerciseHTML(t);draft();sound();const next=$('[data-step]:not(:disabled)');(next||$('#verify-btn')).focus({preventScroll:true});return;}
 if(action==='undo'){active.answer.pop();clearFeedback();$('#exercise').innerHTML=exerciseHTML(t);draft();($('[data-action="undo"]:not(:disabled)')||$('[data-step]:not(:disabled)'))?.focus({preventScroll:true});return;}
 if(button.dataset.incident){
  const r=C.stepIncident(active.answer,button.dataset.incident,QL.get());active.answer=r.state;active.feedback={ok:r.ok,message:r.message};if(!r.ok&&!state.done[t.id])state.attempts[t.id]=(state.attempts[t.id]||0)+1;
  $('#exercise').innerHTML=incidentHTML();renderFeedback();draft();sound(r.ok?'tap':'wrong');
  if(r.done){verify();}else requestAnimationFrame(()=>{const btn=$(`[data-incident="${button.dataset.incident}"]`);btn?.focus({preventScroll:true});});
 }
});
$('#dialog-content').addEventListener('change',e=>{if(!active||active.success)return;const field=e.target.dataset.field;if(!field)return;active.answer[field]=e.target.value;clearFeedback();draft();});
function download(name,content,type='text/markdown;charset=utf-8'){
 const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);toast(T('filePrepared',name));
}
function downloadArtifact(mi){const m=D.missions[mi];if(!m.tasks.every(t=>state.done[t.id])){toast(T('artifactLocked'));return;}download(m.artifact,D.artifacts[m.artifact],m.artifact.endsWith('.json')?'application/json':'text/markdown;charset=utf-8');}
function exportReport(){
 const st=C.stats(state,D),time=new Date().toISOString();let out=`# SDLC Quest — Meu playbook de aprendizagem\n\nGerado em: ${time}\n\n## Limite desta evidência\nEste é um registro local de uma simulação didática. Não comprova a execução de uma API, pipeline ou infraestrutura real. Não é certificado profissional nem autorização de release. O save é local e editável.\n\n## Progresso\n${st.completed}/6 missões, ${st.done}/18 desafios, ${st.bosses.length}/5 chefes. Pontuação: ${st.xp}/1800 XP.\n\n## Decisões e aprendizado\n`;
 for(const m of D.missions){out+=`\n### ${m.tag} — ${m.name}\n${m.lesson}\n\n`;for(const t of m.tasks){out+=`- ${state.done[t.id]?'CONCLUÍDO':'PENDENTE'}: ${t.title}. Erros: ${state.attempts[t.id]||0}. Ajuda: ${state.hints[t.id]?'sim':'não'}. XP: ${state.done[t.id]?.score||0}.\n  ${t.takeaway}\n`;}}
 out+='\n## Minha aplicação a uma feature real\nEste rascunho é do jogador e não foi validado por IA, teste ou revisor. Não concede aprovação.\n';for(const [k,title] of transferFields)out+=`\n### ${title}\n${state.transfer?.[k]||'[Não preenchido]'}\n`;
 out+='\n## Modelos desbloqueados (não são evidência operacional)\n';for(const m of D.missions)if(m.tasks.every(t=>state.done[t.id]))out+=`\n### ${m.artifact}\n\n\`\`\`${m.artifact.endsWith('.json')?'json':'markdown'}\n${D.artifacts[m.artifact]}\n\`\`\`\n`;
 out+='\n## Referências primárias\nMaterial consultado em 8 de setembro de 2026. As políticas e cenários do jogo são propostas didáticas, não padrões universais.\n';for(const s of D.sources)out+=`\n- ${s.name}: ${s.url}\n`;if(window.SDLCQuestTLC)out+='\n\n'+SDLCQuestTLC.guide();download('meu-playbook-sdlc-quest.md',out);
}
function infoShell(title,body,focusSelector=null){$('#info-content').innerHTML=`<div class="dialog-top"><span class="eyebrow">${T('fieldNotebook')}</span><button class="close-btn" data-info="close" aria-label="${T('closeNotebook')}">×</button></div><div class="info-main"><h2 id="info-title" tabindex="-1">${title}</h2>${body}</div>`;openDialog(info);requestAnimationFrame(()=>{const target=focusSelector?info.querySelector(focusSelector):$('#info-title');target?.focus({preventScroll:true});});}
function openManual(tab='glossary'){
 infoTab=tab;const tabs=`<div class="info-tabs"><button data-info="glossary" aria-pressed="${tab==='glossary'}" class="${tab==='glossary'?'active':''}">${T('tabConcepts')}</button><button data-info="method" aria-pressed="${tab==='method'}" class="${tab==='method'?'active':''}">${T('tabMethod')}</button><button data-info="sources" aria-pressed="${tab==='sources'}" class="${tab==='sources'?'active':''}">${T('tabSources')}</button></div>`;
 let body='';if(tab==='glossary')body=`<label class="hidden" for="glossary-search">${T('searchAria')}</label><input type="search" class="search" id="glossary-search" aria-label="${T('searchAria')}" placeholder="${T('searchPlaceholder')}"><div id="glossary-results"></div>`;
 else if(tab==='method')body=`<p>${T('methodIntro')}</p>${D.missions.map((m,i)=>`<div class="glossary-item"><h3>${i+1}. ${esc(m.name)} · ${m.tag}</h3><p>${esc(m.lesson)}</p><p><strong>${T('artifactLabel')}</strong> ${m.artifact}</p></div>`).join('')}<p class="info-note">${T('methodNote')}</p>`;
 else body=`<p>${T('sourcesIntro')}</p>${D.sources.map(s=>`<a class="source-item" href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.name)} ↗<small>${esc(s.topic)}</small></a>`).join('')}<p class="info-note">${T('sourcesNote')}</p>`;
 infoShell(T('manualTitle'),tabs+body+`<div class="transfer-link"><button class="secondary" data-open-tlc="kit">${T('tlcLink')}</button></div><div class="transfer-link"><button class="secondary" data-info="transfer">${T('transferLink')}</button></div>`);if(tab==='glossary'){renderGlossary('');$('#glossary-search').addEventListener('input',e=>renderGlossary(e.target.value));}
}
function renderGlossary(query){const norm=s=>String(s).toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');const q=norm(query);const items=D.glossary.filter(g=>norm(g.join(' ')).includes(q));$('#glossary-results').innerHTML=items.length?items.map(([name,text])=>`<article class="glossary-item"><h3>${esc(name)}</h3><p>${esc(text)}</p></article>`).join(''):`<p>${T('glossaryEmpty')}</p>`;}
function openBag(){
 const st=C.stats(state,D);infoShell(T('bagTitle'),`<p>${T('bagIntro',st.completed)}</p>${D.missions.map((m,i)=>{const unlocked=m.tasks.every(t=>state.done[t.id]);return `<div class="artifact-row"><div><code>${esc(m.artifact)}</code><small>${unlocked?T('unlocked'):T('lockedMission',i+1)} · ${m.tag}</small></div><button class="small-btn" data-info="artifact" data-mi="${i}" ${unlocked?'':'disabled'}>${T('open')}</button></div>`;}).join('')}<p class="info-note">${T('bagNote')}</p><button class="primary" data-info="report">${T('exportProgress')}</button>`);
}
function showArtifact(mi){const m=D.missions[mi];if(!m.tasks.every(t=>state.done[t.id]))return;infoShell(esc(m.artifact),`<p>${T('artifactIntro',m.name)}</p><pre class="artifact-preview">${esc(D.artifacts[m.artifact])}</pre><div class="reward-buttons"><button class="secondary" data-info="bag">${T('backArtifacts')}</button><button class="primary" data-info="download" data-mi="${mi}">${T('saveFile')}</button></div>`);}
function openSettings(){const previous=document.activeElement?.dataset.info;infoShell(T('settingsTitle'),`<div class="settings-row"><div>${T('soundLabel')}<span>${T('soundNote')}</span></div><button class="secondary" data-info="sound" aria-pressed="${state.sound}">${state.sound?T('on'):T('off')}</button></div><div class="settings-row"><div>${T('motionLabel')}<span>${T('motionNote')}</span></div><button class="secondary" data-info="motion" aria-pressed="${state.motion}">${state.motion?T('motionOn'):T('motionPaused')}</button></div><div class="settings-row"><div>${T('progressLabel')}<span>${storageOK?T('progressSaved'):T('progressTemp')}</span></div><button class="secondary" data-info="report">${T('exportBtn')}</button></div><div class="settings-row"><div>${T('resetLabel')}<span>${T('resetNote')}</span></div><button class="danger-outline" data-info="reset-confirm">${T('restart')}</button></div><div class="backup-controls"><button class="secondary" data-info="backup">${T('backupDown')}</button><button class="secondary" data-info="import">${T('backupUp')}</button><input class="hidden" type="file" id="import-file" accept=".json,application/json" aria-label="${T('backupFileAria')}"></div><p class="info-note">${T('settingsNote')}</p><button class="text-button" data-info="help">${T('helpLink')}</button>`,['sound','motion'].includes(previous)?`[data-info="${previous}"]`:null);}
function openHelp(){infoShell(T('helpTitle'),`<p>${T('helpIntro')}</p><div class="help-step"><b>1</b><p><strong>${T('help1Title')}</strong> ${T('help1Body')}</p></div><div class="help-step"><b>2</b><p><strong>${T('help2Title')}</strong> ${T('help2Body')}</p></div><div class="help-step"><b>3</b><p><strong>${T('help3Title')}</strong> ${T('help3Body')}</p></div><div class="help-step"><b>4</b><p><strong>${T('help4Title')}</strong> ${T('help4Body')}</p></div><p class="info-note">${T('keyboardNote')}</p><button class="primary" data-info="start">${T('goToAvailable')}</button>`);}
$('#info-content').addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const action=b.dataset.info;
 if(action==='close')info.close();
 if(['glossary','method','sources'].includes(action))openManual(action);
 if(action==='bag')openBag();if(action==='artifact')showArtifact(Number(b.dataset.mi));if(action==='download')downloadArtifact(Number(b.dataset.mi));if(action==='report')exportReport();
 if(action==='sound'){state.sound=!state.sound;save();sound('win');openSettings();}
 if(action==='motion'){state.motion=!state.motion;save();renderHome();openSettings();}
 if(action==='help')openHelp();
 if(action==='transfer')openTransfer();
 if(action==='backup')download('sdlc-quest-backup.json',JSON.stringify(C.makeBackup(state,D),null,2),'application/json');
 if(action==='import')$('#import-file')?.click();
 if(action==='cancel-import'){pendingImport=null;openSettings();}
 if(action==='confirm-import'&&pendingImport){state=C.normalize(pendingImport,D);pendingImport=null;if(matchMedia('(prefers-reduced-motion: reduce)').matches)state.motion=false;save();active=null;if(play.open)play.close();info.close();renderHome();toast(T('backupRestored'));document.dispatchEvent(new Event('quest-state-replaced'));}

 if(action==='start'){info.close();openMission(currentAvailable());}
 if(action==='reset-confirm'){infoShell(T('resetConfirmTitle'),`<p>${T('resetConfirmBody')}</p><div class="reward-buttons"><button class="secondary" data-info="settings">${T('cancel')}</button><button class="danger-outline" data-info="reset">${T('resetConfirmBtn')}</button></div>`);}
 if(action==='settings')openSettings();
 if(action==='reset'){state=C.empty();if(matchMedia('(prefers-reduced-motion: reduce)').matches)state.motion=false;save();active=null;if(play.open)play.close();info.close();renderHome();toast(T('newCampaign'));document.dispatchEvent(new Event('quest-state-replaced'));}
});
const transferFields=[['intent','1. Intenção e resultado observável'],['evidence','2. Prova de aceitação e revisão verificada'],['authority','3. Limite de autoridade e responsável'],['stop','4. Sinal para abortar, mitigar ou escalar']];
function openTransfer(){
 const fields=SN('transferFields'),prompts=SN('transferPrompts');
 infoShell(T('transferTitle'),`<p>${T('transferIntro')}</p><p class="info-note">${T('transferSecrets')}</p><div class="worksheet">${C.transferKeys.map(k=>`<label class="worksheet-field" for="transfer-${k}"><strong>${fields[k]}</strong><span>${prompts[k]}</span><textarea id="transfer-${k}" data-transfer="${k}" maxlength="1600" rows="4">${esc(state.transfer?.[k]||'')}</textarea></label>`).join('')}</div><p class="worksheet-status" id="worksheet-status"></p><div class="reward-buttons"><button class="primary" data-info="report">${T('transferExport')}</button><button class="secondary" data-info="backup">${T('backupDown')}</button></div><p class="info-note">${T('transferNote')}</p>`);
 updateWorksheetStatus();
}
function updateWorksheetStatus(){const el=$('#worksheet-status');if(el)el.textContent=`${T('transferFilled',C.transferKeys.filter(k=>state.transfer?.[k]?.trim()).length)}${storageOK?T('transferSaved'):T('transferTemp')}.`;}
$('#info-content').addEventListener('input',e=>{const k=e.target.dataset.transfer;if(!C.transferKeys.includes(k))return;state.transfer[k]=e.target.value.slice(0,1600);save();updateWorksheetStatus();});
$('#info-content').addEventListener('change',async e=>{
 if(e.target.id!=='import-file')return;const file=e.target.files?.[0];if(!file)return;
 const token=++importToken;pendingImport=null;
 try{
  if(file.size>262144)throw new Error('Backup muito grande. O limite é 256 KiB.');
  const text=await file.text();if(token!==importToken||!info.open)return;
  const candidate=C.importBackup(text,D,QL.get());pendingImport=candidate;const st=C.stats(candidate,D);
  infoShell(T('importTitle'),`<p>${T('importFile')} <strong>${esc(file.name)}</strong></p><p>${T('importSummary',st.done,st.completed,st.xp,QuestTLC.stats(candidate.tlc).done)}</p><p class="info-note">${T('importNote')}</p><div class="reward-buttons"><button class="secondary" data-info="backup">${T('importCurrentBackup')}</button><button class="secondary" data-info="cancel-import">${T('cancel')}</button><button class="primary" data-info="confirm-import">${T('replaceBtn')}</button></div>`);
 }catch(error){pendingImport=null;infoShell(T('importFailTitle'),`<p class="info-note" role="alert">${esc(error.message)}</p><p>${T('importUnchanged')}</p><button class="secondary" data-info="settings">${T('backSettings')}</button>`);}
});
$('#quick-start')?.addEventListener('click',()=>C.stats(state,D).completed===6?showFinal():openMission(currentAvailable()));
$('#book-btn').addEventListener('click',()=>openManual());$('#bag-btn').addEventListener('click',openBag);$('#settings-btn').addEventListener('click',openSettings);$('#how-btn').addEventListener('click',openHelp);$('#lang-btn').addEventListener('click',()=>QL.toggle());
document.addEventListener('quest-lang-changed',()=>{renderChrome();renderHome();updateSave();});
$('.brand').addEventListener('click',e=>{e.preventDefault();chooseMission(currentAvailable());window.scrollTo({top:0,behavior:'instant'});});
$('#motion-btn').addEventListener('click',()=>{state.motion=!state.motion;save();renderHome();});
renderChrome();renderHome();
try{world=new QuestWorld($('#world'),D,()=>state,chooseMission);}catch(error){$('#world-tip').textContent=T('worldFallback');console.warn('O mapa não está disponível, mas os desafios continuam acessíveis.',error);}
// Read-only inspection aids: no debug bypass, network, prompt execution, or production actions.
Object.defineProperty(window,'SDLCQuest',{value:Object.freeze({version:'1.3.0',getState:()=>structuredClone(state),getStats:()=>C.stats(state,D),currentTask:()=>active?getTask().id:null}),writable:false});
Object.defineProperty(window,'QuestBridge',{value:Object.freeze({readHarness:()=>structuredClone(state.harness),writeHarness:value=>{state.harness=QuestHarness.normalizeDraft(value);save();},read:()=>structuredClone(state.tlc),write:value=>{state.tlc=QuestTLC.normalize(value);save();},toast,download,backup:()=>download('sdlc-quest-backup.json',JSON.stringify(C.makeBackup(state,D),null,2),'application/json')}),writable:false});
if(saveNotice)toast(saveNotice);save();
})();
