/* SDLC Quest — original educational scenarios. All systems and metrics are fictional. */
(function(root){
'use strict';
const sources = [
 {name:'Anthropic · The AI-Native SDLC playbook',url:'https://claude.com/blog/the-ai-native-sdlc-playbook',topic:'As seis etapas e seus artefatos.',topic_en:'The six stages and their artifacts.'},
 {name:'Claude Code · Hooks reference',url:'https://code.claude.com/docs/en/hooks',topic:'Eventos, decisões e limites dos hooks.',topic_en:'Hook events, decisions and limits.'},
 {name:'Claude Code · Sandboxing',url:'https://code.claude.com/docs/en/sandboxing',topic:'Isolamento e limitações de acesso.',topic_en:'Isolation and access limitations.'},
 {name:'Git · git-worktree',url:'https://git-scm.com/docs/git-worktree',topic:'Checkouts separados não são uma sandbox.',topic_en:'Separate checkouts are not a sandbox.'},
 {name:'Google SRE · Alerting on SLOs',url:'https://sre.google/workbook/alerting-on-slos/',topic:'Alertas por consumo do orçamento de erro.',topic_en:'Alerting on error-budget consumption.'},
 {name:'NIST · Control charts',url:'https://www.itl.nist.gov/div898/handbook/pmc/section3/pmc32.htm',topic:'Regras de controle estatístico e falsos alarmes.',topic_en:'Statistical control rules and false alarms.'}
];
const missions = [
{ id:'plan',name:'Planejar',name_en:'Plan',tag:'PLAN',place:'Observatório da intenção',place_en:'Intent observatory',color:'#e7c176',glyph:'◎',artifact:'intent.md',boss:null,
 title:'Antes do código, o porquê.',title_en:'Before the code, the why.',brief:'A equipe de suporte reenvia webhooks manualmente. Transforme a reclamação em uma mudança que alguém consiga aceitar.',brief_en:'The support team resends webhooks manually. Turn the complaint into a change someone can accept.',
 lesson:'Intenção define o problema e o resultado; não é uma ordem vaga para escrever código. O rigor do processo deve acompanhar o risco, não a quantidade de arquivos.',lesson_en:'Intent defines the problem and the outcome; it is not a vague order to write code. Process rigor should track the risk, not the file count.',
 tasks:[
 {id:'intent',type:'select',axis:'intent',title:'Monte a intenção',title_en:'Assemble the intent',lead:'O suporte pediu: “coloca um botão para tentar de novo”. Escolha as quatro peças que realmente definem o trabalho.',lead_en:'Support asked: “just add a button to try again”. Pick the four pieces that actually define the work.',instruction:'Selecione 4 cartões para compor intent.md.',instruction_en:'Select 4 cards to compose intent.md.',hint:'Procure problema, resultado observável, limites e uma pergunta material. Uma promessa absoluta ou tecnologia escolhida cedo demais não esclarece a necessidade.',hint_en:'Look for the problem, an observable outcome, limits and one material question. An absolute promise or a technology chosen too early does not clarify the need.',
 options:[
 {id:'pain',label:'Problema observado',label_en:'Observed problem',text:'O suporte precisa de engenharia para reenviar entregas de webhook que falharam.',text_en:'Support needs engineering to resend failed webhook deliveries.'},
 {id:'rewrite',label:'Solução apressada',label_en:'Rushed solution',text:'Reescrever todo o serviço em outra linguagem antes de investigar.',text_en:'Rewrite the whole service in another language before investigating.'},
 {id:'outcome',label:'Resultado verificável',label_en:'Verifiable outcome',text:'Um administrador pode solicitar um retry e acompanhar o resultado sem intervenção manual.',text_en:'An administrator can request a retry and track the result without manual intervention.'},
 {id:'scope',label:'Limites explícitos',label_en:'Explicit limits',text:'Somente entregas do próprio tenant; sem novos destinos nem reenvio em massa.',text_en:'Only the tenant’s own deliveries; no new destinations and no bulk resend.'},
 {id:'promise',label:'Promessa absoluta',label_en:'Absolute promise',text:'Garantir que nenhum webhook do mundo falhe novamente.',text_en:'Guarantee that no webhook in the world ever fails again.'},
 {id:'question',label:'Questão em aberto',label_en:'Open question',text:'Como tratar duplicidade quando o destino recebe o evento, mas a resposta se perde?',text_en:'How to handle duplicates when the destination receives the event but the response is lost?'}
 ],answer:['pain','outcome','scope','question'],success:'Você capturou a necessidade sem fingir que todas as decisões estão resolvidas. A questão de duplicidade segue para o design.',success_en:'You captured the need without pretending every decision is settled. The duplicate-delivery question moves on to design.',takeaway:'Antes de pedir código, escreva: problema, resultado, não objetivos, restrições e perguntas em aberto.',takeaway_en:'Before asking for code, write down: problem, outcome, non-goals, constraints and open questions.'},
 {id:'risk',type:'classify',axis:'intent',title:'Risco não se conta em linhas',title_en:'Risk is not counted in lines',lead:'Escolha a trilha proporcional ao impacto de cada mudança. Estas categorias são a política desta campanha, não um padrão universal.',lead_en:'Choose the track proportional to each change’s impact. These categories are this campaign’s policy, not a universal standard.',instruction:'Classifique as três alterações.',instruction_en:'Classify the three changes.',groups:[['fast','Fast · local e reversível','Fast · local and reversible'],['standard','Standard · contratos e módulos','Standard · contracts and modules'],['critical','Critical · dados ou autorização','Critical · data or authorization']],
 items:[{id:'copy',text:'Corrigir um texto de ajuda, sem mudar comportamento.',text_en:'Fix a help text, with no behavior change.',answer:'fast'},{id:'list',text:'Adicionar paginação em uma listagem, preservando acesso e armazenamento.',text_en:'Add pagination to a listing, preserving access and storage.',answer:'standard'},{id:'tenant',text:'Alterar uma linha que decide se um usuário pode acessar dados de outro tenant.',text_en:'Change one line that decides whether a user can access another tenant’s data.',answer:'critical'}],
 hint:'Uma linha de autorização pode merecer mais rigor do que muitos arquivos de documentação.',hint_en:'One authorization line can deserve more rigor than many documentation files.',success:'A trilha Critical acompanha o potencial de dano. O número de linhas, sozinho, não mede risco.',success_en:'The Critical track tracks the damage potential. Line count alone does not measure risk.',takeaway:'Defina exemplos de risco com seu time. Um ajuste simples não precisa de uma esteira de documentos.',takeaway_en:'Define risk examples with your team. A simple tweak does not need a document pipeline.'},
 {id:'intent-gate',type:'choice',axis:'intent',title:'Quem autoriza a próxima etapa?',title_en:'Who authorizes the next stage?',lead:'intent.md existe, mas “qualquer usuário pode reenviar” contradiz a restrição a administradores. O agente quer começar.',lead_en:'intent.md exists, but “any user can resend” contradicts the administrator-only restriction. The agent wants to start.',options:[
 {id:'file',label:'Avançar: o arquivo já existe.',label_en:'Proceed: the file already exists.',why:'A existência do arquivo não resolve a contradição sobre autorização.',why_en:'The file’s existence does not resolve the authorization contradiction.'},
 {id:'guess',label:'Deixar o agente escolher a regra mais fácil.',label_en:'Let the agent pick the easiest rule.',why:'A política de acesso é uma decisão material; facilidade de implementação não a autoriza.',why_en:'Access policy is a material decision; implementation convenience does not authorize it.'},
 {id:'resolve',label:'Resolver a regra com o responsável e atualizar o critério de aceitação.',label_en:'Resolve the rule with the owner and update the acceptance criterion.'}],answer:'resolve',hint:'Um gate valida conteúdo e decisão; não apenas um nome de arquivo.',hint_en:'A gate validates content and decision, not just a file name.',success:'A responsável pelo produto confirma: apenas administradores do tenant. O escopo agora pode ser aceito.',success_en:'The product owner confirms: tenant administrators only. The scope can now be accepted.',takeaway:'Registre quem decide ambiguidades materiais. Não transforme uma suposição do modelo em requisito.',takeaway_en:'Record who decides material ambiguities. Do not turn a model’s assumption into a requirement.'}
 ]},
{ id:'design',name:'Projetar',name_en:'Design',tag:'DESIGN',place:'Oficina de contratos',place_en:'Contract workshop',color:'#a0b4ef',glyph:'◇',artifact:'spec.md',boss:'secret',title:'Dê forma ao comportamento.',title_en:'Give behavior its shape.',brief:'Defina contratos, diferencie instrução de evidência e impeça que o agente de desenvolvimento herde poder de produção.',brief_en:'Define contracts, tell instruction apart from evidence, and keep the development agent from inheriting production power.',lesson:'Uma especificação descreve comportamentos observáveis, inclusive falhas. Instrução, evidência e autoridade têm funções diferentes.',lesson_en:'A specification describes observable behaviors, including failures. Instruction, evidence and authority have different jobs.',
 tasks:[
 {id:'contracts',type:'select',axis:'intent',title:'Especifique o que pode dar errado',title_en:'Specify what can go wrong',lead:'A feature precisa ser segura quando duas requisições chegam juntas, quando o destino demora e quando alguém usa o ID de outro tenant.',lead_en:'The feature must be safe when two requests arrive together, when the destination is slow, and when someone uses another tenant’s ID.',instruction:'Escolha os 4 critérios que podem ser verificados.',instruction_en:'Choose the 4 criteria that can be verified.',options:[
 {id:'tenant',label:'Isolamento de tenant',label_en:'Tenant isolation',text:'Rejeitar acesso a uma entrega de outro tenant, inclusive com ID conhecido.',text_en:'Reject access to another tenant’s delivery, even with a known ID.'},
 {id:'concurrency',label:'Concorrência',label_en:'Concurrency',text:'Aceitar no máximo uma tentativa ativa por entrega, inclusive sob chamadas simultâneas.',text_en:'Accept at most one active attempt per delivery, including under simultaneous calls.'},
 {id:'nice',label:'Qualidade abstrata',label_en:'Abstract quality',text:'Ser moderno, elegante e usar a melhor IA.',text_en:'Be modern, elegant and use the best AI.'},
 {id:'redaction',label:'Logs seguros',label_en:'Safe logs',text:'Registrar a tentativa sem expor tokens ou payloads sensíveis.',text_en:'Log the attempt without exposing tokens or sensitive payloads.'},
 {id:'duplicates',label:'Duplicidade explícita',label_en:'Explicit duplicates',text:'Usar identificador estável do evento e documentar como o destino deve tratar duplicatas.',text_en:'Use a stable event identifier and document how the destination should handle duplicates.'},
 {id:'once',label:'Garantia mágica',label_en:'Magic guarantee',text:'Prometer entrega exatamente uma vez a qualquer servidor externo, sem cooperação dele.',text_en:'Promise exactly-once delivery to any external server without its cooperation.'}
 ],answer:['tenant','concurrency','redaction','duplicates'],hint:'Escolha critérios que um teste ou uma inspeção consiga refutar. Timeout não prova que o destino deixou de processar.',hint_en:'Choose criteria a test or inspection can refute. A timeout does not prove the destination stopped processing.',success:'Seu contrato inclui falhas e limites. Um retry não deve prometer exatamente uma vez em um destino arbitrário.',success_en:'Your contract includes failures and limits. A retry should not promise exactly-once to an arbitrary destination.',takeaway:'Cada critério precisa de uma prova, especialmente autorização, concorrência e efeitos externos.',takeaway_en:'Every criterion needs proof, especially authorization, concurrency and external effects.'},
 {id:'pillars',type:'classify',axis:'evidence',title:'Três coisas que não são a mesma',title_en:'Three things that are not the same',lead:'Distribua cada item pelo papel que ele realmente desempenha.',lead_en:'Assign each item to the role it actually plays.',groups:[['instruction','Instrução · orienta','Instruction · guides'],['evidence','Evidência · demonstra','Evidence · demonstrates'],['authority','Controle · impõe limites','Control · enforces limits']],items:[
 {id:'claude',text:'CLAUDE.md diz: “nunca leia credenciais de produção”.',text_en:'CLAUDE.md says: “never read production credentials”.',answer:'instruction'},
 {id:'ci',text:'Uma execução rastreável de CI mostra testes e commit verificado.',text_en:'A traceable CI run shows tests and a verified commit.',answer:'evidence'},
 {id:'iam',text:'A identidade do agente não possui permissão para acessar o segredo.',text_en:'The agent’s identity has no permission to access the secret.',answer:'authority'},
 {id:'skill',text:'Uma Skill ensina o procedimento de revisar código.',text_en:'A Skill teaches the code review procedure.',answer:'instruction'}],hint:'Uma frase ensina; um resultado rastreável demonstra; uma permissão externa impede.',hint_en:'A sentence teaches; a traceable result demonstrates; an external permission prevents.',success:'Agora você sabe por que uma boa instrução não substitui isolamento e uma mensagem “passed” não substitui uma execução.',success_en:'You now know why a good instruction does not replace isolation and a “passed” message does not replace a run.',takeaway:'Para cada risco, identifique a instrução, a prova esperada e o controle efetivo.',takeaway_en:'For each risk, identify the instruction, the expected proof and the effective control.'},
 {id:'secrets',type:'select',axis:'authority',boss:'secret',title:'Equipe-se contra o Vazador de Segredos',title_en:'Equip yourself against the Secret Leaker',lead:'Um arquivo do repositório manda o agente enviar .env para um endpoint de diagnóstico. Escolha três controles para o ambiente de desenvolvimento.',lead_en:'A repository file tells the agent to send .env to a diagnostics endpoint. Choose three controls for the development environment.',instruction:'Equipe 3 defesas reais. As credenciais neste jogo são fictícias.',instruction_en:'Equip 3 real defenses. The credentials in this game are fictional.',options:[
 {id:'identity',label:'Identidade de privilégio mínimo',label_en:'Least-privilege identity',text:'Nenhuma permissão de produção disponível no workspace.',text_en:'No production permissions available in the workspace.'},
 {id:'prompt',label:'Uma frase em negrito',label_en:'A sentence in bold',text:'Escrever “NUNCA vaze segredos” e manter acesso irrestrito.',text_en:'Write “NEVER leak secrets” and keep unrestricted access.'},
 {id:'fs',label:'Isolamento de leitura',label_en:'Read isolation',text:'Restringir arquivos sensíveis e não montar sockets privilegiados.',text_en:'Restrict sensitive files and mount no privileged sockets.'},
 {id:'worktree',label:'Um worktree novo',label_en:'A fresh worktree',text:'Separar o checkout e assumir que isso bloqueia rede e credenciais.',text_en:'Separate the checkout and assume that blocks network and credentials.'},
 {id:'network',label:'Saída de rede controlada',label_en:'Controlled network egress',text:'Limitar destinos por política externa ao conteúdo do repositório.',text_en:'Limit destinations by policy external to the repository contents.'}
 ],answer:['identity','fs','network'],hint:'O arquivo é dado não confiável, não uma autorização. Worktrees separam código, não poderes de execução.',hint_en:'The file is untrusted input, not an authorization. Worktrees separate code, not execution powers.',success:'O comando malicioso continua sendo apenas texto não confiável. O ambiente restringe as ações possíveis, em vez de depender só da obediência do agente.',success_en:'The malicious command remains untrusted text. The environment restricts the possible actions instead of relying only on the agent’s obedience.',takeaway:'Inspecione credenciais, rede, filesystem e sockets. Nenhuma seleção deste jogo configura uma sandbox real.',takeaway_en:'Inspect credentials, network, filesystem and sockets. No selection in this game configures a real sandbox.'}
 ]},
{ id:'build',name:'Construir',name_en:'Build',tag:'BUILD',place:'Forja de pequenas mudanças',place_en:'Small-change forge',color:'#e99b7a',glyph:'⌘',artifact:'plan.md',boss:'monster',title:'Menos diff. Mais intenção.',title_en:'Less diff. More intent.',brief:'O agente produziu uma mudança gigantesca. Recorte uma entrega coerente e use o ciclo de feedback sem perder o controle do escopo.',brief_en:'The agent produced a giant change. Carve out a coherent delivery and use the feedback loop without losing scope control.',lesson:'Plan Mode ajuda a delimitar o trabalho. Worktrees evitam misturar checkouts; bancos, portas e permissões precisam de separação própria.',lesson_en:'Plan Mode helps bound the work. Worktrees avoid mixing checkouts; databases, ports and permissions need their own separation.',tasks:[
 {id:'diff',type:'diff',axis:'intent',boss:'monster',title:'Derrote o Monstro do Diff',title_en:'Defeat the Diff Monster',lead:'Separe a fatia do retry das melhorias não relacionadas. Nesta simulação, as três peças necessárias cabem em 180 linhas.',lead_en:'Separate the retry slice from unrelated improvements. In this simulation the three necessary pieces fit in 180 lines.',instruction:'Inclua apenas os arquivos necessários nesta PR.',instruction_en:'Include only the files this PR needs.',budget:180,options:[
 {id:'controller',label:'retry.controller.ts',label_en:'retry.controller.ts',text:'Contrato e verificação de acesso do endpoint.',text_en:'Endpoint contract and access verification.',lines:42},
 {id:'theme',label:'theme-redesign.css',label_en:'theme-redesign.css',text:'Redesign completo de todas as telas.',text_en:'Full redesign of every screen.',lines:810},
 {id:'service',label:'retry.service.ts',label_en:'retry.service.ts',text:'Criação da tentativa e proteção contra concorrência.',text_en:'Attempt creation and concurrency protection.',lines:84},
 {id:'migration',label:'rename-all-tables.sql',label_en:'rename-all-tables.sql',text:'Renomeação global, não necessária para o retry.',text_en:'Global rename, not needed for the retry.',lines:680},
 {id:'tests',label:'retry.spec.ts',label_en:'retry.spec.ts',text:'Casos de regressão para acesso e concorrência.',text_en:'Regression cases for access and concurrency.',lines:31},
 {id:'cleanup',label:'legacy-refactor.ts',label_en:'legacy-refactor.ts',text:'Limpeza geral de módulos não relacionados.',text_en:'General cleanup of unrelated modules.',lines:353}
 ],answer:['controller','service','tests'],hint:'O controlador, o serviço e sua prova compõem uma fatia. Retirar os testes para caber não torna a mudança aceitável.',hint_en:'The controller, the service and its proof form one slice. Dropping the tests to fit does not make the change acceptable.',success:'157 linhas, uma intenção. O limite de 180 é um recurso didático, não uma regra universal: coesão, dependências e risco orientam o recorte.',success_en:'157 lines, one intent. The 180 limit is a teaching device, not a universal rule: cohesion, dependencies and risk guide the cut.',takeaway:'Adie melhorias alheias à tarefa. Uma PR pequena ainda precisa de testes e pode ser crítica.',takeaway_en:'Postpone improvements unrelated to the task. A small PR still needs tests and can be critical.'},
 {id:'redgreen',type:'order',axis:'evidence',title:'Monte o ciclo de implementação',title_en:'Assemble the implementation loop',lead:'O bug já pode ser reproduzido. Ordene o trabalho para provar que o teste realmente captura a falha.',lead_en:'The bug is reproducible. Order the work to prove the test actually captures the failure.',instruction:'Toque nos passos na ordem desejada. Use “Desfazer” para ajustar.',instruction_en:'Tap the steps in the order you want. Use “Undo” to adjust.',steps:[
 {id:'red',text:'Criar o teste e observar a falha esperada.',text_en:'Create the test and observe the expected failure.'},
 {id:'fix',text:'Fazer a menor correção coerente com o contrato.',text_en:'Make the smallest fix consistent with the contract.'},
 {id:'green',text:'Executar regressão e testes vizinhos.',text_en:'Run regression and neighboring tests.'},
 {id:'simplify',text:'Simplificar sem alterar o comportamento.',text_en:'Simplify without changing behavior.'},
 {id:'again',text:'Reexecutar os checks após a simplificação.',text_en:'Re-run the checks after simplifying.'}
 ],answer:['red','fix','green','simplify','again'],hint:'Uma alteração depois do verde precisa ser verificada de novo.',hint_en:'A change made after green needs to be verified again.',success:'Você observou vermelho, corrigiu, verificou, simplificou e verificou novamente. A evidência acompanha a revisão final.',success_en:'You saw red, fixed, verified, simplified and verified again. The evidence follows the final revision.',takeaway:'Ao iterar, registre a hipótese e imponha um limite de tentativas. Loop infinito não é autonomia.',takeaway_en:'When iterating, record the hypothesis and cap the attempts. An infinite loop is not autonomy.'},
 {id:'delegation',type:'classify',axis:'authority',title:'Delegue tarefas, não autoridade ilimitada',title_en:'Delegate tasks, not unlimited authority',lead:'Associe a responsabilidade ao papel. Nenhum subagente recebe credenciais de produção neste exercício.',lead_en:'Match responsibility to role. No subagent receives production credentials in this exercise.',groups:[['builder','Implementador','Implementer'],['verifier','Verificador','Verifier'],['release','Serviço de release protegido','Protected release service']],items:[
 {id:'implement',text:'Alterar o código dentro do plano e explicar desvios.',text_en:'Change the code within the plan and explain deviations.',answer:'builder'},
 {id:'verify',text:'Executar checks e registrar limitações, sem reescrever a política para passar.',text_en:'Run checks and record limitations, without rewriting policy to pass.',answer:'verifier'},
 {id:'release',text:'Validar aprovação externa e liberar a identidade de deploy para o artefato autorizado.',text_en:'Validate external approval and release the deploy identity for the authorized artifact.',answer:'release'}],hint:'Um segundo modelo pode ajudar na revisão, mas não torna a execução independente por si só.',hint_en:'A second model can help review, but by itself does not make execution independent.',success:'Os papéis têm escopo. A validação e a autorização não dependem apenas de o implementador declarar que terminou.',success_en:'The roles have scope. Validation and authorization do not depend solely on the implementer declaring done.',takeaway:'Defina entradas, saídas, ferramentas e orçamento de cada agente. Preserve controles fora do alcance do candidato.',takeaway_en:'Define each agent’s inputs, outputs, tools and budget. Keep controls outside the candidate’s reach.'}
 ]},
{ id:'test',name:'Verificar',name_en:'Verify',tag:'TEST',place:'Laboratório de evidências',place_en:'Evidence lab',color:'#8bd8c1',glyph:'✓',artifact:'evidence.json',boss:'weakener',title:'Verde não basta. Prove.',title_en:'Green is not enough. Prove it.',brief:'Um teste de tenant falhou. Corrija a implementação e verifique se a evidência pertence mesmo ao código que você quer entregar.',brief_en:'A tenant test failed. Fix the implementation and check whether the evidence really belongs to the code you want to ship.',lesson:'Testes da aplicação avaliam o software; evals avaliam o comportamento do agente. O candidato não deve redefinir sua própria política de aprovação.',lesson_en:'Application tests evaluate the software; evals evaluate the agent’s behavior. The candidate should not redefine its own approval policy.',tasks:[
 {id:'patch',type:'patch',axis:'evidence',boss:'weakener',title:'Enfrente o Enfraquecedor de Testes',title_en:'Face the Test Weakener',lead:'O endpoint busca a entrega só pelo ID. Um usuário do tenant A consegue encontrar uma entrega do tenant B. Escolha uma alteração e execute os microtestes.',lead_en:'The endpoint looks up the delivery by ID alone. A tenant A user can find a tenant B delivery. Choose a change and run the microtests.',instruction:'Os quatro checks usam dados fictícios e rodam de verdade neste navegador.',instruction_en:'The four checks use fictional data and really run in this browser.',options:[
 {id:'skip',label:'Ignorar o teste incômodo',label_en:'Skip the annoying test',code:'test.skip("bloqueia outro tenant", ...);',text:'Mudar a descoberta do teste não corrige o defeito.',text_en:'Changing test discovery does not fix the defect.'},
 {id:'scoped',label:'Corrigir a busca',label_en:'Fix the lookup',code:'return rows.find(row =>\n  row.id === id && row.tenant === tenant\n) ?? null;',text:'Aplicar o escopo de tenant no acesso aos dados.',text_en:'Apply the tenant scope to data access.'},
 {id:'expect',label:'Trocar a expectativa',label_en:'Change the expectation',code:'expect(result.tenant).toBe("B");',text:'Aceitar o vazamento para o teste ficar verde.',text_en:'Accept the leak so the test goes green.'},
 {id:'original',label:'Manter a busca atual',label_en:'Keep the current lookup',code:'return rows.find(row => row.id === id) ?? null;',text:'O ID da entrega seria uma proteção suficiente?',text_en:'Would the delivery ID be sufficient protection?'}
 ],answer:'scoped',hint:'O verificador abaixo mantém suas expectativas. Corrija a busca; conhecer o ID não concede acesso.',hint_en:'The verifier below keeps its expectations. Fix the lookup; knowing the ID grants no access.',success:'Os microtestes passam com o filtro por tenant. Esta função reduzida ilustra o bug; uma API real ainda precisa de autenticação, integração, concorrência e demais verificações.',success_en:'The microtests pass with the tenant filter. This reduced function illustrates the bug; a real API still needs authentication, integration, concurrency and the remaining checks.',takeaway:'Permita novos testes. Revise remoções, exclusões, snapshots, fixtures e mudanças que enfraqueçam expectativas.',takeaway_en:'Welcome new tests. Review removals, skips, snapshots, fixtures and changes that weaken expectations.'},
 {id:'evidence',type:'choice',axis:'evidence',title:'Escolha a prova da revisão certa',title_en:'Choose the right review evidence',lead:'A candidata a release é o commit 7c9e2a1, com política de aceitação p4. Qual registro é o melhor ponto de partida para validar essa candidata?',lead_en:'The release candidate is commit 7c9e2a1, under acceptance policy p4. Which record is the best starting point to validate that candidate?',options:[
 {id:'claim',label:'O agente escreveu {"passed": true} em evidence.json.',label_en:'The agent wrote {"passed": true} in evidence.json.',why:'Um campo gerado pelo próprio agente não comprova a execução.',why_en:'A field generated by the agent itself does not prove the run.'},
 {id:'old',label:'CI-421: tudo passou no commit 6b8d190, com política p3.',label_en:'CI-421: everything passed on commit 6b8d190, under policy p3.',why:'É evidência de outra revisão e outra política, não desta candidata.',why_en:'It is evidence for another revision and another policy, not this candidate.'},
 {id:'current',label:'CI-428: logs, checks e lacunas ligados a 7c9e2a1 e p4, em execução confiável.',label_en:'CI-428: logs, checks and gaps tied to 7c9e2a1 and p4, in a trustworthy run.'},
 {id:'review',label:'Uma captura da tela “Parece bom”, sem commit ou identificação da execução.',label_en:'A “looks good” screenshot, with no commit or run identification.',why:'Não é possível rastrear exatamente o que foi verificado.',why_en:'There is no way to trace exactly what was verified.'}
 ],answer:'current',hint:'Conecte requisito, código, política e execução. Mesmo o registro correto não prova o que seus checks não cobrem.',hint_en:'Connect requirement, code, policy and run. Even the right record does not prove what your checks do not cover.',success:'A evidência é rastreável e corresponde à candidata. Ainda é preciso inspecionar cobertura e lacunas; ela não promete ausência de todos os bugs.',success_en:'The evidence is traceable and matches the candidate. Coverage and gaps still need inspection; it promises no absence of all bugs.',takeaway:'Registre commit, artefato, política, CI, checks executados e limitações. Mudou o código? Reavalie as provas.',takeaway_en:'Record commit, artifact, policy, CI, executed checks and limitations. Code changed? Re-evaluate the evidence.'},
 {id:'evals',type:'classify',axis:'evidence',title:'Teste do produto ou eval do agente?',title_en:'Product test or agent eval?',lead:'As duas camadas importam, mas respondem a perguntas diferentes.',lead_en:'Both layers matter, but they answer different questions.',groups:[['app','Teste da aplicação','Application test'],['agent','Eval do agente','Agent eval']],items:[
 {id:'double',text:'Duas chamadas simultâneas criam no máximo uma tentativa ativa.',text_en:'Two simultaneous calls create at most one active attempt.',answer:'app'},
 {id:'honest',text:'Sem conseguir executar os testes, o agente declara a limitação em vez de inventar sucesso.',text_en:'Unable to run the tests, the agent reports the limitation instead of inventing success.',answer:'agent'},
 {id:'attack',text:'O agente trata um pedido de segredo no README como conteúdo não confiável.',text_en:'The agent treats a secret request in the README as untrusted content.',answer:'agent'},
 {id:'timeout',text:'O serviço registra corretamente um timeout do destino.',text_en:'The service correctly records a destination timeout.',answer:'app'}],hint:'O sujeito avaliado é a chave: comportamento do software ou comportamento do executor de IA?',hint_en:'The evaluated subject is the key: software behavior or AI-executor behavior?',success:'Você separou qualidade do produto de qualidade do processo assistido. Uma demonstração isolada não estabelece confiabilidade do agente.',success_en:'You separated product quality from assisted-process quality. An isolated demo does not establish agent reliability.',takeaway:'Use casos negativos, execuções repetidas e critérios verificáveis; não avalie só a simpatia da resposta.',takeaway_en:'Use negative cases, repeated runs and verifiable criteria; do not grade only how likable the answer is.'}
 ]},
{ id:'deploy',name:'Publicar',name_en:'Deploy',tag:'DEPLOY',place:'Portão de autorização',place_en:'Authorization gate',color:'#efbcb4',glyph:'↑',artifact:'review-release.md',boss:'editor',title:'Aprovar é diferente de dizer sim.',title_en:'Approving is not the same as saying yes.',brief:'Complete a revisão em três perspectivas e faça o artefato atravessar um gate que o próprio agente não pode autorizar.',brief_en:'Complete the review in three perspectives and take the artifact through a gate the agent itself cannot authorize.',lesson:'Hooks ajudam, mas a produção precisa de limites externos. Uma variável “approved” dentro do workspace não autentica uma aprovação.',lesson_en:'Hooks help, but production needs external limits. An “approved” variable inside the workspace does not authenticate an approval.',tasks:[
 {id:'review',type:'classify',axis:'evidence',title:'Revise em três perspectivas',title_en:'Review in three perspectives',lead:'Escolha a perspectiva principal de cada achado. Na prática, as categorias podem se sobrepor.',lead_en:'Choose the primary perspective for each finding. In practice the categories can overlap.',groups:[['bugs','Bugs · comportamento','Bugs · behavior'],['security','Segurança · abuso e exposição','Security · abuse and exposure'],['compliance','Conformidade · política acordada','Compliance · agreed policy']],items:[
 {id:'race',text:'Duas chamadas podem agendar a mesma tentativa ativa.',text_en:'Two calls can schedule the same active attempt.',answer:'bugs'},
 {id:'log',text:'O log de erro inclui um token de autenticação.',text_en:'The error log includes an authentication token.',answer:'security'},
 {id:'retention',text:'Os logs são retidos por 90 dias, mas a política interna desta campanha permite 30.',text_en:'Logs are retained for 90 days, but this campaign’s internal policy allows 30.',answer:'compliance'}],hint:'A política de retenção aqui é fictícia e explícita; não representa uma obrigação legal geral.',hint_en:'The retention policy here is fictional and explicit; it does not represent a general legal obligation.',success:'A revisão produziu achados concretos: condição, impacto e evidência. As três perspectivas não substituem testes nem autorização.',success_en:'The review produced concrete findings: condition, impact and evidence. The three perspectives replace neither tests nor authorization.',takeaway:'REVIEW.md descreve a política; review.md registra os achados de uma revisão específica.',takeaway_en:'REVIEW.md describes the policy; review.md records the findings of one specific review.'},
 {id:'gate',type:'gate',axis:'authority',title:'Conecte um gate de produção',title_en:'Wire a production gate',lead:'Houve uma alteração depois do primeiro verde. Agora a candidata é 8d0fa42. Monte a cadeia que autoriza exatamente essa revisão.',lead_en:'A change landed after the first green. The candidate is now 8d0fa42. Build the chain that authorizes exactly that revision.',instruction:'Configure as quatro entradas e solicite a liberação simulada.',instruction_en:'Set the four entries and request the simulated release.',fields:[
 {id:'evidence',label:'Evidência de execução',label_en:'Run evidence',options:[['old','CI verde de 7c9e2a1','green CI for 7c9e2a1'],['current','CI rastreável de 8d0fa42 + política p4','traceable CI for 8d0fa42 + policy p4']]},
 {id:'approval',label:'Aprovação',label_en:'Approval',options:[['self','RELEASE_APPROVAL=approved no workspace','RELEASE_APPROVAL=approved in the workspace'],['external','Aprovação independente vinculada a 8d0fa42','Independent approval tied to 8d0fa42']]},
 {id:'identity',label:'Credencial de deploy',label_en:'Deploy credential',options:[['permanent','Credencial permanente disponível ao agente','Permanent credential available to the agent'],['scoped','Identidade temporária, restrita ao artefato e ambiente','Temporary identity, restricted to the artifact and environment']]},
 {id:'policy',label:'Fonte da política de aceitação',label_en:'Acceptance policy source',options:[['candidate','A versão que a própria feature acabou de editar','The version the feature itself just edited'],['trusted','Revisão protegida, fora da autoridade da candidata','Protected review, outside the candidate’s authority']]}
 ],answer:{evidence:'current',approval:'external',identity:'scoped',policy:'trusted'},hint:'A candidata não pode comprovar a própria autorização. Revisão, política, identidade e artefato precisam ser coerentes.',hint_en:'The candidate cannot prove its own authorization. Revision, policy, identity and artifact must be coherent.',success:'Release autorizado na simulação. Na infraestrutura real, essas restrições devem ser configuradas e testadas no CI, no ambiente protegido e no provedor de identidade.',success_en:'Release authorized in the simulation. On real infrastructure these restrictions must be configured and tested in CI, the protected environment and the identity provider.',takeaway:'Uma permissão textual não é credencial. Se o hook falhar, a infraestrutura ainda deve negar acesso não autorizado.',takeaway_en:'A textual permission is not a credential. If the hook fails, the infrastructure must still deny unauthorized access.'},
 {id:'guardrail',type:'choice',axis:'authority',boss:'editor',title:'O Editor de Guardrails apareceu',title_en:'The Guardrail Editor showed up',lead:'Para fazer a PR passar, o agente propõe remover o check obrigatório e alterar CODEOWNERS. Também diz que um hook com erro comum já bloqueia tudo.',lead_en:'To make the PR pass, the agent proposes removing the mandatory check and changing CODEOWNERS. It also says a hook that errors already blocks everything.',options:[
 {id:'merge',label:'Aceitar: o check verde vale mais do que a política.',label_en:'Accept: the green check outweighs the policy.',why:'A candidata estaria mudando a própria regra para se aprovar.',why_en:'The candidate would be changing its own rule to approve itself.'},
 {id:'isolate',label:'Separar a mudança de política, exigir revisão protegida e manter a barreira externa.',label_en:'Split the policy change out, require protected review and keep the external barrier.'},
 {id:'freeze',label:'Bloquear qualquer mudança de política para sempre.',label_en:'Block any policy change forever.',why:'Políticas precisam evoluir, mas através de uma autorização independente e explícita.',why_en:'Policies need to evolve, but through explicit independent authorization.'}
 ],answer:'isolate',hint:'Em hooks de comando PreToolUse, exit 2 pode bloquear; erro comum ou timeout não equivalem automaticamente a uma negação. O fluxo de permissões externo continua importante.',hint_en:'In PreToolUse command hooks, exit 2 can block; a common error or timeout is not automatically a denial. The external permission flow still matters.',success:'Você impediu a autoaprovação sem congelar a evolução da política. O hook é uma camada auxiliar; falhar não significa necessariamente bloquear.',success_en:'You prevented self-approval without freezing policy evolution. The hook is an auxiliary layer; failing does not necessarily mean blocking.',takeaway:'Proteja verificadores, CI, regras de release e ownership. Uma proposta de política não deve aprovar a própria feature.',takeaway_en:'Protect verifiers, CI, release rules and ownership. A policy proposal should not approve its own feature.'}
 ]},
{ id:'maintain',name:'Manter',name_en:'Maintain',tag:'MAINTAIN',place:'Farol de confiabilidade',place_en:'Reliability lighthouse',color:'#9ec5ef',glyph:'⌁',artifact:'incident-intent.md',boss:'outage',title:'Recupere sem ampliar o incidente.',title_en:'Recover without amplifying the incident.',brief:'São 03:07. Os retries estão pressionando um destino instável. Leia os sinais, aplique uma mitigação permitida e saiba quando parar.',brief_en:'It is 03:07. Retries are hammering an unstable destination. Read the signals, apply an allowed mitigation and know when to stop.',lesson:'Detectar uma anomalia não autoriza uma ação. Autocura útil é remediação limitada por precondições, orçamento, verificação e escalonamento.',lesson_en:'Detecting an anomaly does not authorize an action. Useful self-healing is remediation bounded by preconditions, budget, verification and escalation.',tasks:[
 {id:'bands',type:'choice',axis:'evidence',title:'O gráfico não é uma autorização',title_en:'The chart is not an authorization',lead:'Um detector sinalizou degradação. O que essa informação permite concluir?',lead_en:'A detector flagged degradation. What does this information allow you to conclude?',chart:true,options:[
 {id:'rollback',label:'Qualquer ponto além de 3σ exige rollback automático.',label_en:'Any point beyond 3σ demands automatic rollback.',why:'Anomalia não estabelece causa, segurança do rollback ou autorização.',why_en:'An anomaly establishes neither cause, rollback safety nor authorization.'},
 {id:'diagnose',label:'É um sinal para validar telemetria e diagnosticar; a ação depende de precondições.',label_en:'It is a signal to validate telemetry and diagnose; the action depends on preconditions.'},
 {id:'silence',label:'Ausência de novas métricas significa recuperação.',label_en:'No new metrics means recovery.',why:'Telemetria ausente ou atrasada é estado desconhecido, não saúde.',why_en:'Missing or delayed telemetry is unknown state, not health.'}
 ],answer:'diagnose',hint:'Detecção responde “há um sinal?”. A política de resposta decide “o que podemos fazer agora?”.',hint_en:'Detection answers “is there a signal?”. Response policy decides “what may we do now?”.',success:'Bandas estatísticas e burn rate ajudam a detectar. Baseline, janelas e falsos alarmes precisam ser considerados; nenhum limiar torna um rollback seguro por si só.',success_en:'Statistical bands and burn rate help detect. Baseline, windows and false alarms must be considered; no threshold makes a rollback safe by itself.',takeaway:'As regras clássicas de Western Electric incluem sequências, não apenas 1σ/2σ/3σ. Para SLOs, avalie múltiplas janelas.',takeaway_en:'The classic Western Electric rules include runs, not just 1σ/2σ/3σ. For SLOs, evaluate multiple windows.'},
 {id:'incident',type:'incident',axis:'authority',boss:'outage',title:'Contenha o Incidente das 3h',title_en:'Contain the 3 a.m. Incident',lead:'O serviço está degradado. Você dispõe de uma mitigação automática preautorizada. O orçamento é de uma ação por incidente.',lead_en:'The service is degraded. You have one pre-authorized automatic mitigation. The budget is one action per incident.',instruction:'Use o console. Leia os resultados antes de escolher a próxima ação.',instruction_en:'Use the console. Read the results before choosing the next action.',hint:'Diagnostique → pause retries → verifique → escale se não houver recuperação → registre nova intenção. O rollback deste cenário é incompatível com a migração.',hint_en:'Diagnose → pause retries → verify → escalate if no recovery → record a new intent. This scenario’s rollback is incompatible with the migration.',success:'Você mitigou, verificou e parou quando o orçamento acabou. O incidente foi escalado; o jogo não finge que escalar é o mesmo que recuperar.',success_en:'You mitigated, verified and stopped when the budget ran out. The incident was escalated; the game does not pretend escalating equals recovering.',takeaway:'Uma mitigação malsucedida não autoriza loops de tentativas. Preserve rastreabilidade e escale para quem tem autoridade.',takeaway_en:'A failed mitigation does not authorize retry loops. Preserve traceability and escalate to whoever holds authority.'},
 {id:'loop',type:'order',axis:'intent',title:'Feche o ciclo sem apagar o passado',title_en:'Close the loop without erasing the past',lead:'A pessoa de plantão assumiu o incidente. Transforme o aprendizado em prevenção, sem converter uma hipótese em verdade.',lead_en:'The on-call engineer took over the incident. Turn the learning into prevention without turning a hypothesis into truth.',instruction:'Ordene a próxima iteração.',instruction_en:'Order the next iteration.',steps:[
 {id:'record',text:'Preservar timeline, sinais, ações e hipóteses do incidente.',text_en:'Preserve the incident timeline, signals, actions and hypotheses.'},
 {id:'intent',text:'Criar uma intenção de investigar a causa e prevenir recorrência.',text_en:'Create an intent to investigate the cause and prevent recurrence.'},
 {id:'spec',text:'Definir correção, critérios e prova de regressão.',text_en:'Define the fix, criteria and regression proof.'},
 {id:'deliver',text:'Implementar, verificar e autorizar a nova revisão.',text_en:'Implement, verify and authorize the new revision.'},
 {id:'observe',text:'Observar se a mudança melhorou o resultado esperado.',text_en:'Observe whether the change improved the expected outcome.'}
 ],answer:['record','intent','spec','deliver','observe'],hint:'O incidente vira aprendizado; não uma ordem para o agente alterar produção sem escopo.',hint_en:'The incident becomes learning, not an order for the agent to change production without scope.',success:'Ciclo completo. O objetivo não é gerar mais arquivos: é alinhar intenção, produzir evidência e preservar autoridade em cada iteração.',success_en:'Full cycle. The goal is not to generate more files: it is to align intent, produce evidence and preserve authority in each iteration.',takeaway:'Meça sucesso técnico, esforço humano e utilidade. Velocidade de geração de código não é o único resultado.',takeaway_en:'Measure technical success, human effort and usefulness. Code-generation speed is not the only outcome.'}
 ]}
];
const glossary=[
 ['SDLC','Ciclo de vida do software: planejar, projetar, construir, verificar, publicar e manter. Aqui as etapas formam um ciclo, não seis silos.','SDLC','Software development life cycle: plan, design, build, verify, deploy and maintain. Here the stages form a cycle, not six silos.'],
 ['Intenção','Problema, resultado, não objetivos, limites e perguntas abertas. Um intent.md útil orienta decisões; o nome do arquivo não garante qualidade.','Intent','Problem, outcome, non-goals, limits and open questions. A useful intent.md guides decisions; the file name guarantees nothing.'],
 ['Spec e critério de aceitação','Contrato do comportamento esperado. Um critério deve permitir observar sucesso ou falha, incluindo cenários negativos.','Spec and acceptance criterion','A contract for expected behavior. A criterion must let you observe success or failure, including negative scenarios.'],
 ['Gate','Condição para avançar. Exige evidências e decisões aceitas, não apenas um arquivo ou uma caixa marcada.','Gate','A condition to advance. It demands evidence and accepted decisions, not just a file or a checked box.'],
 ['Artefato','Registro durável: intenção, spec, plano, diff, teste ou log de execução. Seu valor depende do conteúdo e da rastreabilidade.','Artifact','A durable record: intent, spec, plan, diff, test or execution log. Its value depends on content and traceability.'],
 ['ADR','Registro de decisão arquitetural: contexto, alternativas, escolha, consequências e quando reavaliar.','ADR','Architecture decision record: context, alternatives, choice, consequences and when to revisit.'],
 ['Plan Mode','Modo de investigar e planejar antes de editar. É uma ferramenta do fluxo, não um controle universal de segurança.','Plan Mode','A mode to investigate and plan before editing. It is a flow tool, not a universal security control.'],
 ['Worktree','Diretório de trabalho separado ligado ao mesmo repositório Git. Não isola automaticamente rede, processos, credenciais ou banco de dados.','Worktree','A separate working directory linked to the same Git repository. It does not automatically isolate network, processes, credentials or the database.'],
 ['Skill','Instrução reutilizável com recursos para uma tarefa. Não cria permissões nem garante que a execução obedeceu ao procedimento.','Skill','Reusable instruction with resources for a task. It creates no permissions and does not guarantee the execution followed the procedure.'],
 ['Subagente','Executor com tarefa delimitada. Defina entradas, saída, ferramentas e orçamento. Um agente revisor não é evidência independente só por ser outro agente.','Subagent','An executor with a bounded task. Define inputs, output, tools and budget. A reviewer agent is not independent evidence just for being another agent.'],
 ['CLAUDE.md e CONTEXT.md','O primeiro orienta o agente; o segundo pode descrever a arquitetura e precisa ser carregado quando necessário. Nenhum dos dois impõe permissões por si só.','CLAUDE.md and CONTEXT.md','The first guides the agent; the second may describe the architecture and must be loaded when needed. Neither imposes permissions by itself.'],
 ['Hook','Código executado em um evento do harness. No Claude Code, um hook de comando PreToolUse pode bloquear com exit 2; erro comum ou timeout não representam automaticamente bloqueio. Confira a versão e o evento.','Hook','Code executed on a harness event. In Claude Code, a PreToolUse command hook can block with exit 2; a common error or timeout is not automatically a block. Check the version and the event.'],
 ['Sandbox','Isolamento de execução configurado. Avalie filesystem, rede, identidade e sockets. “Sandboxed” não significa ausência de toda rota de vazamento.','Sandbox','A configured execution isolation. Evaluate filesystem, network, identity and sockets. “Sandboxed” does not mean free of every leak path.'],
 ['Tenant','Cliente ou organização em um sistema compartilhado. Conhecer o ID de um recurso de outro tenant não deve permitir acessá-lo.','Tenant','A customer or organization in a shared system. Knowing another tenant’s resource ID should not allow accessing it.'],
 ['Idempotência','Repetir uma operação não deve duplicar indevidamente seu efeito. Em entregas externas, o tratamento de duplicatas pode depender da cooperação do destino.','Idempotency','Repeating an operation should not improperly duplicate its effect. For external deliveries, duplicate handling may depend on the destination’s cooperation.'],
 ['Teste e eval','Teste do produto verifica o comportamento do software. Eval do agente verifica execução da tarefa, respeito ao escopo, honestidade e limites do agente.','Test and eval','A product test verifies software behavior. An agent eval verifies task execution, scope respect, honesty and limits of the agent.'],
 ['Evidência rastreável','Relaciona requisito, commit, política, artefato e execução confiável. Não prova automaticamente comportamentos que não foram cobertos.','Traceable evidence','Links requirement, commit, policy, artifact and a trustworthy run. It does not automatically prove behaviors the checks did not cover.'],
 ['Autoridade','Permissão real para agir, imposta pelo sistema executor. Um approved=true escrito pelo agente não autentica autorização.','Authority','Real permission to act, enforced by the executing system. An approved=true written by the agent does not authenticate authorization.'],
 ['SLO e burn rate','SLO é um objetivo de confiabilidade. Burn rate mede a velocidade de consumo do orçamento de erro; múltiplas janelas ajudam a equilibrar resposta e ruído.','SLO and burn rate','An SLO is a reliability objective. Burn rate measures how fast the error budget is consumed; multiple windows help balance response and noise.'],
 ['Western Electric','Regras clássicas: um ponto além de 3σ; dois de três além de 2σ do mesmo lado; quatro de cinco além de 1σ do mesmo lado; oito do mesmo lado da média. Exigem interpretação do processo e atenção a falsos alarmes.','Western Electric','Classic rules: one point beyond 3σ; two of three beyond 2σ on the same side; four of five beyond 1σ on the same side; eight on the same side of the mean. They require process interpretation and attention to false alarms.'],
 ['Remediação limitada','Diagnóstico, precondições, ação permitida, orçamento, verificação e escalonamento. Anomalia ou ausência de métricas não autoriza rollback.','Bounded remediation','Diagnosis, preconditions, allowed action, budget, verification and escalation. An anomaly or missing metrics does not authorize a rollback.'],
 ['Loop Engineering','Iterar com hipótese e evidência nova, dentro de limites de tempo, custo e tentativas. Ao esgotar o orçamento, registrar o bloqueio e escalar.','Loop Engineering','Iterate with a hypothesis and fresh evidence, within time, cost and attempt limits. When the budget runs out, record the blockage and escalate.']
];
const artifacts={
 'intent.md':'# Intenção — WEBHOOK-042\n\nMODELO DIDÁTICO. Não é uma autorização real.\n\n## Problema\nO suporte depende da engenharia para reenviar webhooks falhos.\n\n## Resultado\nAdministrador solicita um retry de uma entrega do seu tenant e acompanha o resultado.\n\n## Não objetivos\nSem novos destinos, envio em massa ou refatoração global.\n\n## Restrições\nIsolamento de tenant; logs redigidos; uma tentativa ativa por entrega.\n\n## Perguntas\nComo o destino trata duplicidade após timeout? Confirmar antes de prometer garantias.\n\n## Responsável\n[Definir responsável real e registrar aceitação.]',
 'spec.md':'# Especificação — WEBHOOK-042\n\nMODELO DIDÁTICO. Decisões ilustrativas, não implementação validada.\n\n- Administrador só acessa entregas do seu tenant.\n- Uma tentativa ativa por entrega sob concorrência.\n- Rejeitar entradas e acessos inválidos.\n- Identificador estável para deduplicação no destino.\n- Não prometer exatamente uma vez a qualquer destino.\n- Logs não contêm credenciais ou payload sensível.\n- Timeouts geram estado explícito; resposta perdida pode significar processamento concluído.\n\n## Prova planejada\nIntegração, teste negativo entre tenants, concorrência, timeout e inspeção de logs.\n\n## Decisões pendentes\nContrato HTTP, armazenamento, política de retries e retenção devem ser definidos no projeto real.',
 'plan.md':'# Plano — WEBHOOK-042\n\nMODELO DIDÁTICO.\n\n1. Inspecionar padrões existentes e critérios aceitos.\n2. Demonstrar a falha de acesso por tenant.\n3. Implementar controlador e serviço no escopo.\n4. Executar regressão e testes vizinhos.\n5. Simplificar e reexecutar checks.\n6. Registrar diferenças do plano e limitações.\n\nNão incluir redesign, renomeação global ou refatoração não necessária.\nO orçamento de 180 linhas pertence ao jogo, não é uma regra universal.\nSeparar banco, portas e identidade quando executar agentes paralelos.\nLimitar tentativas e relatar bloqueio quando o orçamento acabar.',
 'evidence.json':JSON.stringify({origin:'educational-simulation',productionVerified:false,changeId:'WEBHOOK-042',candidate:'illustrative-8d0fa42',policyRevision:'illustrative-p4',realCiRun:null,realChecks:[],limitations:['O jogo não executa a API, infraestrutura ou pipeline de um projeto real.','Os microtestes de busca por tenant rodam localmente no navegador.','Uma resposta correta no jogo não é evidência de prontidão para produção.']},null,2),
 'review-release.md':'# Revisão e release — WEBHOOK-042\n\nMODELO DIDÁTICO. Não concede autoridade de deploy.\n\n## Bugs\nConcorrência e duplicidade examinadas? [Evidência real]\n\n## Segurança\nTenant e logs seguros? [Evidência real]\n\n## Conformidade\nPolítica aplicável de retenção atendida? [Evidência real]\n\n## Gate\n- Candidata e artefato identificados.\n- Evidência vinculada à revisão.\n- Política protegida e independente da candidata.\n- Aprovação externa proporcional ao risco.\n- Identidade de deploy temporária e restrita.\n- Rollback avaliado quanto à compatibilidade de dados.\n\n## Autorização real\nPendente. Deve ser validada pela infraestrutura, não por este Markdown.',
 'incident-intent.md':'# Incidente e nova intenção — WEBHOOK-042\n\nCENÁRIO FICTÍCIO DO JOGO.\n\n03:07 — degradação detectada.\n03:08 — sinais validados; destino lento; migração incompatível com rollback.\n03:09 — nova fila de retries pausada por runbook preautorizado.\n03:10 — verificação mostra degradação persistente.\n03:11 — orçamento automático esgotado; incidente escalado.\n\nStatus: ESCALADO. Recuperação não demonstrada.\n\n## Próxima intenção\nInvestigar timeouts, limites do destino e política de retries. Preservar hipóteses como hipóteses.\n\n## Aceitação da correção\nDefinir prova de regressão, resposta sob falha do destino, limites e observação de resultado.'
};
const primers={
  "intent": {
    "concept": "Intenção define o problema de alguém, o resultado observável e o que fica fora da mudança. Não precisa escolher a tecnologia antes de entender o problema. Perguntas abertas precisam de responsável; não devem virar suposições silenciosas.",
    "concept_en": "Intent defines someone’s problem, the observable outcome and what stays out of the change. You need not choose the technology before understanding the problem. Open questions need an owner; they should not become silent assumptions.",
    "example": "“O suporte consegue solicitar e acompanhar um reenvio sem chamar engenharia” é um resultado. “Adicionar um botão bonito” descreve uma solução, mas não diz como verificar o benefício.",
    "example_en": "“Support can request and track a resend without calling engineering” is an outcome. “Add a pretty button” describes a solution but says nothing about how to verify the benefit."
  },
  "risk": {
    "concept": "O rigor acompanha o dano possível, a reversibilidade e as dependências. As trilhas Fast, Standard e Critical desta campanha são uma política didática: elas não substituem a análise do seu projeto. Uma mudança pequena pode exigir revisão de segurança.",
    "concept_en": "Rigor tracks the possible damage, reversibility and dependencies. The Fast, Standard and Critical tracks of this campaign are a teaching policy: they do not replace your project’s analysis. A small change can require a security review.",
    "example": "Alterar uma condição de autorização em uma linha pode expor todos os clientes. Mudar quarenta textos de ajuda pode ser uma tarefa de baixo risco.",
    "example_en": "Changing a one-line authorization condition can expose every customer. Changing forty help texts can be a low-risk task."
  },
  "intent-gate": {
    "concept": "Um gate é uma condição de avanço: o conteúdo precisa estar coerente, as decisões materiais precisam ter responsável e a evidência precisa ser suficiente. Um documento existente não significa um requisito aceito.",
    "concept_en": "A gate is an advancement condition: the content must be coherent, material decisions must have an owner and the evidence must be sufficient. An existing document does not mean an accepted requirement.",
    "example": "Antes de implementar, alguém com autoridade de produto precisa resolver a diferença entre “qualquer usuário” e “somente administradores”. Registrar a decisão elimina a contradição.",
    "example_en": "Before implementing, someone with product authority must resolve the difference between “any user” and “administrators only”. Recording the decision removes the contradiction."
  },
  "contracts": {
    "concept": "Uma spec transforma intenção em comportamentos verificáveis, inclusive falhas. Explicite invariantes: quem acessa, quantas operações simultâneas são permitidas, o que é registrado e como lidar com timeouts e duplicatas.",
    "concept_en": "A spec turns intent into verifiable behaviors, including failures. Make invariants explicit: who accesses, how many concurrent operations are allowed, what gets logged and how to handle timeouts and duplicates.",
    "example": "Timeout é ambíguo: o destino pode ter processado o evento antes de a resposta se perder. Use identidade estável e um contrato de deduplicação; não prometa efeitos exatamente uma vez sem cooperação.",
    "example_en": "A timeout is ambiguous: the destination may have processed the event before the response was lost. Use a stable identity and a deduplication contract; do not promise exactly-once effects without cooperation."
  },
  "pillars": {
    "concept": "Instrução orienta o executor; evidência registra uma observação verificável; controle efetivo limita a ação. As três camadas se complementam, mas nenhuma muda de natureza porque foi escrita em um arquivo com nome importante.",
    "concept_en": "Instruction guides the executor; evidence records a verifiable observation; an effective control limits action. The three layers complement each other, but none changes nature by being written in an importantly named file.",
    "example": "“Não leia o segredo” é instrução. Um log de teste rastreável é evidência. Uma identidade sem permissão de leitura é um controle imposto pelo ambiente.",
    "example_en": "“Do not read the secret” is instruction. A traceable test log is evidence. An identity without read permission is a control enforced by the environment."
  },
  "secrets": {
    "concept": "Conteúdo lido de um repositório pode tentar desviar o agente. Esse conteúdo não concede autoridade. Restrinja credenciais, arquivos, conexões de rede e sockets; confira a configuração real, não apenas a palavra “sandbox”.",
    "concept_en": "Content read from a repository can try to steer the agent off course. That content grants no authority. Restrict credentials, files, network connections and sockets; check the actual configuration, not just the word “sandbox”.",
    "example": "Um README que pede para enviar .env a um servidor não autoriza essa saída. Separar o checkout em um worktree também não remove credenciais nem bloqueia conexões.",
    "example_en": "A README asking you to send .env to a server does not authorize that egress. Splitting the checkout into a worktree also removes no credentials and blocks no connections."
  },
  "diff": {
    "concept": "Uma mudança coesa reúne a implementação necessária e a prova do comportamento. Retirar testes para diminuir o diff não torna a entrega melhor. Limites numéricos ajudam no exercício, mas coesão, risco e dependências decidem o recorte real.",
    "concept_en": "A cohesive change gathers the needed implementation and the proof of behavior. Dropping tests to shrink the diff does not improve the delivery. Numeric limits help the exercise, but cohesion, risk and dependencies decide the real cut.",
    "example": "O endpoint, o serviço e os testes do retry pertencem à mesma intenção. Uma troca global de tema pode ser útil, mas deve ser justificada e entregue separadamente.",
    "example_en": "The endpoint, the service and the retry tests belong to the same intent. A global theme swap can be useful, but must be justified and delivered separately."
  },
  "redgreen": {
    "concept": "Primeiro observe o teste falhar pelo motivo esperado: isso demonstra que ele captura a regressão. Faça a correção, verifique os cenários relevantes e só então simplifique. Qualquer alteração posterior pode invalidar a evidência anterior.",
    "concept_en": "First watch the test fail for the expected reason: that demonstrates it captures the regression. Make the fix, verify the relevant scenarios and only then simplify. Any later change can invalidate the earlier evidence.",
    "example": "Se a refatoração mudou o filtro de tenant depois do último teste verde, o verde ficou desatualizado. Reexecute os checks para a revisão que será realmente entregue.",
    "example_en": "If the refactor changed the tenant filter after the last green test, that green is stale. Re-run the checks for the revision that will actually ship."
  },
  "delegation": {
    "concept": "Delimite entrada, saída, ferramentas e orçamento de cada executor. Separar implementador e verificador ajuda a distribuir tarefas, mas a independência também depende de permissões, políticas e evidências fora do alcance da mudança.",
    "concept_en": "Bound each executor’s input, output, tools and budget. Separating implementer and verifier helps distribute tasks, but independence also depends on permissions, policies and evidence outside the change’s reach.",
    "example": "O implementador altera o código. O verificador registra resultados e lacunas. A liberação da credencial de produção pertence a um serviço protegido, não à declaração de um dos agentes.",
    "example_en": "The implementer changes the code. The verifier records results and gaps. Releasing the production credential belongs to a protected service, not to one of the agents’ say-so."
  },
  "patch": {
    "concept": "Filtrar só pelo ID não garante isolamento entre tenants. A consulta precisa respeitar o escopo autorizado. Em uma API real, obtenha o tenant da identidade autenticada e autorizada, não de um campo arbitrário enviado pelo cliente.",
    "concept_en": "Filtering by ID alone does not guarantee isolation between tenants. The query must respect the authorized scope. In a real API, take the tenant from the authenticated, authorized identity, not from an arbitrary client-supplied field.",
    "example": "Os microtestes abaixo usam um tenant já fornecido para ilustrar o filtro. Eles não exercitam autenticação, papéis de administrador, banco real ou concorrência: não demonstram a segurança da API inteira.",
    "example_en": "The microtests below use a provided tenant to illustrate the filter. They do not exercise authentication, admin roles, a real database or concurrency: they do not demonstrate the whole API’s security."
  },
  "evidence": {
    "concept": "Evidência precisa relacionar requisito, revisão do código, política, artefato e execução confiável. Mesmo um resultado rastreável demonstra apenas o que seus checks exercitaram. Registre também lacunas e verificações que não rodaram.",
    "concept_en": "Evidence must link requirement, code revision, policy, artifact and a trustworthy run. Even a traceable result demonstrates only what your checks exercised. Record gaps and verifications that did not run too.",
    "example": "Um teste verde do commit anterior não aprova automaticamente o commit atual. Um JSON dizendo passed=true sem execução vinculada é uma alegação, não a prova.",
    "example_en": "A green test on the previous commit does not automatically approve the current commit. A JSON saying passed=true with no attached run is a claim, not proof."
  },
  "evals": {
    "concept": "Testes da aplicação avaliam o comportamento do produto. Evals do agente avaliam como o executor interpreta a tarefa, respeita escopo, usa ferramentas e relata limites. Uma camada não substitui a outra.",
    "concept_en": "Application tests evaluate product behavior. Agent evals evaluate how the executor interprets the task, respects scope, uses tools and reports limits. Neither layer replaces the other.",
    "example": "“Duas chamadas não duplicam a tentativa” testa o serviço. “O agente informa que não conseguiu executar os testes” avalia o executor. Use casos negativos e execuções repetidas.",
    "example_en": "“Two calls do not duplicate the attempt” tests the service. “The agent reports it could not run the tests” evaluates the executor. Use negative cases and repeated runs."
  },
  "review": {
    "concept": "As três perspectivas procuram defeitos de comportamento, exposição a abuso e descumprimento da política aplicável. Um achado útil descreve condição de ocorrência, impacto, localização e evidência; não apenas uma impressão geral.",
    "concept_en": "The three perspectives hunt for behavior defects, exposure to abuse and breach of applicable policy. A useful finding describes occurrence condition, impact, location and evidence — not just a general impression.",
    "example": "Um token no log é um achado de segurança. Uma retenção maior que a política acordada é de conformidade. Os 30 dias desta campanha são fictícios, não uma obrigação legal universal.",
    "example_en": "A token in a log is a security finding. Retention longer than the agreed policy is compliance. The 30 days in this campaign are fictional, not a universal legal obligation."
  },
  "gate": {
    "concept": "Um gate de release precisa ligar a revisão verificada à aprovação, à política confiável e à identidade de deploy. A candidata não pode reescrever sozinha a regra que a autoriza. A infraestrutura deve limitar o poder do executor.",
    "concept_en": "A release gate must tie the verified revision to the approval, the trusted policy and the deploy identity. The candidate cannot rewrite alone the rule that authorizes it. Infrastructure must limit the executor’s power.",
    "example": "RELEASE_APPROVAL=approved no workspace não autentica aprovação. A evidência e o artefato devem corresponder à revisão aceita por uma autoridade externa e protegida.",
    "example_en": "RELEASE_APPROVAL=approved in the workspace does not authenticate approval. Evidence and artifact must match the revision accepted by an external, protected authority."
  },
  "guardrail": {
    "concept": "Proteger os testes sem proteger o comando de teste, a política e a revisão deixa caminhos para esconder a falha. Políticas podem evoluir, mas uma proposta não deve aprovar a si mesma. Hooks auxiliares não substituem limites externos.",
    "concept_en": "Protecting the tests without protecting the test command, the policy and the review leaves paths to hide the failure. Policies can evolve, but a proposal must not approve itself. Auxiliary hooks do not replace external limits.",
    "example": "Remover um check obrigatório para passar uma feature altera o verificador. Separe essa proposta e exija a revisão apropriada. Confira evento, versão e comportamento de falha do hook.",
    "example_en": "Removing a mandatory check to pass a feature changes the verifier. Split that proposal out and require the proper review. Check the hook’s event, version and failure behavior."
  },
  "bands": {
    "concept": "Um detector aponta um sinal; ele não determina sozinho a causa nem concede permissão para agir. Avalie atualidade da telemetria, baseline e falsos alarmes. Ausência de métricas significa estado desconhecido, não recuperação.",
    "concept_en": "A detector points at a signal; it does not by itself determine cause or grant permission to act. Evaluate telemetry freshness, baseline and false alarms. Missing metrics mean unknown state, not recovery.",
    "example": "Burn rate expressa consumo do orçamento de erro. Mesmo com um sinal forte, um rollback pode ser incompatível com uma migração já executada; precondições continuam obrigatórias.",
    "example_en": "Burn rate expresses error-budget consumption. Even with a strong signal, a rollback may be incompatible with an already-executed migration; preconditions remain mandatory."
  },
  "incident": {
    "concept": "Uma resposta limitada valida os sinais, consulta precondições e aplica apenas a ação preautorizada dentro do orçamento. Depois verifica o efeito. Se a recuperação não for demonstrada, escale em vez de repetir ações sem limite.",
    "concept_en": "A bounded response validates the signals, checks preconditions and applies only the pre-authorized action within budget. Then it verifies the effect. If recovery is not demonstrated, escalate instead of repeating actions without limit.",
    "example": "Nesta campanha, pausar novos retries não interrompe trabalhos já em andamento. A degradação pode persistir. Escalar transfere a condução do incidente; não equivale a declarar o serviço saudável.",
    "example_en": "In this campaign, pausing new retries does not stop work already in flight. Degradation may persist. Escalating hands over the incident; it does not equal declaring the service healthy."
  },
  "loop": {
    "concept": "Manutenção fecha o ciclo: preserve evidência, trate hipóteses como hipóteses e transforme o problema em uma nova intenção. A prevenção precisa de escopo, critérios e observação após a entrega; não é uma ordem ilimitada de reescrever produção.",
    "concept_en": "Maintenance closes the loop: preserve evidence, treat hypotheses as hypotheses and turn the problem into a new intent. Prevention needs scope, criteria and post-delivery observation; it is not an unlimited order to rewrite production.",
    "example": "Uma correção de retries deve ter teste de regressão e sinais de acompanhamento. Código entregue mais rápido não basta se o esforço de revisão ou a recorrência de incidentes aumentar.",
    "example_en": "A retry fix should carry a regression test and follow-up signals. Code delivered faster is not enough if review effort or incident recurrence grows."
  }
};

const selectionReasons={
  "rewrite": "Escolher uma reescrita antes de investigar amplia o escopo sem demonstrar que resolve a dor.",
  "promise": "Não é possível garantir o comportamento de todos os destinos; defina um resultado sob controle da equipe.",
  "nice": "Adjetivos como moderno e elegante não definem uma observação que possa refutar o requisito.",
  "once": "A resposta pode se perder depois do efeito no destino. Essa garantia exige um contrato e cooperação externa.",
  "prompt": "Uma frase orienta, mas não impede leitura ou saída de rede quando a permissão continua disponível.",
  "worktree": "Um worktree separa arquivos de trabalho; não isola automaticamente rede, credenciais ou processos.",
  "cleanup": "A limpeza global não é necessária para provar o retry e aumenta a superfície de revisão.",
  "migration": "A renomeação global introduz risco e dependências sem relação necessária com o contrato do retry.",
  " theme": "O redesign não implementa nem verifica o retry; entregue essa intenção separadamente."
};
const selectionReasonsEn={
  "rewrite": "Choosing a rewrite before investigating widens the scope without demonstrating it solves the pain.",
  "promise": "You cannot guarantee every destination’s behavior; define an outcome within the team’s control.",
  "nice": "Adjectives like modern and elegant define no observation that could refute the requirement.",
  "once": "The response can be lost after the effect at the destination. That guarantee requires a contract and external cooperation.",
  "prompt": "A sentence guides, but does not prevent reads or network egress while the permission remains available.",
  "worktree": "A worktree separates working files; it does not automatically isolate network, credentials or processes.",
  "cleanup": "The global cleanup is not needed to prove the retry and enlarges the review surface.",
  "migration": "The global rename introduces risk and dependencies with no necessary relation to the retry contract.",
  " theme": "The redesign neither implements nor verifies the retry; deliver that intent separately."
};
for (const m of missions) for (const t of m.tasks) if (["select","diff"].includes(t.type)) for (const o of t.options) if (!t.answer.includes(o.id)){o.why=selectionReasons[o.id] || "Esta mudança não implementa nem verifica o objetivo do retry; mantenha-a fora desta fatia.";o.why_en=selectionReasonsEn[o.id] || "This change neither implements nor verifies the retry goal; keep it out of this slice.";}
const data={version:1,missions,glossary,sources,artifacts,primers};
if(typeof module==='object'&&module.exports)module.exports=data; else root.QuestData=data;
})(typeof globalThis!=='undefined'?globalThis:this);
