/* TLC lesson interface. Nothing here invokes an agent, a package manager or GitHub.
 * Chrome is bilingual via QuestLang; exported guides/artifacts stay pt-BR documents. */
(function(){
'use strict';
const D=QuestTLCData,C=QuestTLC,B=QuestBridge,QL=QuestLang,$=s=>document.querySelector(s);
const dialog=$('#tlc-dialog'),content=$('#tlc-content');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const STRINGS={
pt:{
 bannerLabel:'EXPANSÃO · TECH LEADS CLUB',bannerTitle:'Seu time de quatro especialistas.',bannerFlow:'Discover → Plan → Implement → Judge',bannerAria:(d,t)=>`${d} de ${t} desafios TLC concluídos`,bannerCount:'desafios TLC',bannerEnter:'Entrar na oficina',
 backAria:'Voltar à oficina TLC',backLabel:'← Oficina',closeAria:'Fechar oficina TLC',
 hubTitle:'Quatro especialistas. Uma entrega verificável.',hubKicker:'TLC AI DEV FLOW',hubLead:'A mesma feature de retry, agora com papéis, entradas e saídas explícitas. Estude em qualquer ordem; os desafios de cada especialista formam uma sequência.',meterChallenges:'desafios',meterXp:'XP TLC',meterSpecialists:'especialistas',kitLink:'Instalação, prompts e fontes ↗',agentAria:(skill,d)=>`${skill}, ${d} de 4 desafios concluídos`,agentRevisit:'Revisitar ✓',agentContinue:'Continuar →',agentStart:'Começar →',splitTitle:'18 + 16, sem perder o que você já fez.',splitBody:'A campanha original continua com seu XP e seus desbloqueios. A expansão tem progressão própria e entra no mesmo backup. Ao trocar o arquivo, importe o JSON da v1.1 em Configurações → Restaurar backup.',split2Title:'As skills não substituem a infraestrutura.',split2Body:'Deploy, monitoramento e autorização continuam nas estações originais. Este jogo ensina o uso das skills; não executa agentes reais.',harnessLink:'Coloque este fluxo à prova →',harnessLinkBody:'Abra o laboratório de execução: pré-condições, testes reais em memória e evidências invalidadas após alterações.',guideBtn:'Exportar meu guia TLC ↓',backupBtn:'Backup completo do jogo ↓',
 metaChallenge:(i)=>`Desafio ${i} de 4 · `,metaReview:'Revisão sem XP extra',metaXp:n=>`até ${n} XP TLC`,navAria:skill=>`Desafios de ${skill}`,taskAria:(i,title,done)=>`Desafio ${i}: ${title}${done?', concluído':''}`,doneCount:d=>`${d}/4 concluídos`,conceptSummary:'Entender o conceito ',conceptFree:'Grátis · sem desconto de XP',exampleLabel:'Exemplo',readSource:'Ler a skill original ↗',submitProof:'Executar provas',submitReview:'Preparar review simulada',submitChoice:'Verificar decisão',nextTask:'Próximo desafio →',nextArtifact:'Receber artefato →',moduleKitLink:'Ver entrada, saída e prompt ↗',disclaimer:'Cenário didático. Nenhum comando, agente, serviço externo ou ação de produção é executado.',
 optionsAria:'Escolhas do desafio',instrSelect:n=>`Selecione ${n} cartões.`,instrChoice:'Escolha uma decisão.',instrClassify:'Associe cada situação ao seu destino.',choose:'Escolha…',labLabel:'LABORATÓRIO EXECUTÁVEL · DADOS FICTÍCIOS',labGoal:'Objetivo: antes do patch <b>falha</b> → candidata <b>passa</b> → mutante que nega tudo <b>falha</b>.',labSuite:'1. Escolha o que testar',labSuiteEmpty:'Selecione a suíte…',labSuites:{happy:'Só acessos permitidos',placebo:'Só quantidade de fixtures',contract:'Contrato: acessos permitidos, cruzados e ID ausente'},labPatch:'2. Escolha a candidata',labPatchEmpty:'Selecione a implementação…',labPatches:{original:'Manter: busca somente pelo ID',denyAll:'Negar tudo: retornar null',scoped:'Corrigir: filtrar ID e tenant'},codeAria:'Código da implementação escolhida',labCaption:'As funções são predefinidas e usam fixtures locais. Não há eval nem execução de código digitado. O teste pré-patch aplica-se aqui a um bug conhecido, não a todo teste novo.',pickCandidate:'Escolha uma candidata para inspecionar a função.',diffAria:'Trecho fictício revisado',instrReview:'Selecione os achados para a revisão inline consolidada e escolha o veredito.',verdictLabel:'Veredito da review',reviewCaption:'Adaptador didático: este tribunal não executa o review_gate.py oficial, não publica review e não autoriza merge.',
 failed:'FALHOU',passed:'PASSOU',localStatus:s=>`status local ${s}`,expected:(e,a)=>`Esperado: ${e} · obtido: ${a}`,proofCaption:n=>`${n} asserções locais executadas nesta rodada. Status 0/1 é calculado no navegador; não é um processo de CI.`,
 fbOk:'Decisão verificada.',fbEmpty:'Falta uma escolha.',fbFail:'Ainda não. Vamos ajustar.',labProofBtn:'Baixar execução local ↓',findingsBtn:'Exportar findings didático ↓',
 rewardTitle:'Especialista concluído.',rewardText:xp=>`4 desafios · ${xp} XP TLC. O importante não é o título: é saber o que entra, o que sai e o que ainda precisa ser provado.`,artifactBtn:'Baixar exemplo didático ↓',useBtn:'Usar no meu projeto ↗',revisitBtn:'Revisitar desafios',nextSpecialist:'Próximo especialista →',backHub:'Voltar à oficina →',rewardDisclaimer:'Esta conquista é local e didática, não uma certificação ou auditoria independente.',
 kitTitle:'Leve o fluxo para seu projeto.',kitKicker:'INSTALAÇÃO + HANDOFF',kitLead:'A oficina ensina as decisões. A instalação das skills acontece no terminal do seu projeto, fora deste HTML.',installLabel:'COMANDO PUBLICADO PELO TECH LEADS CLUB',copyInstall:'Copiar comando',installNote:'O comando requer Node.js/npm e acesso à rede. Revise a origem e as opções apresentadas pelo instalador. Copiar não executa nem instala nada.',dlInput:'Quando entra',dlOutput:'O que entrega',dlStage:'No SDLC Quest',copyPrompt:'Copiar prompt',practice:'Praticar →',originalSkill:'Skill original ↗',notesTitle:'Fidelidade, limites e fontes',noteArtifacts:'<strong>Artefatos:</strong> .design, .tasks e .checks são os caminhos documentados. Os exemplos baixados aqui são fichas resumidas da campanha, não cópias completas dos templates oficiais.',noteVerify:'<strong>Verificação:</strong> a skill tlc-implement exige um verificador novo. Sem esse recurso, o resultado permanece sem verificação independente — não basta renomear o autor.',noteReview:'<strong>Review:</strong> the-judge produz APPROVE, COMMENT ou REQUEST_CHANGES, não uma nota de 0 a 10. Tem limite de três rodadas para o mesmo conjunto de achados. Uma review não é autorização de deploy.',noteScope:'<strong>Escopo:</strong> as quatro skills são o núcleo do fluxo consultado. Entrada, triagem e produção aparecem como futuras estações nessa página; as seis etapas completas continuam sendo ensinadas pela campanha original.',exportGuide:'Exportar guia com prompts ↓',backupAll:'Backup completo ↓',
 copied:'Texto copiado. Nenhum comando foi executado.',copyFallback:'Cópia automática indisponível. Copie o texto selecionado com Ctrl+C / ⌘C.'
},
en:{
 bannerLabel:'EXPANSION · TECH LEADS CLUB',bannerTitle:'Your team of four specialists.',bannerFlow:'Discover → Plan → Implement → Judge',bannerAria:(d,t)=>`${d} of ${t} TLC challenges completed`,bannerCount:'TLC challenges',bannerEnter:'Enter the workshop',
 backAria:'Back to the TLC workshop',backLabel:'← Workshop',closeAria:'Close TLC workshop',
 hubTitle:'Four specialists. One verifiable delivery.',hubKicker:'TLC AI DEV FLOW',hubLead:'The same retry feature, now with explicit roles, inputs and outputs. Study in any order; each specialist’s challenges form a sequence.',meterChallenges:'challenges',meterXp:'TLC XP',meterSpecialists:'specialists',kitLink:'Installation, prompts and sources ↗',agentAria:(skill,d)=>`${skill}, ${d} of 4 challenges completed`,agentRevisit:'Revisit ✓',agentContinue:'Continue →',agentStart:'Start →',splitTitle:'18 + 16, without losing what you already did.',splitBody:'The original campaign keeps your XP and unlocks. The expansion has its own progression and ships in the same backup. When swapping files, import the v1.1 JSON under Settings → Restore backup.',split2Title:'The skills do not replace infrastructure.',split2Body:'Deploy, monitoring and authorization stay in the original stations. This game teaches using the skills; it does not run real agents.',harnessLink:'Put this flow to the test →',harnessLinkBody:'Open the execution lab: preconditions, real in-memory tests and evidence invalidated after changes.',guideBtn:'Export my TLC guide ↓',backupBtn:'Full game backup ↓',
 metaChallenge:(i)=>`Challenge ${i} of 4 · `,metaReview:'Review without extra XP',metaXp:n=>`up to ${n} TLC XP`,navAria:skill=>`Challenges of ${skill}`,taskAria:(i,title,done)=>`Challenge ${i}: ${title}${done?', completed':''}`,doneCount:d=>`${d}/4 completed`,conceptSummary:'Understand the concept ',conceptFree:'Free · no XP cost',exampleLabel:'Example',readSource:'Read the original skill ↗',submitProof:'Run proofs',submitReview:'Prepare simulated review',submitChoice:'Verify decision',nextTask:'Next challenge →',nextArtifact:'Receive artifact →',moduleKitLink:'See input, output and prompt ↗',disclaimer:'Teaching scenario. No command, agent, external service or production action is executed.',
 optionsAria:'Challenge choices',instrSelect:n=>`Select ${n} cards.`,instrChoice:'Choose a decision.',instrClassify:'Match each situation to its destination.',choose:'Choose…',labLabel:'EXECUTABLE LAB · FICTIONAL DATA',labGoal:'Goal: before the patch <b>fails</b> → candidate <b>passes</b> → deny-everything mutant <b>fails</b>.',labSuite:'1. Choose what to test',labSuiteEmpty:'Select the suite…',labSuites:{happy:'Permitted accesses only',placebo:'Fixture count only',contract:'Contract: permitted, cross-tenant and missing ID'},labPatch:'2. Choose the candidate',labPatchEmpty:'Select the implementation…',labPatches:{original:'Keep: look up by ID only',denyAll:'Deny everything: return null',scoped:'Fix: filter by ID and tenant'},codeAria:'Code of the chosen implementation',labCaption:'The functions are predefined and use local fixtures. There is no eval and no execution of typed code. The pre-patch test applies here to a known bug, not to every new test.',pickCandidate:'Choose a candidate to inspect the function.',diffAria:'Fictional reviewed snippet',instrReview:'Select the findings for the consolidated inline review and choose the verdict.',verdictLabel:'Review verdict',reviewCaption:'Teaching adapter: this tribunal does not run the official review_gate.py, publishes no review and authorizes no merge.',
 failed:'FAILED',passed:'PASSED',localStatus:s=>`local status ${s}`,expected:(e,a)=>`Expected: ${e} · got: ${a}`,proofCaption:n=>`${n} local assertions executed in this round. Status 0/1 is computed in the browser; it is not a CI process.`,
 fbOk:'Decision verified.',fbEmpty:'A choice is missing.',fbFail:'Not yet. Let’s adjust.',labProofBtn:'Download local run ↓',findingsBtn:'Export teaching findings ↓',
 rewardTitle:'Specialist completed.',rewardText:xp=>`4 challenges · ${xp} TLC XP. What matters is not the title: it is knowing what goes in, what comes out and what still needs proof.`,artifactBtn:'Download teaching example ↓',useBtn:'Use in my project ↗',revisitBtn:'Revisit challenges',nextSpecialist:'Next specialist →',backHub:'Back to the workshop →',rewardDisclaimer:'This achievement is local and didactic, not a certification or independent audit.',
 kitTitle:'Take the flow to your project.',kitKicker:'INSTALLATION + HANDOFF',kitLead:'The workshop teaches the decisions. Installing the skills happens in your project’s terminal, outside this HTML.',installLabel:'COMMAND PUBLISHED BY TECH LEADS CLUB',copyInstall:'Copy command',installNote:'The command requires Node.js/npm and network access. Review the origin and the options presented by the installer. Copying does not run or install anything.',dlInput:'When it starts',dlOutput:'What it delivers',dlStage:'In SDLC Quest',copyPrompt:'Copy prompt',practice:'Practice →',originalSkill:'Original skill ↗',notesTitle:'Fidelity, limits and sources',noteArtifacts:'<strong>Artifacts:</strong> .design, .tasks and .checks are the documented paths. The examples downloaded here are condensed campaign cards, not complete copies of the official templates.',noteVerify:'<strong>Verification:</strong> the tlc-implement skill requires a new verifier. Without it, the result remains without independent verification — renaming the author is not enough.',noteReview:'<strong>Review:</strong> the-judge produces APPROVE, COMMENT or REQUEST_CHANGES, not a 0-to-10 grade. It caps the same finding set at three rounds. A review is not a deploy authorization.',noteScope:'<strong>Scope:</strong> the four skills are the core of the consulted flow. Intake, triage and production appear as future stations on this page; the six full stages remain taught by the original campaign.',exportGuide:'Export guide with prompts ↓',backupAll:'Full backup ↓',
 copied:'Text copied. No command was executed.',copyFallback:'Automatic copy unavailable. Copy the selected text with Ctrl+C / ⌘C.'
}};
const T=(k,...args)=>{const v=(QL.get()==='en'?STRINGS.en[k]:undefined)??STRINGS.pt[k];return typeof v==='function'?v(...args):v;};
const SN=k=>(QL.get()==='en'?STRINGS.en[k]:undefined)??STRINGS.pt[k];
const F=(r,n)=>QL.field(r,n,QL.get());
const tupleLabel=t=>QL.get()==='en'&&t.length>2?t[2]:t[1];
let state=B.read(),moduleIndex=0,taskIndex=0,answer=null,opener=null,view='hub',lastLab=null;
function save(){B.write(state);state=B.read();}
function notify(text){B.toast(text);}
function modalSync(){document.dispatchEvent(new Event('quest-modal'));}
function frame(title,kicker,body){
 content.innerHTML=`<div class="dialog-top"><button class="tlc-back" data-tlc="hub" aria-label="${T('backAria')}">${T('backLabel')}</button><span class="eyebrow">${esc(kicker)}</span><button class="close-btn" data-tlc="close" aria-label="${T('closeAria')}">×</button></div><div class="tlc-main"><h2 id="tlc-title" tabindex="-1">${esc(title)}</h2>${body}</div>`;
 if(!dialog.open)dialog.showModal();dialog.scrollTop=0;modalSync();$('#tlc-title').focus({preventScroll:true});
}
function open(where='hub'){
 state=B.read();opener=document.activeElement;
 for(const other of document.querySelectorAll('dialog[open]'))if(other!==dialog)other.close();
 if(where==='kit')showKit();else {const i=D.modules.findIndex(m=>m.id===where);if(i>=0)showModule(i);else showHub();}
}
function banner(){
 state=B.read();const st=C.stats(state),el=$('#tlc-banner');
 el.innerHTML=`<div><span class="tlc-label">${T('bannerLabel')}</span><strong>${T('bannerTitle')}</strong><span class="tlc-banner-note">${T('bannerFlow')}</span></div><div class="tlc-banner-actions"><span class="tlc-count" aria-label="${T('bannerAria',st.done,st.total)}">${st.done}/${st.total} <span>${T('bannerCount')}</span></span><button class="primary" id="tlc-launch" data-open-tlc="hub">${T('bannerEnter')} <span aria-hidden="true">↗</span></button></div>`;
}
function showHub(){
 view='hub';state=B.read();const st=C.stats(state);
 frame(T('hubTitle'),T('hubKicker'),`
 <p class="tlc-lead">${T('hubLead')}</p>
 <div class="tlc-hub-meter"><span><strong>${st.done}/${st.total}</strong> ${T('meterChallenges')}</span><span><strong>${st.xp}</strong> ${T('meterXp')}</span><span><strong>${st.modules}/4</strong> ${T('meterSpecialists')}</span><button class="text-button" data-tlc="kit">${T('kitLink')}</button></div>
 <div class="tlc-agents">${D.modules.map((m,i)=>{const done=m.tasks.filter(t=>state.done[t.id]).length;return `<button class="tlc-agent" data-tlc-module="${i}" aria-label="${T('agentAria',m.skill,done)}"><span class="tlc-agent-top"><span class="tlc-agent-glyph" aria-hidden="true">${m.glyph}</span><span class="tlc-agent-role">0${i+1} / ${esc(F(m,'role'))}</span></span><code>${m.skill}</code><h3>${esc(F(m,'name'))}</h3><p>${esc(F(m,'brief'))}</p><span class="tlc-agent-end">${done===4?T('agentRevisit'):done?T('agentContinue'):T('agentStart')}<span>${done}/4</span></span></button>`;}).join('')}</div>
 <div class="tlc-split-note"><p><strong>${T('splitTitle')}</strong> ${T('splitBody')}</p><p><strong>${T('split2Title')}</strong> ${T('split2Body')}</p></div>
 <button class="harness-link" data-open-harness="true"><strong>${T('harnessLink')}</strong><br>${T('harnessLinkBody')}</button><div class="tlc-footer-actions"><button class="secondary" data-tlc="guide">${T('guideBtn')}</button><button class="secondary" data-tlc="backup">${T('backupBtn')}</button></div>`);
}
function showModule(index){
 moduleIndex=Math.max(0,Math.min(3,index));state.selected=moduleIndex;save();
 const m=D.modules[moduleIndex],next=m.tasks.findIndex(t=>!state.done[t.id]);
 if(next<0)showReward();else showTask(next);
}
function showTask(index){
 const m=D.modules[moduleIndex],t=m.tasks[index];if(!t||!C.canOpen(state,t.id))return;
 view='task';taskIndex=index;lastLab=null;answer=structuredClone(state.drafts[t.id]??C.cleanAnswer(t,null));
 const done=m.tasks.filter(t=>state.done[t.id]).length;
 frame(F(t,'title'),m.skill,`
 <div class="tlc-lesson-meta"><span>${esc(F(m,'stage'))}</span><span>${T('metaChallenge',index+1)}${state.done[t.id]?T('metaReview'):T('metaXp',C.score(state.attempts[t.id]))}</span></div>
 <nav class="tlc-task-nav" aria-label="${T('navAria',m.skill)}">${m.tasks.map((x,i)=>`<button data-tlc-task="${i}" ${C.canOpen(state,x.id)?'':'disabled'} ${i===index?'aria-current="step"':''} aria-label="${T('taskAria',i+1,F(x,'title'),!!state.done[x.id])}">${state.done[x.id]?'✓':i+1}</button>`).join('')}<span>${T('doneCount',done)}</span></nav>
 <p class="tlc-lead">${esc(F(t,'lead'))}</p>
 <details class="tlc-concept"><summary>${T('conceptSummary')}<span>${T('conceptFree')}</span></summary><p>${esc(F(t,'concept'))}</p><div class="tlc-example"><strong>${T('exampleLabel')}</strong><p>${esc(F(t,'example'))}</p></div><a href="${esc(m.source)}" target="_blank" rel="noopener noreferrer">${T('readSource')}</a></details>
 ${exercise(t)}
 <div id="tlc-lab-output"></div>
 <div id="tlc-feedback" class="feedback hidden" role="status" aria-live="polite" tabindex="-1"></div>
 <div class="tlc-task-actions"><button class="text-button" data-tlc="module-kit">${T('moduleKitLink')}</button><div><button class="primary" id="tlc-submit" data-tlc="submit">${t.type==='prooflab'?T('submitProof'):t.type==='reviewlab'?T('submitReview'):T('submitChoice')}</button><button class="primary hidden" id="tlc-next" data-tlc="next">${index===3?T('nextArtifact'):T('nextTask')}</button></div></div>
 <p class="tlc-disclaimer">${T('disclaimer')}</p>`);
 paintOptions(t);
}
function optionsHTML(t){
 const selected=id=>t.type==='choice'?answer===id:t.type==='reviewlab'?answer.findings.includes(id):answer.includes(id);
 return `<div class="options-list tlc-options" role="group" aria-label="${T('optionsAria')}">${QuestCore.shuffled(t.options,t.id).map(o=>`<button class="option" data-tlc-option="${o.id}" aria-pressed="${selected(o.id)}"><span class="check" aria-hidden="true">✓</span><div><strong>${esc(F(o,'label'))}</strong></div></button>`).join('')}</div>`;
}
function exercise(t){
 if(t.type==='choice'||t.type==='select')return `<p class="instruction">${t.type==='select'?T('instrSelect',t.answer.length):T('instrChoice')}</p>${optionsHTML(t)}`;
 if(t.type==='classify')return `<p class="instruction">${T('instrClassify')}</p><div class="classify-list tlc-classify">${t.items.map(i=>`<div class="classify-row"><label for="tlc-field-${i.id}">${esc(F(i,'text'))}</label><select id="tlc-field-${i.id}" data-tlc-field="${i.id}"><option value="">${T('choose')}</option>${t.groups.map(g=>`<option value="${g[0]}" ${answer[i.id]===g[0]?'selected':''}>${esc(tupleLabel(g))}</option>`).join('')}</select></div>`).join('')}</div>`;
 if(t.type==='prooflab')return `<div class="tlc-lab-intro"><span class="tlc-label">${T('labLabel')}</span><p>${T('labGoal')}</p></div><div class="tlc-lab-config">
 <label for="tlc-suite">${T('labSuite')}<select id="tlc-suite" data-tlc-field="suite"><option value="">${T('labSuiteEmpty')}</option>${['happy','placebo','contract'].map(v=>`<option value="${v}" ${answer.suite===v?'selected':''}>${SN('labSuites')[v]}</option>`).join('')}</select></label>
 <label for="tlc-patch">${T('labPatch')}<select id="tlc-patch" data-tlc-field="patch"><option value="">${T('labPatchEmpty')}</option>${['original','denyAll','scoped'].map(v=>`<option value="${v}" ${answer.patch===v?'selected':''}>${SN('labPatches')[v]}</option>`).join('')}</select></label></div>
 <pre class="tlc-code" id="tlc-code-sample" tabindex="0" aria-label="${T('codeAria')}">${esc(patchCode(answer.patch))}</pre><p class="tlc-caption">${T('labCaption')}</p>`;
 if(t.type==='reviewlab')return `<pre class="tlc-code" tabindex="0" aria-label="${T('diffAria')}">${esc('src/retry.ts — diff fictício\n1  async function retry(req, repo, logger) {\n2    const item = await repo.find(req.params.id, req.user.tenant);\n3    if (!item) return { status: 404 };\n4 +  logger.info({ authorization: req.headers.authorization });\n5    return { status: 202, body: { deliveryId: item.id } };\n6  }')}</pre><p class="instruction">${T('instrReview')}</p>${optionsHTML(t)}<label class="tlc-verdict-field" for="tlc-verdict">${T('verdictLabel')}<select id="tlc-verdict" data-tlc-field="verdict"><option value="">${T('choose')}</option>${['APPROVE','COMMENT','REQUEST_CHANGES'].map(v=>`<option ${answer.verdict===v?'selected':''}>${v}</option>`).join('')}</select></label><p class="tlc-caption">${T('reviewCaption')}</p>`;
 return '';
}
function patchCode(patch){return patch==='scoped'?'return rows.find(row =>\n  row.id === id && row.tenant === tenant\n) ?? null;':patch==='denyAll'?'return null; // defeito: também nega os acessos permitidos':patch==='original'?'return rows.find(row => row.id === id) ?? null;':T('pickCandidate');}
function paintOptions(t){for(const button of content.querySelectorAll('[data-tlc-option]')){const id=button.dataset.tlcOption;button.setAttribute('aria-pressed',String(t.type==='choice'?answer===id:t.type==='reviewlab'?answer.findings.includes(id):answer.includes(id)));}}
function clearResult(){lastLab=null;$('#tlc-lab-output').innerHTML='';$('#tlc-feedback').className='feedback hidden';$('#tlc-next').classList.add('hidden');$('#tlc-submit').classList.remove('hidden');}
function remember(){const t=D.modules[moduleIndex].tasks[taskIndex];state.drafts[t.id]=C.cleanAnswer(t,answer);save();}
function renderLab(result){
 if(!result.versions?.length)return;
 $('#tlc-lab-output').innerHTML=`<div class="tlc-proof-grid">${result.versions.map(v=>`<section class="tlc-proof ${v.exitCode?'proof-red':'proof-green'}"><h3>${esc(v.label)}</h3><strong>${v.exitCode?T('failed'):T('passed')} <small>${T('localStatus',v.exitCode)}</small></strong><ul>${v.checks.map(x=>`<li><span aria-hidden="true">${x.pass?'✓':'×'}</span><div>${esc(x.label)}<small>${T('expected',x.expected===null?'null':x.expected,x.actual===null?'null':x.actual)}</small></div></li>`).join('')}</ul></section>`).join('')}</div><p class="tlc-caption">${T('proofCaption',result.versions.reduce((n,v)=>n+v.checks.length,0))}</p>`;
}
function submit(){
 const t=D.modules[moduleIndex].tasks[taskIndex];
 if(t.type==='prooflab'&&C.hasAnswer(t,answer)){lastLab=C.runLab(answer.suite,answer.patch,QL.get());renderLab(lastLab);}
 const result=C.submit(state,t.id,answer,QL.get());save();const feedback=$('#tlc-feedback');
 feedback.className='feedback'+(result.ok?' good':'');feedback.innerHTML=`<strong>${result.ok?T('fbOk'):result.empty?T('fbEmpty'):T('fbFail')}</strong>${esc(result.message)}${t.type==='prooflab'&&result.ok?`<p><button class="secondary" data-tlc="lab-proof">${T('labProofBtn')}</button></p>`:''}${t.type==='reviewlab'&&result.ok?`<p><button class="secondary" data-tlc="findings">${T('findingsBtn')}</button></p>`:''}`;
 if(result.ok){$('#tlc-next').classList.remove('hidden');$('#tlc-submit').classList.add('hidden');}
 feedback.focus({preventScroll:true});feedback.scrollIntoView({block:'nearest',behavior:'instant'});
}
function artifactText(m){
 const common=`# ${m.artifact}\n\nADAPTAÇÃO DIDÁTICA — exemplo fictício, não resultado de agente real.\nFonte: ${m.source}\nConsulta: ${D.checkedAt}\n\n`;
 if(m.id==='discover')return common+'## Situation\nRetry para administradores aprovado no cenário.\n\n## Problem\nO suporte depende de reenvio manual de entregas falhas.\n\n## Verdict\nConstruir a menor capacidade que reduza a intervenção manual.\n\n## What counts as worked\nMeta fictícia acordada: reduzir 40 para menos de 15 min/dia em duas semanas; Ana revisa. Não é um critério de teste unitário.\n\n## Boundary\nSem reenvio em massa ou novos destinos.\n\n## Shape\nAdds: solicitação de retry e consulta de tentativa.\nChanges: autorização do novo caminho e mensagens de resultado.\nLeaves: restante do serviço e contratos não relacionados.\n\n## Decisions\nSomente admin do próprio tenant. Nenhuma promessa de exactly-once arbitrário.\n\n## Roadmap\nEsclarecer tratamento de duplicatas; então passar a tlc-plan.\n';
 if(m.id==='plan')return common+'## Intent\nTornar o retry elegível observável do pedido à consulta da tentativa.\n\n## Criteria\nC1: ID vazio retorna 400.\nC2: entrega ausente retorna 404.\nC3: acesso exige admin e o tenant correto.\nC4: estados queued → processing → succeeded ou failed.\n\n## Out of scope\nReenvio em massa.\n\n## Observable\nAPI: critérios C1–C3. Tela: definir estados de loading, vazio e erro antes de implementar a interface.\n\n## Swept\nvalidation: C1\nfailure modes: C2\nidempotency and retry: existing — deduplicação inspecionada no cenário\nauthorization: C3\nconcurrency and ordering: Unresolved 1\ndata lifecycle: Unresolved 2\nexternal-dependency failure: existing — timeout do adaptador vira failed\nstate transitions: C4\nobservability: existing — eventos de auditoria e redação inspecionados no cenário\n\n## Unresolved\n1 | blocks build | decidir resposta concorrente e mecanismo de exclusão\n2 | open | confirmar retenção das tentativas com o responsável\n\nNão implementar uma garantia ainda não decidida. Esta ficha é resumida e não substitui o template oficial.\n';
 if(m.id==='implement')return common+'## Sources\n.tasks/retry-webhook.md — critérios aprovados\n\n## Out of scope\nDeploy, push e qualquer mudança de produção sem autorização.\n\n## Landing\nConsulta local com filtro de ID e tenant; não equivale a autenticação de uma API.\n\n## Checks\nC1: acesso permitido A → A tem prova own-a.\nC2: acesso permitido B → B tem prova own-b.\nC3: acesso A → B negado tem prova cross-a.\nC4: acesso B → A negado tem prova cross-b.\nC5: ID ausente retorna null tem prova missing.\n\n## Coverage\nCinco casos explícitos. Regressão: contrato detecta o código anterior e o mutante que nega tudo.\nLacunas: HTTP, autenticação, concorrência e infraestrutura não são exercitados neste laboratório.\n\n## Handoff\nNo projeto real: fatias fechadas, commit, checklist, diff, esclarecimentos e tentativas abandonadas.\n\n## Verification\nEsta ficha descreve os checks do laboratório, mas não atesta que o jogador os executou. Use o botão de exportar execução na tela do laboratório para registrar resultados. Nenhum subagente independente é executado pelo jogo.\n';
 return JSON.stringify(C.reviewArtifact(),null,2)+'\n';
}
function showReward(){
 view='reward';const m=D.modules[moduleIndex],xp=m.tasks.reduce((n,t)=>n+(state.done[t.id]?.score||0),0);
 frame(T('rewardTitle'),m.skill,`<div class="tlc-reward"><span class="tlc-agent-glyph" aria-hidden="true">${m.glyph}</span><h3>${esc(F(m,'name'))}</h3><p>${T('rewardText',xp)}</p><code>${esc(m.artifact)}</code><div class="tlc-footer-actions"><button class="primary" data-tlc="artifact">${T('artifactBtn')}</button><button class="secondary" data-tlc="module-kit">${T('useBtn')}</button></div></div><div class="tlc-footer-actions"><button class="secondary" data-tlc-task="0">${T('revisitBtn')}</button><button class="primary" ${moduleIndex<3?`data-tlc-module="${moduleIndex+1}"`:'data-tlc="hub"'}>${moduleIndex<3?T('nextSpecialist'):T('backHub')}</button></div><p class="tlc-disclaimer">${T('rewardDisclaimer')}</p>`);
}
function showKit(onlyModule=false){
 view='kit';const modules=onlyModule?[D.modules[moduleIndex]]:D.modules;
 frame(T('kitTitle'),T('kitKicker'),`
 <p class="tlc-lead">${T('kitLead')}</p><div class="tlc-install"><span class="tlc-label">${T('installLabel')}</span><pre class="tlc-code" id="tlc-install-command" tabindex="0">${esc(D.install)}</pre><button class="secondary" data-tlc="copy-install">${T('copyInstall')}</button><p>${T('installNote')}</p></div>
 <div class="tlc-prompt-list">${modules.map(m=>`<section class="tlc-prompt-card"><h3><span aria-hidden="true">${m.glyph}</span> <code>${m.skill}</code></h3><dl><div><dt>${T('dlInput')}</dt><dd>${esc(F(m,'input'))}</dd></div><div><dt>${T('dlOutput')}</dt><dd>${esc(F(m,'output'))}</dd></div><div><dt>${T('dlStage')}</dt><dd>${esc(F(m,'stage'))}</dd></div></dl><pre class="tlc-code" tabindex="0">${esc(F(m,'prompt'))}</pre><div class="tlc-footer-actions"><button class="secondary" data-tlc-copy="${m.id}">${T('copyPrompt')}</button><button class="text-button" data-tlc-module="${D.modules.indexOf(m)}">${T('practice')}</button><a href="${esc(m.source)}" target="_blank" rel="noopener noreferrer">${T('originalSkill')}</a></div></section>`).join('')}</div>
 <section class="tlc-source-notes"><h3>${T('notesTitle')}</h3><p>${T('noteArtifacts')}</p><p>${T('noteVerify')}</p><p>${T('noteReview')}</p><p>${T('noteScope')}</p><p>${esc(F(D,'notice'))}</p><p><a href="${esc(D.flow)}" target="_blank" rel="noopener noreferrer">TLC AI Dev Flow ↗</a> · <a href="${esc(D.license)}" target="_blank" rel="noopener noreferrer">CC BY 4.0 ↗</a></p></section><div class="tlc-footer-actions"><button class="primary" data-tlc="guide">${T('exportGuide')}</button><button class="secondary" data-tlc="backup">${T('backupAll')}</button></div>`);
}
async function copy(text){
 try{if(!navigator.clipboard?.writeText)throw new Error('unavailable');await navigator.clipboard.writeText(text);notify(T('copied'));}
 catch{let box=$('#tlc-copy-fallback');if(!box){box=document.createElement('div');box.id='tlc-copy-fallback';box.className='tlc-copy-fallback';box.innerHTML=`<label for="tlc-copy-text">${T('copyFallback')}</label><textarea id="tlc-copy-text" readonly rows="5"></textarea>`;content.querySelector('.tlc-main').prepend(box);}const field=$('#tlc-copy-text');field.value=text;field.focus();field.select();box.scrollIntoView({block:'nearest',behavior:'instant'});}
}
function guide(){
 state=B.read();const st=C.stats(state);
 return `# SDLC Quest v1.2 — Oficina TLC\n\nConsulta das fontes: ${D.checkedAt}\nProgresso didático: ${st.done}/${st.total} desafios; ${st.xp} XP TLC.\nNão é evidência de execução de skills ou de uma feature real.\n\n## Instalação fora do jogo\n\`\`\`sh\n${D.install}\n\`\`\`\n\n`+D.modules.map(m=>`## ${m.skill}\n\nEntrada: ${m.input}\nSaída: ${m.output}\nIntegração: ${m.stage}\nFonte: ${m.source}\n\n### Prompt sugerido\n${m.prompt}\n\n### Desafios e princípios (checkbox = concluído no jogo)\n`+m.tasks.map(t=>`- ${state.done[t.id]?'[x]':'[ ]'} ${t.title} — ${t.success}`).join('\n')+`\n\n### Exemplo de artefato (didático, não template oficial completo)\n\`\`\`text\n${artifactText(m)}\`\`\`\n`).join('\n')+`\n## Limites\nNão executa npx, agentes, gh ou produção. Laboratório cobre consulta local; não cobre autenticação HTTP nem concorrência real. Verificação independente não foi executada pelo jogo. Pontuação não prova domínio.\n\n## Atribuição\n${D.notice}\n${D.license}\n${D.flow}\n`;
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-open-tlc]');if(b)open(b.dataset.openTlc);});
content.addEventListener('click',e=>{
 const b=e.target.closest('button');if(!b||b.disabled)return;
 if(b.dataset.tlcModule!==undefined){showModule(Number(b.dataset.tlcModule));return;}
 if(b.dataset.tlcTask!==undefined){showTask(Number(b.dataset.tlcTask));return;}
 if(b.dataset.tlcCopy){copy(F(D.modules.find(m=>m.id===b.dataset.tlcCopy),'prompt'));return;}
 if(b.dataset.tlcOption){const t=D.modules[moduleIndex].tasks[taskIndex],id=b.dataset.tlcOption;if(t.type==='choice')answer=id;else {const arr=t.type==='reviewlab'?answer.findings:answer;const at=arr.indexOf(id);if(at<0)arr.push(id);else arr.splice(at,1);}paintOptions(t);clearResult();remember();return;}
 switch(b.dataset.tlc){
  case 'close':dialog.close();break;
  case 'hub':showHub();break;
  case 'kit':showKit();break;
  case 'module-kit':showKit(true);break;
  case 'submit':submit();break;
  case 'next':taskIndex===3?showReward():showTask(taskIndex+1);break;
  case 'copy-install':copy(D.install);break;
  case 'guide':B.download('SDLC-Quest-TLC-meu-guia.md',guide(),'text/markdown');break;
  case 'backup':B.backup();break;
  case 'artifact':{const m=D.modules[moduleIndex];B.download('TLC-'+m.id+'-'+m.artifact.split('/').pop(),artifactText(m),'text/plain');break;}
  case 'lab-proof':if(lastLab)B.download('TLC-execucao-local.json',JSON.stringify({simulation:true,scope:'Funções de consulta em memória; não é CI, HTTP, autenticação ou um verificador independente.',appVersion:D.version,exportedAt:new Date().toISOString(),...lastLab},null,2),'application/json');break;
  case 'findings':B.download('TLC-findings-didatico.json',JSON.stringify(C.reviewArtifact(),null,2),'application/json');break;
 }
});
content.addEventListener('change',e=>{if(!e.target.dataset.tlcField)return;answer[e.target.dataset.tlcField]=e.target.value;clearResult();remember();if(e.target.id==='tlc-patch')$('#tlc-code-sample').textContent=patchCode(answer.patch);});
dialog.addEventListener('close',()=>{modalSync();if(opener?.isConnected)opener.focus({preventScroll:true});else $('#tlc-launch')?.focus({preventScroll:true});});
dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();});
QuestData.glossary.push(
 ['TLC AI Dev Flow','Núcleo de quatro skills: tlc-discover, tlc-plan, tlc-implement e the-judge. A oficina adicional pratica seu uso; não as executa. Fontes e instalação estão no painel Skills TLC.','TLC AI Dev Flow','A core of four skills: tlc-discover, tlc-plan, tlc-implement and the-judge. The extra workshop practices using them; it does not run them. Sources and installation are in the TLC skills panel.'],
 ['tlc-discover','Investiga o problema e decisões abertas; produz veredito e design quando aplicável. Compromissos já tomados não precisam de um novo gate encenado.','tlc-discover','Investigates the problem and open decisions; produces a verdict and design when applicable. Commitments already made need no staged new gate.'],
 ['tlc-plan','Converte decisões em tarefas com resultados observáveis, faz o surface walk e a varredura de nove dimensões. Uma lacuna vira pergunta, não requisito inventado.','tlc-plan','Turns decisions into tasks with observable outcomes, does the surface walk and the nine-dimension sweep. A gap becomes a question, not an invented requirement.'],
 ['tlc-implement','Extrai checks com provas, implementa e exige verificação por um executor novo. Os perfis light, standard e ui explicitam a profundidade e as limitações.','tlc-implement','Extracts checks with proofs, implements and requires verification by a fresh executor. The light, standard and ui profiles make depth and limitations explicit.'],
 ['the-judge','Revisor de PR com evidências e vereditos APPROVE, COMMENT ou REQUEST_CHANGES. Não dá nota de perfeição, não implementa a correção e não autoriza deploy.','the-judge','A PR reviewer with evidence and APPROVE, COMMENT or REQUEST_CHANGES verdicts. It gives no perfection grade, implements no fix and authorizes no deploy.'],
 ['Carryover e convergência','Pendências de rodadas anteriores continuam contando no veredito. O the-judge limita a revisão do mesmo conjunto de achados a três rodadas; divergências restantes são resolvidas, acordadas ou escaladas.','Carryover and convergence','Pending items from previous rounds still count in the verdict. the-judge caps review of the same finding set at three rounds; remaining disagreements are resolved, agreed or escalated.']
);
document.addEventListener('quest-state-changed',banner);
document.addEventListener('quest-lang-changed',banner);
banner();
Object.defineProperty(window,'SDLCQuestTLC',{value:Object.freeze({version:D.version,getStats:()=>C.stats(B.read()),currentTask:()=>view==='task'?D.modules[moduleIndex].tasks[taskIndex].id:null,guide}),writable:false});
})();
