import type { AppDefinition, CoreAppId } from '../domain'

export const appCatalog = [
  { name: 'Trilhas Dojo', category: 'Aprender', concepts: ['progressão', 'prática deliberada'], status: 'disponivel', appId: 'dojo' },
  { name: 'Terminal', category: 'Sistema', concepts: ['shell', 'processos'], status: 'disponivel', appId: 'terminal' },
  { name: 'Arquivos', category: 'Sistema', concepts: ['sistema de arquivos', 'árvores'], status: 'disponivel', appId: 'files' },
  { name: 'Mapa da Arquitetura', category: 'Desenvolver', concepts: ['camadas', 'contratos'], status: 'disponivel', appId: 'architecture' },
  { name: 'Central de Apps', category: 'Sistema', concepts: ['pacotes', 'dependências'], status: 'disponivel', appId: 'software' },
  { name: 'Engine Hub', category: 'Sistema', concepts: ['motores', 'adapters'], status: 'disponivel', appId: 'engines' },
  { name: 'Fundamentos', category: 'Aprender', concepts: ['computação', 'modelos mentais'], status: 'laboratorio' },
  { name: 'Mentor IA', category: 'Aprender', concepts: ['tutoria contextual', 'feedback'], status: 'laboratorio' },
  { name: 'Projetos', category: 'Aprender', concepts: ['aprendizagem ativa', 'portfólio'], status: 'laboratorio' },
  { name: 'Desafios', category: 'Aprender', concepts: ['recall', 'resolução de problemas'], status: 'planejado' },
  { name: 'Arena de Quiz', category: 'Aprender', concepts: ['repetição espaçada', 'avaliação'], status: 'planejado' },
  { name: 'Caderno', category: 'Aprender', concepts: ['anotações', 'síntese'], status: 'planejado' },
  { name: 'Progresso', category: 'Aprender', concepts: ['métricas', 'metacognição'], status: 'planejado' },
  { name: 'Portfólio', category: 'Aprender', concepts: ['evidências', 'reflexão'], status: 'planejado' },
  { name: 'Editor de Código', category: 'Desenvolver', concepts: ['linguagens', 'AST'], status: 'laboratorio' },
  { name: 'Git Studio', category: 'Desenvolver', concepts: ['versionamento', 'grafos'], status: 'planejado' },
  { name: 'API Lab', category: 'Desenvolver', concepts: ['HTTP', 'contratos'], status: 'planejado' },
  { name: 'Database Studio', category: 'Desenvolver', concepts: ['SQL', 'índices'], status: 'planejado' },
  { name: 'Network Lab', category: 'Desenvolver', concepts: ['TCP/IP', 'DNS'], status: 'planejado' },
  { name: 'Container Lab', category: 'Desenvolver', concepts: ['isolamento', 'imagens'], status: 'planejado' },
  { name: 'Regex Lab', category: 'Desenvolver', concepts: ['autômatos', 'padrões'], status: 'planejado' },
  { name: 'Algoritmos', category: 'Desenvolver', concepts: ['complexidade', 'estratégias'], status: 'planejado' },
  { name: 'Estruturas de Dados', category: 'Desenvolver', concepts: ['listas', 'árvores'], status: 'planejado' },
  { name: 'Testing Lab', category: 'Desenvolver', concepts: ['testes', 'qualidade'], status: 'planejado' },
  { name: 'Security Lab', category: 'Desenvolver', concepts: ['ameaças', 'defesas'], status: 'planejado' },
  { name: 'Cloud Lab', category: 'Desenvolver', concepts: ['distribuição', 'escalabilidade'], status: 'planejado' },
  { name: 'OS Lab', category: 'Desenvolver', concepts: ['kernel', 'memória'], status: 'planejado' },
  { name: 'Compiler Lab', category: 'Desenvolver', concepts: ['parsing', 'bytecode'], status: 'planejado' },
  { name: 'Web Lab', category: 'Desenvolver', concepts: ['DOM', 'event loop'], status: 'planejado' },
  { name: 'Game Lab', category: 'Desenvolver', concepts: ['loop de jogo', 'estado'], status: 'planejado' },
  { name: 'AI Lab', category: 'Desenvolver', concepts: ['modelos', 'avaliações'], status: 'planejado' },
  { name: 'Hardware Lab', category: 'Desenvolver', concepts: ['CPU', 'lógica digital'], status: 'planejado' },
  { name: 'Navegador', category: 'Criar', concepts: ['web', 'sandbox'], status: 'planejado' },
  { name: 'Texto', category: 'Criar', concepts: ['documentos', 'codificação'], status: 'planejado' },
  { name: 'Notas', category: 'Criar', concepts: ['persistência', 'busca'], status: 'planejado' },
  { name: 'Planilhas', category: 'Criar', concepts: ['funções', 'dependências'], status: 'planejado' },
  { name: 'Apresentações', category: 'Criar', concepts: ['composição', 'renderização'], status: 'planejado' },
  { name: 'Imagens', category: 'Criar', concepts: ['pixels', 'compressão'], status: 'planejado' },
  { name: 'Música', category: 'Criar', concepts: ['áudio digital', 'streaming'], status: 'planejado' },
  { name: 'Vídeos', category: 'Criar', concepts: ['codecs', 'buffers'], status: 'planejado' },
  { name: 'Calculadora', category: 'Utilitários', concepts: ['parsing', 'precisão'], status: 'planejado' },
  { name: 'Calendário', category: 'Utilitários', concepts: ['datas', 'sincronização'], status: 'planejado' },
  { name: 'Clima', category: 'Utilitários', concepts: ['APIs', 'cache'], status: 'planejado' },
  { name: 'Mapas', category: 'Utilitários', concepts: ['grafos', 'geodados'], status: 'planejado' },
  { name: 'E-mail', category: 'Utilitários', concepts: ['SMTP', 'filas'], status: 'planejado' },
  { name: 'Chat', category: 'Utilitários', concepts: ['websockets', 'eventos'], status: 'planejado' },
  { name: 'Monitor do Sistema', category: 'Sistema', concepts: ['telemetria', 'recursos'], status: 'laboratorio' },
  { name: 'Configurações', category: 'Sistema', concepts: ['preferências', 'estado'], status: 'planejado' },
  { name: 'Discos', category: 'Sistema', concepts: ['blocos', 'partições'], status: 'planejado' },
  { name: 'Logs', category: 'Sistema', concepts: ['observabilidade', 'eventos'], status: 'planejado' },
  { name: 'Senhas', category: 'Sistema', concepts: ['criptografia', 'segredos'], status: 'planejado' },
  { name: 'Captura de Tela', category: 'Sistema', concepts: ['framebuffer', 'permissões'], status: 'planejado' },
  { name: 'Compactador', category: 'Sistema', concepts: ['compressão', 'entropia'], status: 'planejado' },
  { name: 'Gerenciador de Tarefas', category: 'Sistema', concepts: ['processos', 'sinais'], status: 'planejado' },
  { name: 'Sandbox', category: 'Sistema', concepts: ['isolamento', 'capabilities'], status: 'planejado' },
] as const satisfies readonly AppDefinition[]

export const appTitles: Readonly<Record<CoreAppId, string>> = {
  dojo: 'Trilhas Dojo',
  terminal: 'Terminal',
  files: 'Arquivos',
  architecture: 'Mapa da Arquitetura',
  software: 'Central de Apps',
  engines: 'Engine Hub',
}
