// Types for the guided-practice read model projected from the canonical
// curriculum package (AID-3527). The projection itself is generated by
// scripts/gen-guided-practice.mjs into src/data/generated/guidedPractice.ts;
// these types are the stable engine-side contract consumed by the practice
// app and its tests. Grader-facing material (guia-de-correcao/) is outside
// this contract by design.

export type GuidedPracticeInputRole = 'bugreport' | 'rule' | 'fixture' | 'fixture-suite'

export type GuidedPracticeInput = {
  readonly role: GuidedPracticeInputRole
  readonly path: string
  readonly contents: string
}

export type GuidedPracticeCriterion = {
  readonly id: string
  readonly criterion: string
  readonly perCheck: string
}

export type GuidedPracticeManifestEntry = {
  readonly path: string
  readonly sha256: string
}

export type GuidedPracticeProjection = {
  readonly practiceId: string
  readonly contentVersion: string
  readonly track: string
  readonly anchorLessonId: string
  readonly title: string
  readonly objective: string
  readonly estimatedMinutes: { readonly min: number; readonly max: number }
  readonly exemplar: {
    readonly markdown: string
    readonly sourcePath: string
  }
  readonly inputs: readonly GuidedPracticeInput[]
  readonly attemptSteps: readonly string[]
  readonly rubric: readonly GuidedPracticeCriterion[]
  readonly takeawayPrompts: Readonly<{ readonly a: string; readonly b: string }>
  readonly manifest: readonly GuidedPracticeManifestEntry[]
}
