// AUTO-GENERATED by learner/substrate/dashboard_snapshot.py.
// DO NOT EDIT BY HAND — run `python3 -m learner.substrate` to regenerate.
// Read-only review slice for voxelDojo: the game reads scheduling truth here,
// emits evidence only, and never marks mastery (GameNeverMarksMastery).
// Generated: 2026-07-05T19:09:48.881907Z

import type { ReviewSlice } from "./types"

export const reviewSlice: ReviewSlice = {
  nextReviews: [
    {
      unitId: "U0-sonda-rate-limiter-robustness",
      title: "agentic orchestration for token-bucket robustness",
      dueIn: "today",
      reason: "due",
    },
    {
      unitId: "P-001",
      title: "Reivindicar domínio a partir de trabalho de documentação/dashboard",
      dueIn: "today",
      reason: "recurring-trap",
    },
  ],
  streak: {
    current: 0,
    longest: 0,
    lastGateDate: null,
    freezesEquipped: 2,
    freezesMax: 2,
  },
}
