from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Final

from learner.substrate.dashboard_data import DashboardItem, render_ts_value


_LEVEL_PHASES: Final = {
    0: "aplicacao_ia",
    1: "fundamentos",
    2: "concorrencia",
    3: "arquitetura",
    4: "escalabilidade",
    5: "resiliencia",
    6: "sistemas_complexos",
}
_PROJECT_HEADING: Final = re.compile(r"^### (\d{2})\. (.+)$")
_LEVEL_HEADING: Final = re.compile(r"^## Level (\d+)\b")
_FIELD_ROW: Final = re.compile(r"^\| \*\*(.+?)\*\* \| (.+?) \|$")


@dataclass(frozen=True, slots=True)
class CatalogProject:
    number: int
    level: int
    title: str
    slug: str
    status: str
    concepts: str
    key_question: str
    learning_goal: str
    directory: str
    dependencies: str
    evidence: str


class CatalogFormatError(ValueError):
    def __init__(self, detail: str) -> None:
        self.detail = detail
        super().__init__(f"invalid curriculum catalog: {detail}")


def _clean_cell(value: str) -> str:
    return value.replace("&lt;", "<").replace("&gt;", ">").strip().strip("`")


def _normalized_status(value: str) -> str:
    lowered = value.lower()
    if "partially implemented" in lowered:
        return "implemented (Node.js only)"
    if "implemented" in lowered:
        return "implemented"
    for status in ("scaffolded", "planned", "proposal", "blocked"):
        if status in lowered:
            return status
    return _clean_cell(value)


def parse_catalog(text: str) -> tuple[CatalogProject, ...]:
    projects: list[CatalogProject] = []
    level: int | None = None
    heading: tuple[int, str] | None = None
    fields: dict[str, str] = {}

    def finish() -> None:
        nonlocal heading, fields
        if heading is None:
            return
        if level is None:
            raise CatalogFormatError(f"project {heading[0]:02d} appears before a level")
        required = ("Slug", "Status", "Concepts", "Key question", "Directory", "Dependencies")
        missing = [name for name in required if name not in fields]
        if missing:
            raise CatalogFormatError(f"project {heading[0]:02d} missing {', '.join(missing)}")
        status = _normalized_status(fields["Status"])
        evidence = fields.get("Evidence") or (
            "Catalog-certified executable evidence." if status.startswith("implemented")
            else "Project artifacts exist; catalog verification is pending."
        )
        projects.append(
            CatalogProject(
                number=heading[0],
                level=level,
                title=heading[1],
                slug=_clean_cell(fields["Slug"]),
                status=status,
                concepts=_clean_cell(fields["Concepts"]),
                key_question=_clean_cell(fields["Key question"]),
                learning_goal=_clean_cell(fields.get("Learning goal", fields["Key question"])),
                directory=_clean_cell(fields["Directory"]),
                dependencies=_clean_cell(fields["Dependencies"]),
                evidence=_clean_cell(evidence),
            )
        )
        heading = None
        fields = {}

    for line in text.splitlines():
        level_match = _LEVEL_HEADING.match(line)
        if level_match:
            finish()
            level = int(level_match.group(1))
            continue
        project_match = _PROJECT_HEADING.match(line)
        if project_match:
            finish()
            heading = (int(project_match.group(1)), project_match.group(2))
            continue
        field_match = _FIELD_ROW.match(line)
        if heading is not None and field_match:
            fields[field_match.group(1)] = field_match.group(2)
    finish()

    numbers = [project.number for project in projects]
    first = numbers[0] if numbers else 1
    if first not in (0, 1) or numbers != list(range(first, first + len(projects))):
        raise CatalogFormatError(f"project numbers must be contiguous from 00 or 01, got {numbers}")
    return tuple(projects)


def load_catalog(path: Path) -> tuple[CatalogProject, ...]:
    return parse_catalog(path.read_text(encoding="utf-8"))


def render_projects_ts(projects: tuple[CatalogProject, ...]) -> str:
    lines = [
        "// AUTO-GENERATED by learner/substrate/catalog.py.",
        "// DO NOT EDIT BY HAND — edit curriculum/catalog.md and run `python3 -m learner.substrate`.",
        "",
        'import type { DojoProject } from "../domain"',
        "",
        "export const projects: readonly DojoProject[] = [",
    ]
    for project in projects:
        phase = _LEVEL_PHASES.get(project.level)
        if phase is None:
            raise CatalogFormatError(f"project {project.number:02d} has unsupported level {project.level}")
        item: DashboardItem = {
            "id": f"p{project.number:02d}",
            "title": project.title,
            "phase": phase,
            "level": project.level,
            "language": "Go, Rust, Node",
            "architecture": project.concepts,
            "learningGoal": project.learning_goal,
            "evidence": [
                project.evidence,
                project.status,
                project.directory,
                project.dependencies,
            ],
        }
        rendered = render_ts_value(item, 1).splitlines()
        lines.append(f"  {rendered[0]}")
        lines.extend(rendered[1:])
        lines[-1] += ","
    lines.extend(["]", ""])
    return "\n".join(lines)


def render_backlog(projects: tuple[CatalogProject, ...]) -> str:
    lines = [
        "<!-- AUTO-GENERATED by learner/substrate/catalog.py. -->",
        "<!-- DO NOT EDIT BY HAND — edit curriculum/catalog.md and run `python3 -m learner.substrate`. -->",
        "# Curriculum Backlog Status",
        "",
        "Canonical source: [catalog.md](./catalog.md). This operational view preserves the catalog's status and evidence narrative.",
        "",
        "| Project | Status | Evidence |",
        "| --- | --- | --- |",
    ]
    for project in projects:
        evidence = project.evidence.replace("|", "\\|")
        status = "implemented" if project.status.startswith("implemented") else project.status
        lines.append(f"| `{project.slug}` | `{status}` | {evidence} |")
    lines.extend(
        [
            "",
            "## Update rule",
            "",
            "Edit `curriculum/catalog.md`, then run `python3 -m learner.substrate`. This file is a generated projection and must never be edited directly.",
            "",
        ]
    )
    return "\n".join(lines)
