from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

import yaml


JsonScalar = str | int | float | bool | None
JsonValue = JsonScalar | list["JsonValue"] | dict[str, "JsonValue"]
DashboardItem = dict[str, JsonValue]
_TS_IDENTIFIER = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def _render_key(key: str) -> str:
    return key if _TS_IDENTIFIER.fullmatch(key) else json.dumps(key, ensure_ascii=False)


@dataclass(frozen=True, slots=True)
class DashboardData:
    user_facing_agents: tuple[DashboardItem, ...]
    agents: tuple[DashboardItem, ...]
    cycle_stages: tuple[DashboardItem, ...]
    metrics: tuple[DashboardItem, ...]


class DashboardDataError(ValueError):
    def __init__(self, detail: str) -> None:
        self.detail = detail
        super().__init__(f"invalid dashboard data: {detail}")


def _items(raw: JsonValue, key: str) -> tuple[DashboardItem, ...]:
    if not isinstance(raw, list):
        raise DashboardDataError(f"{key} must be a list")
    items: list[DashboardItem] = []
    for index, item in enumerate(raw):
        if not isinstance(item, dict):
            raise DashboardDataError(f"{key}[{index}] must be a mapping")
        identifier = item.get("id")
        if not isinstance(identifier, str) or not identifier:
            raise DashboardDataError(f"{key}[{index}].id must be a non-empty string")
        items.append(item)
    identifiers = [item["id"] for item in items]
    if len(identifiers) != len(set(identifiers)):
        raise DashboardDataError(f"{key} ids must be unique")
    return tuple(items)


def load_dashboard_data(path: Path) -> DashboardData:
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise DashboardDataError("root must be a mapping")
    return DashboardData(
        user_facing_agents=_items(raw.get("user_facing_agents"), "user_facing_agents"),
        agents=_items(raw.get("agents"), "agents"),
        cycle_stages=_items(raw.get("cycle_stages"), "cycle_stages"),
        metrics=_items(raw.get("metrics"), "metrics"),
    )


def render_ts_value(value: JsonValue, indent: int) -> str:
    if isinstance(value, dict):
        if not value:
            return "{}"
        pad = "  " * indent
        inner = "  " * (indent + 1)
        lines = ["{"]
        for key, item in value.items():
            rendered_key = _render_key(key)
            rendered = render_ts_value(item, indent + 1)
            one_line = f"{inner}{rendered_key}: {rendered},"
            if "\n" not in rendered and len(one_line) <= 100:
                lines.append(one_line)
            elif isinstance(item, str):
                lines.extend([f"{inner}{rendered_key}:", f"{inner}  {rendered},"])
            elif isinstance(item, list) and "\n" not in rendered:
                lines.append(f"{inner}{rendered_key}: [")
                lines.extend(
                    f"{inner}  {render_ts_value(value, indent + 2)}," for value in item
                )
                lines.append(f"{inner}],")
            else:
                rendered_lines = rendered.splitlines()
                lines.append(f"{inner}{rendered_key}: {rendered_lines[0]}")
                lines.extend(rendered_lines[1:-1])
                lines.append(f"{rendered_lines[-1]},")
        lines.append(f"{pad}}}")
        return "\n".join(lines)
    if isinstance(value, list):
        compact = "[" + ", ".join(render_ts_value(item, indent) for item in value) + "]"
        if len("  " * indent + compact) <= 100:
            return compact
        inner = "  " * (indent + 1)
        return "[\n" + "\n".join(f"{inner}{render_ts_value(item, indent + 1)}," for item in value) + f"\n{'  ' * indent}]"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if value is None:
        return "null"
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    return str(value)


def _render_array(name: str, type_name: str, items: tuple[DashboardItem, ...]) -> list[str]:
    lines = [f"export const {name}: readonly {type_name}[] = ["]
    for item in items:
        rendered = render_ts_value(item, 1).splitlines()
        lines.append(f"  {rendered[0]}")
        lines.extend(rendered[1:])
        lines[-1] += ","
    lines.append("]")
    return lines


def render_agents_ts(data: DashboardData) -> str:
    lines = [
        "// AUTO-GENERATED by learner/substrate/dashboard_data.py.",
        "// DO NOT EDIT BY HAND — edit engines/minimaxDojo/config/dashboard.yaml and run `python3 -m learner.substrate`.",
        "",
        'import type { Agent, UserFacingAgent } from "../domain"',
        "",
        *_render_array("userFacingAgents", "UserFacingAgent", data.user_facing_agents),
        "",
        *_render_array("agents", "Agent", data.agents),
        "",
    ]
    return "\n".join(lines)


def render_cycle_ts(data: DashboardData) -> str:
    lines = [
        "// AUTO-GENERATED by learner/substrate/dashboard_data.py.",
        "// DO NOT EDIT BY HAND — edit engines/minimaxDojo/config/dashboard.yaml and run `python3 -m learner.substrate`.",
        "",
        'import type { CycleStage, Metric } from "../domain"',
        "",
        *_render_array("cycleStages", "CycleStage", data.cycle_stages),
        "",
        *_render_array("metrics", "Metric", data.metrics),
        "",
    ]
    return "\n".join(lines)
