from __future__ import annotations

import json
import re
from typing import Any


_TS_IDENTIFIER = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def _render_key(key: str) -> str:
    return key if _TS_IDENTIFIER.fullmatch(key) else json.dumps(key, ensure_ascii=False)


def render_dashboard_ts(snapshot: dict[str, Any]) -> str:
    lines: list[str] = []
    lines.append("// AUTO-GENERATED by learner/substrate/dashboard_snapshot.py.")
    lines.append("// DO NOT EDIT BY HAND — run `python3 -m learner.substrate` to regenerate.")
    lines.append("// Source: learner/learning_state.yaml + learner/learner_profile.md +")
    lines.append("//         learner/pitfalls.md + learner/journal.md + curriculum/BACKLOG_STATUS.md +")
    lines.append("//         learner/predictions.yaml")
    lines.append("")
    lines.append('import type { LearnerSnapshot } from "../domain"')
    lines.append("")
    lines.append("export const learnerSnapshot: LearnerSnapshot = " + _format_snapshot(snapshot, indent=0) + "")
    lines.append("")
    return "\n".join(lines)


# The OS engine consumes the exact same canonical learner contract.
render_codexdojo_os_ts = render_dashboard_ts


def render_mission_catalog_ts(snapshot: dict[str, Any]) -> str:
    lines = [
        "// AUTO-GENERATED by learner/substrate/mission_catalog.py.",
        "// DO NOT EDIT BY HAND — edit curriculum catalogs or OS mission bindings,",
        "// then run `python3 -m learner.substrate` to regenerate.",
        "// This catalog is read-only launch metadata; it has no canonical write or mastery API.",
        "",
        'import type { MissionCatalogSnapshot } from "../domain"',
        "",
        "export const missionCatalog: MissionCatalogSnapshot = "
        + _format_snapshot(snapshot, indent=0),
        "",
    ]
    return "\n".join(lines)


_REVIEW_SLICE_IMPORTS = {
    "pixel": '"../game/review/types"',
}
_REVIEW_SLICE_ENGINES = {
    "pixel": "pixelDojo",
}


def render_review_slice_ts(slice_dict: dict[str, Any], *, engine: str) -> str:
    engine_name = _REVIEW_SLICE_ENGINES[engine]
    import_path = _REVIEW_SLICE_IMPORTS[engine]
    lines: list[str] = []
    lines.append("// AUTO-GENERATED by learner/substrate/dashboard_snapshot.py.")
    lines.append("// DO NOT EDIT BY HAND — run `python3 -m learner.substrate` to regenerate.")
    lines.append(f"// Read-only review slice for {engine_name}: the game reads scheduling truth here,")
    lines.append("// emits evidence only, and never marks mastery (GameNeverMarksMastery).")
    lines.append("")
    lines.append(f"import type {{ ReviewSlice }} from {import_path}")
    lines.append("")
    lines.append("export const reviewSlice: ReviewSlice = " + _format_snapshot(slice_dict, indent=0) + "")
    lines.append("")
    return "\n".join(lines)


def render_pixel_review_ts(slice_dict: dict[str, Any]) -> str:
    return render_review_slice_ts(slice_dict, engine="pixel")


_REVIEW_REASON_DECL = 'export type ReviewReason = "due" | "overdue" | "interleaving" | "recurring-trap"'


def _review_slice_type_lines(*, with_game_key: bool) -> list[str]:
    """The shared ``ReviewSlice`` type declaration for voxelDojo slice files.

    ``with_game_key`` adds the ``gameId``/``unitId`` fields of the per-game
    variant. Both renderers emit from this one body so the type cannot drift
    between the legacy shared file and the per-game fan-out files.
    """
    lines = ["export type ReviewSlice = {"]
    if with_game_key:
        lines.append("  readonly gameId: string")
        lines.append("  readonly unitId: string")
    lines += [
        "  readonly nextReviews: ReadonlyArray<{",
        "    readonly unitId: string",
        "    readonly title: string",
        "    readonly dueIn: string",
        "    readonly reason: ReviewReason",
        "  }>",
        "  readonly streak: {",
        "    readonly current: number",
        "    readonly longest: number",
        "    readonly lastGateDate: string | null",
        "    readonly freezesEquipped: number",
        "    readonly freezesMax: number",
        "  }",
        "}",
    ]
    return lines


def render_voxel_review_ts(slice_dict: dict[str, Any]) -> str:
    lines: list[str] = []
    lines.append("// AUTO-GENERATED review-slice types + data (shared across all voxelDojo games).")
    lines.append("// DO NOT EDIT BY HAND — run `python3 -m learner.substrate` to regenerate.")
    lines.append("// Read-only review slice for voxelDojo: the game reads scheduling truth here,")
    lines.append("// emits evidence only, and never marks mastery (GameNeverMarksMastery).")
    lines.append("")
    lines.append(_REVIEW_REASON_DECL)
    lines.append("")
    lines.append("/**")
    lines.append(" * Read-only slice generated by the learner substrate")
    lines.append(" * (`learner/substrate/ts_render.py`, `render_voxel_review_ts`).")
    lines.append(" * voxelDojo reads scheduling truth (which unit is due, the streak counts) here")
    lines.append(" * and emits evidence only — it never marks mastery or appends to units_log")
    lines.append(" * (GameNeverMarksMastery / evidence_only). Regenerate with")
    lines.append(" * `python3 -m learner.substrate` from the repo root.")
    lines.append(" */")
    lines.extend(_review_slice_type_lines(with_game_key=False))
    lines.append("")
    lines.append("export const reviewSlice: ReviewSlice = " + _format_snapshot(slice_dict, indent=0) + "")
    lines.append("")
    return "\n".join(lines)


def render_voxel_per_game_review_ts(
    game_id: str,
    unit_id: str,
    slice_dict: dict[str, Any],
) -> str:
    """Render a per-game review slice for one voxelDojo ``game-*`` package.

    Writes ``engines/voxelDojo/<game_id>/src/reviewSlice.ts`` for each of the
    16 games. The fan-out closes the audit gap (TECH_DEBT_AUDIT_2026-07-08 #4)
    where 15/16 hand-copied stubs were falsely headed "AUTO-GENERATED" while
    only game-10 was actually synced. Each per-game file:

    - Re-declares ``ReviewReason`` and ``ReviewSlice`` so the file is
      self-contained — a game does not need to resolve the shared types to
      type-check its evidence emitter. (Shared types still exist in
      ``engines/voxelDojo/shared/content.ts`` for legacy consumers; the
      substrate keeps both in sync by regenerating from one source.)
    - Carries a ``@substrate-generated`` marker in the header so a stub
      detector can fail CI if the file is hand-edited back to a static shape.
    - Is keyed by the game's own ``unit_id``; the ``nextReviews`` array is
      filtered to that unit so the ``reason`` field actually reflects the
      FSRS-computed scheduling truth for this game's concept, never a
      hand-typed "due" or "overdue" stub.
    """
    lines: list[str] = []
    lines.append(f"// AUTO-GENERATED by learner/substrate/ts_render.py for {game_id}.")
    lines.append("// @substrate-generated — do NOT hand-edit.")
    lines.append(f"// Read-only review slice for voxelDojo game {game_id!r} (unit {unit_id!r}).")
    lines.append("// DO NOT EDIT BY HAND — run `python3 -m learner.substrate` to regenerate.")
    lines.append("// The game reads scheduling truth here and emits evidence only; it never")
    lines.append("// marks mastery or appends to units_log (GameNeverMarksMastery).")
    lines.append("// nextReviews is filtered to this game's unit by the substrate, so the")
    lines.append("// 'reason' field reflects real FSRS scheduling state, not a hand-typed stub.")
    lines.append("")
    lines.append(_REVIEW_REASON_DECL)
    lines.append("")
    lines.extend(_review_slice_type_lines(with_game_key=True))
    lines.append("")
    payload = {
        "gameId": game_id,
        "unitId": unit_id,
        "nextReviews": slice_dict.get("nextReviews", []),
        "streak": slice_dict.get("streak", {}),
    }
    lines.append("export const reviewSlice: ReviewSlice = " + _format_snapshot(payload, indent=0) + "")
    lines.append("")
    return "\n".join(lines)


def _format_snapshot(snapshot: dict[str, Any], indent: int) -> str:
    pad = "  " * indent
    inner_pad = "  " * (indent + 1)
    parts: list[str] = ["{"]
    items: list[str] = []
    for key, value in snapshot.items():
        rendered_key = _render_key(key)
        if isinstance(value, dict):
            items.append(f"{inner_pad}{rendered_key}: {_format_snapshot(value, indent + 1)},")
        elif isinstance(value, list):
            if not value:
                items.append(f"{inner_pad}{rendered_key}: [],")
                continue
            list_inner = "  " * (indent + 2)
            list_lines = [f"{list_inner}{_format_value(item, indent + 2)}," for item in value]
            items.append(
                f"{inner_pad}{rendered_key}: [\n"
                + "\n".join(list_lines)
                + f"\n{inner_pad}],"
            )
        else:
            items.append(f"{inner_pad}{rendered_key}: {_format_value(value, indent + 1)},")
    if not items:
        return "{}"
    parts.append("\n".join(items))
    parts.append(pad + "}")
    return "\n".join(parts)


def _format_value(value: Any, indent: int) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, float):
        text = f"{value:.2f}"
        if "." in text:
            whole, _, frac = text.partition(".")
            frac = frac.rstrip("0")
            text = f"{whole}.{frac}" if frac else whole
        return text
    if isinstance(value, int):
        return str(value)
    if isinstance(value, dict):
        return _format_snapshot(value, indent)
    if value is None:
        return "null"
    return json.dumps(str(value), ensure_ascii=False)
