from __future__ import annotations

import json
from datetime import datetime
from typing import Any


def render_dashboard_ts(snapshot: dict[str, Any]) -> str:
    lines: list[str] = []
    lines.append("// AUTO-GENERATED by learner/substrate/dashboard_snapshot.py.")
    lines.append("// DO NOT EDIT BY HAND — run `python3 -m learner.substrate` to regenerate.")
    lines.append("// Source: learner/learning_state.yaml + learner/learner_profile.md +")
    lines.append("//         learner/pitfalls.md + learner/journal.md + curriculum/BACKLOG_STATUS.md +")
    lines.append("//         learner/predictions.yaml")
    lines.append(f"// Generated: {datetime.now().isoformat()}Z")
    lines.append("")
    lines.append('import type { LearnerSnapshot } from "../domain"')
    lines.append("")
    lines.append("export const learnerSnapshot: LearnerSnapshot = " + _format_snapshot(snapshot, indent=0) + "")
    lines.append("")
    return "\n".join(lines)


_REVIEW_SLICE_IMPORTS = {
    "pixel": '"../game/review/types"',
    "voxel": '"./types"',
}
_REVIEW_SLICE_ENGINES = {
    "pixel": "pixelDojo",
    "voxel": "voxelDojo",
}


def render_review_slice_ts(slice_dict: dict[str, Any], *, engine: str) -> str:
    engine_name = _REVIEW_SLICE_ENGINES[engine]
    import_path = _REVIEW_SLICE_IMPORTS[engine]
    lines: list[str] = []
    lines.append("// AUTO-GENERATED by learner/substrate/dashboard_snapshot.py.")
    lines.append("// DO NOT EDIT BY HAND — run `python3 -m learner.substrate` to regenerate.")
    lines.append(f"// Read-only review slice for {engine_name}: the game reads scheduling truth here,")
    lines.append("// emits evidence only, and never marks mastery (GameNeverMarksMastery).")
    lines.append(f"// Generated: {datetime.now().isoformat()}Z")
    lines.append("")
    lines.append(f"import type {{ ReviewSlice }} from {import_path}")
    lines.append("")
    lines.append("export const reviewSlice: ReviewSlice = " + _format_snapshot(slice_dict, indent=0) + "")
    lines.append("")
    return "\n".join(lines)


def render_pixel_review_ts(slice_dict: dict[str, Any]) -> str:
    return render_review_slice_ts(slice_dict, engine="pixel")


def render_voxel_review_ts(slice_dict: dict[str, Any]) -> str:
    return render_review_slice_ts(slice_dict, engine="voxel")


def _format_snapshot(snapshot: dict[str, Any], indent: int) -> str:
    pad = "  " * indent
    inner_pad = "  " * (indent + 1)
    parts: list[str] = ["{"]
    items: list[str] = []
    for key, value in snapshot.items():
        if isinstance(value, dict):
            items.append(f"{inner_pad}{key}: {_format_snapshot(value, indent + 1)},")
        elif isinstance(value, list):
            if not value:
                items.append(f"{inner_pad}{key}: [],")
                continue
            list_inner = "  " * (indent + 2)
            list_lines = [f"{list_inner}{_format_value(item, indent + 2)}," for item in value]
            items.append(
                f"{inner_pad}{key}: [\n" + "\n".join(list_lines) + f"\n{inner_pad}],"
            )
        else:
            items.append(f"{inner_pad}{key}: {_format_value(value, indent + 1)},")
    if not items:
        return "{}"
    parts.append("\n".join(items))
    parts.append(pad + "}")
    return "\n".join(parts)


def _format_value(value: Any, indent: int) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, float):
        text = f"{value:.2f}"
        if "." in text:
            whole, _, frac = text.partition(".")
            frac = frac.rstrip("0")
            text = f"{whole}.{frac}" if frac else whole
        return text
    if isinstance(value, int):
        return str(value)
    if isinstance(value, dict):
        return _format_snapshot(value, indent)
    if value is None:
        return "null"
    return json.dumps(str(value), ensure_ascii=False)
