// AUTO-GENERATED review-slice types + data (shared across all voxelDojo games).
// DO NOT EDIT BY HAND — run `python3 -m learner.substrate` to regenerate.
// Read-only review slice for voxelDojo: the game reads scheduling truth here,
// emits evidence only, and never marks mastery (GameNeverMarksMastery).

export type ReviewReason = "due" | "overdue" | "interleaving" | "recurring-trap"

/**
 * Read-only slice generated by the learner substrate
 * (`learner/substrate/ts_render.py`, `render_voxel_review_ts`).
 * voxelDojo reads scheduling truth (which unit is due, the streak counts) here
 * and emits evidence only — it never marks mastery or appends to units_log
 * (GameNeverMarksMastery / evidence_only). Regenerate with
 * `python3 -m learner.substrate` from the repo root.
 */
export type ReviewSlice = {
  readonly nextReviews: ReadonlyArray<{
    readonly unitId: string
    readonly title: string
    readonly dueIn: string
    readonly reason: ReviewReason
  }>
  readonly streak: {
    readonly current: number
    readonly longest: number
    readonly lastGateDate: string | null
    readonly freezesEquipped: number
    readonly freezesMax: number
  }
}

export const reviewSlice: ReviewSlice = {
  nextReviews: [
    {
      unitId: "U0-sonda-rate-limiter-robustness",
      title: "GATEKEEPER: token-bucket rate limiter robustness",
      dueIn: "overdue 42d",
      reason: "overdue",
    },
    {
      unitId: "U2-key-value-store",
      title: "KV WAREHOUSE: hash-map-backed CRUD with TTL expiration",
      dueIn: "overdue 3d",
      reason: "overdue",
    },
    {
      unitId: "P-001",
      title: "Reivindicar domínio a partir de trabalho de documentação/dashboard",
      dueIn: "today",
      reason: "recurring-trap",
    },
  ],
  streak: {
    current: 0,
    longest: 2,
    lastGateDate: "2026-08-13",
    freezesEquipped: 0,
    freezesMax: 2,
  },
}
