// AUTO-GENERATED by learner/substrate/dashboard_snapshot.py.
// DO NOT EDIT BY HAND — run `python3 -m learner.substrate` to regenerate.
// Source: learner/learning_state.yaml + learner/learner_profile.md +
//         learner/pitfalls.md + learner/journal.md + curriculum/BACKLOG_STATUS.md +
//         learner/predictions.yaml

import type { LearnerSnapshot } from "../domain"

export const learnerSnapshot: LearnerSnapshot = {
  activeUnit: {
    id: "U2-key-value-store",
    title: "KV WAREHOUSE: hash-map-backed CRUD with TTL expiration",
    project: "02_key_value_store",
    state: "evaluating",
    retryCount: 0,
    retryLimit: 3,
  },
  gate: {
    implementationBlocked: false,
    unblockCondition: "learner_attempt_evaluated",
  },
  profile: {
    dreyfus: "proficient",
    bloom: "analyze",
    activeLanguage: "TypeScript",
    weeklyTimeHours: 5,
  },
  aidi: {
    current: 0.34,
    thresholdAmber: 0.6,
    thresholdRed: 0.75,
    measurementSource: "self_reported",
    trend: [],
  },
  topPitfalls: [
    {
      id: "P-001",
      description: "Reivindicar domínio a partir de trabalho de documentação/dashboard",
      occurrences: 1,
      lastSeen: "2026-06-18",
    },
  ],
  nextReviews: [
    {
      unitId: "U0-sonda-rate-limiter-robustness",
      title: "GATEKEEPER: token-bucket rate limiter robustness",
      dueIn: "overdue 10d",
      reason: "overdue",
    },
    {
      unitId: "U2-key-value-store",
      title: "KV WAREHOUSE: hash-map-backed CRUD with TTL expiration",
      dueIn: "today",
      reason: "due",
    },
    {
      unitId: "P-001",
      title: "Reivindicar domínio a partir de trabalho de documentação/dashboard",
      dueIn: "today",
      reason: "recurring-trap",
    },
  ],
  masteredCount: 2,
  scaffoldedCount: 16,
  streak: {
    current: 0,
    longest: 1,
    lastGateDate: "2026-07-05",
    freezesEquipped: 0,
    freezesMax: 2,
  },
  curr: 0,
  predictions: {
    count: 0,
    byMetric: {
      latency: {
        correct: 0,
        total: 0,
      },
      memory: {
        correct: 0,
        total: 0,
      },
      throughput: {
        correct: 0,
        total: 0,
      },
    },
  },
  challenges: [
    {
      id: "00_ai_in_practice",
      phase: "spec",
      passed: false,
      attemptPresent: false,
    },
    {
      id: "01_rate_limiter",
      phase: "spec",
      passed: false,
      attemptPresent: true,
    },
    {
      id: "02_key_value_store",
      phase: "cycle-complete",
      passed: false,
      attemptPresent: false,
    },
    {
      id: "03_url_shortener",
      phase: "cycle-complete",
      passed: false,
      attemptPresent: false,
    },
    {
      id: "04_concurrent_task_queue",
      phase: "cycle-complete",
      passed: false,
      attemptPresent: false,
    },
    {
      id: "05_websocket_chat",
      phase: "cycle-complete",
      passed: false,
      attemptPresent: false,
    },
    {
      id: "06_file_upload_pipeline",
      phase: "cycle-complete",
      passed: false,
      attemptPresent: false,
    },
    {
      id: "07_rest_api_auth",
      phase: "cycle-complete",
      passed: false,
      attemptPresent: false,
    },
    {
      id: "08_event_driven_order_system",
      phase: "cycle-complete",
      passed: false,
      attemptPresent: false,
    },
    {
      id: "09_plugin_system",
      phase: "cycle-complete",
      passed: false,
      attemptPresent: false,
    },
    {
      id: "10_distributed_cache",
      phase: "cycle-complete",
      passed: false,
      attemptPresent: false,
    },
    {
      id: "11_load_balancer",
      phase: "cycle-complete",
      passed: false,
      attemptPresent: false,
    },
    {
      id: "12_distributed_job_scheduler",
      phase: "cycle-complete",
      passed: false,
      attemptPresent: false,
    },
    {
      id: "13_api_gateway_circuit_breaker",
      phase: "cycle-complete",
      passed: false,
      attemptPresent: false,
    },
    {
      id: "14_log_aggregator",
      phase: "cycle-complete",
      passed: false,
      attemptPresent: false,
    },
    {
      id: "15_metrics_collector",
      phase: "cycle-complete",
      passed: false,
      attemptPresent: false,
    },
    {
      id: "16_mini_message_queue",
      phase: "cycle-complete",
      passed: false,
      attemptPresent: false,
    },
    {
      id: "17_distributed_config_service",
      phase: "cycle-complete",
      passed: false,
      attemptPresent: false,
    },
    {
      id: "18_search_engine",
      phase: "cycle-complete",
      passed: false,
      attemptPresent: false,
    },
  ],
}
