// AUTO-GENERATED by learner/substrate/mission_catalog.py.
// DO NOT EDIT BY HAND — edit curriculum catalogs or OS mission bindings,
// then run `python3 -m learner.substrate` to regenerate.
// This catalog is read-only launch metadata; it has no canonical write or mastery API.

import type { MissionCatalogSnapshot } from '../domain'

export const missionCatalog: MissionCatalogSnapshot = {
  schemaVersion: 1,
  contentVersion: '2026-07-25.1',
  tracks: [
    {
      id: 'ai-pratica',
      contentVersion: '2026-07-25.1',
      recommendedEntryMissionId: 'l02',
    },
    {
      id: 'dev',
      contentVersion: '2026-07-25.1',
      recommendedEntryMissionId: 'game-02-warehouse',
    },
  ],
  missions: [
    {
      id: 'l01',
      version: 1,
      trackId: 'ai-pratica',
      unitId: 'ai-literacy:l01',
      projectId: '00_ai_in_practice',
      title: 'Sua primeira conversa com uma IA',
      objective:
        'Fazer uma primeira pergunta a uma IA e interpretar a resposta como um rascunho, não como uma ordem.',
      estimatedMinutes: 3,
      chapterOrder: 1,
      prerequisites: [],
      stages: ['understand', 'respond', 'apply'],
      runtime: {
        engineId: 'literacyDojo',
        entrypoint: 'http://127.0.0.1:5178/?hosted=1',
        environmentKey: 'VITE_LITERACYDOJO_URL',
        protocolVersion: '1.0',
        contentVersion: '2026-07-25.1',
      },
      evidence: {
        schema: 'literacy-evidence',
        version: 1,
        verifierRequired: true,
      },
      fallback: {
        kind: 'dom',
        summary:
          'Conduza a primeira conversa por controles rotulados e trate a resposta como um rascunho revisavel.',
      },
    },
    {
      id: 'l02',
      version: 3,
      trackId: 'ai-pratica',
      unitId: 'ai-literacy:l02',
      projectId: '00_ai_in_practice',
      title: 'IA não é uma fonte de verdade',
      objective:
        'Diante de uma resposta convincente sem evidência, reconhecer que ela precisa ser verificada antes de ser usada no trabalho.',
      estimatedMinutes: 4,
      chapterOrder: 2,
      prerequisites: [],
      stages: ['understand', 'respond', 'apply'],
      runtime: {
        engineId: 'literacyDojo',
        entrypoint: 'http://127.0.0.1:5178/?hosted=1',
        environmentKey: 'VITE_LITERACYDOJO_URL',
        protocolVersion: '1.0',
        contentVersion: '2026-07-25.1',
      },
      evidence: {
        schema: 'literacy-evidence',
        version: 1,
        verifierRequired: true,
      },
      fallback: {
        kind: 'dom',
        summary:
          'Compare as duas respostas, escolha a mais confiavel e marque os criterios de verificacao.',
      },
    },
    {
      id: 'l03',
      version: 1,
      trackId: 'ai-pratica',
      unitId: 'ai-literacy:l03',
      projectId: '00_ai_in_practice',
      title: 'O que a IA faz bem e onde costuma falhar',
      objective:
        'Distinguir tarefas em que a IA costuma ajudar (rascunhos, resumos, ideias) de tarefas em que ela costuma falhar (dados recentes, cálculos exatos, fatos específicos).',
      estimatedMinutes: 4,
      chapterOrder: 3,
      prerequisites: ['l02'],
      stages: ['understand', 'respond', 'apply'],
      runtime: {
        engineId: 'literacyDojo',
        entrypoint: 'http://127.0.0.1:5178/?hosted=1',
        environmentKey: 'VITE_LITERACYDOJO_URL',
        protocolVersion: '1.0',
        contentVersion: '2026-07-25.1',
      },
      evidence: {
        schema: 'literacy-evidence',
        version: 1,
        verifierRequired: true,
      },
      fallback: {
        kind: 'dom',
        summary:
          'Classifique tarefas adequadas e arriscadas sem depender de cor, movimento ou ponteiro preciso.',
      },
    },
    {
      id: 'game-02-warehouse',
      version: 1,
      trackId: 'dev',
      unitId: 'U2-key-value-store',
      projectId: '02_key_value_store',
      title: 'WAREHOUSE: Key-Value Store (in-memory)',
      objective: 'Comparar mapas e dicionários sob carga concorrente e persistência simples.',
      estimatedMinutes: 12,
      chapterOrder: 1,
      prerequisites: [],
      stages: ['understand', 'respond', 'apply'],
      runtime: {
        engineId: 'voxelDojo',
        entrypoint: 'http://127.0.0.1:5202/?hosted=1',
        environmentKey: 'VITE_WAREHOUSE_URL',
        protocolVersion: '1.0',
        contentVersion: 'game-02-warehouse@0.1.0',
      },
      evidence: {
        schema: 'teaching-game-evidence',
        version: 1,
        verifierRequired: true,
      },
      fallback: {
        kind: 'dom',
        summary:
          'Preveja a prateleira de cada chave e acompanhe a mesma simulacao deterministica por controles rotulados.',
      },
    },
    {
      id: 'game-03-wormhole',
      version: 1,
      trackId: 'dev',
      unitId: 'U3-url-shortener',
      projectId: '03_url_shortener',
      title: 'WORMHOLE: URL Shortener',
      objective: 'Explorar hashing, geração de IDs e redirecionamento seguro.',
      estimatedMinutes: 12,
      chapterOrder: 2,
      prerequisites: ['game-02-warehouse'],
      stages: ['understand', 'respond', 'apply'],
      runtime: {
        engineId: 'voxelDojo',
        entrypoint: 'http://127.0.0.1:5203/?hosted=1',
        environmentKey: 'VITE_WORMHOLE_URL',
        protocolVersion: '1.0',
        contentVersion: 'game-03-wormhole@0.1.0',
      },
      evidence: {
        schema: 'teaching-game-evidence',
        version: 1,
        verifierRequired: true,
      },
      fallback: {
        kind: 'dom',
        summary:
          'Preveja codigos curtos e colisoes com os mesmos dados e criterios da simulacao visual.',
      },
    },
    {
      id: 'game-05-relay-station',
      version: 1,
      trackId: 'dev',
      unitId: 'U5-websocket-chat',
      projectId: '05_websocket_chat',
      title: 'RELAY STATION: WebSocket Chat Server',
      objective: 'Gerir conexões persistentes e broadcast em escala.',
      estimatedMinutes: 12,
      chapterOrder: 3,
      prerequisites: ['game-03-wormhole'],
      stages: ['understand', 'respond', 'apply'],
      runtime: {
        engineId: 'voxelDojo',
        entrypoint: 'http://127.0.0.1:5205/?hosted=1',
        environmentKey: 'VITE_RELAY_STATION_URL',
        protocolVersion: '1.0',
        contentVersion: 'game-05-relay-station@0.1.0',
      },
      evidence: {
        schema: 'teaching-game-evidence',
        version: 1,
        verifierRequired: true,
      },
      fallback: {
        kind: 'dom',
        summary:
          'Inspecione conexoes, fan-out e heartbeat por uma lista semantica com controles equivalentes.',
      },
    },
  ],
}
