// AUTO-GENERATED by learner/substrate/mission_catalog.py.
// DO NOT EDIT BY HAND — edit curriculum/ai-literacy or OS mission bindings,
// then run `python3 -m learner.substrate` to regenerate.
// This catalog is read-only launch metadata; it has no canonical write or mastery API.

import type { MissionCatalogSnapshot } from "../domain"

export const missionCatalog: MissionCatalogSnapshot = {
  schemaVersion: 1,
  contentVersion: "2026-07-25.1",
  missions: [
    {
      id: "l02",
      version: 3,
      trackId: "ai-pratica",
      unitId: "ai-literacy:l02",
      projectId: "00_ai_in_practice",
      title: "IA não é uma fonte de verdade",
      objective: "Diante de uma resposta convincente sem evidência, reconhecer que ela precisa ser verificada antes de ser usada no trabalho.",
      estimatedMinutes: 4,
      prerequisites: [],
      stages: [
        "understand",
        "respond",
        "apply",
      ],
      runtime: {
        engineId: "literacyDojo",
        entrypoint: "http://127.0.0.1:5178/?hosted=1",
        environmentKey: "VITE_LITERACYDOJO_URL",
        protocolVersion: "1.0",
      },
      evidence: {
        schema: "literacy-evidence",
        version: 1,
        verifierRequired: true,
      },
      fallback: {
        kind: "dom",
        summary: "Compare as duas respostas, escolha a mais confiavel e marque os criterios de verificacao.",
      },
    },
  ],
}
