from __future__ import annotations

import json
from pathlib import Path

from .catalog_rules import PUBLIC_JOURNEY
from .semantic import validate_track

GENERATED_HEADER = "// DO NOT EDIT BY HAND — generated by curriculum/ai-literacy/tools"


def _generate_skill_id_union(skills):
    """Gera a union type SkillId dinamicamente a partir das skills do catálogo."""
    ids = sorted(skill['id'] for skill in skills)
    return ' | '.join(f'"{sid}"' for sid in ids)


def _make_ts_types(skills):
    return ("""
export type SkillId = %s

export type StoragePolicy = "structured_only" | "digest_only" | "none"

export type ActivityFeedback = {
  onFailure: string
  onSuccess?: string
  perCheck?: Record<string, string>
}

type ActivityBase<T extends string, D, E> = {
  id: string
  type: T
  skillId: SkillId
  instruction: string
  data: D
  evaluation: E & { strategy: "deterministic" }
  feedback: ActivityFeedback
  storage: { policy: StoragePolicy }
  hints?: string[]
}

type LabeledItem = { id: string; text: string }

export type ChoiceActivity = ActivityBase<
  "choice",
  { prompt?: string; multiSelect?: boolean; options: LabeledItem[] },
  { correctOptionIds: string[] }
>

export type SortActivity = ActivityBase<
  "sort",
  { items: LabeledItem[] },
  { expectedOrder: string[] }
>

export type MissingContextActivity = ActivityBase<
  "missing_context",
  { prompt: string; contextOptions: LabeledItem[] },
  { requiredContextIds: string[]; optionalContextIds?: string[] }
>

export type SafetyClassificationActivity = ActivityBase<
  "safety_classification",
  { labels: { safe: string; sensitive: string }; items: LabeledItem[] },
  { classification: Record<string, "safe" | "sensitive"> }
>

export type PromptBuilderActivity = ActivityBase<
  "prompt_builder",
  {
    scenario: string
    genericPrompt: string
    fields: { id: string; label: string; hint: string }[]
  },
  {
    fields: Record<
      string,
      { minLength?: number; maxLength?: number; mustIncludeAny?: string[] }
    >
  }
>

export type OutputComparisonActivity = ActivityBase<
  "output_comparison",
  { scenario: string; outputs: LabeledItem[]; criteria: LabeledItem[] },
  { betterOutputId: string; requiredCriterionIds: string[] }
>

export type RubricReviewActivity = ActivityBase<
  "rubric_review",
  { responseText: string; criteria: LabeledItem[] },
  { expectedVerdicts: Record<string, "met" | "partial" | "not_met"> }
>

export type ActivityDefinition =
  | ChoiceActivity
  | SortActivity
  | MissingContextActivity
  | SafetyClassificationActivity
  | PromptBuilderActivity
  | OutputComparisonActivity
  | RubricReviewActivity

export type LessonRubric = {
  id: string
  criteria: { id: string; text: string; weight?: number }[]
}

export type LessonDefinition = {
  id: string
  version: number
  moduleId: string
  title: string
  objective: string
  estimatedMinutes: 3 | 4 | 5
  skillIds: SkillId[]
  prerequisites: string[]
  activities: ActivityDefinition[]
  rubric: LessonRubric
  evidence: {
    verifierRequired: true
    completionClaim: "lesson_completed" | "application_reported"
    includesFreeText: false
  }
  review: { intervalsDays: number[] }
  completion: { minimumScore: number; requiredActivityIds: string[] }
}

export type CatalogLessonEntry = {
  id: string
  moduleId: string
  title: string
  estimatedMinutes: 3 | 4 | 5
  prerequisites: string[]
  skillIds: SkillId[]
  status: "planned" | "ready"
  /** true quando a lição tem arquivo validado e entra no read model (`lessons`). */
  hasContent: boolean
}

export type ModuleDefinition = {
  id: string
  slug: string
  title: string
  order: number
  journey: "ia_pratica" | "dev"
  skillIds: SkillId[]
  lessons: CatalogLessonEntry[]
}

export type SkillDefinition = { id: SkillId; title: string; description: string }

export type Track = {
  id: string
  title: string
  audience: string
  promise: string
  language: string
}
""" % _generate_skill_id_union(skills)).lstrip("\n")


# AID-3569 (Fase 1 do contrato AID-3514, §6.1): tipos de competência emitidos
# SOMENTE no opt-in (`--with-competency`). Sem a flag o bloco de tipos legado
# permanece byte-idêntico — nenhum identificador `competency` é declarado.
COMPETENCY_TYPE_BLOCK = """export type CompetencyId =
  | "F1" | "F2" | "F3" | "F4"
  | "D1" | "D2" | "D3" | "D4" | "D5" | "D6" | "D7"

export type LessonCompetency = {
  primary: CompetencyId
  supporting: CompetencyId[]
}

"""


def _with_competency_types(ts_types):
    """Injeta as declarações opcionais de competência (CompetencyId,
    LessonCompetency, `competency?` em LessonDefinition e CatalogLessonEntry)
    no bloco de tipos legado. Âncoras exatas; sem reordenação: o campo entra
    após `skillIds`, como especificado no §6.1 do contrato."""
    lesson_def_anchor = "export type LessonDefinition = {"
    ts_types = ts_types.replace(
        lesson_def_anchor, COMPETENCY_TYPE_BLOCK + lesson_def_anchor, 1
    )
    ts_types = ts_types.replace(
        "  skillIds: SkillId[]\n  prerequisites: string[]\n",
        '  skillIds: SkillId[]\n'
        '  /** Opcional — ausência = "não mapeada" (default; AID-3514). */\n'
        "  competency?: LessonCompetency\n"
        "  prerequisites: string[]\n",
        1,
    )
    ts_types = ts_types.replace(
        "  skillIds: SkillId[]\n  status:",
        "  skillIds: SkillId[]\n  competency?: LessonCompetency\n  status:",
        1,
    )
    return ts_types


def _lesson_payload(lesson, include_competency):
    """AID-3569 (Fase 1, §6.1): propaga a chave opcional `competency`
    SOMENTE no opt-in. Sem a flag o strip legado (AID-3457) permanece e o
    read model é byte-idêntico; com a flag a posição da chave preserva a
    ordem documental do YAML canônico (entre `prerequisites` e
    `activities`) — o compilador não reordena."""
    if include_competency:
        return dict(lesson)
    return {key: value for key, value in lesson.items() if key != "competency"}


def _catalog_entries(catalog, ready_lessons, module_ids, include_competency=False):
    ready_by_id = {lesson["id"]: lesson for lesson in ready_lessons}
    entries = []
    for entry in catalog.get("lessons") or []:
        if entry["moduleId"] not in module_ids:
            continue
        has_content = entry["id"] in ready_by_id
        # AID-3569 (Fase 1, §6.1): join do catálogo — 9ª chave opcional
        # `competency` APENAS no opt-in, apenas em entradas hasContent cuja
        # lição ready está mapeada; ausente, as 8 chaves legadas e a ordem
        # permanecem exatas (entradas planned nunca ganham o campo).
        competency = (
            ready_by_id[entry["id"]].get("competency")
            if include_competency and has_content
            else None
        )
        payload = {
            "id": entry["id"],
            "moduleId": entry["moduleId"],
            "title": entry["title"],
            "estimatedMinutes": entry["estimatedMinutes"],
            "prerequisites": entry.get("prerequisites") or [],
            "skillIds": entry.get("skillIds") or [],
        }
        if competency is not None:
            payload["competency"] = competency
        payload["status"] = entry["status"]
        payload["hasContent"] = has_content
        entries.append(payload)
    return entries


def _modules_payload(modules, entries):
    modules_payload = []
    for module in sorted(modules, key=lambda item: item.get("order", 0)):
        modules_payload.append(
            {
                "id": module["id"],
                "slug": module["slug"],
                "title": module["title"],
                "order": module["order"],
                "journey": module["journey"],
                "skillIds": module.get("skillIds") or [],
                "lessons": [entry for entry in entries if entry["moduleId"] == module["id"]],
            }
        )
    return modules_payload


def _as_ts(payload):
    return json.dumps(payload, ensure_ascii=False, indent=2)


def _render_content(catalog, ready_lessons, include_competency=False):
    journey_module_ids = {
        module["id"] for module in catalog.get("modules") or []
    }
    ready_lessons_all = [
        lesson for lesson in ready_lessons if lesson["moduleId"] in journey_module_ids
    ]
    # AID-3457 (scaffolding de schema) + AID-3569 (Fase 1 do contrato
    # AID-3514 §6.1/§7): o campo opcional `competency` só alcança o read
    # model no opt-in (`--with-competency`, default OFF). Sem a flag a saída
    # permanece byte-idêntica ao legado com ou sem o metadado no YAML
    # (testemunhado por test_compatibility em
    # tools/tests/test_competency_field_contract.py e pela suíte de inércia
    # de metadados ratificados). Consumo de runtime é Fase 2 (LAE).
    lessons_payload = [
        _lesson_payload(lesson, include_competency)
        for lesson in ready_lessons_all
    ]
    entries = _catalog_entries(
        catalog, ready_lessons_all, journey_module_ids, include_competency
    )
    modules_payload = _modules_payload(catalog.get("modules") or [], entries)
    track_payload = {key: catalog["track"][key] for key in ("id", "title", "audience", "promise", "language")}
    skills_payload = [
        {"id": skill["id"], "title": skill["title"], "description": skill["description"]}
        for skill in catalog.get("skills") or []
    ]
    ts_types = _make_ts_types(skills_payload)
    if include_competency:
        ts_types = _with_competency_types(ts_types)
    regen_hint = (
        "// Regenere com: python3 curriculum/ai-literacy/tools/validate.py"
        " --compile <outdir> --with-competency\n"
        if include_competency
        else "// Regenere com: python3 curriculum/ai-literacy/tools/validate.py --compile <outdir>\n"
    )

    content = (
        GENERATED_HEADER
        + "\n// Read model de lições validadas das duas jornadas (ia_pratica e dev).\n"
        + "// O percurso público do app standalone filtra por journey no adapter;\n"
        + "// missões hospedadas do OS podem servir lições dev (ver content-contract.md).\n"
        + "// Fonte canônica: curriculum/ai-literacy/.\n"
        + regen_hint
        + "\n"
        + ts_types
        + "\nexport const contentVersion: string = "
        + json.dumps(str(catalog.get("contentVersion")), ensure_ascii=False)
        + "\n\nexport const track: Track = "
        + _as_ts(track_payload)
        + "\n\nexport const modules: ModuleDefinition[] = "
        + _as_ts(modules_payload)
        + "\n\nexport const skills: SkillDefinition[] = "
        + _as_ts(skills_payload)
        + "\n\nexport const lessons: LessonDefinition[] = "
        + _as_ts(lessons_payload)
        + "\n"
    )
    return content


VERIFIER_CORPUS_FILENAME = "literacy-corpus.mjs"


def _verifier_corpus_payload(ready_lessons):
    """Projeção mínima por lição: exatamente os campos que o verificador
    independente lê (learner/gate/literacy_evaluator.py). Nada de texto de
    instrução/feedback/hints entra no trust boundary hospedado."""

    def activity_payload(activity):
        return {
            "id": activity["id"],
            "type": activity["type"],
            "data": activity["data"],
            "evaluation": activity["evaluation"],
        }

    corpus = {}
    for lesson in sorted(ready_lessons, key=lambda item: item["id"]):
        corpus[lesson["id"]] = {
            "version": lesson["version"],
            "skillIds": lesson["skillIds"],
            "activities": [activity_payload(a) for a in lesson["activities"]],
        }
    return corpus


def _render_verifier_corpus(catalog, ready_lessons):
    payload = _verifier_corpus_payload(ready_lessons)
    return (
        GENERATED_HEADER
        + "\n// Verifier corpus for the staged literacy bridge (AID-449): the exact\n"
        + "// lesson/activity facts the canonical Python verifier reads from\n"
        + "// curriculum/ai-literacy/. Do not add producer-facing fields here.\n"
        + "// Canonical evaluator: learner/gate/literacy_evaluator.py.\n"
        + "// Regenere com: python3 curriculum/ai-literacy/tools/validate.py --compile-verifier <outdir>\n\n"
        + "export const literacyCorpus = "
        + json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True)
        + "\n\nexport const literacyCorpusVersion = "
        + json.dumps(str(catalog.get("contentVersion")), ensure_ascii=False)
        + "\n"
    )


def compile_verifier_corpus(track_dir, outdir, validated=None):
    """Compila o corpus do verificador hospedado. Retorna (errors, output_path).

    validated: tupla já computada de validate_track(track_dir), para não revalidar.

    AID-449/AID-3569: fronteira de confiança — este corpus NUNCA recebe
    `competency` (nem qualquer campo producer-facing), com ou sem a flag
    `--with-competency` (pinado por test_competency_read_seam.py e
    test_competency_optin_flag.py). Não existe parâmetro de propagação aqui
    de propósito.
    """
    errors, ready_lessons, catalog = (
        validated if validated is not None else validate_track(track_dir)
    )
    if errors:
        return errors, None
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    out_path = outdir / VERIFIER_CORPUS_FILENAME
    out_path.write_text(_render_verifier_corpus(catalog, ready_lessons), encoding="utf-8")
    return [], out_path


def compile_track(track_dir, outdir, validated=None, include_competency=False):
    """Compila as lições válidas para o read model tipado. Retorna (errors, output_path).

    validated: tupla já computada de validate_track(track_dir), para não revalidar a trilha.
    include_competency: AID-3569 (Fase 1 do contrato AID-3514 §7) — propaga a
        chave opcional `competency` (tipos + payload + join do catálogo).
        Default False: saída byte-idêntica ao legado.
    """
    errors, ready_lessons, catalog = validated if validated is not None else validate_track(track_dir)
    if errors:
        return errors, None
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    out_path = outdir / "lessons.ts"
    out_path.write_text(
        _render_content(catalog, ready_lessons, include_competency), encoding="utf-8"
    )
    return [], out_path
