from __future__ import annotations

import json
from pathlib import Path

from .semantic import validate_track

GENERATED_HEADER = "// DO NOT EDIT BY HAND — generated by curriculum/ai-literacy/tools"

COMPETENCY_MAP_FILENAME = "competency-map.ts"
COMPETENCY_MAP_VERSION = 1

# Glossário canônico de competências (spec AID-3453 R1/R2 @579ce995):
# IDs estáveis (F* fundamentos, D* dev) com público-alvo. O enum é espelhado
# em schemas/lesson.schema.json; o drift entre as duas fontes falha fechado em
# tools/tests/test_competency_read_model_contract.py. `aliases` existe para
# que renomeações futuras de título NUNCA mudem IDs vistos pelas lições.
GLOSSARY = [
    {"id": "F1", "domain": "fundamentos", "audience": "cotidiano", "title": "Entender IA", "aliases": []},
    {"id": "F2", "domain": "fundamentos", "audience": "cotidiano", "title": "Uso seguro", "aliases": []},
    {"id": "F3", "domain": "fundamentos", "audience": "cotidiano", "title": "Prompt e contexto", "aliases": []},
    {"id": "F4", "domain": "fundamentos", "audience": "cotidiano", "title": "Verificação", "aliases": []},
    {"id": "D1", "domain": "dev", "audience": "dev", "title": "Fundamentos e harness", "aliases": []},
    {"id": "D2", "domain": "dev", "audience": "dev", "title": "Intenção, spec e plano", "aliases": []},
    {"id": "D3", "domain": "dev", "audience": "dev", "title": "Construção", "aliases": []},
    {"id": "D4", "domain": "dev", "audience": "dev", "title": "Teste, debug, review e manutenção", "aliases": []},
    {"id": "D5", "domain": "dev", "audience": "dev", "title": "Produto de IA e evals", "aliases": []},
    {"id": "D6", "domain": "dev", "audience": "dev", "title": "Agentes, tools e skills", "aliases": []},
    {"id": "D7", "domain": "dev", "audience": "dev", "title": "Capstone escolhido", "aliases": []},
]

_GLOSSARY_IDS = {entry["id"] for entry in GLOSSARY}


def _mapping(competency):
    """Projeta o objeto canônico `competency` (primary + supporting[]) no
    formato do read model. IDs fora do glossário já foram rejeitados pela
    validação de schema antes de chegar aqui (fail closed upstream)."""
    if competency is None:
        return None
    primary = competency["primary"]
    supporting = list(competency.get("supporting") or [])
    assert primary in _GLOSSARY_IDS, "primary fora do glossário: %r" % primary
    for supporting_id in supporting:
        assert supporting_id in _GLOSSARY_IDS, "supporting fora do glossário: %r" % supporting_id
    return {"primary": primary, "supporting": supporting}


def _lesson_entry(lesson, journey_by_module, order_by_module):
    return {
        "lessonId": lesson["id"],
        "moduleId": lesson["moduleId"],
        "journey": journey_by_module[lesson["moduleId"]],
        "order": order_by_module[lesson["moduleId"]],
        "prerequisites": list(lesson.get("prerequisites") or []),
        "mapping": _mapping(lesson.get("competency")),
    }


def _competency_payload(catalog, ready_lessons):
    """Ordenação documental idêntica ao read model de lições: módulos por
    `order` crescente e lições na ordem do catálogo dentro do módulo. Apenas
    lições ready (com arquivo validado) entram — planned continua fora, como
    em lessons.ts. O filtro de jornada NÃO é aplicado aqui (decisão AID-3453
    R6: visibilidade permanece no adaptador consumidor)."""
    modules = sorted(catalog.get("modules") or [], key=lambda module: module.get("order", 0))
    journey_by_module = {module["id"]: module["journey"] for module in modules}
    order_by_module = {module["id"]: module.get("order", 0) for module in modules}
    ready_by_id = {lesson["id"]: lesson for lesson in ready_lessons}
    entries = []
    for module in modules:
        for entry in catalog.get("lessons") or []:
            if entry["moduleId"] != module["id"]:
                continue
            lesson = ready_by_id.get(entry["id"])
            if lesson is None:
                continue
            entries.append(_lesson_entry(lesson, journey_by_module, order_by_module))
    return entries


def _as_ts(payload):
    return json.dumps(payload, ensure_ascii=False, indent=2)


def _render_competency_map(catalog, ready_lessons):
    glossary_ids = sorted(_GLOSSARY_IDS)
    competency_id_union = " | ".join('"%s"' % glossary_id for glossary_id in glossary_ids)
    entries = _competency_payload(catalog, ready_lessons)
    return (
        GENERATED_HEADER
        + "\n// Read model OPCIONAL de competências (spec AID-3514; fila AID-3525 r2, fatia S5).\n"
        + "// Projeção pontual do currículo compartilhado (curriculum/ai-literacy/):\n"
        + "// mapeamento lição → competência (primary + supporting[]) com defaults\n"
        + "// compatíveis — ausência de atribuição = mapping null (\"não mapeada\").\n"
        + "// Este artefato NÃO substitui lessons.ts e consumidores atuais não precisam\n"
        + "// importá-lo: geração por flag opt-in (--compile-competency), arquivo separado.\n"
        + "// Sem sincronia entre engines: cada consumidor compila a sua cópia e pinna\n"
        + "// o contentVersion; nenhuma promessa de consistência em tempo real.\n"
        + "// Contrato completo: docs/curriculum/competency-read-model.md\n"
        + "// Regenere com: python3 curriculum/ai-literacy/tools/validate.py --compile-competency <outdir>\n\n"
        + "export type CompetencyId = %s\n\n"
        % competency_id_union
        + "export type CompetencyGlossaryEntry = {\n"
        + "  id: CompetencyId\n"
        + "  domain: \"fundamentos\" | \"dev\"\n"
        + "  audience: \"cotidiano\" | \"dev\" | \"ambos\"\n"
        + "  title: string\n"
        + "  /** Apelidos estáveis para busca/legado — renomear título nunca muda o id. */\n"
        + "  aliases: string[]\n"
        + "}\n\n"
        + "export type CompetencyMapping = {\n"
        + "  primary: CompetencyId\n"
        + "  supporting: CompetencyId[]\n"
        + "}\n\n"
        + "export type CompetencyLessonEntry = {\n"
        + "  lessonId: string\n"
        + "  moduleId: string\n"
        + "  journey: \"ia_pratica\" | \"dev\"\n"
        + "  /** Ordem documental do módulo (visibilidade continua no adaptador). */\n"
        + "  order: number\n"
        + "  prerequisites: string[]\n"
        + "  /** null = \"não mapeada\" (default real) — ausência de atribuição, não erro. */\n"
        + "  mapping: CompetencyMapping | null\n"
        + "}\n\n"
        + "export const competencyMapVersion: number = %d\n\n"
        % COMPETENCY_MAP_VERSION
        + "export const competencyMapContentVersion: string = "
        + json.dumps(str(catalog.get("contentVersion")), ensure_ascii=False)
        + "\n\n"
        + "export const competencyGlossary: CompetencyGlossaryEntry[] = "
        + _as_ts(GLOSSARY)
        + "\n\n"
        + "export const competencyLessons: CompetencyLessonEntry[] = "
        + _as_ts(entries)
        + "\n\n"
        + "/** Contrato sem atainment (spec AID-3514 / AID-3453 R9): este artefato\n"
        + " *  NÃO carrega estados de aprendiz. `completed` (teto do produtor na UI),\n"
        + " *  `pass` (recibo PASS do verificador independente), `simulação` (recibos de\n"
        + " *  harness/piloto) e `mastered` (reservado ao gate) continuam propriedade dos\n"
        + " *  domínios de progresso de cada engine. Ler competências nunca altera\n"
        + " *  progresso e nada aqui promove aprendiz a mastered. */\n"
        + "export const carriesAttainment = false as const\n\n"
        + "export const producerWritesMastered = false as const\n"
    )


def compile_competency_map(track_dir, outdir, validated=None):
    """Compila o read model opcional de competências. Retorna (errors, output_path).

    Fail closed: só gera artefato com validação verde (schema + semântica);
    qualquer erro devolve os erros e nenhum arquivo é escrito. `validated` é
    a tupla já computada de validate_track(track_dir), para não revalidar.
    """
    errors, ready_lessons, catalog = (
        validated if validated is not None else validate_track(track_dir)
    )
    if errors:
        return errors, None
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    out_path = outdir / COMPETENCY_MAP_FILENAME
    out_path.write_text(_render_competency_map(catalog, ready_lessons), encoding="utf-8")
    return [], out_path
