from __future__ import annotations

import json
from pathlib import Path

from .semantic import validate_track

GENERATED_HEADER = "// DO NOT EDIT BY HAND — generated by curriculum/ai-literacy/tools"
PUBLIC_JOURNEY = "ia_pratica"


def _generate_skill_id_union(skills):
    """Gera a union type SkillId dinamicamente a partir das skills do catálogo."""
    ids = sorted(skill['id'] for skill in skills)
    return ' | '.join(f'"{sid}"' for sid in ids)


def _make_ts_types(skills):
    return ("""
export type SkillId = %s

export type StoragePolicy = "structured_only" | "digest_only" | "none"

export type ActivityFeedback = {
  onFailure: string
  onSuccess?: string
  perCheck?: Record<string, string>
}

type ActivityBase<T extends string, D, E> = {
  id: string
  type: T
  skillId: SkillId
  instruction: string
  data: D
  evaluation: E & { strategy: "deterministic" }
  feedback: ActivityFeedback
  storage: { policy: StoragePolicy }
  hints?: string[]
}

type LabeledItem = { id: string; text: string }

export type ChoiceActivity = ActivityBase<
  "choice",
  { prompt?: string; multiSelect?: boolean; options: LabeledItem[] },
  { correctOptionIds: string[] }
>

export type SortActivity = ActivityBase<
  "sort",
  { items: LabeledItem[] },
  { expectedOrder: string[] }
>

export type MissingContextActivity = ActivityBase<
  "missing_context",
  { prompt: string; contextOptions: LabeledItem[] },
  { requiredContextIds: string[]; optionalContextIds?: string[] }
>

export type SafetyClassificationActivity = ActivityBase<
  "safety_classification",
  { labels: { safe: string; sensitive: string }; items: LabeledItem[] },
  { classification: Record<string, "safe" | "sensitive"> }
>

export type PromptBuilderActivity = ActivityBase<
  "prompt_builder",
  {
    scenario: string
    genericPrompt: string
    fields: { id: string; label: string; hint: string }[]
  },
  {
    fields: Record<
      string,
      { minLength?: number; maxLength?: number; mustIncludeAny?: string[] }
    >
  }
>

export type OutputComparisonActivity = ActivityBase<
  "output_comparison",
  { scenario: string; outputs: LabeledItem[]; criteria: LabeledItem[] },
  { betterOutputId: string; requiredCriterionIds: string[] }
>

export type RubricReviewActivity = ActivityBase<
  "rubric_review",
  { responseText: string; criteria: LabeledItem[] },
  { expectedVerdicts: Record<string, "met" | "partial" | "not_met"> }
>

export type ActivityDefinition =
  | ChoiceActivity
  | SortActivity
  | MissingContextActivity
  | SafetyClassificationActivity
  | PromptBuilderActivity
  | OutputComparisonActivity
  | RubricReviewActivity

export type LessonRubric = {
  id: string
  criteria: { id: string; text: string; weight?: number }[]
}

export type LessonDefinition = {
  id: string
  version: number
  moduleId: string
  title: string
  objective: string
  estimatedMinutes: 3 | 4 | 5
  skillIds: SkillId[]
  prerequisites: string[]
  activities: ActivityDefinition[]
  rubric: LessonRubric
  evidence: {
    verifierRequired: true
    completionClaim: "lesson_completed" | "application_reported"
    includesFreeText: false
  }
  review: { intervalsDays: number[] }
  completion: { minimumScore: number; requiredActivityIds: string[] }
}

export type CatalogLessonEntry = {
  id: string
  moduleId: string
  title: string
  estimatedMinutes: 3 | 4 | 5
  prerequisites: string[]
  skillIds: SkillId[]
  status: "planned" | "ready"
  /** true quando a lição tem arquivo validado e entra no read model (`lessons`). */
  hasContent: boolean
}

export type ModuleDefinition = {
  id: string
  slug: string
  title: string
  order: number
  journey: "ia_pratica" | "dev"
  skillIds: SkillId[]
  lessons: CatalogLessonEntry[]
}

export type SkillDefinition = { id: SkillId; title: string; description: string }

export type Track = {
  id: string
  title: string
  audience: string
  promise: string
  language: string
}
""" % _generate_skill_id_union(skills)).lstrip("\n")


def _catalog_entries(catalog, ready_lessons, module_ids):
    ready_ids = {lesson["id"] for lesson in ready_lessons}
    entries = []
    for entry in catalog.get("lessons") or []:
        if entry["moduleId"] not in module_ids:
            continue
        entries.append(
            {
                "id": entry["id"],
                "moduleId": entry["moduleId"],
                "title": entry["title"],
                "estimatedMinutes": entry["estimatedMinutes"],
                "prerequisites": entry.get("prerequisites") or [],
                "skillIds": entry.get("skillIds") or [],
                "status": entry["status"],
                "hasContent": entry["id"] in ready_ids,
            }
        )
    return entries


def _modules_payload(modules, entries):
    modules_payload = []
    for module in sorted(modules, key=lambda item: item.get("order", 0)):
        modules_payload.append(
            {
                "id": module["id"],
                "slug": module["slug"],
                "title": module["title"],
                "order": module["order"],
                "journey": module["journey"],
                "skillIds": module.get("skillIds") or [],
                "lessons": [entry for entry in entries if entry["moduleId"] == module["id"]],
            }
        )
    return modules_payload


def _as_ts(payload):
    return json.dumps(payload, ensure_ascii=False, indent=2)


def _render_content(catalog, ready_lessons):
    journey_module_ids = {
        module["id"] for module in catalog.get("modules") or []
    }
    ready_lessons_all = [
        lesson for lesson in ready_lessons if lesson["moduleId"] in journey_module_ids
    ]
    entries = _catalog_entries(catalog, ready_lessons_all, journey_module_ids)
    modules_payload = _modules_payload(catalog.get("modules") or [], entries)
    track_payload = {key: catalog["track"][key] for key in ("id", "title", "audience", "promise", "language")}
    skills_payload = [
        {"id": skill["id"], "title": skill["title"], "description": skill["description"]}
        for skill in catalog.get("skills") or []
    ]
    ts_types = _make_ts_types(skills_payload)

    content = (
        GENERATED_HEADER
        + "\n// Read model de lições validadas das duas jornadas (ia_pratica e dev).\n"
        + "// O percurso público do app standalone filtra por journey no adapter;\n"
        + "// missões hospedadas do OS podem servir lições dev (ver content-contract.md).\n"
        + "// Fonte canônica: curriculum/ai-literacy/.\n"
        + "// Regenere com: python3 curriculum/ai-literacy/tools/validate.py --compile <outdir>\n\n"
        + ts_types
        + "\nexport const contentVersion: string = "
        + json.dumps(str(catalog.get("contentVersion")), ensure_ascii=False)
        + "\n\nexport const track: Track = "
        + _as_ts(track_payload)
        + "\n\nexport const modules: ModuleDefinition[] = "
        + _as_ts(modules_payload)
        + "\n\nexport const skills: SkillDefinition[] = "
        + _as_ts(skills_payload)
        + "\n\nexport const lessons: LessonDefinition[] = "
        + _as_ts(ready_lessons_all)
        + "\n"
    )
    return content


def compile_track(track_dir, outdir, validated=None):
    """Compila as lições válidas para o read model tipado. Retorna (errors, output_path).

    validated: tupla já computada de validate_track(track_dir), para não revalidar a trilha.
    """
    errors, ready_lessons, catalog = validated if validated is not None else validate_track(track_dir)
    if errors:
        return errors, None
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    out_path = outdir / "lessons.ts"
    out_path.write_text(_render_content(catalog, ready_lessons), encoding="utf-8")
    return [], out_path
