#!/usr/bin/env python3
"""Validador e compilador de conteúdo da trilha ai-literacy.

Uso (a partir da raiz do repositório):

    python3 curriculum/ai-literacy/tools/validate.py
    python3 curriculum/ai-literacy/tools/validate.py --compile <outdir>

O validador falha com exit code 1 e mensagens claras quando o conteúdo é
inválido — não existe fallback silencioso. O modo --compile gera o read model
tipado TypeScript (lessons.ts) consumido pelo engine literacyDojo; o arquivo
gerado carrega o cabeçalho "DO NOT EDIT BY HAND".

Dependências: stdlib + pyyaml (já declarada em pyproject.toml). A validação de
schema usa um validador mínimo próprio (o repositório não depende do pacote
``jsonschema``); o subconjunto suportado cobre exatamente os schemas em
curriculum/ai-literacy/schemas/.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import yaml

TRACK_DIR = Path(__file__).resolve().parent.parent
SCHEMAS_DIR = TRACK_DIR / "schemas"
GENERATED_HEADER = "// DO NOT EDIT BY HAND — generated by curriculum/ai-literacy/tools"

VALID_STATUSES = ("planned", "ready")
VALID_DURATIONS = (3, 4, 5)


# ---------------------------------------------------------------------------
# Validador mínimo de JSON Schema (subconjunto usado pelos schemas da trilha)
# ---------------------------------------------------------------------------


class SchemaResolver:
    """Carrega e resolve $refs locais ("#/...") e relativos a arquivo ("x.json", "x.json#/...")."""

    def __init__(self, schemas_dir):
        self.schemas_dir = Path(schemas_dir)
        self._cache = {}

    def load(self, name):
        if name not in self._cache:
            path = self.schemas_dir / name
            if not path.is_file():
                raise ValueError("schema referenciado não existe: %s" % name)
            self._cache[name] = json.loads(path.read_text(encoding="utf-8"))
        return self._cache[name]

    def resolve(self, ref, current_file):
        if ref.startswith("#"):
            target_file, pointer = current_file, ref[1:]
        elif "#" in ref:
            target_file, pointer = ref.split("#", 1)
        else:
            target_file, pointer = ref, ""
        schema = self.load(target_file)
        if pointer:
            for raw_part in pointer.strip("/").split("/"):
                part = raw_part.replace("~1", "/").replace("~0", "~")
                if not isinstance(schema, dict) or part not in schema:
                    raise ValueError("$ref inválida %s em %s" % (ref, current_file))
                schema = schema[part]
        return schema, target_file


def _is_integer(value):
    return isinstance(value, int) and not isinstance(value, bool)


def _is_number(value):
    return (isinstance(value, (int, float)) and not isinstance(value, bool))


def _type_matches(instance, expected):
    if expected == "object":
        return isinstance(instance, dict)
    if expected == "array":
        return isinstance(instance, list)
    if expected == "string":
        return isinstance(instance, str)
    if expected == "integer":
        return _is_integer(instance)
    if expected == "number":
        return _is_number(instance)
    if expected == "boolean":
        return isinstance(instance, bool)
    if expected == "null":
        return instance is None
    return False


def _validate(instance, schema, current_file, resolver, path, errors):
    if not isinstance(schema, dict):
        errors.append("%s: schema inválido (não é objeto) em %s" % (current_file, path))
        return

    if "$ref" in schema:
        target, target_file = resolver.resolve(schema["$ref"], current_file)
        _validate(instance, target, target_file, resolver, path, errors)
        return

    if "const" in schema and instance != schema["const"]:
        errors.append("%s: %s deve ser %r (encontrado %r)" % (current_file, path, schema["const"], instance))
        return

    if "enum" in schema and instance not in schema["enum"]:
        errors.append("%s: %s deve ser um de %r (encontrado %r)" % (current_file, path, schema["enum"], instance))
        return

    if "type" in schema and not _type_matches(instance, schema["type"]):
        errors.append("%s: %s deve ser do tipo %s (encontrado %s)" % (current_file, path, schema["type"], type(instance).__name__))
        return

    if "oneOf" in schema or "anyOf" in schema or "allOf" in schema:
        if "allOf" in schema:
            for i, sub in enumerate(schema["allOf"]):
                _validate(instance, sub, current_file, resolver, "%s(allOf[%d])" % (path, i), errors)
        for keyword, exactly_one in (("oneOf", True), ("anyOf", False)):
            if keyword not in schema:
                continue
            matches = 0
            collected = []
            for sub in schema[keyword]:
                sub_errors = []
                _validate(instance, sub, current_file, resolver, path, sub_errors)
                if not sub_errors:
                    matches += 1
                else:
                    collected.append(sub_errors)
            if exactly_one and matches != 1:
                errors.append("%s: %s deve corresponder a exatamente uma variante (%s); %d corresponderam" % (current_file, path, keyword, matches))
                if matches == 0 and collected:
                    closest = min(collected, key=len)
                    errors.append("%s: %s variante mais próxima falhou com: %s" % (current_file, path, "; ".join(closest[:3])))
            elif not exactly_one and matches == 0:
                detail = collected[0][0] if collected and collected[0] else "nenhuma variante correspondeu"
                errors.append("%s: %s não corresponde a nenhuma variante (%s): %s" % (current_file, path, keyword, detail))

    if isinstance(instance, dict):
        for key in schema.get("required", []):
            if key not in instance:
                errors.append("%s: %s.%s é obrigatório e está ausente" % (current_file, path, key))
        properties = schema.get("properties", {})
        additional = schema.get("additionalProperties", True)
        for key, value in instance.items():
            child_path = "%s.%s" % (path, key)
            if key in properties:
                _validate(value, properties[key], current_file, resolver, child_path, errors)
            elif additional is False:
                errors.append("%s: %s não é uma propriedade permitida" % (current_file, child_path))
            elif isinstance(additional, dict):
                _validate(value, additional, current_file, resolver, child_path, errors)
        if "minProperties" in schema and len(instance) < schema["minProperties"]:
            errors.append("%s: %s deve ter ao menos %d propriedade(s)" % (current_file, path, schema["minProperties"]))

    if isinstance(instance, list):
        if "minItems" in schema and len(instance) < schema["minItems"]:
            errors.append("%s: %s deve ter ao menos %d item(ns)" % (current_file, path, schema["minItems"]))
        if "maxItems" in schema and len(instance) > schema["maxItems"]:
            errors.append("%s: %s deve ter no máximo %d item(ns)" % (current_file, path, schema["maxItems"]))
        if "items" in schema:
            for i, item in enumerate(instance):
                _validate(item, schema["items"], current_file, resolver, "%s[%d]" % (path, i), errors)

    if isinstance(instance, str):
        if "minLength" in schema and len(instance) < schema["minLength"]:
            errors.append("%s: %s deve ter ao menos %d caractere(s)" % (current_file, path, schema["minLength"]))
        if "maxLength" in schema and len(instance) > schema["maxLength"]:
            errors.append("%s: %s deve ter no máximo %d caractere(s)" % (current_file, path, schema["maxLength"]))
        if "pattern" in schema and not re.search(schema["pattern"], instance):
            errors.append("%s: %s não corresponde ao padrão %s (encontrado %r)" % (current_file, path, schema["pattern"], instance))

    if _is_number(instance):
        if "minimum" in schema and instance < schema["minimum"]:
            errors.append("%s: %s deve ser >= %s (encontrado %s)" % (current_file, path, schema["minimum"], instance))
        if "maximum" in schema and instance > schema["maximum"]:
            errors.append("%s: %s deve ser <= %s (encontrado %s)" % (current_file, path, schema["maximum"], instance))


def validate_against_schema(instance, schema_name, resolver):
    """Retorna lista de erros de schema para ``instance`` contra ``schema_name``."""
    errors = []
    _validate(instance, resolver.load(schema_name), schema_name, resolver, "$", errors)
    return errors


# ---------------------------------------------------------------------------
# Validação semântica da trilha (catálogo + lições)
# ---------------------------------------------------------------------------


def _load_yaml(path, errors):
    try:
        return yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        errors.append("%s: YAML inválido: %s" % (path, exc))
        return None


def _check_catalog_shape(catalog, errors):
    """Integridade estrutural do catalog.yaml (índice canônico da trilha)."""
    prefix = "catalog.yaml"
    if not isinstance(catalog, dict):
        errors.append("%s: catálogo deve ser um objeto YAML" % prefix)
        return None
    for key in ("schemaVersion", "contentVersion", "track", "skills", "modules", "lessons"):
        if key not in catalog:
            errors.append("%s: chave obrigatória ausente: %s" % (prefix, key))
    if errors:
        return None
    return catalog


def _index_by_id(items, what, errors):
    index = {}
    for item in items or []:
        item_id = item.get("id") if isinstance(item, dict) else None
        if not item_id:
            errors.append("catalog.yaml: %s sem id" % what)
            continue
        if item_id in index:
            errors.append("catalog.yaml: id de %s duplicado: %s" % (what, item_id))
        index[item_id] = item
    return index


def _detect_prereq_cycles(lesson_index, errors):
    """Detecta ciclos no grafo de pré-requisitos (DFS com três cores)."""
    WHITE, GRAY, BLACK = 0, 1, 2
    color = {lesson_id: WHITE for lesson_id in lesson_index}

    def visit(lesson_id, stack):
        color[lesson_id] = GRAY
        stack.append(lesson_id)
        for prereq in lesson_index[lesson_id].get("prerequisites") or []:
            if prereq not in lesson_index:
                continue  # referência inexistente é reportada em outra checagem
            if color[prereq] == GRAY:
                cycle = stack[stack.index(prereq):] + [prereq]
                errors.append("catalog.yaml: ciclo de pré-requisitos detectado: %s" % " -> ".join(cycle))
            elif color[prereq] == WHITE:
                visit(prereq, stack)
        stack.pop()
        color[lesson_id] = BLACK

    for lesson_id in lesson_index:
        if color[lesson_id] == WHITE:
            visit(lesson_id, [])


def _check_activity_evaluation_references(lesson, lesson_file, errors):
    """Checks determinísticos devem referenciar ids declarados em data."""
    prefix = "%s (%s)" % (lesson_file, lesson.get("id", "?"))
    for activity in lesson.get("activities") or []:
        act_id = activity.get("id", "?")
        act_type = activity.get("type", "?")
        data = activity.get("data") or {}
        evaluation = activity.get("evaluation") or {}
        if not isinstance(data, dict) or not isinstance(evaluation, dict):
            continue  # erro estrutural já reportado pelo schema

        def ids_of(key):
            return {entry.get("id") for entry in data.get(key) or [] if isinstance(entry, dict)}

        if act_type == "choice":
            known = ids_of("options")
            for ref in evaluation.get("correctOptionIds") or []:
                if ref not in known:
                    errors.append("%s: atividade %s referencia opção inexistente em correctOptionIds: %s" % (prefix, act_id, ref))
        elif act_type == "sort":
            known = ids_of("items")
            order = evaluation.get("expectedOrder") or []
            if set(order) != known:
                errors.append("%s: atividade %s: expectedOrder deve ser uma permutação dos ids de data.items" % (prefix, act_id))
        elif act_type == "missing_context":
            known = ids_of("contextOptions")
            for key in ("requiredContextIds", "optionalContextIds"):
                for ref in evaluation.get(key) or []:
                    if ref not in known:
                        errors.append("%s: atividade %s referencia contexto inexistente em %s: %s" % (prefix, act_id, key, ref))
        elif act_type == "safety_classification":
            known = ids_of("items")
            classification = evaluation.get("classification") or {}
            if set(classification.keys()) != known:
                errors.append("%s: atividade %s: classification deve classificar exatamente os ids de data.items" % (prefix, act_id))
        elif act_type == "prompt_builder":
            known = ids_of("fields")
            for ref in (evaluation.get("fields") or {}).keys():
                if ref not in known:
                    errors.append("%s: atividade %s avalia campo inexistente em data.fields: %s" % (prefix, act_id, ref))
        elif act_type == "output_comparison":
            output_ids = ids_of("outputs")
            criterion_ids = ids_of("criteria")
            if evaluation.get("betterOutputId") not in output_ids:
                errors.append("%s: atividade %s: betterOutputId inexistente: %s" % (prefix, act_id, evaluation.get("betterOutputId")))
            for ref in evaluation.get("requiredCriterionIds") or []:
                if ref not in criterion_ids:
                    errors.append("%s: atividade %s referencia critério inexistente: %s" % (prefix, act_id, ref))
        elif act_type == "rubric_review":
            known = ids_of("criteria")
            for ref in (evaluation.get("expectedVerdicts") or {}).keys():
                if ref not in known:
                    errors.append("%s: atividade %s avalia critério inexistente em data.criteria: %s" % (prefix, act_id, ref))


def validate_track(track_dir):
    """Valida a trilha inteira. Retorna (errors, ready_lessons, catalog)."""
    track_dir = Path(track_dir)
    errors = []

    catalog_path = track_dir / "catalog.yaml"
    if not catalog_path.is_file():
        return ["catalog.yaml não encontrado em %s" % track_dir], [], None
    catalog = _load_yaml(catalog_path, errors)
    catalog = _check_catalog_shape(catalog, errors)
    if catalog is None:
        return errors, [], None

    skill_index = _index_by_id(catalog.get("skills"), "skill", errors)
    module_index = _index_by_id(catalog.get("modules"), "módulo", errors)
    lesson_index = _index_by_id(catalog.get("lessons"), "lição", errors)

    # Integridade das entradas do catálogo.
    for lesson_id, entry in lesson_index.items():
        for key in ("moduleId", "title", "objective", "estimatedMinutes", "prerequisites", "skillIds", "status"):
            if key not in entry:
                errors.append("catalog.yaml: lição %s sem campo obrigatório: %s" % (lesson_id, key))
        module_id = entry.get("moduleId")
        if module_id and module_id not in module_index:
            errors.append("catalog.yaml: lição %s referencia módulo inexistente: %s" % (lesson_id, module_id))
        for skill_id in entry.get("skillIds") or []:
            if skill_id not in skill_index:
                errors.append("catalog.yaml: lição %s referencia skill inexistente: %s" % (lesson_id, skill_id))
        for prereq in entry.get("prerequisites") or []:
            if prereq not in lesson_index:
                errors.append("catalog.yaml: lição %s referencia pré-requisito inexistente: %s" % (lesson_id, prereq))
        if entry.get("estimatedMinutes") not in VALID_DURATIONS:
            errors.append("catalog.yaml: lição %s com duração fora de {3,4,5}: %r" % (lesson_id, entry.get("estimatedMinutes")))
        if entry.get("status") not in VALID_STATUSES:
            errors.append("catalog.yaml: lição %s com status inválido: %r (válidos: %s)" % (lesson_id, entry.get("status"), ", ".join(VALID_STATUSES)))

    _detect_prereq_cycles(lesson_index, errors)

    # Carrega arquivos de lição.
    lesson_files = {}
    modules_dir = track_dir / "modules"
    if modules_dir.is_dir():
        for path in sorted(modules_dir.glob("*/*.yaml")):
            lesson_files[path] = None  # preenchido após parse

    resolver = SchemaResolver(track_dir / "schemas")
    parsed_lessons = {}
    activity_ids = {}
    for path in sorted(lesson_files):
        rel = path.relative_to(track_dir)
        data = _load_yaml(path, errors)
        if data is None:
            continue
        schema_errors = validate_against_schema(data, "lesson.schema.json", resolver)
        for err in schema_errors:
            errors.append("%s: %s" % (rel, err))
        if schema_errors:
            continue
        lesson_id = data["id"]
        if lesson_id in parsed_lessons:
            errors.append("%s: id de lição duplicado: %s (também em %s)" % (rel, lesson_id, parsed_lessons[lesson_id][0]))
        parsed_lessons[lesson_id] = (rel, data)
        for activity in data.get("activities") or []:
            act_id = activity.get("id")
            if act_id in activity_ids:
                errors.append("%s: id de atividade duplicado: %s (também em %s)" % (rel, act_id, activity_ids[act_id]))
            activity_ids[act_id] = rel
        _check_activity_evaluation_references(data, rel, errors)
        for skill_id in data.get("skillIds") or []:
            if skill_id not in skill_index:
                errors.append("%s: lição %s referencia skill inexistente: %s" % (rel, lesson_id, skill_id))
        for activity in data.get("activities") or []:
            skill_id = activity.get("skillId")
            if skill_id and skill_id not in skill_index:
                errors.append("%s: atividade %s referencia skill inexistente: %s" % (rel, activity.get("id"), skill_id))
        if data.get("moduleId") not in module_index:
            errors.append("%s: lição %s referencia módulo inexistente: %s" % (rel, lesson_id, data.get("moduleId")))
        for prereq in data.get("prerequisites") or []:
            if prereq not in lesson_index:
                errors.append("%s: lição %s referencia pré-requisito inexistente: %s" % (rel, lesson_id, prereq))
        own_activity_ids = {a.get("id") for a in data.get("activities") or []}
        for required in (data.get("completion") or {}).get("requiredActivityIds") or []:
            if required not in own_activity_ids:
                errors.append("%s: lição %s exige atividade inexistente em completion.requiredActivityIds: %s" % (rel, lesson_id, required))

    # Consistência catálogo <-> arquivos.
    file_lesson_ids = set(parsed_lessons)
    for lesson_id, entry in lesson_index.items():
        status = entry.get("status")
        if status == "ready" and lesson_id not in file_lesson_ids:
            errors.append("catalog.yaml: lição %s marcada como ready mas sem arquivo em modules/" % lesson_id)
        if status == "planned" and lesson_id in file_lesson_ids:
            errors.append("catalog.yaml: lição %s tem arquivo mas está marcada como planned — promova para ready" % lesson_id)
        if lesson_id in file_lesson_ids:
            rel, data = parsed_lessons[lesson_id]
            for field in ("moduleId", "title", "estimatedMinutes", "prerequisites", "skillIds"):
                if entry.get(field) != data.get(field):
                    errors.append("catalog.yaml: lição %s diverge do arquivo %s no campo %s (%r != %r)" % (lesson_id, rel, field, entry.get(field), data.get(field)))
    for lesson_id, (rel, _data) in parsed_lessons.items():
        if lesson_id not in lesson_index:
            errors.append("%s: lição %s não está listada no catalog.yaml" % (rel, lesson_id))

    ready = [data for lesson_id, (_rel, data) in sorted(parsed_lessons.items()) if lesson_index.get(lesson_id, {}).get("status") == "ready"]
    return errors, ready, catalog


# ---------------------------------------------------------------------------
# Compilador: read model tipado TypeScript
# ---------------------------------------------------------------------------

TS_TYPES = """
export type SkillId = "entender" | "pedir" | "avaliar" | "proteger" | "aplicar"

export type StoragePolicy = "structured_only" | "digest_only" | "none"

export type ActivityFeedback = {
  onFailure: string
  onSuccess?: string
  perCheck?: Record<string, string>
}

type ActivityBase<T extends string, D, E> = {
  id: string
  type: T
  skillId: SkillId
  instruction: string
  data: D
  evaluation: E & { strategy: "deterministic" }
  feedback: ActivityFeedback
  storage: { policy: StoragePolicy }
  hints?: string[]
}

type LabeledItem = { id: string; text: string }

export type ChoiceActivity = ActivityBase<
  "choice",
  { prompt?: string; multiSelect?: boolean; options: LabeledItem[] },
  { correctOptionIds: string[] }
>

export type SortActivity = ActivityBase<
  "sort",
  { items: LabeledItem[] },
  { expectedOrder: string[] }
>

export type MissingContextActivity = ActivityBase<
  "missing_context",
  { prompt: string; contextOptions: LabeledItem[] },
  { requiredContextIds: string[]; optionalContextIds?: string[] }
>

export type SafetyClassificationActivity = ActivityBase<
  "safety_classification",
  { labels: { safe: string; sensitive: string }; items: LabeledItem[] },
  { classification: Record<string, "safe" | "sensitive"> }
>

export type PromptBuilderActivity = ActivityBase<
  "prompt_builder",
  {
    scenario: string
    genericPrompt: string
    fields: { id: string; label: string; hint: string }[]
  },
  {
    fields: Record<
      string,
      { minLength?: number; maxLength?: number; mustIncludeAny?: string[] }
    >
  }
>

export type OutputComparisonActivity = ActivityBase<
  "output_comparison",
  { scenario: string; outputs: LabeledItem[]; criteria: LabeledItem[] },
  { betterOutputId: string; requiredCriterionIds: string[] }
>

export type RubricReviewActivity = ActivityBase<
  "rubric_review",
  { responseText: string; criteria: LabeledItem[] },
  { expectedVerdicts: Record<string, "met" | "partial" | "not_met"> }
>

export type ActivityDefinition =
  | ChoiceActivity
  | SortActivity
  | MissingContextActivity
  | SafetyClassificationActivity
  | PromptBuilderActivity
  | OutputComparisonActivity
  | RubricReviewActivity

export type LessonRubric = {
  id: string
  criteria: { id: string; text: string; weight?: number }[]
}

export type LessonDefinition = {
  id: string
  version: number
  moduleId: string
  title: string
  objective: string
  estimatedMinutes: 3 | 4 | 5
  skillIds: SkillId[]
  prerequisites: string[]
  activities: ActivityDefinition[]
  rubric: LessonRubric
  evidence: {
    verifierRequired: true
    completionClaim: "lesson_completed" | "application_reported"
    includesFreeText: false
  }
  review: { intervalsDays: number[] }
  completion: { minimumScore: number; requiredActivityIds: string[] }
}

export type CatalogLessonEntry = {
  id: string
  moduleId: string
  title: string
  estimatedMinutes: 3 | 4 | 5
  prerequisites: string[]
  skillIds: SkillId[]
  status: "planned" | "ready"
  /** true quando a lição tem arquivo validado e entra no read model (`lessons`). */
  hasContent: boolean
}

export type ModuleDefinition = {
  id: string
  slug: string
  title: string
  order: number
  skillIds: SkillId[]
  lessons: CatalogLessonEntry[]
}

export type SkillDefinition = { id: SkillId; title: string; description: string }

export type Track = {
  id: string
  title: string
  audience: string
  promise: string
  language: string
}
""".lstrip("\n")


def compile_track(track_dir, outdir):
    """Compila as lições válidas para o read model tipado. Retorna (errors, output_path)."""
    errors, ready_lessons, catalog = validate_track(track_dir)
    if errors:
        return errors, None
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    out_path = outdir / "lessons.ts"

    ready_ids = {lesson["id"] for lesson in ready_lessons}
    entries = []
    for entry in catalog.get("lessons") or []:
        entries.append(
            {
                "id": entry["id"],
                "moduleId": entry["moduleId"],
                "title": entry["title"],
                "estimatedMinutes": entry["estimatedMinutes"],
                "prerequisites": entry.get("prerequisites") or [],
                "skillIds": entry.get("skillIds") or [],
                "status": entry["status"],
                "hasContent": entry["id"] in ready_ids,
            }
        )
    modules_payload = []
    for module in sorted(catalog.get("modules") or [], key=lambda item: item.get("order", 0)):
        modules_payload.append(
            {
                "id": module["id"],
                "slug": module["slug"],
                "title": module["title"],
                "order": module["order"],
                "skillIds": module.get("skillIds") or [],
                "lessons": [entry for entry in entries if entry["moduleId"] == module["id"]],
            }
        )
    skills_payload = [
        {"id": skill["id"], "title": skill["title"], "description": skill["description"]}
        for skill in catalog.get("skills") or []
    ]
    track_payload = {key: catalog["track"][key] for key in ("id", "title", "audience", "promise", "language")}

    def as_ts(payload):
        return json.dumps(payload, ensure_ascii=False, indent=2)

    content = (
        GENERATED_HEADER
        + "\n// Read model tipado da trilha ai-literacy. Fonte canônica: curriculum/ai-literacy/.\n"
        + "// Regenere com: python3 curriculum/ai-literacy/tools/validate.py --compile <outdir>\n\n"
        + TS_TYPES
        + "\nexport const contentVersion: string = "
        + json.dumps(str(catalog.get("contentVersion")), ensure_ascii=False)
        + "\n\nexport const track: Track = "
        + as_ts(track_payload)
        + "\n\nexport const modules: ModuleDefinition[] = "
        + as_ts(modules_payload)
        + "\n\nexport const skills: SkillDefinition[] = "
        + as_ts(skills_payload)
        + "\n\nexport const lessons: LessonDefinition[] = "
        + as_ts(ready_lessons)
        + "\n"
    )
    out_path.write_text(content, encoding="utf-8")
    return [], out_path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv=None):
    parser = argparse.ArgumentParser(description="Valida a trilha ai-literacy e opcionalmente compila o read model TypeScript.")
    parser.add_argument("--track", default=str(TRACK_DIR), help="diretório da trilha (padrão: curriculum/ai-literacy)")
    parser.add_argument("--compile", metavar="OUTDIR", default=None, help="gera OUTDIR/lessons.ts após validação bem-sucedida")
    args = parser.parse_args(argv)

    track_dir = Path(args.track)
    errors, ready, catalog = validate_track(track_dir)
    out_path = None
    if not errors and args.compile:
        errors, out_path = compile_track(track_dir, args.compile)

    if errors:
        print("VALIDAÇÃO FALHOU — %d erro(s):" % len(errors), file=sys.stderr)
        for err in errors:
            print("  - %s" % err, file=sys.stderr)
        return 1

    planned = sum(1 for entry in (catalog or {}).get("lessons", []) if entry.get("status") == "planned")
    print("OK: %d lição(ões) ready validadas, %d planned (sem arquivo exigido)." % (len(ready), planned))
    if out_path is not None:
        print("Read model gerado: %s" % out_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
