// AUTO-GENERATED by learner/substrate/ts_render.py for game-05-relay-station.
// @substrate-generated — do NOT hand-edit.
// Read-only review slice for voxelDojo game 'game-05-relay-station' (unit 'U5-websocket-chat').
// DO NOT EDIT BY HAND — run `python3 -m learner.substrate` to regenerate.
// The game reads scheduling truth here and emits evidence only; it never
// marks mastery or appends to units_log (GameNeverMarksMastery).
// nextReviews is filtered to this game's unit by the substrate, so the
// 'reason' field reflects real FSRS scheduling state, not a hand-typed stub.

export type ReviewReason = "due" | "overdue" | "interleaving" | "recurring-trap"

export type ReviewSlice = {
  readonly gameId: string
  readonly unitId: string
  readonly nextReviews: ReadonlyArray<{
    readonly unitId: string
    readonly title: string
    readonly dueIn: string
    readonly reason: ReviewReason
  }>
  readonly streak: {
    readonly current: number
    readonly longest: number
    readonly lastGateDate: string | null
    readonly freezesEquipped: number
    readonly freezesMax: number
  }
}

export const reviewSlice: ReviewSlice = {
  gameId: "game-05-relay-station",
  unitId: "U5-websocket-chat",
  nextReviews: [],
  streak: {
    current: 0,
    longest: 2,
    lastGateDate: "2026-08-13",
    freezesEquipped: 0,
    freezesMax: 2,
  },
}
