// AUTO-GENERATED by learner/substrate/dashboard_snapshot.py.
// DO NOT EDIT BY HAND — run `python3 -m learner.substrate` to regenerate.
// Source: learner/learning_state.yaml + learner/learner_profile.md +
//         learner/pitfalls.md + learner/journal.md + curriculum/BACKLOG_STATUS.md
// Generated: 2026-06-21T21:05:13.615290Z

import type { LearnerSnapshot } from "../domain"

export const learnerSnapshot: LearnerSnapshot = {
  activeUnit: {
    id: "U0-sonda-rate-limiter-robustness",
    title: "Sonda diagnostic: token-bucket robustness",
    project: "01_rate_limiter",
    state: "presenting",
    retryCount: 0,
    retryLimit: 3,
  },
  gate: {
    implementationBlocked: true,
    unblockCondition: "learner_attempt_evaluated",
  },
  profile: {
    dreyfus: "competent",
    bloom: "apply",
    activeLanguage: "TypeScript",
    weeklyTimeHours: 5,
  },
  aidi: {
    current: 0.34,
    thresholdAmber: 0.6,
    thresholdRed: 0.75,
    trend: [
      {
        date: "2026-06-01",
        value: 0.21,
      },
      {
        date: "2026-06-08",
        value: 0.28,
      },
      {
        date: "2026-06-15",
        value: 0.34,
      },
    ],
  },
  topPitfalls: [
    {
      id: "P-001",
      description: "Reivindicar domínio a partir de trabalho de documentação/dashboard",
      occurrences: 1,
      lastSeen: "2026-06-18",
    },
  ],
  nextReviews: [
    {
      unitId: "U0-sonda-rate-limiter-robustness",
      title: "token-bucket robustness",
      dueIn: "today",
      reason: "due",
    },
    {
      unitId: "P-001",
      title: "Reivindicar domínio a partir de trabalho de documentação/dashboard",
      dueIn: "today",
      reason: "recurring-trap",
    },
  ],
  masteredCount: 1,
  scaffoldedCount: 17,
  streak: {
    current: 0,
    longest: 0,
    lastGateDate: null,
    freezesEquipped: 2,
    freezesMax: 2,
  },
  curr: 0,
}
