// AUTO-GENERATED by learner/substrate/catalog.py.
// DO NOT EDIT BY HAND — edit curriculum/catalog.md and run `python3 -m learner.substrate`.

import type { DojoProject } from "../domain"

export const projects: readonly DojoProject[] = [
  {
    id: "p01",
    title: "Rate Limiter (Token Bucket)",
    phase: "fundamentos",
    level: 1,
    language: "Go, Rust, Node",
    architecture: "Token bucket algorithm, concurrency primitives, atomic refills, shared state",
    learningGoal: "Entender concorrência básica, estado compartilhado e refills atômicos.",
    evidence: [
      "Six executable evidence groups cover the spec, Go/Rust/Node implementations and tests, review, benchmark, evolution, and verifier gate. Certification caveat: benchmark and optimization are Node.js-only execution-verified in this sandbox; Go and Rust are code-reviewed/proposed-only for those phases, not performance-parity certified.",
      "implemented",
      "01_rate_limiter/",
      "None (entry point)",
    ],
  },
  {
    id: "p02",
    title: "Key-Value Store (in-memory)",
    phase: "fundamentos",
    level: 1,
    language: "Go, Rust, Node",
    architecture:
      "Hash maps, CRUD API, TCP/HTTP, serialization, TTL expiration, snapshot/persistence basics",
    learningGoal: "Comparar mapas e dicionários sob carga concorrente e persistência simples.",
    evidence: [
      "Node.js has executable spec, tests, review, benchmark, evolution, and verifier evidence. Certification caveat: this is Node.js-only; the Go and Rust directories came from an earlier ungated backfill and have not been compiled, tested, reviewed, or benchmarked in the certified cycle.",
      "implemented (Node.js only)",
      "02_key_value_store/",
      "Project 01 (concurrency basics)",
    ],
  },
  {
    id: "p03",
    title: "URL Shortener",
    phase: "fundamentos",
    level: 1,
    language: "Go, Rust, Node",
    architecture:
      "Hashing (base62, SHA-256 trunc), relational DB design, HTTP redirects (301/302), unique ID generation, analytics pipeline",
    learningGoal: "Explorar hashing, geração de IDs e redirecionamento seguro.",
    evidence: [
      "Project artifacts exist; catalog verification is pending.",
      "scaffolded",
      "03_url_shortener/",
      "Project 02 (storage basics)",
    ],
  },
  {
    id: "p04",
    title: "Concurrent Task Queue",
    phase: "concorrencia",
    level: 2,
    language: "Go, Rust, Node",
    architecture:
      "Worker pools, job scheduling, backpressure, priorities, timeouts, retry policies, dead-letter queues, idempotency",
    learningGoal: "Orquestrar jobs concorrentes com prioridades e retry.",
    evidence: [
      "Project artifacts exist; catalog verification is pending.",
      "scaffolded",
      "04_concurrent_task_queue/",
      "Projects 01-03",
    ],
  },
  {
    id: "p05",
    title: "WebSocket Chat Server",
    phase: "concorrencia",
    level: 2,
    language: "Go, Rust, Node",
    architecture:
      "WebSocket protocol, connection management, fan-out broadcasting, rooms, presence, heartbeats",
    learningGoal: "Gerir conexões persistentes e broadcast em escala.",
    evidence: [
      "Project artifacts exist; catalog verification is pending.",
      "scaffolded",
      "05_websocket_chat/",
      "Projects 01-03",
    ],
  },
  {
    id: "p06",
    title: "File Upload/Processing Pipeline",
    phase: "concorrencia",
    level: 2,
    language: "Go, Rust, Node",
    architecture:
      "Streaming I/O, chunked processing, multipart upload, memory management, parallel processing, bounded memory",
    learningGoal: "Processar uploads grandes sem estourar memória.",
    evidence: [
      "Project artifacts exist; catalog verification is pending.",
      "scaffolded",
      "06_file_upload_pipeline/",
      "Projects 01-03",
    ],
  },
  {
    id: "p07",
    title: "REST API with Auth",
    phase: "arquitetura",
    level: 3,
    language: "Go, Rust, Node",
    architecture:
      "JWT (sign/verify), RBAC, middleware chains, layered architecture, dependency injection, input validation, versioning",
    learningGoal: "Separar identidade, sessão, autorização e versionamento.",
    evidence: [
      "Project artifacts exist; catalog verification is pending.",
      "scaffolded",
      "07_rest_api_auth/",
      "Projects 04-06",
    ],
  },
  {
    id: "p08",
    title: "Event-Driven Order System",
    phase: "arquitetura",
    level: 3,
    language: "Go, Rust, Node",
    architecture:
      "Pub/sub, event sourcing, eventual consistency, projections, sagas (orchestrated + choreographed), outbox pattern",
    learningGoal: "Estudar consistência eventual, sagas e replay.",
    evidence: [
      "Project artifacts exist; catalog verification is pending.",
      "scaffolded",
      "08_event_driven_order_system/",
      "Projects 04-06",
    ],
  },
  {
    id: "p09",
    title: "Plugin System",
    phase: "arquitetura",
    level: 3,
    language: "Go, Rust, Node",
    architecture:
      "Dynamic loading, interfaces/traits, plugin lifecycle, sandboxing, WASM/FFI/JS sandboxing, API versioning",
    learningGoal: "Comparar FFI, WASM e dynamic loading com isolamento.",
    evidence: [
      "Project artifacts exist; catalog verification is pending.",
      "scaffolded",
      "09_plugin_system/",
      "Projects 04-06",
    ],
  },
  {
    id: "p10",
    title: "Distributed Cache",
    phase: "escalabilidade",
    level: 4,
    language: "Go, Rust, Node",
    architecture:
      "Cache invalidation, TTL, LRU/LFU eviction, consistent hashing, gossip protocol, cache-aside vs write-through, cache stampede prevention, sharding",
    learningGoal: "Medir invalidação, TTL e proteção contra stampede.",
    evidence: [
      "Project artifacts exist; catalog verification is pending.",
      "scaffolded",
      "10_distributed_cache/",
      "Projects 07-09",
    ],
  },
  {
    id: "p11",
    title: "Load Balancer",
    phase: "escalabilidade",
    level: 4,
    language: "Go, Rust, Node",
    architecture:
      "Reverse proxy, health checks, round-robin, least-connections, consistent hashing, TLS termination, sticky sessions, circuit breaker per backend",
    learningGoal: "Equilibrar tráfego e failover com critérios claros.",
    evidence: [
      "Project artifacts exist; catalog verification is pending.",
      "scaffolded",
      "11_load_balancer/",
      "Projects 07-09",
    ],
  },
  {
    id: "p12",
    title: "Distributed Job Scheduler",
    phase: "escalabilidade",
    level: 4,
    language: "Go, Rust, Node",
    architecture:
      "Leader election (Raft simplified), distributed locks, cron-like scheduling, fault tolerance, DAG dependencies, exponential backoff retry",
    learningGoal: "Coordenar jobs distribuídos sem split-brain.",
    evidence: [
      "Project artifacts exist; catalog verification is pending.",
      "scaffolded",
      "12_distributed_job_scheduler/",
      "Projects 07-09",
    ],
  },
  {
    id: "p13",
    title: "API Gateway with Circuit Breaker",
    phase: "resiliencia",
    level: 5,
    language: "Go, Rust, Node",
    architecture:
      "Fault tolerance, circuit breaker states (closed/open/half-open), retry with exponential backoff + jitter, fallbacks, bulkheading, rate limit per tenant, request coalescing",
    learningGoal: "Proteger serviços downstream contra falhas em cascata.",
    evidence: [
      "Project artifacts exist; catalog verification is pending.",
      "scaffolded",
      "13_api_gateway_circuit_breaker/",
      "Projects 10-12",
    ],
  },
  {
    id: "p14",
    title: "Log Aggregator",
    phase: "resiliencia",
    level: 5,
    language: "Go, Rust, Node",
    architecture:
      "Structured logging (JSON), log levels, aggregation pipelines, compression, indexing, retention, distributed tracing (OpenTelemetry), correlation IDs",
    learningGoal: "Coletar, estruturar e consultar logs em grande volume.",
    evidence: [
      "Project artifacts exist; catalog verification is pending.",
      "scaffolded",
      "14_log_aggregator/",
      "Projects 10-12",
    ],
  },
  {
    id: "p15",
    title: "Metrics Collector & Dashboard",
    phase: "resiliencia",
    level: 5,
    language: "Go, Rust, Node",
    architecture:
      "Time-series data, counters/gauges/histograms, aggregation (sum/avg/p95), downsampling, retention, Prometheus-compatible format, alerting",
    learningGoal: "Modelar métricas, buckets e alertas com precisão.",
    evidence: [
      "Project artifacts exist; catalog verification is pending.",
      "scaffolded",
      "15_metrics_collector/",
      "Projects 10-12",
    ],
  },
  {
    id: "p16",
    title: "Mini Message Queue (like Kafka)",
    phase: "sistemas_complexos",
    level: 6,
    language: "Go, Rust, Node",
    architecture:
      "Topics, partitions, consumer groups, offsets, log-structured storage, replication, exactly-once semantics, log compaction",
    learningGoal: "Entender partições, offsets e consumer groups.",
    evidence: [
      "Project artifacts exist; catalog verification is pending.",
      "scaffolded",
      "16_mini_message_queue/",
      "Projects 13-15",
    ],
  },
  {
    id: "p17",
    title: "Distributed Configuration Service",
    phase: "sistemas_complexos",
    level: 6,
    language: "Go, Rust, Node",
    architecture:
      "Consensus (Raft/Paxos simplified), watch/notify, versioning, linearizability, ACL per key, audit, rollback, multi-region replication, feature flags",
    learningGoal: "Praticar consistência, ACLs e feature flags distribuídas.",
    evidence: [
      "Project artifacts exist; catalog verification is pending.",
      "scaffolded",
      "17_distributed_config_service/",
      "Projects 13-15",
    ],
  },
  {
    id: "p18",
    title: "Search Engine",
    phase: "sistemas_complexos",
    level: 6,
    language: "Go, Rust, Node",
    architecture:
      "Inverted indexes, tokenization, TF-IDF/BM25 ranking, query parsing, fuzzy search, autocomplete, incremental indexing, index persistence",
    learningGoal: "Construir busca com tokenização, ranking e autocomplete.",
    evidence: [
      "Project artifacts exist; catalog verification is pending.",
      "scaffolded",
      "18_search_engine/",
      "Projects 13-15",
    ],
  },
]
