from __future__ import annotations

from typing import Final

PROJECT_CATALOG: Final = "\n".join(
    (
        "# Curriculum",
        "",
        "## Level 0",
        "",
        "### 00. AI in Practice",
        "",
        "| Field | Value |",
        "|-------|-------|",
        "| **Slug** | `00_ai_in_practice` |",
        "| **Status** | scaffolded |",
        "| **Concepts** | AI literacy |",
        "| **Key question** | Can the learner verify an AI answer? |",
        "| **Learning goal** | Verify before use. |",
        "| **Directory** | `00_ai_in_practice/` |",
        "| **Dependencies** | None |",
        "",
        "### 01. Rate Limiter",
        "",
        "| Field | Value |",
        "|-------|-------|",
        "| **Slug** | `01_rate_limiter` |",
        "| **Status** | implemented |",
        "| **Concepts** | Concurrency |",
        "| **Key question** | How are requests limited? |",
        "| **Learning goal** | Bound concurrent requests. |",
        "| **Directory** | `01_rate_limiter/` |",
        "| **Dependencies** | None |",
        "",
        "### 02. Key-Value Store",
        "",
        "| Field | Value |",
        "|-------|-------|",
        "| **Slug** | `02_key_value_store` |",
        "| **Status** | implemented |",
        "| **Concepts** | Hash maps and TTL |",
        "| **Key question** | Where does a key live? |",
        "| **Learning goal** | Predict hash-map CRUD and TTL behavior. |",
        "| **Directory** | `02_key_value_store/` |",
        "| **Dependencies** | Project 01 |",
        "",
        "### 03. URL Shortener",
        "",
        "| Field | Value |",
        "|-------|-------|",
        "| **Slug** | `03_url_shortener` |",
        "| **Status** | scaffolded |",
        "| **Concepts** | Short codes |",
        "| **Key question** | How are collisions resolved? |",
        "| **Learning goal** | Predict short-code generation and collision handling. |",
        "| **Directory** | `03_url_shortener/` |",
        "| **Dependencies** | Project 02 |",
        "",
        "### 04. Concurrent Task Queue",
        "",
        "| Field | Value |",
        "|-------|-------|",
        "| **Slug** | `04_concurrent_task_queue` |",
        "| **Status** | scaffolded |",
        "| **Concepts** | Worker pools |",
        "| **Key question** | How is work scheduled? |",
        "| **Learning goal** | Coordinate bounded work. |",
        "| **Directory** | `04_concurrent_task_queue/` |",
        "| **Dependencies** | Project 03 |",
        "",
        "### 05. WebSocket Chat",
        "",
        "| Field | Value |",
        "|-------|-------|",
        "| **Slug** | `05_websocket_chat` |",
        "| **Status** | scaffolded |",
        "| **Concepts** | Persistent connections |",
        "| **Key question** | How does fan-out reach subscribers? |",
        "| **Learning goal** | Predict connection, fan-out, and heartbeat behavior. |",
        "| **Directory** | `05_websocket_chat/` |",
        "| **Dependencies** | Project 03 |",
        "",
        "### 06. File Upload/Processing Pipeline",
        "",
        "| Field | Value |",
        "|-------|-------|",
        "| **Slug** | `06_file_upload_pipeline` |",
        "| **Status** | scaffolded |",
        "| **Concepts** | Streaming vs buffering |",
        "| **Key question** | How do streaming and buffering compare for large files? |",
        "| **Learning goal** | Process large uploads without exhausting memory. |",
        "| **Directory** | `06_file_upload_pipeline/` |",
        "| **Dependencies** | Project 03 |",
        "",
        "### 07. REST API Auth Middleware",
        "",
        "| Field | Value |",
        "|-------|-------|",
        "| **Slug** | `07_rest_api_auth` |",
        "| **Status** | scaffolded |",
        "| **Concepts** | Middleware layers + JWT verification |",
        "| **Key question** | How do layered middleware gates decide who reaches the handler? |",
        "| **Learning goal** | Reason about ordered middleware (logging, auth, rate limiting). |",
        "| **Directory** | `07_rest_api_auth/` |",
        "| **Dependencies** | Project 03 |",
        "",
    )
)
