// AUTO-GENERATED by learner/substrate/dashboard_snapshot.py.
// DO NOT EDIT BY HAND — run `python3 -m learner.substrate` to regenerate.
// Read-only review slice for voxelDojo: the game reads scheduling truth here,
// emits evidence only, and never marks mastery (GameNeverMarksMastery).
// Generated: 2026-07-05T20:32:00.000000Z
//
// NOTE: U5-websocket-chat is not yet an honestly-gated unit in the substrate
// (only U0 is, as of 2026-07-05). So nextReviews is empty for U5 and every
// RELAY STATION attempt is recorded as `deepening` play until the scheduler
// promotes U5 to the active review set. See docs/plans/05_websocket_chat.md §12.

import type { ReviewSlice } from "./types"

export const reviewSlice: ReviewSlice = {
  nextReviews: [],
  streak: {
    current: 0,
    longest: 0,
    lastGateDate: null,
    freezesEquipped: 2,
    freezesMax: 2,
  },
}
