// AUTO-GENERATED by learner/substrate/dashboard_snapshot.py.
// DO NOT EDIT BY HAND — run `python3 -m learner.substrate` to regenerate.
// Read-only review slice for voxelDojo: the game reads scheduling truth here,
// emits evidence only, and never marks mastery (GameNeverMarksMastery).
// Generated: 2026-07-05T20:30:00.000000Z

import type { ReviewSlice } from "./types"

export const reviewSlice: ReviewSlice = {
  nextReviews: [],
  streak: {
    current: 0,
    longest: 0,
    lastGateDate: null,
    freezesEquipped: 2,
    freezesMax: 2,
  },
}
