export type ReviewReason = "due" | "overdue" | "interleaving" | "recurring-trap"

/**
 * Read-only slice generated by the learner substrate
 * (`learner/substrate/dashboard_snapshot.py`, `sync_voxel_review_slice`).
 * voxelDojo reads scheduling truth (which unit is due, the streak counts) here
 * and emits evidence only — it never marks mastery or appends to units_log
 * (GameNeverMarksMastery / evidence_only). Regenerate with
 * `python3 -m learner.substrate` from the repo root.
 */
export type ReviewSlice = {
  readonly nextReviews: ReadonlyArray<{
    readonly unitId: string
    readonly title: string
    readonly dueIn: string
    readonly reason: ReviewReason
  }>
  readonly streak: {
    readonly current: number
    readonly longest: number
    readonly lastGateDate: string | null
    readonly freezesEquipped: number
    readonly freezesMax: number
  }
}
