export type ReviewReason = "due" | "overdue" | "interleaving" | "recurring-trap"

export type ReviewStatus = "due" | "verifier_pending" | "retry_due"

export type ReviewProjection = {
  readonly unitId: string
  readonly title: string
  readonly dueIn: string
  readonly reason: ReviewReason
  readonly status: ReviewStatus
}

export type StreakProjection = {
  readonly current: number
  readonly longest: number
  readonly freezesEquipped: number
  readonly freezesMax: number
  readonly daysToBreak: number | null
  readonly pendingGateDelta: 0 | 1
}

export type ReviewTrack = {
  readonly active: ReviewProjection
  readonly streak: StreakProjection
  readonly schedulerSource: "learner-substrate"
  readonly verifierRequired: true
}

/**
 * Read-only slice generated by the learner substrate
 * (`learner/substrate/dashboard_snapshot.py`). pixelDojo reads scheduling truth
 * (which unit is due, the streak counts) here and emits evidence only — it never
 * marks mastery or appends to units_log (GameNeverMarksMastery / evidence_only).
 */
export type ReviewSlice = {
  readonly nextReviews: ReadonlyArray<{
    readonly unitId: string
    readonly title: string
    readonly dueIn: string
    readonly reason: ReviewReason
  }>
  readonly streak: {
    readonly current: number
    readonly longest: number
    readonly lastGateDate: string | null
    readonly freezesEquipped: number
    readonly freezesMax: number
  }
}
