// AUTO-GENERATED by learner/substrate/dashboard_snapshot.py.
// DO NOT EDIT BY HAND — run `python3 -m learner.substrate` to regenerate.
// Read-only review slice for voxelDojo: the game reads scheduling truth here,
// emits evidence only, and never marks mastery (GameNeverMarksMastery).
// Static fallback: U12-job-scheduler is not yet seeded in the substrate
// (only U0 exists as of 2026-07-05), so no reviews are scheduled — every
// attempt is deepening play until the scheduler extends the substrate.

import type { ReviewSlice } from "./types"

export const reviewSlice: ReviewSlice = {
  nextReviews: [],
  streak: {
    current: 0,
    longest: 0,
    lastGateDate: null,
    freezesEquipped: 2,
    freezesMax: 2,
  },
}
