// DO NOT EDIT BY HAND — generated by curriculum/ai-literacy/tools
// Verifier corpus for the staged literacy bridge (AID-449): the exact
// lesson/activity facts the canonical Python verifier reads from
// curriculum/ai-literacy/. Do not add producer-facing fields here.
// Canonical evaluator: learner/gate/literacy_evaluator.py.
// Regenere com: python3 curriculum/ai-literacy/tools/validate.py --compile-verifier <outdir>

export const literacyCorpus = {
  "l01": {
    "activities": [
      {
        "data": {
          "options": [
            {
              "id": "opt-rascunho",
              "text": "Uso como rascunho: reviso, ajusto à realidade da minha equipe e só então uso."
            },
            {
              "id": "opt-copia",
              "text": "Uso exatamente como veio — a IA sabe qual é o melhor formato de pauta."
            },
            {
              "id": "opt-descarta",
              "text": "Descarto na hora — IA não entende nada de reunião."
            }
          ]
        },
        "evaluation": {
          "correctOptionIds": [
            "opt-rascunho"
          ],
          "strategy": "deterministic"
        },
        "id": "l01-a1",
        "type": "choice"
      }
    ],
    "skillIds": [
      "entender"
    ],
    "version": 1
  },
  "l02": {
    "activities": [
      {
        "data": {
          "criteria": [
            {
              "id": "c-fontes",
              "text": "Diz de onde vêm os números ou onde verificá-los"
            },
            {
              "id": "c-limites",
              "text": "Deixa claro o que a IA não sabe ou o que é estimativa"
            },
            {
              "id": "c-confianca",
              "text": "Apresenta números bem detalhados com total confiança"
            }
          ],
          "outputs": [
            {
              "id": "out-a",
              "text": "O mercado de delivery no Brasil movimentou R$ 48,7 bilhões no último ano, crescendo 23,4% em relação ao ano anterior. São 112 milhões de usuários ativos, com ticket médio de R$ 42,50. A previsão para o próximo ano é de R$ 61,2 bilhões. Pode usar esses números direto na sua apresentação."
            },
            {
              "id": "out-b",
              "text": "Não tenho acesso a dados oficiais auditados desse mercado e qualquer número exato que eu der pode estar desatualizado ou inventado. O caminho seguro é checar relatórios de associações do setor (como a ABRASEL) ou de consultorias antes de apresentar. Se quiser, eu monto a estrutura da sua análise com espaços para você preencher com os números verificados."
            }
          ],
          "scenario": "Você pediu à IA: 'Quais são os números do mercado de delivery de comida no Brasil?' para embasar uma apresentação para a diretoria."
        },
        "evaluation": {
          "betterOutputId": "out-b",
          "requiredCriterionIds": [
            "c-fontes",
            "c-limites"
          ],
          "strategy": "deterministic"
        },
        "id": "l02-a1",
        "type": "output_comparison"
      }
    ],
    "skillIds": [
      "entender",
      "avaliar"
    ],
    "version": 3
  },
  "l03": {
    "activities": [
      {
        "data": {
          "multiSelect": true,
          "options": [
            {
              "id": "t-rascunho",
              "text": "Rascunhar e-mails e textos que você vai revisar depois"
            },
            {
              "id": "t-resumo",
              "text": "Resumir um documento longo que você mesmo forneceu"
            },
            {
              "id": "t-faturamento",
              "text": "Informar o faturamento de ontem da sua empresa"
            },
            {
              "id": "t-ideias",
              "text": "Sugerir ideias de nomes para um projeto novo"
            },
            {
              "id": "t-imposto",
              "text": "Calcular o valor exato do imposto que você deve este ano"
            }
          ]
        },
        "evaluation": {
          "correctOptionIds": [
            "t-rascunho",
            "t-resumo",
            "t-ideias"
          ],
          "strategy": "deterministic"
        },
        "id": "l03-a1",
        "type": "choice"
      },
      {
        "data": {
          "multiSelect": true,
          "options": [
            {
              "id": "f-noticia",
              "text": "Resumir as notícias desta semana sobre o seu setor"
            },
            {
              "id": "f-planilha",
              "text": "Somar uma coluna de 200 valores da sua planilha com precisão total"
            },
            {
              "id": "f-email",
              "text": "Melhorar o tom de um e-mail que você escreveu"
            },
            {
              "id": "f-lei",
              "text": "Citar o artigo exato de uma lei trabalhista com o texto atualizado"
            }
          ]
        },
        "evaluation": {
          "correctOptionIds": [
            "f-noticia",
            "f-planilha",
            "f-lei"
          ],
          "strategy": "deterministic"
        },
        "id": "l03-a2",
        "type": "choice"
      }
    ],
    "skillIds": [
      "entender"
    ],
    "version": 1
  },
  "l04": {
    "activities": [
      {
        "data": {
          "options": [
            {
              "id": "opt-melhora",
              "text": "\"Melhora esse texto pra mim.\""
            },
            {
              "id": "opt-claro",
              "text": "\"Reescreva este e-mail de cobrança deixando o tom mais cordial, mantendo o valor e a data de vencimento.\""
            },
            {
              "id": "opt-negocio",
              "text": "\"Faz um negócio de cobrança aí.\""
            },
            {
              "id": "opt-algo",
              "text": "\"Escreve algo sobre pagamento atrasado.\""
            }
          ]
        },
        "evaluation": {
          "correctOptionIds": [
            "opt-claro"
          ],
          "strategy": "deterministic"
        },
        "id": "l04-a1",
        "type": "choice"
      }
    ],
    "skillIds": [
      "pedir"
    ],
    "version": 1
  },
  "l05": {
    "activities": [
      {
        "data": {
          "fields": [
            {
              "hint": "O que você quer que a IA produza? Ex.: redigir um e-mail avisando sobre a mudança de horário.",
              "id": "objetivo",
              "label": "Objetivo"
            },
            {
              "hint": "O que a IA precisa saber sobre a situação? Ex.: é uma clínica odontológica e o novo horário começa no próximo mês.",
              "id": "contexto",
              "label": "Contexto"
            },
            {
              "hint": "Quem vai receber a mensagem? Ex.: clientes da clínica, em tom cordial.",
              "id": "publico",
              "label": "Público"
            },
            {
              "hint": "Como a resposta deve vir? Ex.: e-mail curto, de até 10 linhas, com assunto.",
              "id": "formato",
              "label": "Formato"
            }
          ],
          "genericPrompt": "Escreve um e-mail pra mim.",
          "scenario": "Você trabalha no atendimento de uma clínica odontológica. No próximo mês a clínica vai mudar o horário de funcionamento, e você precisa avisar os clientes com antecedência."
        },
        "evaluation": {
          "fields": {
            "contexto": {
              "minLength": 25,
              "mustIncludeAny": [
                "horário",
                "horario"
              ]
            },
            "formato": {
              "minLength": 8,
              "mustIncludeAny": [
                "e-mail",
                "email"
              ]
            },
            "objetivo": {
              "minLength": 15,
              "mustIncludeAny": [
                "avisar",
                "comunicar",
                "informar"
              ]
            },
            "publico": {
              "minLength": 8,
              "mustIncludeAny": [
                "cliente",
                "paciente"
              ]
            }
          },
          "strategy": "deterministic"
        },
        "id": "l05-a1",
        "type": "prompt_builder"
      }
    ],
    "skillIds": [
      "pedir"
    ],
    "version": 2
  },
  "l06": {
    "activities": [
      {
        "data": {
          "contextOptions": [
            {
              "id": "ctx-publico",
              "text": "Quem vai receber a mensagem (a equipe no chat interno)"
            },
            {
              "id": "ctx-tom",
              "text": "O tom desejado (direto e descontraído)"
            },
            {
              "id": "ctx-formato",
              "text": "O formato (mensagem curta de chat, não e-mail formal)"
            },
            {
              "id": "ctx-cor",
              "text": "A cor da fonte que a IA deve usar"
            },
            {
              "id": "ctx-historico",
              "text": "O histórico completo de reuniões da empresa"
            }
          ],
          "prompt": "Escreva uma mensagem avisando que a reunião de sexta mudou para as 14h."
        },
        "evaluation": {
          "requiredContextIds": [
            "ctx-publico",
            "ctx-tom",
            "ctx-formato"
          ],
          "strategy": "deterministic"
        },
        "id": "l06-a1",
        "type": "missing_context"
      }
    ],
    "skillIds": [
      "pedir"
    ],
    "version": 1
  },
  "l07": {
    "activities": [
      {
        "data": {
          "items": [
            {
              "id": "step-ajuste",
              "text": "Peça um ajuste específico (ex.: \"deixe mais curto\" ou \"troque o exemplo\")."
            },
            {
              "id": "step-pedido",
              "text": "Faça o primeiro pedido com objetivo e contexto claros."
            },
            {
              "id": "step-repita",
              "text": "Repita os ajustes até o texto ficar pronto para a sua revisão final."
            },
            {
              "id": "step-leitura",
              "text": "Leia a resposta e identifique o que ficou mais fraco."
            }
          ]
        },
        "evaluation": {
          "expectedOrder": [
            "step-pedido",
            "step-leitura",
            "step-ajuste",
            "step-repita"
          ],
          "strategy": "deterministic"
        },
        "id": "l07-a1",
        "type": "sort"
      }
    ],
    "skillIds": [
      "pedir",
      "avaliar"
    ],
    "version": 1
  },
  "l08": {
    "activities": [
      {
        "data": {
          "criteria": [
            {
              "id": "c-acoes",
              "text": "Traz ações concretas que dá para começar esta semana"
            },
            {
              "id": "c-comeco",
              "text": "Indica por onde começar e como medir o resultado"
            },
            {
              "id": "c-extenso",
              "text": "É longo e cobre muitos temas de uma vez"
            }
          ],
          "outputs": [
            {
              "id": "out-a",
              "text": "Reduzir faltas é essencial para clínicas modernas. Recomenda-se melhorar a experiência do paciente, investir em relacionamento, otimizar processos internos, valorizar a equipe, criar uma cultura de pontualidade, acompanhar indicadores e inovar constantemente. Com dedicação e foco no cliente, os resultados aparecem a médio prazo."
            },
            {
              "id": "out-b",
              "text": "Três ações para testar esta semana: 1) Enviar lembrete por mensagem 24h antes da consulta com pedido de confirmação. 2) Oferecer encaixe para a lista de espera quando alguém desmarcar. 3) Ligar para quem faltou duas vezes seguidas para entender o motivo. Comece pelo lembrete: é o mais barato e você já mede o resultado na sexta-feira."
            }
          ],
          "scenario": "A clínica tem 20% de faltas nas consultas. Você precisa de ações práticas para testar já nesta semana, sem contratar nada."
        },
        "evaluation": {
          "betterOutputId": "out-b",
          "requiredCriterionIds": [
            "c-acoes",
            "c-comeco"
          ],
          "strategy": "deterministic"
        },
        "id": "l08-a1",
        "type": "output_comparison"
      }
    ],
    "skillIds": [
      "avaliar"
    ],
    "version": 1
  },
  "l09": {
    "activities": [
      {
        "data": {
          "criteria": [
            {
              "id": "c-fontes",
              "text": "As fontes citadas são identificáveis e verificáveis (autor, instituição, link ou data checável)?"
            },
            {
              "id": "c-numeros",
              "text": "Os números precisos (87%, 35%) têm origem indicada com clareza?"
            },
            {
              "id": "c-incerteza",
              "text": "A resposta distingue o que é fato comprovado do que é opinião ou recomendação?"
            }
          ],
          "responseText": "O home office aumenta a produtividade. Segundo um estudo da Universidade de São Paulo publicado em 2024, 87% das empresas brasileiras que adotaram o home office viram as vendas crescer 35% em um ano. O relatório 'Futuro do Trabalho 2025' confirma essa tendência. Vale dizer que os resultados variam bastante de empresa para empresa, então o efeito pode ser menor no seu caso. Minha recomendação é implementar o quanto antes, pois os dados são claros."
        },
        "evaluation": {
          "expectedVerdicts": {
            "c-fontes": "not_met",
            "c-incerteza": "partial",
            "c-numeros": "not_met"
          },
          "strategy": "deterministic"
        },
        "id": "l09-a1",
        "type": "rubric_review"
      }
    ],
    "skillIds": [
      "avaliar"
    ],
    "version": 1
  },
  "l10": {
    "activities": [
      {
        "data": {
          "multiSelect": true,
          "options": [
            {
              "id": "s-inflacao",
              "text": "\"A inflação no Brasil ficou em 4,2% no último ano.\""
            },
            {
              "id": "s-paragrafo",
              "text": "\"Parágrafos curtos costumam facilitar a leitura de relatórios.\""
            },
            {
              "id": "s-lei",
              "text": "\"A lei determina prazo de 30 dias para esse tipo de reembolso.\""
            },
            {
              "id": "s-estrutura",
              "text": "\"Uma estrutura de problema-solução funciona bem em propostas comerciais.\""
            },
            {
              "id": "s-concorrente",
              "text": "\"Seu concorrente lançou um produto parecido em março deste ano.\""
            }
          ]
        },
        "evaluation": {
          "correctOptionIds": [
            "s-inflacao",
            "s-lei",
            "s-concorrente"
          ],
          "strategy": "deterministic"
        },
        "id": "l10-a1",
        "type": "choice"
      }
    ],
    "skillIds": [
      "avaliar"
    ],
    "version": 1
  },
  "l11": {
    "activities": [
      {
        "data": {
          "items": [
            {
              "id": "step-compara",
              "text": "Compare as alternativas critério por critério, lado a lado."
            },
            {
              "id": "step-criterios",
              "text": "Liste os critérios que importam para você (ex.: preço, facilidade, suporte em português)."
            },
            {
              "id": "step-decide",
              "text": "Decida você mesmo, registrando o motivo principal da escolha."
            },
            {
              "id": "step-pede",
              "text": "Peça à IA as alternativas e peça que avalie cada uma nos seus critérios."
            }
          ]
        },
        "evaluation": {
          "expectedOrder": [
            "step-criterios",
            "step-pede",
            "step-compara",
            "step-decide"
          ],
          "strategy": "deterministic"
        },
        "id": "l11-a1",
        "type": "sort"
      }
    ],
    "skillIds": [
      "avaliar"
    ],
    "version": 1
  },
  "l12": {
    "activities": [
      {
        "data": {
          "items": [
            {
              "id": "i-senha",
              "text": "A senha do sistema de vendas da empresa"
            },
            {
              "id": "i-site",
              "text": "O texto público da página 'Sobre nós' do site da empresa, que você quer resumir"
            },
            {
              "id": "i-planilha",
              "text": "Uma planilha com nome, CPF e salário dos funcionários"
            },
            {
              "id": "i-vaga",
              "text": "O anúncio de uma vaga que a empresa publicou no LinkedIn"
            },
            {
              "id": "i-cartao",
              "text": "O número do cartão corporativo usado nas viagens"
            },
            {
              "id": "i-ata",
              "text": "A ata de uma reunião interna com valores de contrato e nomes de clientes"
            },
            {
              "id": "i-legenda",
              "text": "Uma ideia de legenda para o post comemorativo de fim de ano, sem dados internos"
            }
          ],
          "labels": {
            "safe": "Seguro para compartilhar",
            "sensitive": "Sensível — não compartilhar"
          }
        },
        "evaluation": {
          "classification": {
            "i-ata": "sensitive",
            "i-cartao": "sensitive",
            "i-legenda": "safe",
            "i-planilha": "sensitive",
            "i-senha": "sensitive",
            "i-site": "safe",
            "i-vaga": "safe"
          },
          "strategy": "deterministic"
        },
        "id": "l12-a1",
        "type": "safety_classification"
      }
    ],
    "skillIds": [
      "proteger"
    ],
    "version": 2
  },
  "l13": {
    "activities": [
      {
        "data": {
          "fields": [
            {
              "hint": "O que a IA deve produzir? Use um verbo: criar, escrever, resumir, planejar, redigir…",
              "id": "objetivo",
              "label": "Objetivo"
            },
            {
              "hint": "Os fatos que a IA precisa saber sobre a sua tarefa (sem dados sensíveis!).",
              "id": "contexto",
              "label": "Contexto"
            },
            {
              "hint": "Como a resposta deve vir: e-mail, lista, tópicos, tabela, mensagem…",
              "id": "formato",
              "label": "Formato"
            }
          ],
          "genericPrompt": "Me ajuda com uma tarefa do trabalho.",
          "scenario": "Pense em uma tarefa que você realmente precisa entregar nos próximos dias. Você vai montar o pedido como se fosse enviar à IA agora — e depois pode usar de verdade."
        },
        "evaluation": {
          "fields": {
            "contexto": {
              "minLength": 25
            },
            "formato": {
              "minLength": 8,
              "mustIncludeAny": [
                "e-mail",
                "email",
                "lista",
                "tópicos",
                "topicos",
                "tabela",
                "mensagem",
                "relatório",
                "relatorio",
                "apresentação",
                "apresentacao",
                "texto",
                "planilha"
              ]
            },
            "objetivo": {
              "minLength": 15,
              "mustIncludeAny": [
                "criar",
                "escrever",
                "resumir",
                "planejar",
                "redigir",
                "montar",
                "revisar",
                "organizar"
              ]
            }
          },
          "strategy": "deterministic"
        },
        "id": "l13-a1",
        "type": "prompt_builder"
      }
    ],
    "skillIds": [
      "aplicar"
    ],
    "version": 1
  },
  "l14": {
    "activities": [
      {
        "data": {
          "fields": [
            {
              "hint": "O que a IA deve produzir? Ex.: redigir uma proposta comercial.",
              "id": "objetivo",
              "label": "Objetivo"
            },
            {
              "hint": "Os fatos que mudam a proposta: quem é o cliente, o que ele precisa, qual prazo.",
              "id": "contexto",
              "label": "Contexto"
            },
            {
              "hint": "Como a proposta deve vir: documento, e-mail, tópicos com preços…",
              "id": "formato",
              "label": "Formato"
            }
          ],
          "genericPrompt": "Faz uma proposta pra mim.",
          "scenario": "Sua empresa vende planos de limpeza para escritórios. Um cliente novo, dono de um prédio comercial com 12 andares, pediu uma proposta até sexta-feira."
        },
        "evaluation": {
          "fields": {
            "contexto": {
              "minLength": 25,
              "mustIncludeAny": [
                "cliente",
                "prédio",
                "predio",
                "escritório",
                "escritorio",
                "limpeza"
              ]
            },
            "formato": {
              "minLength": 8,
              "mustIncludeAny": [
                "proposta",
                "documento",
                "e-mail",
                "email",
                "tópicos",
                "topicos",
                "tabela"
              ]
            },
            "objetivo": {
              "minLength": 15,
              "mustIncludeAny": [
                "proposta",
                "redigir",
                "escrever",
                "montar",
                "criar"
              ]
            }
          },
          "strategy": "deterministic"
        },
        "id": "l14-a1",
        "type": "prompt_builder"
      },
      {
        "data": {
          "items": [
            {
              "id": "i-tabela",
              "text": "A tabela de preços pública dos planos de limpeza, já publicada no site"
            },
            {
              "id": "i-margem",
              "text": "A margem de lucro interna de cada plano"
            },
            {
              "id": "i-contato",
              "text": "O nome, telefone e e-mail do contato do cliente"
            },
            {
              "id": "i-andares",
              "text": "O fato de o prédio ter 12 andares e precisar de limpeza diária"
            },
            {
              "id": "i-contrato",
              "text": "Os valores de um contrato parecido fechado com outro cliente"
            }
          ],
          "labels": {
            "safe": "Pode ir para a IA",
            "sensitive": "Fica de fora"
          }
        },
        "evaluation": {
          "classification": {
            "i-andares": "safe",
            "i-contato": "sensitive",
            "i-contrato": "sensitive",
            "i-margem": "sensitive",
            "i-tabela": "safe"
          },
          "strategy": "deterministic"
        },
        "id": "l14-a2",
        "type": "safety_classification"
      },
      {
        "data": {
          "criteria": [
            {
              "id": "c-verificar",
              "text": "Deixa claro o que você precisa verificar ou preencher"
            },
            {
              "id": "c-ajusta",
              "text": "Serve de base para adaptar ao cliente e à sua tabela de preços"
            },
            {
              "id": "c-pronta",
              "text": "Parece pronta para enviar sem nenhuma revisão"
            }
          ],
          "outputs": [
            {
              "id": "out-a",
              "text": "Prezado cliente, temos o prazer de apresentar a melhor proposta do mercado: R$ 8.470/mês pelo pacote completo para os 12 andares, com desconto exclusivo de 15% válido até sexta-feira. Nossa equipe de 40 profissionais garante qualidade comprovada por 200 clientes satisfeitos. É só assinar e começamos na segunda."
            },
            {
              "id": "out-b",
              "text": "Estrutura de proposta para você completar: 1) Apresentação da empresa [2-3 linhas sobre sua empresa]; 2) Entendimento da necessidade [prédio de 12 andares, limpeza diária]; 3) Plano sugerido com itens inclusos [verificar o que seu plano cobre]; 4) Investimento [preencher com seus preços da tabela]; 5) Prazo e próximos passos [ajustar datas]. Revise cada seção antes de enviar."
            }
          ],
          "scenario": "Você pediu a proposta do prédio de 12 andares. Antes de enviar ao cliente, qual versão serve de base de trabalho?"
        },
        "evaluation": {
          "betterOutputId": "out-b",
          "requiredCriterionIds": [
            "c-verificar",
            "c-ajusta"
          ],
          "strategy": "deterministic"
        },
        "id": "l14-a3",
        "type": "output_comparison"
      }
    ],
    "skillIds": [
      "pedir",
      "avaliar",
      "proteger",
      "aplicar"
    ],
    "version": 1
  },
  "l15": {
    "activities": [
      {
        "data": {
          "options": [
            {
              "id": "opt-a",
              "text": "Descobrir qual commit introduziu um bug: o histórico tem 1.200 commits e o erro aparece só em produção com um payload específico."
            },
            {
              "id": "opt-b",
              "text": "Escrever o boilerplate de um CRUD REST com validação Zod, autenticação JWT e testes de integração para uma entidade nova."
            },
            {
              "id": "opt-c",
              "text": "Garantir que uma função de cálculo de juros compostos está correta até a quarta casa decimal para uma auditoria regulatória."
            }
          ]
        },
        "evaluation": {
          "correctOptionIds": [
            "opt-b"
          ],
          "strategy": "deterministic"
        },
        "id": "l15-a1",
        "type": "choice"
      },
      {
        "data": {
          "criteria": [
            {
              "id": "c-concreto",
              "text": "Menciona tecnologia específica e como integrá-la"
            },
            {
              "id": "c-cenario",
              "text": "Considera o cenário real (Redis, múltiplas instâncias)"
            },
            {
              "id": "c-ressalvas",
              "text": "Indica limitações ou próximos passos para aprofundar"
            }
          ],
          "outputs": [
            {
              "id": "out-a",
              "text": "Use o pacote 'express-rate-limit' com RedisStore. Aqui está o código: app.use(rateLimit({ windowMs: 60000, max: 100, store: new RedisStore({ client }) })). Configure também o X-RateLimit-* nos headers. Para mais detalhes, veja a documentação do pacote em npm."
            },
            {
              "id": "out-b",
              "text": "Rate limiting é importante para proteger sua API. Você pode implementar com um middleware simples que conta requisições por IP em memória. Não esqueça de limpar os contadores periodicamente para não estourar a memória. Segurança é fundamental!"
            }
          ],
          "scenario": "Você está implementando rate limiting em uma API Express em produção com Redis compartilhado entre três instâncias."
        },
        "evaluation": {
          "betterOutputId": "out-a",
          "requiredCriterionIds": [
            "c-concreto",
            "c-cenario"
          ],
          "strategy": "deterministic"
        },
        "id": "l15-a2",
        "type": "output_comparison"
      }
    ],
    "skillIds": [
      "decidir"
    ],
    "version": 1
  },
  "l16": {
    "activities": [
      {
        "data": {
          "fields": [
            {
              "hint": "Ex: TypeScript 5.x, Node 20",
              "id": "linguagem",
              "label": "Linguagem e runtime"
            },
            {
              "hint": "Ex: a função recebe unknown, retorna Result<T, ValidationError> ou lança",
              "id": "contrato",
              "label": "Contrato de entrada e saída"
            },
            {
              "hint": "Ex: sem dependência externa além de zod, não logar campos com 'token' ou 'secret' no nome",
              "id": "restricoes",
              "label": "Restrições importantes"
            },
            {
              "hint": "Ex: roda no handler de um webhook Express com 5k req/min",
              "id": "cenario",
              "label": "Contexto de uso"
            }
          ],
          "genericPrompt": "Escreve uma função pra validar payload de webhook.",
          "scenario": "Você precisa de uma função que valide e sanitize um payload JSON de webhook vindo de um serviço externo (Stripe). O payload precisa ser validado contra um schema e campos sensíveis (como tokens) precisam ser removidos antes de logar."
        },
        "evaluation": {
          "fields": {
            "cenario": {
              "minLength": 5,
              "mustIncludeAny": [
                "webhook",
                "api",
                "express",
                "fastify",
                "hono",
                "lambda",
                "endpoint",
                "handler",
                "servidor",
                "requisição",
                "request",
                "produção",
                "produção"
              ]
            },
            "contrato": {
              "minLength": 5,
              "mustIncludeAny": [
                "retorna",
                "recebe",
                "parâmetro",
                "resultado",
                "Result",
                "throws",
                "lança",
                "erro",
                "input",
                "output",
                "payload",
                "unknown",
                "schema",
                "valida"
              ]
            },
            "linguagem": {
              "minLength": 5,
              "mustIncludeAny": [
                "TypeScript",
                "Node",
                "TS",
                "JavaScript",
                "Python",
                "Go",
                "Rust",
                "ts",
                "js",
                "node"
              ]
            },
            "restricoes": {
              "minLength": 5,
              "mustIncludeAny": [
                "token",
                "secret",
                "log",
                "dependência",
                "biblioteca",
                "lib",
                "pacote",
                "zod",
                "joi",
                "yup",
                "ajv",
                "não",
                "sem",
                "remover",
                "sanitize"
              ]
            }
          },
          "strategy": "deterministic"
        },
        "id": "l16-a1",
        "type": "prompt_builder"
      },
      {
        "data": {
          "criteria": [
            {
              "id": "c-schema",
              "text": "Valida o payload contra um schema explícito"
            },
            {
              "id": "c-redact",
              "text": "Remove ou omite campos sensíveis antes de logar"
            },
            {
              "id": "c-types",
              "text": "Tipos de entrada e saída são explícitos e seguros"
            },
            {
              "id": "c-erros",
              "text": "Trata erros de validação de forma previsível (ex: lança ou retorna Result)"
            },
            {
              "id": "c-deps",
              "text": "Declara dependências externas e versão"
            }
          ],
          "responseText": "import { z } from 'zod';\n\nconst WebhookPayload = z.object({\n  id: z.string(),\n  type: z.string(),\n  data: z.object({}).passthrough(),\n});\n\ntype SafePayload = z.infer<typeof WebhookPayload>;\n\n// Redact sensitive fields before logging\ntype Redacted<T> = Omit<T, 'client_secret' | 'api_key' | 'token'>;\n\nexport function validateWebhook(input: unknown): SafePayload {\n  return WebhookPayload.parse(input);\n}\n\nexport function safeForLogging(payload: SafePayload): Redacted<SafePayload> {\n  const { ...safe } = payload;\n  return safe;\n}\n"
        },
        "evaluation": {
          "expectedVerdicts": {
            "c-deps": "not_met",
            "c-erros": "not_met",
            "c-redact": "partial",
            "c-schema": "met",
            "c-types": "met"
          },
          "strategy": "deterministic"
        },
        "id": "l16-a2",
        "type": "rubric_review"
      }
    ],
    "skillIds": [
      "codificar"
    ],
    "version": 1
  },
  "l17": {
    "activities": [
      {
        "data": {
          "items": [
            {
              "id": "api-key",
              "text": "Chave de API da OpenAI (sk-...)"
            },
            {
              "id": "prompt-template",
              "text": "Template do prompt: 'Resuma o seguinte texto em 3 tópicos: {{texto}}'"
            },
            {
              "id": "model-name",
              "text": "Nome do modelo usado: 'gpt-4o'"
            },
            {
              "id": "user-text",
              "text": "Texto que o usuário enviou para ser resumido"
            },
            {
              "id": "max-tokens",
              "text": "Parâmetro max_tokens: 500"
            },
            {
              "id": "org-id",
              "text": "Organization ID da conta OpenAI"
            }
          ],
          "labels": {
            "safe": "Seguro (pode ir ao cliente)",
            "sensitive": "Sensível (só no backend)"
          }
        },
        "evaluation": {
          "classification": {
            "api-key": "sensitive",
            "max-tokens": "safe",
            "model-name": "safe",
            "org-id": "sensitive",
            "prompt-template": "safe",
            "user-text": "safe"
          },
          "strategy": "deterministic"
        },
        "id": "l17-a1",
        "type": "safety_classification"
      },
      {
        "data": {
          "criteria": [
            {
              "id": "c-timeout",
              "text": "Define timeout e trata timeout vs erro de forma diferente"
            },
            {
              "id": "c-seguranca",
              "text": "Não expõe dados sensíveis em logs, respostas de erro ou no cliente"
            },
            {
              "id": "c-resiliencia",
              "text": "Lida com falha sem derrubar a experiência do usuário"
            }
          ],
          "outputs": [
            {
              "id": "out-a",
              "text": "O frontend chama o backend em POST /api/summarize com { text }. O backend: (1) valida tamanho máximo, (2) chama OpenAI com timeout de 8s, (3) em erro retorna 502 com mensagem amigável, (4) em timeout retorna 504 e agenda retry assíncrono, (5) loga duração e status sem o texto do usuário, (6) retorna { summary, model, tokens }."
            },
            {
              "id": "out-b",
              "text": "O frontend chama o backend em POST /api/summarize. O backend chama OpenAI e retorna o que vier. Se der erro, retorna 500 com a mensagem original da API. O endpoint não tem timeout. O texto do usuário é logado para debug."
            }
          ],
          "scenario": "App React + Node/Express. O usuário digita um texto e clica em 'Resumir'. O backend chama a API da OpenAI e devolve o resumo. O app tem 2k usuários ativos."
        },
        "evaluation": {
          "betterOutputId": "out-a",
          "requiredCriterionIds": [
            "c-timeout",
            "c-seguranca",
            "c-resiliencia"
          ],
          "strategy": "deterministic"
        },
        "id": "l17-a2",
        "type": "output_comparison"
      }
    ],
    "skillIds": [
      "integrar"
    ],
    "version": 1
  },
  "l18": {
    "activities": [
      {
        "data": {
          "fields": [
            {
              "hint": "O que o modelo de pedido pede à IA? Ex.: resumir o desempenho semanal da equipe.",
              "id": "tarefa",
              "label": "Tarefa"
            },
            {
              "hint": "Que dados da própria rotina o modelo deve trazer? Ex.: números de vendas, atendimento e prazos da semana.",
              "id": "contexto",
              "label": "Contexto"
            },
            {
              "hint": "Para quem é a saída? Ex.: diretoria, em linguagem executiva.",
              "id": "publico",
              "label": "Público"
            },
            {
              "hint": "Que forma a saída deve ter? Ex.: resumo executivo de uma página com destaques em tópicos.",
              "id": "formato",
              "label": "Formato"
            }
          ],
          "genericPrompt": "Faz um relatório.",
          "scenario": "Toda sexta-feira você pede à IA um relatório semanal da equipe para a diretoria. O pedido que funcionou dizia o que analisar, trazia os números da semana e pedia um resumo executivo curto. Agora você quer guardar esse pedido como modelo para não recomeçar do zero toda semana."
        },
        "evaluation": {
          "fields": {
            "contexto": {
              "minLength": 12,
              "mustIncludeAny": [
                "semana",
                "números",
                "numeros",
                "dados",
                "resultado"
              ]
            },
            "formato": {
              "minLength": 6,
              "mustIncludeAny": [
                "resumo executivo",
                "resumo de",
                "uma página",
                "uma pagina",
                "tópicos",
                "topicos",
                "curto"
              ]
            },
            "publico": {
              "minLength": 6,
              "mustIncludeAny": [
                "diretoria",
                "diretor",
                "gestor",
                "equipe"
              ]
            },
            "tarefa": {
              "minLength": 8,
              "mustIncludeAny": [
                "resumir",
                "sumari",
                "relat"
              ]
            }
          },
          "strategy": "deterministic"
        },
        "id": "l18-a1",
        "type": "prompt_builder"
      },
      {
        "data": {
          "criteria": [
            {
              "id": "c-adaptou-contexto",
              "text": "Troca o contexto e o público do modelo pelos do novo cenário"
            },
            {
              "id": "c-preservou-estrutura",
              "text": "Preserva a estrutura de campos que funcionou (tarefa, contexto, público, formato)"
            },
            {
              "id": "c-sem-sobra",
              "text": "Não deixa resto do cenário antigo (relatório, diretoria, sexta-feira)"
            }
          ],
          "outputs": [
            {
              "id": "out-a",
              "text": "Pego meu modelo e troco só o que muda: tarefa — escrever um e-mail sobre atraso de entrega; contexto — pedido 1042, atraso de 2 dias por falta de estoque, cliente é recorrente; público — o cliente, em tom cordial e direto; formato — e-mail curto com pedido de desculpas, motivo e nova data. Mantenho a estrutura de quatro campos que já funcionava."
            },
            {
              "id": "out-b",
              "text": "Escrevo um pedido novo do zero, do meu jeito: 'IA, me ajuda com uma coisa pro cliente, preciso de um texto bonito sobre uma entrega, qualquer coisa serve, você sabe, algo profissional'."
            }
          ],
          "scenario": "Usando a IA, você precisa escrever um e-mail para um cliente avisando que a entrega vai atrasar dois dias. Você tem o modelo do relatório semanal salvo (tarefa + contexto + público + formato)."
        },
        "evaluation": {
          "betterOutputId": "out-a",
          "requiredCriterionIds": [
            "c-adaptou-contexto",
            "c-sem-sobra"
          ],
          "strategy": "deterministic"
        },
        "id": "l18-a2",
        "type": "output_comparison"
      },
      {
        "data": {
          "options": [
            {
              "id": "opt-a",
              "text": "Uma nova tarefa de resumo para um público parecido com o de sempre — a estrutura de campos serve de novo."
            },
            {
              "id": "opt-b",
              "text": "O pedido antigo continha dados sensíveis de um cliente (valores, nomes) e o novo cenário é um projeto de outro cliente."
            },
            {
              "id": "opt-c",
              "text": "O formato de saída pedido agora é igual ao do modelo — resumo curto em tópicos."
            }
          ]
        },
        "evaluation": {
          "correctOptionIds": [
            "opt-b"
          ],
          "strategy": "deterministic"
        },
        "id": "l18-a3",
        "type": "choice"
      }
    ],
    "skillIds": [
      "pedir",
      "aplicar"
    ],
    "version": 1
  },
  "l19": {
    "activities": [
      {
        "data": {
          "contextOptions": [
            {
              "id": "ctx-publico-original",
              "text": "O público da nova versão: para quem é e o que esse público espera (o turno só disse 'time técnico', sem dizer o que mudava em relação à diretoria)"
            },
            {
              "id": "ctx-tom-original",
              "text": "O tom: manter o registro formal do início — ou mudá-lo de forma explícita, não por omissão"
            },
            {
              "id": "ctx-limite-tamanho",
              "text": "O limite de tamanho: o máximo de 1 página definido no turno 1 seguia valendo"
            },
            {
              "id": "ctx-formato-anterior",
              "text": "O formato da versão anterior (tópicos com destaques), caso devesse ser preservado na adaptação"
            },
            {
              "id": "ctx-ia-lenta",
              "text": "A IA ficou lenta porque a conversa ficou longa demais"
            },
            {
              "id": "ctx-ia-nova",
              "text": "Seria necessário usar um modelo de IA mais novo"
            }
          ],
          "prompt": "TURNO 1 (você): 'Resuma o relatório do trimestre. Público: diretoria. Tom: formal. No máximo 1 página.' · TURNO 2 (IA): entrega resumo formal de 1 página, com destaques. · TURNO 3 (você): 'Agora adapte esse resumo para o time técnico.' · TURNO 4 (IA): entrega 3 páginas informais, com jargão e sem destaques."
        },
        "evaluation": {
          "optionalContextIds": [
            "ctx-formato-anterior"
          ],
          "requiredContextIds": [
            "ctx-publico-original",
            "ctx-tom-original",
            "ctx-limite-tamanho"
          ],
          "strategy": "deterministic"
        },
        "id": "l19-a1",
        "type": "missing_context"
      },
      {
        "data": {
          "items": [
            {
              "id": "step-pedir",
              "text": "Pedir a nova versão ('refaça o resumo seguindo o que combinamos acima')"
            },
            {
              "id": "step-citar",
              "text": "Citar a restrição perdida ('volte ao público diretoria, tom formal, no máximo 1 página')"
            },
            {
              "id": "step-conferir",
              "text": "Conferir a versão entregue contra as restrições antes de usar"
            },
            {
              "id": "step-confirmar",
              "text": "Confirmar o entendimento ('resuma em 3 linhas o que você vai entregar')"
            }
          ]
        },
        "evaluation": {
          "expectedOrder": [
            "step-citar",
            "step-confirmar",
            "step-pedir",
            "step-conferir"
          ],
          "strategy": "deterministic"
        },
        "id": "l19-a2",
        "type": "sort"
      },
      {
        "data": {
          "options": [
            {
              "id": "opt-a",
              "text": "Seis turnos úteis e a IA esqueceu uma restrição no meio do caminho."
            },
            {
              "id": "opt-b",
              "text": "A conversa acumulou três correções conflitantes e a IA agora mistura versões diferentes dos requisitos."
            },
            {
              "id": "opt-c",
              "text": "A resposta está boa, mas você quer o resultado em outro formato."
            }
          ]
        },
        "evaluation": {
          "correctOptionIds": [
            "opt-b"
          ],
          "strategy": "deterministic"
        },
        "id": "l19-a3",
        "type": "choice"
      }
    ],
    "skillIds": [
      "pedir",
      "avaliar"
    ],
    "version": 1
  },
  "l20": {
    "activities": [
      {
        "data": {
          "multiSelect": true,
          "options": [
            {
              "id": "opt-crescimento",
              "text": "As vendas cresceram 23% no último trimestre."
            },
            {
              "id": "opt-emails",
              "text": "E-mails claros ajudam a manter clientes."
            },
            {
              "id": "opt-pesquisa",
              "text": "Segundo uma pesquisa de 2024 da consultoria X, 61% dos clientes valorizam atendimento rápido."
            },
            {
              "id": "opt-equipes",
              "text": "Equipes de vendas variam de empresa para empresa."
            },
            {
              "id": "opt-ticket",
              "text": "O ticket médio ficou em R$ 412."
            }
          ]
        },
        "evaluation": {
          "correctOptionIds": [
            "opt-crescimento",
            "opt-pesquisa",
            "opt-ticket"
          ],
          "strategy": "deterministic"
        },
        "id": "l20-a1",
        "type": "choice"
      },
      {
        "data": {
          "items": [
            {
              "id": "src-imprensa",
              "text": "Matéria da imprensa especializada citando o relatório de vendas"
            },
            {
              "id": "src-relatorio",
              "text": "Relatório oficial de vendas da própria empresa"
            },
            {
              "id": "src-social",
              "text": "Post em rede social comentando o assunto"
            },
            {
              "id": "src-planilha",
              "text": "Planilha primária do setor de vendas"
            }
          ]
        },
        "evaluation": {
          "expectedOrder": [
            "src-relatorio",
            "src-planilha",
            "src-imprensa",
            "src-social"
          ],
          "strategy": "deterministic"
        },
        "id": "l20-a2",
        "type": "sort"
      },
      {
        "data": {
          "contextOptions": [
            {
              "id": "ctx-fonte-oficial",
              "text": "A fonte oficial do número (qual relatório ou sistema gerou os 23%)"
            },
            {
              "id": "ctx-periodo-exato",
              "text": "O período exato medido (datas de início e fim do 'último trimestre')"
            },
            {
              "id": "ctx-modelo-ia",
              "text": "O nome do modelo de IA que gerou a resposta"
            },
            {
              "id": "ctx-opiniao-time",
              "text": "A opinião do time de vendas sobre o crescimento"
            }
          ],
          "prompt": "As vendas cresceram 23% no último trimestre."
        },
        "evaluation": {
          "requiredContextIds": [
            "ctx-fonte-oficial",
            "ctx-periodo-exato"
          ],
          "strategy": "deterministic"
        },
        "id": "l20-a3",
        "type": "missing_context"
      }
    ],
    "skillIds": [
      "avaliar"
    ],
    "version": 1
  }
}

export const literacyCorpusVersion = "2026-08-31.1"
